### ISSUE TITLE
Filtering on categoricals much slower than filtering on strings or physical with a StringCache

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#5586] opened 2022-11-22 12:50 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

If I filter a dataframe on a categorical column that was not created with a string cache then it is fast to filter on:
- the original string column
- the categorical column
- the physical representation column

However, if I filter a dataframe on a categorical column created with a StringCache it is much (3-10x) slower than the equivalent filter applied to:
- the original string column
- the physical representation column

Perhaps the lookup in the StringCache is slow?

In the example below

### Reproducible example

```python
import polars as pl
import numpy as np

N = 5_000_000
integer_array = np.random.randint(0,N // 2,N)
with pl.StringCache():
    df_left = (
    pl.DataFrame(
        {
            "id":[f"id{i}" for i in integer_array],
            "values":integer_array
        }
    ).with_column(pl.col("id").cast(pl.Categorical).alias("cats"))
    .with_column(pl.col("cats").to_physical().alias("p"))
    )

id1_physical = df_left.filter(pl.col("id") == "id1")["p"][0]

%%timeit -n1 -r3
df_left.filter(pl.col("id") == "id1")
# 14ms

%%timeit -n1 -r3
df_left.filter(pl.col("cats") == "id1")
# 43 ms

%%timeit -n1 -r3
df_left.filter(pl.col("p") == id1_physical)
# 6 ms

# without the stringCache
## 12 ms (filter on string)
## 11 ms (filter on cats)
## 9 ms (filter on physical)
```

### Expected behavior

Filtering with a string cache should not impact performance so much 

### Installed versions

```
---Version info---
Polars: 0.14.29
Index type: UInt32
Platform: Linux-5.10.104-linuxkit-x86_64-with-glibc2.28
Python: 3.10.1 (main, Dec 21 2021, 09:50:13) [GCC 8.3.0]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: <not installed>
connectorx: 0.3.1
xlsx2csv: 0.8
matplotlib: 3.6.2
```

**Comment by avimallu** [comment] 2023-07-06 16:22
Possibly related and answered? https://github.com/pola-rs/polars/issues/7946

**Comment by avimallu** [comment] 2023-07-31 21:46
@stinodego, another one for you to potentially close?

**Comment by stinodego** [comment] 2023-07-31 22:00
Duplicate of #7946

**Closed by stinodego** 2023-07-31 22:00 UTC
Labels: python, performance
