### ISSUE TITLE
Python library date issue

### ISSUE THREAD

**Issue by NarayanB** [pola-rs/polars#2191] opened 2021-12-27 23:42 UTC
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

Latest

#### What operating system are you using polars on?

Linux

#### Describe your bug.

Datetime parse issue

#### What are the steps to reproduce the behavior?

There is datetime issue for years greater than 2300
```



If we cannot reproduce the bug, it is unlikely that we will be able fix it.

#### What is the actual behavior?

The code errors with 'int too big to convert'

#### What is the expected behavior?
Should have returned year = 2300 in above case

What do you think polars should have done?

**Comment by NarayanB** [comment] 2021-12-27 23:43
Sorry, not sure why the sample code didn't get copied

def test_date_range() -> None:
    result = pl.date_range(
        datetime(2300, 1, 1), datetime(2015, 7, 1), timedelta(days=1, hours=12)
    )
    assert result.dt[0] == datetime(2300, 1, 1)

**Comment by zundertj** [comment] 2021-12-28 07:33
Note that in your code `start date > end date`, not sure that is supported by `pl.date_range`, but also when `start date < end date`, I see the same:

```python
import polars as pl
result = pl.date_range(
    datetime(2300, 1, 1), datetime(2300, 7, 1), timedelta(days=1, hours=12)
)
Traceback (most recent call last):
  File "xxx\polars\py-polars\polars\internals\functions.py", line 228, in date_range
    return pli.wrap_s(_py_date_range(start, stop, interval, closed, name))
OverflowError: int too big to convert
```

@ritchie46 : could this be due to using nanoseconds now? The start date has int value `1.0413792e+19`.

**Comment by ritchie46** [comment] 2021-12-28 07:40
Yes, this is due to nanoseconds. This is expected behavior. 

I will add other units in the future.

**Comment by NarayanB** [comment] 2021-12-28 11:54
The issue is that using datetime library to convert to Polar's Date and Datetime suffers from this bug - OverflowError: int too big to convert. This affects parse_csv

**Comment by ritchie46** [comment] 2021-12-28 14:55
Duplicate of #2208

**Closed by ritchie46** 2021-12-28 14:55 UTC
Labels: wontfix
