### ISSUE TITLE
Casting that might surprise R and Pandas users (categorical --> str)

### ISSUE THREAD

**Issue by vnijs** [pola-rs/polars#6283] opened 2023-01-17 09:27 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I am a long time R (and Pandas) user and am new polars. Amazing package!

I posted a question to StackOverflow about a seeming inconsistency between casting requirements for pl.col vs [] indexing. 

In the example below, `scores.filter(scores["zone"].is_in(["North", "South"]))` works without the need for casting when using a global string cache but `scores.filter(scores["zone"] == "North"` requires explicit casting.  `scores.filter(pl.col("zone") == "North")`, on the other hand, automatically casts to a string which seems inconsistent with the fact that `scores.filter(scores["zone"] == "North"` does require casting. Just my 2C as a new user coming from R and Pandas

Thanks for your consideration.

### Reproducible example

```python
import polars as pl

pl.toggle_string_cache(True)
scores = pl.DataFrame(
    {
        "zone": pl.Series([
            "North",
            "North",
            "North",
            "South",
            "South",
            "East",
            "East",
            "East",
            "East",
        ]).cast(pl.Categorical),
        "funding": pl.Series(["yes", "yes", "no", "yes", "no", "no", "no", "yes", "yes"]).cast(pl.Categorical),
        "score": [78, 39, 76, 56, 67, 89, 100, 55, 80],
    }
)

# works with or without global string cache
scores.filter(pl.col("zone") == "North")

# works with or without global string cache
scores.filter(pl.col("zone").cast(str).is_in(["North", "South"]))

# works with global string cache
scores.filter(pl.col("zone").is_in(["North", "South"]))

# works with global string cache, without the need to cast
scores.filter(scores["zone"].is_in(["North", "South"]))

# requires cast(str) with or without global string cache
# the need for casting to str would likely surprise R and Pandas users
scores.filter(scores["zone"] == "North")

# works with or without global string cache
scores.filter(scores["zone"].cast(str) == "North")
```

### Expected behavior

* Casting to string handled automatically when using categorical variables in filtering

### Installed versions

<details>

```
>>> pl.show_versions()
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: macOS-13.0-arm64-arm-64bit
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.4.4
numpy: 1.24.1
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: 0.8.1
matplotlib: 3.5.3
```

</details>

**Comment by ritchie46** [comment] 2023-01-18 10:26
The string caches are as expected. When you compare to a list of strings we convert that to a `Series` of categoricals and once we do that we have the constraint that this must happen under a global string cache.

This is not a bug, this is a constraint for performance reasons.

**Comment by ritchie46** [comment] 2023-01-19 09:16
I will close this as this is expected behavior.

**Comment by vnijs** [comment] 2023-01-19 18:42
Thanks for your consideration. My main question was about why the below doesn't work without casting. If `pl.col("zone") == "North"` works, why not have the same behavior for the below.

`scores.filter(scores["zone"] == "North")`

**Comment by ritchie46** [comment] 2023-01-20 10:46
Oh, right. Seems something goes wrong in dispatch here. Will fix it.

**Closed** 2023-01-20 11:08 UTC
Labels: bug, python
