### ISSUE TITLE
Implement `median` for the list namespace

### ISSUE THREAD

**Issue by FriedLabJHU** [pola-rs/polars#13211] opened 2023-12-22 17:13 UTC
### Description

The `median` expression function exists in the rust implementation of `PyExpr` but not in the Python implementation.

**Comment by stinodego** [comment] 2023-12-22 23:18
`Expr.median` exists and is exposed correctly.
`Expr.list.median` does not exist - neither on the Python nor the Rust side.

I'll take this as a feature request to implement `list.median`, which is a fair request.

**Comment by stinodego** [comment] 2023-12-22 23:21
Actually this is a duplicate of #12163, so I'll close this.

**Closed by stinodego** 2023-12-22 23:21 UTC
Labels: enhancement, accepted
