### ISSUE TITLE
add the typing_extensions.deprecated decorater to deprecated functions so that static type checkers can report them.

### ISSUE THREAD

**Issue by raprocks** [pola-rs/polars#14387] opened 2024-02-09 10:18 UTC
### Description

Many of the functions that were used earlier have been deprecated and the only way to know weather they are is at runtime when a deprecation waring is reported. hovering over the functions documentation does not provide any such indication either because a restructured text label is used to mark the function deprecated.

![hovering over apply](https://github.com/pola-rs/polars/assets/52972480/fb035d9c-b8a6-4de5-b7d2-73500c705be9)
![actual docstring in the library source code](https://github.com/pola-rs/polars/assets/52972480/06b01091-078c-4ba0-b996-8c3a5f6dcb45)

using the deprecated decorator in typing_extensions can be helpful insuch cases
![using the decorator](https://github.com/pola-rs/polars/assets/52972480/d33d0d33-d6ed-444a-9b86-e33fa96ddd2c)
this marks the function call in source code appropriately 
![image](https://github.com/pola-rs/polars/assets/52972480/ede7810d-00eb-4f69-80fe-741ddbb5df35)
![image](https://github.com/pola-rs/polars/assets/52972480/d7f27f18-d2ca-4a27-b168-e0d968e81043)

NOTES:
maybe this is helpful
1. https://stackoverflow.com/questions/2536307/decorators-in-the-python-standard-lib-deprecated-specifically
2. https://peps.python.org/pep-0702/

**Comment by mcrumiller** [comment] 2024-02-09 18:45
Duplicate of #13875.

**Comment by stinodego** [comment] 2024-02-09 22:04
> hovering over the functions documentation does not provide any such indication either because a restructured text label is used to mark the function deprecated

This is news to me though and I can confirm the deprecation message does not show up. That's unfortunate. Maybe we can address that somehow.

For now, please see the issue @mcrumiller linked for why we're not making the switch right now.

**Closed by stinodego** 2024-02-09 22:04 UTC
Labels: documentation

**Comment by raprocks** [comment] 2024-02-09 22:12
cool, i understand why we are not using that decorator, but can we probably atleast try to solve for the docstring label issue? let me know if this will result in grunt work and i will be happy to make a PR for that.

**Comment by stinodego** [comment] 2024-02-09 22:16
> but can we probably atleast try to solve for the docstring label issue

The hardest part will be figuring out why VSCdoe doesn't handle this properly, and if we can figure out a way to satisfy both VSCode and Sphinx. If you could look into that, it would be welcome!

**Comment by raprocks** [comment] 2024-02-09 22:29
okay more issues, vscode pylance entirely ignores sphinx labels somehow, 
![image](https://github.com/pola-rs/polars/assets/52972480/1db19ac5-a07c-442e-b2c5-dbf74a00044f)
the warning is missing the documentation as well, is this maybe a vscode pylance issue?

**Comment by raprocks** [comment] 2024-02-09 22:41
https://github.com/microsoft/pylance-release/issues/5431

someone's facing the same issue lol

**Comment by raprocks** [comment] 2024-02-09 22:47
more info here: https://github.com/microsoft/pylance-release/issues/2251 vscode does not render directives at all, and they treat all docstrings as markdown, most probably non solvable. i'll leave you to decide if changes to docstrings are needed or to let this issue be because it is a upstream, vscode/pylance issue where they need to figure out how to render sphinx style docstrings correctly.

**Comment by stinodego** [comment] 2024-02-09 22:57
Thanks for looking into this. I suspected as much. Not much we can do here unfortunately, so I'll leave it to the VSCode people if they want to properly support these admonitions.
