### ISSUE TITLE
write_parquet function in polars-u64-idx does not support large data frames

### ISSUE THREAD

**Issue by jnthnhss** [pola-rs/polars#3120] opened 2022-04-11 18:27 UTC
#### What language are you using?

Python

#### What version of polars are you using?

0.13.21

#### What operating system are you using polars on?

Ubuntu 20.04.1 LTS

#### What language version are you using

Python 3.8.5

#### Describe your bug.

I'm using the 64 bit version of Polars. However, the `write_parquet` function does not seem to support large data frames.

#### What are the steps to reproduce the behavior?

```
df = pl.select(pl.repeat(0,n=2**32).alias('col_1'))
df.write_parquet('tmp.parquet')
```

#### What is the actual behavior?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/polars/internals/frame.py", line 1400, in write_parquet
    self._df.to_parquet(file, compression, statistics)
exceptions.ArrowErrorException: ExternalFormat("underlying snap error: snappy: input buffer (size = 34359738368) is larger than allowed (size = 4294967295)")
```

**Comment by ritchie46** [comment] 2022-04-12 06:09
I think we must split these large dataframes up in different row groups. I already open a discussion/issue for this upstream: https://github.com/jorgecarleitao/arrow2/issues/932

Maybe we should also default to another compression like `lzo`. :thinking:

**Comment by jnthnhss** [comment] 2022-04-12 14:28
I tried out all the options for compression below. With no compression I also get an error. I should mentioned that it does work with `use_pyarrow=True`.

```py
import polars as pl

df = pl.select(pl.repeat(0,n=2**32).alias('col_1'))

df.write_parquet('tmp.parquet',compression='uncompressed')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/polars/internals/frame.py", line 1400, in write_parquet
    self._df.to_parquet(file, compression, statistics)
exceptions.ArrowErrorException: ExternalFormat("A page can only contain i32::MAX uncompressed bytes. This one contains 34896609285")

df.write_parquet('tmp.parquet',compression='snappy')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/polars/internals/frame.py", line 1400, in write_parquet
    self._df.to_parquet(file, compression, statistics)
exceptions.ArrowErrorException: ExternalFormat("underlying snap error: snappy: input buffer (size = 34359738368) is larger than allowed (size = 4294967295)")

df.write_parquet('tmp.parquet',compression='gzip')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/polars/internals/frame.py", line 1400, in write_parquet
    self._df.to_parquet(file, compression, statistics)
exceptions.ArrowErrorException: ExternalFormat("A page can only contain i32::MAX uncompressed bytes. This one contains 34896609285")

df.write_parquet('tmp.parquet',compression='lzo')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/polars/internals/frame.py", line 1400, in write_parquet
    self._df.to_parquet(file, compression, statistics)
exceptions.ArrowErrorException: ExternalFormat("Compression Lzo is not supported")

df.write_parquet('tmp.parquet',compression='brotli')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/polars/internals/frame.py", line 1400, in write_parquet
    self._df.to_parquet(file, compression, statistics)
exceptions.ArrowErrorException: ExternalFormat("A page can only contain i32::MAX uncompressed bytes. This one contains 34896609285")

df.write_parquet('tmp.parquet',compression='lz4')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/polars/internals/frame.py", line 1400, in write_parquet
    self._df.to_parquet(file, compression, statistics)
exceptions.ArrowErrorException: ExternalFormat("A page can only contain i32::MAX uncompressed bytes. This one contains 34896609285")

df.write_parquet('tmp.parquet',compression='zstd')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/polars/internals/frame.py", line 1400, in write_parquet
    self._df.to_parquet(file, compression, statistics)
exceptions.ArrowErrorException: ExternalFormat("A page can only contain i32::MAX uncompressed bytes. This one contains 34896609285")
```

**Comment by ritchie46** [comment] 2022-04-19 06:50
This should be fixed by #3181. We now split large pages before writing.

**Comment by sammysheep** [comment] 2022-04-22 14:22
Same error implementing in the Rust API using 0.20.0 yesterday. Is the mentioned patch only available on a pre-release version?

**Amazing** work, by the way.

For completeness:
```
Error: ArrowError(ExternalFormat("A page can only contain i32::MAX uncompressed bytes. This one contains 4913383091"))
GZIP ^^

Error: ArrowError(ExternalFormat("underlying snap error: snappy: input buffer (size = 4929419665) is larger than allowed (size = 4294967295)"))
SNAPPY ^^
```

FWIW, Snappy > Lzo as a default. At least Cloudera thinks so and they helped develop parquet.

**Comment by sammysheep** [comment] 2022-04-22 14:28
Also, is there an option to control the page size?

**Comment by ritchie46** [comment] 2022-04-23 17:56
> Also, is there an option to control the page size?

No, there is not. The fix upstream now halves the page size when it is estimated to hit the limit.

**Comment by ritchie46** [comment] 2022-04-23 17:56
> 

Did you took the PR branch? It is not yet on master.

**Comment by ritchie46** [comment] 2022-04-26 14:07
Thanks for giving it another try. I will see if I can try to reproduce this in a few days.

**Comment by ritchie46** [comment] 2022-05-01 07:42
Hi @sammysheep, could you give it another try? There might still be a problem, but that would then mean you have a single value that is huge. Could that be the case?

**Comment by sammysheep** [comment] 2022-05-01 11:26
I'll give it a shot and let you know. This file has been converted before via Spark, which I think also uses arrow, albeit a different implementation. The largest single values are about 32k bytes or so.

**Comment by sammysheep** [comment] 2022-05-01 12:02
This time it does something different. It just says `Killed`. No SO on this test. :)

However, I watched the process and it died after it reached the memory limit of the server, which is about 187G.  The file size this time was 56G, which was my mistake that I did not save the earlier version of the file. I can try to do something closer to the original test on Monday. 

I converted the same file yesterday on a similar server using local mode and coalescing to one partition. This is the closest to what I am doing with `polars`. The peak memory in the history are much lower for the Spark job, about 5G. The jobs aren't exactly the same because the Spark one does a distinct() call, though most of the data if not all should be distinct. In any case, I _think_ Spark may target block sizes similar to the HDFS block size, about 128 MB.

https://medium.com/analytics-vidhya/spark-parquet-file-cac4af92981d#:~:text=Parquet%3A%20Data%20Organization&text=Horizontal%20Partitioning(Row%20Groups)%20is,of%20128%20MB%20(default).

More on Monday with different sizes.

**Comment by cbilot** [comment] 2022-05-01 15:08
> df = pl.select(pl.repeat(0,n=2**32,eager=True).alias('col_1'))
df.write_parquet('tmp.parquet')

I installed polars-u64-idx (0.13.26), and ran the above code.  No errors.  (And reading the resultant parquet file showed no problems.)

If there's anything I can do to test/benchmark/whatever, please let me know.  Just point me to the files.  I have only 0.5TB of RAM, so my machine may not be able to read the absolute largest of files.

**Comment by ritchie46** [comment] 2022-05-04 17:13
I will ping @jorgecarleitao in here as he has more understanding of this. 

What compression algorithm did you use? And do you see a difference with other ones?

**Comment by sammysheep** [comment] 2022-05-04 17:18
I used Snappy because that is the cluster default we use. Happy to try another one. What do you recommend?

**Comment by jorgecarleitao** [comment] 2022-05-26 17:53
I am sorry this slipped through the cracks on my triage. @ritchie46 din't you fixed this by with the split of the array in multiple pages?

**Comment by ritchie46** [comment] 2022-05-26 18:32
> I am sorry this slipped through the cracks on my triage. @ritchie46 din't you fixed this by with the split of the array in multiple pages?

I believe so. My machine is only a mere 16GB, so I am not able to test this.

But @cbilot's successful run gives me trust that it is fixed now.

**Comment by cbilot** [comment] 2022-05-27 04:23
Hmmm, when I ran that code, I was using `polars-u64-idx (0.13.26)`, which was actually **regular** polars, due to #3279, a bug in the build CI.

So just to re-confirm the result, today, using `polars-u64-idx` (0.13.38), I created the following dataset of 10 billion records, wrote it as a parquet file, and then read it back in:
```python3
import polars as pl
import numpy as np

df = pl.DataFrame({
    'col1': np.random.normal(0, 1, 10_000_000_000),
}).with_row_count()
df
```
```
>>> df
shape: (10000000000, 2)
┌────────────┬───────────┐
│ row_nr     ┆ col1      │
│ ---        ┆ ---       │
│ u64        ┆ f64       │
╞════════════╪═══════════╡
│ 0          ┆ -0.212407 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 1          ┆ 0.923423  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ -0.199929 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 3          ┆ -0.358613 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ ...        ┆ ...       │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 9999999996 ┆ 2.465729  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 9999999997 ┆ -0.498744 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 9999999998 ┆ -0.841243 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 9999999999 ┆ -0.303019 │
└────────────┴───────────┘
```
```python3
df.write_parquet("tmp.parquet")
```
```
$ ls -lh *.parquet
-rw-rw-r-- 1 corey corey 115G May 26 23:01 tmp.parquet
```
```python3
df2 = pl.read_parquet('tmp.parquet')
df2
```
```
shape: (10000000000, 2)
┌────────────┬───────────┐
│ row_nr     ┆ col1      │
│ ---        ┆ ---       │
│ u64        ┆ f64       │
╞════════════╪═══════════╡
│ 0          ┆ -0.212407 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 1          ┆ 0.923423  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ -0.199929 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 3          ┆ -0.358613 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ ...        ┆ ...       │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 9999999996 ┆ 2.465729  │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 9999999997 ┆ -0.498744 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 9999999998 ┆ -0.841243 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 9999999999 ┆ -0.303019 │
└────────────┴───────────┘
>>> pl.__version__
'0.13.38'
```
I can't compare the two files using `frame_equal` due to #3511.  But the the number of rows, and the head & tail of the dataset look equal.

**Comment by sammysheep** [comment] 2022-06-06 15:23
Hi @jorgecarleitao ! Would you mind taking a look at the example run I posted above?

Questions:
- Is there a way to specify parquet version for compatibility reasons in pyarrow2 that might not be exposed in polars?
- is the memory usage for file conversion something that has to be tweaked at the pyarrow2 level, polars level, or something in the application code?

@ritchie46 I think it is "fixed" in terms of it running now but if you have memory like yours (16GB) or too large a file even on a server then when you try to convert a large file you will get a failure when the OS kills your process due to OOM.

For the alternative I am trying to replace, my hunch is that Spark is chunking the data as it is read and writing to a fixed page/block size that typically won't blow up memory (more than the JVM's usual). In Polars am I basically slurping everything to memory at once and trying to do the conversion in a couple (2?) pages?

In terms of large parquet being splittable in a distributed systems (Cloud, Hadoop) it looks like you'd want to be able to set a smallish (128MB) page/block size in parquet, no? If it is something that is exposed in pyarrow2 it would be great to have available in polars.

Use-case / scenarios:
- Do some highly customized processing in Polars and ship to the distributed FS for downstream analytics
- Simple file conversion faster than alternatives using native code

**Comment by ritchie46** [comment] 2022-07-31 07:59
> Is there a way to specify parquet version for compatibility reasons in pyarrow2 that might not be exposed in polars?

There is. We can/should expose that in polars.

> is the memory usage for file conversion something that has to be tweaked at the pyarrow2 level, polars level, or something in the application code?

What do you mean by conversion? Polars is in-memory. So it will always read a file completely into memory (save for memory mapped ipc/feather files).

> In terms of large parquet being splittable in distributed systems (Cloud, Hadoop) it looks like you'd want to be able to set a smallish (128MB) page/block size in parquet, no? If it is something that is exposed in pyarrow2 it would be great to have available in polars.

This possible for polars datasets that don't have struct data. Polars will write the chunks of your dataframe to parquet. If the dataframe is contiguous, it will write a single chunk.

I will close this issue as it has been resolved. Discussion may continue.

**Closed by ritchie46** 2022-07-31 07:59 UTC
Labels: bug

**Comment by sammysheep** [comment] 2022-07-31 18:51
> There is. We can/should expose that in polars.

Thanks, looking forward to this!

> What do you mean by conversion? Polars is in-memory. So it will always read a file completely into memory (save for memory mapped ipc/feather files).

Conversion from CSV to parquet using POLARS.

I was wondering where one could set the parquet page size functionality that you added recently. If it exists, I'd play with the setting to try to get less peak memory allocated (assuming it re-uses a buffer or de-allocs after writing a page).  My earlier analysis indicated that trying to convert a 28G CSV to parquet needed 150G+ of memory, which is OOM for most machines.

> This possible for polars datasets that don't have struct data. Polars will write the chunks of your dataframe to parquet. If the dataframe is contiguous, it will write a single chunk.

So if I am understanding you, I have to chunk the data frame to possibly lower the page sizes being written?


 _Note: earlier I meant "arrow2" not "pyarrow2"._

**Comment by sammysheep** [comment] 2022-07-31 18:52
By the bye, I really enjoyed your talk at the Data and AI Summit 2022 this year. It was definitely one of the better ones, at least to me.

Thanks so much for your wonderful contributions to the community!
