### ISSUE TITLE
Infer `time_unit` in `pl.duration` when nanoseconds is specified

### ISSUE THREAD

**Issue by douglas-raillard-arm** [pola-rs/polars#14751] opened 2024-02-29 00:03 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

data = pl.LazyFrame(dict(a=[1]))

# the +pl.duration() is basically counted as if nanoseconds=0 was given
data.with_columns(
    pl.col.a.cast(pl.Duration('ns')) + pl.duration(nanoseconds=999)
).collect()
# shape: (1, 1)
# ┌──────────────┐
# │ a            │
# │ ---          │
# │ duration[μs] │
# ╞══════════════╡
# │ 0µs          │
# └──────────────┘


# Adding an extra cast to Duration('ns') shows that the result of the
# operation is in microseconds, so 1ns + 999ns = 0us + 0us = 0us
data.with_columns(
    (
        pl.col.a.cast(pl.Duration('ns')) + pl.duration(nanoseconds=999)
    ).cast(pl.Duration('ns'))
).collect()
# shape: (1, 1)
# ┌──────────────┐
# │ a            │
# │ ---          │
# │ duration[ns] │
# ╞══════════════╡
# │ 0ns          │
# └──────────────┘


# If both operands have a Duration('ns') dtype, the operation
# is executed in ns. Unfortunately, the pl.duration() is still only taken
# into account at the microsecond precision, and is as good as 0us in this case:
# 1ns + 999ns = 1ns + 0ns = 1ns
data.with_columns(
    (
        pl.col.a.cast(pl.Duration('ns')) + pl.duration(nanoseconds=999).cast(pl.Duration('ns'))
    ).cast(pl.Duration('ns'))
).collect()
# shape: (1, 1)
# ┌──────────────┐
# │ a            │
# │ ---          │
# │ duration[ns] │
# ╞══════════════╡
# │ 1ns          │
# └──────────────┘
```

### Issue description

Adding a `pl.duration(nanoseconds=...)` value to a column of dtype `pl.Duration('ns')` results in casts to microsecond resolution in various ways that all prevent actually adding a value in nanoseconds. Either the result of the operation is wrongly inferred to be a `pl.Duration('us')` or the sub-microsecond component of the `pl.duration(nanoseconds=...)` operand is ignored. 

### Expected behavior

Adding a column with `pl.Duration('ns')` dtype with a `pl.duration(nanoseconds=...)` should give the sum of nanoseconds of both operands, and the dtype of the result should be `pl.Duration('ns')`

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.11
Index type:           UInt32
Platform:             Linux-5.15.0-92-generic-x86_64-with-glibc2.29
Python:               3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.7.4
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by douglas-raillard-arm** [comment] 2024-02-29 00:12
It can also be seen with just `pl.duration()`:
```python
>>> pl.LazyFrame().with_columns(pl.duration(nanoseconds=1)).collect()
shape: (1, 1)
┌──────────────┐
│ literal      │
│ ---          │
│ duration[μs] │
╞══════════════╡
│ 0µs          │
└──────────────┘

>>> pl.LazyFrame().with_columns(pl.duration(nanoseconds=1).cast(pl.Int64)).collect()
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ i64     │
╞═════════╡
│ 0       │
└─────────┘

>>> pl.LazyFrame().with_columns(pl.duration(nanoseconds=1).cast(pl.Duration('ns'))).collect()
shape: (1, 1)
┌──────────────┐
│ literal      │
│ ---          │
│ duration[ns] │
╞══════════════╡
│ 0ns          │
└──────────────┘

>>> pl.LazyFrame().with_columns(pl.duration(nanoseconds=1).cast(pl.Duration('ns')).cast(pl.Int64)).collect()
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ i64     │
╞═════════╡
│ 0       │
└─────────┘
```

**Comment by douglas-raillard-arm** [comment] 2024-02-29 00:16
Note that all seems to fall back in order if `pl.duration(..., time_unit='ns')` is specified, so maybe all this needs is a an automatic setting of time_unit that is consistent with the values provided, or an exception if a sub-Xs component is provided when `time_unit='Xs'` is specified.

**Comment by stinodego** [comment] 2024-02-29 07:23
This is not a bug, but we can improve the API here.

The default time unit for `duration` is microseconds. So `pl.duration(nanoseconds=999)` results in a `Duration(us)`.
We can possibly improve here by inferring the time unit from the inputs, e.g. if `time_unit` is None and`nanoseconds` is specified, create a `Duration(ns)`.

Adding two durations of different precisions will use the lowest precision to avoid overflows. So the result here is expected.

**Comment by cojmeister** [comment] 2024-03-11 14:29
Can I assign this to me?
Any places I should start my work at?

**Comment by stinodego** [comment] 2024-03-11 14:34
I think this can be handled purely on the Python side. Make `time_unit` optional and set it based on the value of `nanoseconds`.

**Comment by cojmeister** [comment] 2024-03-11 15:34
Opened PR: #14987

**Closed** 2024-03-20 09:16 UTC
Labels: python, enhancement, A-timeseries, accepted, A-api
