### ISSUE TITLE
Sharp corner: join_asof joins should check for sorted joining column before joining

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#8148] opened 2023-04-11 10:35 UTC
### Problem description

I know the documentation for `join_asof` makes it very clear that the dataframes ought to be sorted by the joining column before joining. However, I think it's too easy for this to go wrong within a large codebase (and hard to troubleshoot)

In practice, I imagine many users will sort by the joining column just before using `join_asof` just to be sure. 

I think the following changes would be good:
1. join_asof should raise an error if the joining column is not sorted
2. join_asof could implement an `assume_sorted:bool` parameter that disables this check for performance reasons 

```python
df1 = pl.DataFrame({
    'iCol1': [1.0,2.0,3.0,4.0,5.0,6.0],
    'vCol1': ['a','b','c','d','e','f']
})

shape: (6, 2)
┌───────┬───────┐
│ iCol1 ┆ vCol1 │
│ ---   ┆ ---   │
│ f64   ┆ str   │
╞═══════╪═══════╡
│ 1.0   ┆ a     │
│ 2.0   ┆ b     │
│ 3.0   ┆ c     │
│ 4.0   ┆ d     │
│ 5.0   ┆ e     │
│ 6.0   ┆ f     │
└───────┴───────┘

df2 = (df1
            .with_columns(
                   iCol2 = pl.col('iCol1')+0.1, 
                   vCol2 = pl.col('vCol1').str.to_uppercase()
               )
             .select(pl.col('^*2$'))
             )

shape: (6, 2)
┌───────┬───────┐
│ iCol2 ┆ vCol2 │
│ ---   ┆ ---   │
│ f64   ┆ str   │
╞═══════╪═══════╡
│ 1.1   ┆ A     │
│ 2.1   ┆ B     │
│ 3.1   ┆ C     │
│ 4.1   ┆ D     │
│ 5.1   ┆ E     │
│ 6.1   ┆ F     │
└───────┴───────┘

# This works
df1.join_asof(df2, left_on='iCol1', right_on='iCol2')

shape: (6, 4)
┌───────┬───────┬───────┬───────┐
│ iCol1 ┆ vCol1 ┆ iCol2 ┆ vCol2 │
│ ---   ┆ ---   ┆ ---   ┆ ---   │
│ f64   ┆ str   ┆ f64   ┆ str   │
╞═══════╪═══════╪═══════╪═══════╡
│ 1.0   ┆ a     ┆ null  ┆ null  │
│ 2.0   ┆ b     ┆ 1.1   ┆ A     │
│ 3.0   ┆ c     ┆ 2.1   ┆ B     │
│ 4.0   ┆ d     ┆ 3.1   ┆ C     │
│ 5.0   ┆ e     ┆ 4.1   ┆ D     │
│ 6.0   ┆ f     ┆ 5.1   ┆ E     │
└───────┴───────┴───────┴───────┘

# This should not work 
df1.sort('iCol1', descending=True).join_asof(df2, left_on='iCol1', right_on='iCol2')

shape: (6, 4)
┌───────┬───────┬───────┬───────┐
│ iCol1 ┆ vCol1 ┆ iCol2 ┆ vCol2 │
│ ---   ┆ ---   ┆ ---   ┆ ---   │
│ f64   ┆ str   ┆ f64   ┆ str   │
╞═══════╪═══════╪═══════╪═══════╡
│ 6.0   ┆ f     ┆ 5.1   ┆ E     │
│ 5.0   ┆ e     ┆ 5.1   ┆ E     │
│ 4.0   ┆ d     ┆ 5.1   ┆ E     │
│ 3.0   ┆ c     ┆ 5.1   ┆ E     │
│ 2.0   ┆ b     ┆ 5.1   ┆ E     │
│ 1.0   ┆ a     ┆ 5.1   ┆ E     │
└───────┴───────┴───────┴───────┘

```

**Comment by mcrumiller** [comment] 2023-04-11 12:44
`pl.Series` have a `set_sorted` function which presumably sets an `is_sorted` flag to True. I'd imagine checking these flags on all columns doesn't have any significant performance cost, so I agree that this check should probably be done first.

On that note, it would also be nice to be able to read the `is_sorted` flag to avoid re-sorting when not necessary.

**Comment by cmdlineluser** [comment] 2023-04-11 13:13
There was a similar check added for the groupby_* methods a while back. 

https://github.com/pola-rs/polars/pull/6593

> Pleasure ensure the index column is sorted.

**Comment by thomasfrederikhoeck** [comment] 2023-04-12 13:54
Isn't this a duplicate of https://github.com/pola-rs/polars/issues/6600 ?

**Comment by mkleinbort** [comment] 2023-04-12 13:55
Big overlap, bot not the same.

**Comment by thomasfrederikhoeck** [comment] 2023-04-12 14:54
@mkleinbort I was a little to fast on the trigger ;-)

I agree on:

> However, I think it's too easy for this to go wrong within a large codebase (and hard to troubleshoot)

**Comment by ritchie46** [comment] 2023-04-12 16:04
I agree on this. Let's start with a warning and a hard error in the future.

**Comment by zundertj** [comment] 2023-05-16 18:02
@ritchie46 : I got bitten by the recent upgrade where Polars emits the warning. First, I think it is great there is a warning printed now, highlighting a potential bug, but it wasn't so great trying to figure out where the calling code was (to find out that there was no bug, but ok). The warning originates from the Polars Rust codebase, meaning Python users have no chance to catch this in their unit tests (I always hard fail on warnings), nor is there a stack trace available. Sometimes you may forgot about the sorting, and a unit test may not cover this (my dummy data in tests is often sorted...) so a stack trace would be useful. 

So I see two options: 
1. we simply hard fail.  I think that is what you are aiming for long-term, but I'm not fully understanding why we don't do that yet. I think users would like to know if they haven't explicitly opted into `set_sorted`, and either do that, or explicitly sort.
2. I see there is a `Series.is_sorted`, can we check Python side in `join_asof` at (near zero) cost, and raise a Python warning otherwise? Warnings printed as text to the terminal are, well, warnings, into a terminal where often a lot of stuff is being printed.

**Comment by ritchie46** [comment] 2023-05-16 18:07
> we simply hard fail. I think that is what you are aiming for long-term, but I'm not fully understanding why we don't do that yet. I think users would like to know if they haven't explicitly opted into set_sorted, and either do that, or explicitly sort.

This is exactly what we will do. There was a grace period of one breaking change. Next release we will error.

We are not yet able to raise python warnings from rust sadly. This is something I do want, but didn't have time for yet. 

> First, I think it is great there is a warning printed now, highlighting a potential bug

If the data is sorted, the println should be silenced. Didn't that work? In that case it is a bug in polars.

> I see there is a Series.is_sorted, can we check Python side in join_asof at (near zero) cost, and raise a Python warning otherwise? Warnings printed as text to the terminal are, well, warnings, into a terminal where often a lot of stuff is being printed. A Python warning can be caught in unit tests, and provide a stack trace.

That's not enough. It must raise for all front-ends. End there can be expressions that evaluate to the join key as well.

My question remains, do we have a bug by raising that warning even though it is sorted?

**Comment by ritchie46** [comment] 2023-05-16 18:08
Btw, this can be closed as we do that check now. Currently we print a warning (not ideal, I know). In the upcoming 0.18 release (in a week or 2), we will raise an error.

**Comment by mcrumiller** [comment] 2023-05-16 18:09
@ritchie46 once I did the proper sorting (sorting only on the `asof` key) the warning went away for me, so I think there is no bug. But I do think we should be more clear about the proper sorting.

**Comment by ritchie46** [comment] 2023-05-16 18:10
Closing this one as per https://github.com/pola-rs/polars/issues/8148#issuecomment-1550136623

**Closed by ritchie46** 2023-05-16 18:10 UTC
Labels: enhancement

**Comment by zundertj** [comment] 2023-05-16 18:26
Just to be complete, I had the same confusion as @mcrumiller , the data was sorted but within groups. So the output was correct, but the sort warning was still being raised.

My point on the Python warning: in addition to the current Rust warning. Should have added that.

**Comment by ritchie46** [comment] 2023-05-16 18:38
I don't believe that's correct in our side. If the data only should be sorted within the groups, we should not check on the whole column.

Could we get an issue on this?

**Comment by mcrumiller** [comment] 2023-05-16 18:45
@ritchie46 if the data is only sorted within the groups, the result is incorrect. The documentation and the warning are both correct, but the sorting requirements are not intuitive.

**Comment by mcrumiller** [comment] 2023-05-16 19:03
Actually, it might work properly as long as we're sorted within the group. I can't replicate the "incorrectness" and it seems to be working properly. But I am still getting the error.

**Comment by oshermaayan** [comment] 2025-03-11 12:56
@mcrumiller Hi, just ran into this issue.

When using `join_asof` on a data frame sorted by a timestamp column (`TIME_COLUMN` in the example below) **within each group** (group is defined by `JOIN_ON_COLUMNS`, which is a list of columns names), the following code **produces correct results**. 

```
df_left.join_asof(df_right,
                                       by=JOIN_ON_COLUMNS,
                                       on=TIME_COLUMN
                                          )
```

However, the UserWarning is still thrown:
` UserWarning: key of asof join is not sorted.`

Therefore, it looks like the warning logic should check whether the data is sorted by the `on` column within each group. Currently, the warning is quite confusing (and incorrect) in this case.

Another option is to sort the (already by-group sorted) dataframe, but that's a redundant operation for the desired result of `join_asof` with the `by` argument.

I think a similar checking logic is performed in the [`group_by_dynamic`](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.group_by_dynamic.html) function.

WDYT?

**Comment by mcrumiller** [comment] 2025-03-11 13:20
@oshermaayan `check_sortedness=True` is now a parameter in `join_asof`, and I agree here that the sortedness should be within each `by` column. I think this warrants a new issue.

**Comment by oshermaayan** [comment] 2025-03-11 13:31
Thanks @mcrumiller for the quick reply :)

Other than linking the new issue to this one, do you think other steps / information is necessary?

**Comment by mcrumiller** [comment] 2025-03-11 14:56
Yes, please provide a minimal example showing the behavior in question (something self-contained that demonstrates the issue). Let me point out though that I cannot reproduce this behavior, are you sure about the error you're seeing? The `check_sortedness` flag appears to do nothing when `by` is provided, *even if the data isn't sorted within by groups*:

```python
import polars as pl

df1 = pl.DataFrame({
    "id": [1, 1, 1, 2, 2, 2],
    "t": [0, 5, 2, 1, 9, 4],
})

df2 = pl.DataFrame({
    "id": [1, 1, 1, 2, 2, 2],
    "t": [1, 8, 9, 4, 3, 2],
})

df1.join_asof(df2, on="t")           # InvalidOperationError: argument in operation 'asof_join' is not sorted
df1.join_asof(df2, on="t", by="id")  # OK (probably shouldn't be)
```

**Comment by oshermaayan** [comment] 2025-03-11 15:07
I opened a [new issue](https://github.com/pola-rs/polars/issues/21693).

I did not explicitly check how the `check_sortedness` flag affects the result. If it doesn't work as expected, shouldn't it be included in a different issue?
