### ISSUE TITLE
geometry column type support

### ISSUE THREAD

**Issue by radi2015** [pola-rs/polars#4023] opened 2022-07-15 03:20 UTC
#### Describe your feature request

Please describe the behavior you want and the motivation. Please also provide
examples of how polars would be used if your feature request were added.

If you're not sure what to write here, then try imagining what the ideal
documentation of your new feature would look like Then try to write it.

**Comment by zundertj** [comment] 2022-07-17 16:18
Hello, thank you for your request. Could you be more specific than just the title? In particular, but this is just a guess, what would you like in addition to the request in #1830?

**Comment by radi2015** [comment] 2022-07-18 11:33
like geopandas for pandas   https://github.com/geopandas/geopandas

may be it need another package support

**Comment by ritchie46** [comment] 2022-07-18 11:39
I will close this as it is duplicate of #1830. Discussion can be done in the main issue.

**Closed by ritchie46** 2022-07-18 11:39 UTC
Labels: feature, question
