### ISSUE TITLE
Process exited with error code: -1073741819 (0xC0000005) when tried to perform collect() on a lazyframe.

### ISSUE THREAD

**Issue by surenderchitteddy** [pola-rs/polars#10113] opened 2023-07-27 11:03 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
python - 3.8
polars - 0.18.2
-------------------
pds_dict
Out[2]: 
{'20221107_2': <polars.LazyFrame object at 0x1B9E929AFD0>,
 '20221107_4': <polars.LazyFrame object at 0x1B9E92E26D0>,
 '20221107_5': <polars.LazyFrame object at 0x1B9E92E2220>,
 '20221107_6': <polars.LazyFrame object at 0x1B9E930A190>,
 '20221108_2': <polars.LazyFrame object at 0x1B9E92E2D30>,
 '20221108_4': <polars.LazyFrame object at 0x1B9E930AE80>,
 '20221108_5': <polars.LazyFrame object at 0x1B9E930A220>,
 '20221108_6': <polars.LazyFrame object at 0x1B9E930AF10>,
 '20221109_2': <polars.LazyFrame object at 0x1B9E930A4C0>,
 '20221109_4': <polars.LazyFrame object at 0x1B9E930A730>,
 '20221109_5': <polars.LazyFrame object at 0x1B9E930ABB0>,
 '20221109_6': <polars.LazyFrame object at 0x1B9F57BB880>}
```
I tried to perform fetch() on the lazyframe as below and the result shows the columns but it wasn't able to fetch any records. 
```
pds_dict['20221107_2'].fetch()
Out[3]: 
shape: (0, 8)
```
I have also tried to perform collect() on the same lazyframe object which resulted in Process finished with exit code -1073741819 (0xC0000005)
```
pds_dict['20221107_2'].collect()
```

### Issue description

This piece of code which I am working on was producing the expected results earlier. However, I have been encountering this issue from past couple of days from the same code and environment which worked fine earlier.

### Expected behavior

This code was supposed to produce the polars dataframe, instead resulting in an error without traceback as below: 
**Process exited with error code: -1073741819 (0xC0000005)**

### Installed versions

<details>

```
pl.show_versions()
--------Version info---------
Polars:      0.18.2
Index type:  UInt32
Platform:    Windows-10-10.0.19041-SP0
Python:      3.8.1 (default, Mar  2 2020, 13:06:26) [MSC v.1916 64 bit (AMD64)]
----Optional dependencies----
numpy:       1.22.3
pandas:      1.5.3
pyarrow:     4.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.6.0
matplotlib:  3.5.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by ritchie46** [comment] 2023-07-27 11:20
Got an MWE? Without it we cannot do anything?

**Comment by surenderchitteddy** [comment] 2023-07-28 08:55
I will try to isolate this issue and get back to you. Thanks for your response Ritchie!

**Comment by stinodego** [comment] 2024-01-23 13:35
I am closing this due to lack of a reproducible example. Please open a new issue if you have something we can look at!

**Closed by stinodego** 2024-01-23 13:35 UTC
Labels: bug, python
