### ISSUE TITLE
join on column with dtype pl.Null panics 

### ISSUE THREAD

**Issue by somilgo** [pola-rs/polars#15837] opened 2024-04-22 22:57 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
s = pl.Series(["null"], dtype=pl.Null)
d = pl.DataFrame({"key": s, "value" : 0})
d.join(d, how="left", left_on="key", right_on="key", join_nulls=True)
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/series/series_trait.rs:55:13:
not implemented
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
      1 d = pl.DataFrame({"key": s, "value" : 0})
----> 2 d.join(d, how="left", left_on="key", right_on="key", join_nulls=True)

polars/dataframe/frame.py in join(self, other, on, how, left_on, right_on, suffix, validate, join_nulls)
   5964 
   5965         return (
-> 5966             self.lazy()
   5967             .join(
   5968                 other=other.lazy(),

polars/lazyframe/frame.py in collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, background, _eager)
   1698             return InProcessQuery(ldf.collect_concurrently())
   1699 
-> 1700         return wrap_df(ldf.collect())
   1701 
   1702     @overload

PanicException: not implemented
```

### Issue description

Using the latest version of polars

### Expected behavior

I definitely don't think polars should panic. I would like the output of the join to be identical to `d` in the example.  

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by coastalwhite** [comment] 2024-06-17 12:34
This doesn't reproduce anymore and seems to be fixed. It now returns.

```
shape: (1, 3)
┌──────┬───────┬─────────────┐
│ key  ┆ value ┆ value_right │
│ ---  ┆ ---   ┆ ---         │
│ null ┆ i32   ┆ i32         │
╞══════╪═══════╪═════════════╡
│ null ┆ 0     ┆ 0           │
└──────┴───────┴─────────────┘
```

Closing.

**Closed by coastalwhite** 2024-06-17 12:34 UTC
Labels: bug, python, needs triage, A-panic
