### ISSUE TITLE
Introcude pl.no_op() (no operation) expression.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#6877] opened 2023-02-14 17:59 UTC
### Problem description

Introduce pl.no_op() (no operation) expression.

This would allow to write complicated queries, which depend on some external python variables a bit nicer.

For example I had a function for which I want to display (or calculate) certain columns or not, based on parameters passed to a function.

Simplified example:

```python
def some_complex_query(df: pl.LazyFrame, cond1, cond2):
    return df.with_columns(
        pl.col("a").max().alias("a_max") if cond1 else pl.Nop(),
        pl.col("b").max().alias("b_max") if cond2 else pl.Nop(),
    )


# Return original dataframe.
some_complex_query(df, False, False)

# Add "a_max".
some_complex_query(df, True, False)

# Add "b_max".
some_complex_query(df, False, True)

# Add "a_max" and "b_max".
some_complex_query(df, True, True)
```

Edit: renamed expression name.

**Comment by alexander-beedie** [comment] 2023-02-14 18:49
That... is actually a very flexible concept/utility :)
(I'd probably name it `pl.no_op()` though)

**Comment by cmdlineluser** [comment] 2023-02-14 18:59
From experimenting with your example I noticed that `pl.col([])` seems to be allowed.

Not sure if this is intended behaviour or not.
```
def some_complex_query(df, cond1, cond2):
    columns = []
    if cond1: columns.append("a")
    if cond2: columns.append("b")
    return df.with_columns(pl.col(columns).max().suffix("_max"))

df = pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
```
```
>>> some_complex_query(df, False, True)
shape: (3, 3)
┌─────┬─────┬───────┐
│ a   | b   | b_max │
│ --- | --- | ---   │
│ i64 | i64 | i64   │
╞═════╪═════╪═══════╡
│ 1   | 4   | 6     │
│ 2   | 5   | 6     │
│ 3   | 6   | 6     │
└─────┴─────┴───────┘
```
```
>>> some_complex_query(df, False, False)
shape: (3, 2)
┌─────┬─────┐
│ a   | b   │
│ --- | --- │
│ i64 | i64 │
╞═════╪═════╡
│ 1   | 4   │
│ 2   | 5   │
│ 3   | 6   │
└─────┴─────┘
```
(Not that this covers other potential uses of your suggested feature.)

**Comment by alexander-beedie** [comment] 2023-02-14 20:13
There are certainly workarounds, but a dedicated/supported expression is going to be generically more useful in a wider set of possible constructs (and more useable inline), with no shenanigans required ;)

**Comment by ghuls** [comment] 2023-02-14 20:26
> (I'd probably name it `pl.no_op()` though)

Yeah, that is better. I thought it should be with a capital, but that would be for a datatype.

@deanm0000 I know I can implement it like this (and have it like this with a pipe call), but it makes the code harder to reason about as there are further chained calls.

**Comment by mcrumiller** [comment] 2023-02-14 20:35
This is almost identical to my open issue from a long time ago #4881. I have wanted this forever because it makes building expression chains MUCH easier. So yeah, when you close this one, you can close 4881 too.

**Comment by mcrumiller** [comment] 2023-02-14 20:38
Hmm, on second thought, this is definitely a little different, since you can't change a `pl.when` to the end of an arbitrary expression, even a no-op expr. However, I suppose you could begin your chain with `pl.when(False).then(pl.no_op())` and low cost.

**Comment by ritchie46** [comment] 2023-02-14 20:47
I think this might work on entry of some logical plan nodes. We can optimize away the `NoOpExpr`. 

However deep in expressions such as `when().then() .otherwise ()` I don't see how this would work. They must materialize to a `Series`. We could allow it only as top level expression so that the we comstrain it to the first situation.

**Comment by ghuls** [comment] 2023-02-14 20:58
> I think this might work on entry of some logical plan nodes. We can optimize away the `NoOpExpr`.
> 
> However deep in expressions such as `when().then() .otherwise ()` I don't see how this would work. They must materialize to a `Series`. We could allow it only as top level expression so that the we comstrain it to the first situation.

It is fine for me if it is only done for simple ones.

**Comment by ritchie46** [comment] 2023-07-17 13:25
That would break assumptions expressions have. They get a `Series` as input when materialized.

**Comment by stinodego** [comment] 2024-02-18 20:16
I really don't see the benefit of this. You could already write this logic easily as @deanm0000 pointed out.

I am going to close this issue as not planned as there are some technical challenges and the benefit is not clear.

**Closed by stinodego** 2024-02-18 20:16 UTC
Labels: enhancement
