### ISSUE TITLE
use pyarrow support for scan_parquet 

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#2633] opened 2022-02-13 11:23 UTC
Hi;

Is it possible to add pyarrow support for scan_parquet? 

Thanks.

**Comment by ritchie46** [comment] 2022-02-13 11:42
No it is not possible. Why would you want this? You miss a dtype?

**Comment by ritchie46** [comment] 2022-02-13 14:48
Could you share the file? 

Another questions: Does it work if you turn `parallel=False`? It could be that we allocate to much memory in front.

**Comment by hakantekbas** [comment] 2022-02-13 17:47
Can you try this?

```
data = pl.DataFrame({"hashId":["dsfddfggsdeewr8ryf4gkwerhnqweijgrenwsbyr"]*50_000_000,"trial":["dfge3"]*50_000_000} )
data.to_parquet("test.parquet")
data = pl.read_parquet("test.parquet")
```

Error message:

> memory allocation of 18446744071620834324 bytes failed

**Comment by ritchie46** [comment] 2022-02-13 19:47
Thanks.. will look into it.

**Comment by ghuls** [comment] 2022-02-14 00:44
Writing it uncompressed and reading already seems to give issues:
```python
In [4]: data.to_parquet("test.uncompressed.parquet", compression="uncompressed")

In [7]: data2 = pl.read_parquet("test.uncompressed.parquet")
thread '<unnamed>' panicked at 'column start and length should not be negative', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet2-0.10.0/src/metadata/column_chunk_metadata.rs:129:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-7-2d7de646e58a> in <module>
----> 1 data2 = pl.read_parquet("test.uncompressed.parquet")

~/software/polars/py-polars/polars/io.py in read_parquet(source, columns, n_rows, use_pyarrow, memory_map, storage_options, parallel, row_count_name, row_count_offset, **kwargs)
    869             )
    870
--> 871         return DataFrame._read_parquet(
    872             source_prep,
    873             columns=columns,

~/software/polars/py-polars/polars/internals/frame.py in _read_parquet(file, columns, n_rows, parallel, row_count_name, row_count_offset)
    535         projection, columns = handle_projection_columns(columns)
    536         self = DataFrame.__new__(DataFrame)
--> 537         self._df = PyDataFrame.read_parquet(
    538             file,
    539             columns,

PanicException: column start and length should not be negative
```

@jorgecarleitao

**Comment by jorgecarleitao** [comment] 2022-02-14 06:02
I found the root cause for this: a data page in parquet can only hold up to `i32::MAX` of uncompressed bytes, and the example has more than that:

```
println!("{} {}", i32::MAX as usize, ("dsfddfggsdeewr8ryf4gkwerhnqweijgrenwsbyr".len() + 4)*50_000_000);
```

yields `2147483647 2200000000`

so, some re-chunking is needed. There is still a bug because the writer should error out; I will address that. There is an improvement where we split the column chunk in smaller pages, but that is not yet supported.

**Comment by ritchie46** [comment] 2022-02-14 07:32
> There is an improvement where we split the column chunk in smaller pages, but that is not yet supported.

Does if make sense if polars would send an iterator of a fixed `Chunk` size to arrows writer? Or should all this be done upstream?

**Comment by hakantekbas** [comment] 2022-02-15 15:00
I have also another issue. When I prefer snappy compression, memory can rise up to 100 gb in lazy computation but it did not free up memory after collect action is over. But if it is gzip, memory is freed up. Probably you will ask for a sample, but data size is really big. If it is not expected, I will prepare a sample or code for you to replicate behaviour.

**Comment by hakantekbas** [comment] 2022-02-15 19:46
ok. I will open when I create a sample data for you. Will I keep this issue open?

**Comment by ritchie46** [comment] 2022-02-15 20:50
As I understand it we need to add a feature to the parquet reader that can chunk pages determined by the row count. This is not something we can do yet. A feature request for this is best fitted upstream, but I think it is in the pipeline/roadmap, so I will close this here.

**Closed by ritchie46** 2022-02-15 20:50 UTC
