### ISSUE TITLE
More that one character as separator for CSV reader

### ISSUE THREAD

**Issue by elferherrera** [pola-rs/polars#2728] opened 2022-02-22 06:22 UTC
#### Describe your feature request

Is it possible to assign multiple characters as separator for the CSV reader? 

A nushell developer is working with special files that need a three characters separator because the file has weird characters in the columns, and sometimes those characters can be semicolons.

**Comment by ritchie46** [comment] 2022-02-22 07:30
This would lead to a very large regression in the csv parsers performance, which I don't want for Polars. I think that for such special cases you could write wrapper parsers which takes a buffer `&[u8]` and has a pre-allocated write buffer `&mut [u8]`, where you read from the read buffer and replace the multibyte delimiter with a single byte one.

The intermediate written buffer is then send to the csv parser. And then rinse and repeat.

**Comment by elferherrera** [comment] 2022-02-22 07:42
That would be the same as doing grep on the file and replace the special separator, no?

**Comment by ritchie46** [comment] 2022-02-22 07:55
> That would be the same as doing grep on the file and replace the special separator, no?

Yep, but than in process. If you read the csv file many times, doing that one time csv fix is likely worth it. @ghuls knows pretty good tooling for fixing csv's.

Maybe we should document that.

**Comment by elferherrera** [comment] 2022-02-22 08:05
The only issue with that is that your replaced character may end up appearing inside the column. Since these are massive files, I don't know how feasible it could be to search first the whole file looking for a character that never appears and then use that as your replacement. What do you think @fdncred?

**Comment by ritchie46** [comment] 2022-02-22 08:13
Maybe `xsv fmt` can help with that?

https://github.com/BurntSushi/xsv

**Comment by elferherrera** [comment] 2022-02-22 08:25
That is a nice crate. Im installing it now

**Comment by fdncred** [comment] 2022-02-22 12:55
It's nice to have suggestions but none of these will work. I was looking at 1 file yesterday that is 159GB. Trying to find a single character which isn't used and then trying to replace the 3 character delimiter with that is not useful unfortunately. I have over 500GB of csv files all separated this way because it's the best way to handle the data. It's unfortunate that no crates in the rust ecosystem support such a thing.

To explain a little of the back story, we first started normally with something like a pipe as a delimiter because it works most of the time. But not this time. This data is data that has been processed with OCR. If you have any experience with OCR, you'll know that sometimes images look bad and when you try to recognize text in a bad part of the image you get "garbage". This "garbage" can literally be any character and it's just a mess. So, in order to avoid having powershell and sql server get confused while doing a bulk load of this data, we had to choose a delimiter that would never appear, even in the garbage. It turns out that that you cannot use a single character because they all appear, so then you have to resort to using multiple characters. So, we chose this as a delimiter that would (probably) never appear in OCR "garbage" text, `»¦«`.

Now the text parses fine and after using this delimiter for over 2 years now for this data, it's never occurred naturally and we're able to bulk load this data into a sql server database. Microsoft's tools work great with multi-character delimiters, however there are no rust crates that I've found that will support this. I'd love to rewrite all our tools in rust but without this cornerstone piece of software, it's just not even worth starting.

Thanks for the suggestions anyway. I was hoping to use nushell's dataframes to analyze this data but it sounds like that won't be possible either.

**Comment by alexander-beedie** [comment] 2022-02-22 13:15
@fdncred @elferherrera : As silly as this may initially sound... you don't actually have to choose a _printable_ character as your delimiter. If you chose the (single character, ascii-compliant) value of `"\x08"` (as a python string), for example, you could be entirely confident that your OCR data won't contain it, because it is the BS control character representing a backspace/delete. As a non-printing character, it has no visual representation, so OCR _cannot_ result in this value.

If you can preprocess your data to replace your current 3-char delim with this instead, you should be able to use any CSV parser you like, be it xsv, polars, or otherwise.

**Comment by ghuls** [comment] 2022-02-22 13:19
@fdncred So does it also contain non-printable characters like `\0`, `\f` \x1f` (unit separator)?
Or any other character before space in the ascii table?
```
       Oct   Dec   Hex   Char                        Oct   Dec   Hex   Char
       ────────────────────────────────────────────────────────────────────────
       000   0     00    NUL '\0' (null character)   100   64    40    @
       001   1     01    SOH (start of heading)      101   65    41    A
       002   2     02    STX (start of text)         102   66    42    B
       003   3     03    ETX (end of text)           103   67    43    C
       004   4     04    EOT (end of transmission)   104   68    44    D
       005   5     05    ENQ (enquiry)               105   69    45    E
       006   6     06    ACK (acknowledge)           106   70    46    F
       007   7     07    BEL '\a' (bell)             107   71    47    G
       010   8     08    BS  '\b' (backspace)        110   72    48    H
       011   9     09    HT  '\t' (horizontal tab)   111   73    49    I
       012   10    0A    LF  '\n' (new line)         112   74    4A    J
       013   11    0B    VT  '\v' (vertical tab)     113   75    4B    K
       014   12    0C    FF  '\f' (form feed)        114   76    4C    L
       015   13    0D    CR  '\r' (carriage ret)     115   77    4D    M
       016   14    0E    SO  (shift out)             116   78    4E    N
       017   15    0F    SI  (shift in)              117   79    4F    O
       020   16    10    DLE (data link escape)      120   80    50    P
       021   17    11    DC1 (device control 1)      121   81    51    Q
       022   18    12    DC2 (device control 2)      122   82    52    R
       023   19    13    DC3 (device control 3)      123   83    53    S
       024   20    14    DC4 (device control 4)      124   84    54    T
       025   21    15    NAK (negative ack.)         125   85    55    U
       026   22    16    SYN (synchronous idle)      126   86    56    V
       027   23    17    ETB (end of trans. blk)     127   87    57    W
       030   24    18    CAN (cancel)                130   88    58    X
       031   25    19    EM  (end of medium)         131   89    59    Y
       032   26    1A    SUB (substitute)            132   90    5A    Z
       033   27    1B    ESC (escape)                133   91    5B    [
       034   28    1C    FS  (file separator)        134   92    5C    \  '\\'
       035   29    1D    GS  (group separator)       135   93    5D    ]
       036   30    1E    RS  (record separator)      136   94    5E    ^
       037   31    1F    US  (unit separator)        137   95    5F    _
       040   32    20    SPACE                       140   96    60    `
```

**Comment by alexander-beedie** [comment] 2022-02-22 13:39
@ghuls: You read my mind - though the one char that you shouldn't use there is "\0" (NUL), due to C-string null terminators; can potentially cause bad reads depending on the parser (I'd probably also avoid any newline-related chars like "\n", "\f", "\r", and "\t", in case those can be produced as newlines on whatever platform creates the files, or the OCR data can create tabs).

Semantically, maybe hex `1E` from that table is ideal: "Record Separator" :)

**Comment by fdncred** [comment] 2022-02-22 16:20
Thanks for the suggestions. In fact, OCR data can return all kinds of crazy non-printable characters. It's unfortunate that we cannot control this as it's from an external source. Most modern OCR engines allow you to filter output to "normal" type output ala `:alphanum:`, `:punct:`, `:space:`, etc. Another limiting factor is, as i hinted to above, this is for sql server and is processed with sqlcmd bulk insert so it must be compliant with [sqlcmd](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/specify-field-and-row-terminators-sql-server?view=sql-server-ver15), which is one of the reasons we can't use non-printable characters. interestingly enough, sqlcmd support a field terminator of up to 10 characters - they're really trying hard there. haha.

one last comment, the challenge is not to figure out a way to change the csv separator. the challenge is to accept the sql separator that we have, which apparently isn't really possible right now. although ritchie's comment about changing from `u8` to `&[u8]` as the data is loaded, as kind of a pre-processing step, has merit. i've always wanted to try the record separator and see what it does in a situation like this but i haven't studied it's interaction with sqlcmd enough yet.

Thank you all, again.

**Comment by slonik-az** [comment] 2022-02-22 16:31
> In fact, OCR data can return all kinds of crazy non-printable characters

Are these non-printable chars really useful? You might want to  clean up the OCR data anyway. As a part of cleanup process you can covert multi-byte separator to a single non-printable one (BackSpace as suggested earlier). IMHO polars should not become a kitchen sink for arbitrary data preprocessing.

**Comment by ghuls** [comment] 2022-02-22 16:57
Do you have an example file (or first 1000 lines or so)?

**Comment by jorgecarleitao** [comment] 2022-02-22 16:58
It is likely that your team considered this, but still worth knowing the rationale: have you considered not using CSV?

The main problem with CSV is that it does not support generic binary data. In binary data, given enough characters, we will produce a sequence of bytes that collides with any delimiter we choose.

From this discussion, it seems that the ORC reader is producing generic binary data (I mean, it produces a backspace from a text, so at this point I would assume that any valid byte will be produced). Using a 3-byte delimiter is a way to reduce the risk of collision, but it offers no guarantee that the it won't happen in the future.

The risk is that if we have a CSV file with a delimiter X and append a field whose content contains X, we invalidate the CSV from that point onwards, as there is no easy way to recover from it (without writing a custom state machine to handle that edge case knowning more about the neighbor context of that offending content).

There are formats that are intended to solve that problem (e.g. Avro and Parquet store binary data as `[length in bytes][bytes]`). Given that your files are already 150 Gb, it may make sense to adopt a format that both handles binary natively, as well as is more suitable for such large file sizes (e.g. block compression, reading in batches, projection pushdown).

**Comment by elferherrera** [comment] 2022-02-22 17:47
Nice. In the future I want to experiment in Nushell reading SQL directly. This is going to help a lot.

Regarding the parsing, how difficult would it be for Polars (Arrow2) to have another function that takes a &[u8] as the delimiter?. It doesnt have to be the same function that does the loading and could not be as optimized as the actual function

**Comment by ritchie46** [comment] 2022-02-23 07:17
> Regarding the parsing, how difficult would it be for Polars (Arrow2) to have another function that takes a &[u8] as the delimiter?.

I think we should not facilitate this in polars. Especially for Rust users it is an edge case that could be fixed by themselves by `de-delimiting` (new scrabble word!) the batches before sending them to polars.

**Comment by ghuls** [comment] 2022-02-23 08:10
If your input CSV file writes a proper quoted fields (where double quotes are escaped by `""`, you could just use a normal delimiter to split on fields.

**Comment by ritchie46** [comment] 2022-02-23 08:20
> If your input CSV file writes a proper quoted fields (where double quotes are escaped by `""`, you could just use a normal delimiter to split on fields.

Yes, I was just thinking that. The closest thing to a reference on csv: https://datatracker.ietf.org/doc/html/rfc4180 describes this.

**Comment by ghuls** [comment] 2022-02-23 08:28
```python
import numpy as np
import polars as pl

# Create whole ASCII table.
In [38]: ascii_table = np.arange(0,128, dtype=np.uint8).tobytes().decode("utf-8")

# Quote each character and put in a separate field. (" needs to be escaped like "").
In [39]: csv_bytes = '"' + '","'.join([b for b in ascii_table]).replace(',""",', ',"""",') + '"\n'

In [40]: ascii_table
Out[40]: '\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\x7f'

In [41]: csv_bytes
Out[41]: '"\x00","\x01","\x02","\x03","\x04","\x05","\x06","\x07","\x08","\t","\n","\x0b","\x0c","\r","\x0e","\x0f","\x10","\x11","\x12","\x13","\x14","\x15","\x16","\x17","\x18","\x19","\x1a","\x1b","\x1c","\x1d","\x1e","\x1f"," ","!","""","#","$","%","&","\'","(",")","*","+",",","-",".","/","0","1","2","3","4","5","6","7","8","9",":",";","<","=",">","?","@","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","[","\\","]","^","_","`","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","{","|","}","~","\x7f"\n'

# read_csv works fine when fields are quoted like this:
In [42]: pl.read_csv(csv_bytes.encode('utf-8'), has_header=False, quote_char='"')
Out[42]:
shape: (1, 128)
┌──────────┬──────────┬──────────┬──────────┬─────┬────────────┬────────────┬────────────┬────────────┐
│ column_1 ┆ column_2 ┆ column_3 ┆ column_4 ┆ ... ┆ column_125 ┆ column_126 ┆ column_127 ┆ column_128 │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆     ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str      ┆ str      ┆ str      ┆ str      ┆     ┆ str        ┆ str        ┆ str        ┆ str        │
╞══════════╪══════════╪══════════╪══════════╪═════╪════════════╪════════════╪════════════╪════════════╡
│          ┆          ┆          ┆          ┆ ... ┆ |          ┆ }          ┆ ~          ┆            │
└──────────┴──────────┴──────────┴──────────┴─────┴────────────┴────────────┴────────────┴────────────┘
```

**Comment by ritchie46** [comment] 2022-03-16 10:03
I will close this as this will not be done in polars

**Closed by ritchie46** 2022-03-16 10:03 UTC
Labels: feature, wontfix

**Comment by NarayanB** [comment] 2023-01-02 00:02
Hi @ritchie46,
I had read your concern about performance of supporting read_csv with multiple characters as separator. In finance world, we have lot of legacy systems that send big csv gz files with multiple character separators. It is not possible to change the upstream. Do you want to consider adding a kwargs to read_csv to support multiple separator ?  The default option would be false and so users are aware of the small penalty of parser. I still feel this option would be faster than Pandas. Please let me know your opinion either way.

**Comment by alexander-beedie** [comment] 2023-01-05 18:50
> In finance world, we have lot of legacy systems that send big csv gz files with multiple character separators. It is not possible to change the upstream. 

@NarayanB: I'm enormously curious as to what format these files these are; I've worked in the financial world for two decades and I'm pretty sure I've never seen one (unless it's an in-house format - that wouldn't surprise me as there are some true abominations in that genre...) :) 

If you can point me at an example of one I might have some ideas that can help you out, but I don't see this feature making it into polars natively; it's an enormously niche use-case with non-trivial performance/complexity.

**Comment by NarayanB** [comment] 2023-01-05 21:19
@alexander-beedie -> I'm working in financial world for 3 decades. Not every project will have this requirement. In regulatory projects, some in-house csv datasets will have more than 100 million rows zipped csv. I myself had processed a 250 million row feed using polars, which was a breeze due to standard seperator. The same cannot be said of all feeds. Different feeds have different seperators (multi-character). I would agree with @ritchie46 and others above that such multi-character feeds would add performance overhead.  These internal feeds come daily and/or monthly (not a once in a year phenomena). The recent dataset that i worked had a billion rows. It is my understanding that Pandas, Spark, Arrow do support this multi-character seperator. They are also aware of time consumption of their own read_csv method.  I can easily do this in pyarrow read_csv. Since polars has the capability of using underlying pyarrow engine, i had asked to enhance the API. While there are ways to extract the file (zipped or unzipped) and change the seperator and rewrite the zipped file, it is not advisable as these are regulatory related and so it is not a good practice to touch the golden copy. Btw, I had worked with the same multi-character zipped csv at multiple banks. I'm sure Polars will add this over a period of time. Pandas had resisted this initially too :)

**Comment by ritchie46** [comment] 2023-01-06 10:05
>  Pandas had resisted this initially too :)

Pandas should have kept their foot down on multiple occasions. ;)

Only thing I can foresee supporting is rewriting in memory from multichar delimited to single byte delimited and then parse with our single byte reader.

**Comment by ghuls** [comment] 2023-01-06 10:23
> It is my understanding that Pandas, Spark, Arrow do support this multi-character seperator.

pyarrow CSV reader (which should be the same as the C++ CSV reader) does not support multibyte separators as far as I can see.
Pandas only supports it, when it falls back to the slowest engine (`python`, instead of `c` or `pyarrow`).

**Comment by fdncred** [comment] 2023-01-06 15:25
> Only thing I can foresee supporting is rewriting in memory from multichar delimited to single byte delimited and then parse with our single byte reader.

At least this option would allow a way forward, even if it's not the most efficient. Speaking for myself, I'd rather have a somewhat slower/inefficient builtin way to handle multi-char delimiters than no way at all.

**Comment by n8henrie** [comment] 2023-01-06 17:27
Long time pandas hobbyist, now learning rust and polars. I was hoping to contribute to this thread a code example of using a custom field separator (and maybe to the docs as well if that would be helpful) -- it seems like this isn't an entirely uncommon concern (https://github.com/pola-rs/polars/issues/3374, https://github.com/pola-rs/polars/issues/4546). Unfortunately I'm having more trouble putting together an example than I expected.

I have a log file that uses ` :: ` as a field separator, which I can guarantee only appears in the FS position. I thought it would be simple to write an iterator adapter to `BufReader` using `replace`, but unfortunately `from_path` requires something like `Into<PathBuf>` (instead of just `impl Read` or something).

Using `CsvReader::new` unfortunately requires an `MmapBytesReader` (not just a Reader), which I assume means I need to have the entire file read into memory first (in order to ensure it is valid utf8 in order to perform the `replace` with a string). Does that sound right? 

I eventually gave up on a lazy / by-line solution, since my example easily fits in memory, but I would love help here if someone can provide a working idiomatic example. Is my code at the bottom pretty close to what was envisioned in comments like those below?

> Only thing I can foresee supporting is rewriting in memory from multichar delimited to single byte delimited and then parse with our single byte reader.

> I think that for such special cases you could write wrapper parsers which takes a buffer &[u8] and has a pre-allocated write buffer &mut [u8], where you read from the read buffer and replace the multibyte delimiter with a single byte one.

```rust
#![warn(clippy::pedantic)]
use std::{error, result};

use polars::prelude::*;

use std::io::Cursor;

type Error = Box<dyn error::Error + Send + Sync>;
type Result<T> = result::Result<T, Error>;

fn main() -> Result<()> {
    let sep = '\x1E';
    let data = std::fs::read_to_string("../log.txt")?.replace(" :: ", sep.to_string().as_ref());
    let df = CsvReader::new(Cursor::new(data))
        .with_delimiter(sep as u8)
        .finish()
        .unwrap();
    dbg!(df.head(Some(5)));
    Ok(())
}
```

**Comment by NarayanB** [comment] 2023-01-06 17:55
@ghuls -> You are correct. If you need to use multi char delimiter, you need to fallback to engine='python' in pandas. And PyArrow ParseOptions doesn't support multi-char delimiter

**Comment by NarayanB** [comment] 2023-01-06 17:57
This link has some idea if you want to do in-memory reading - https://stackoverflow.com/questions/7012398/can-the-csv-module-parse-files-with-multi-character-delimiters

The concept applies to any language ..
