### ISSUE TITLE
wrong return type in `partition_by` with `as_dict=True`

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#11569] opened 2023-10-06 14:46 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl

df = pl.DataFrame({'a': [0, 1, 2], 'b': [0, 0, 0]})

print(type(list(
    df
    .partition_by(by = 'a', as_dict=True)
    .keys()
)[0]))
# <class 'int'> # good

print(type(list(
    df
    .partition_by(by=['a', 'b'], as_dict=True)
    .keys()
)[0]))
# <class 'tuple'># good

print(type(list(
    df
    .partition_by(by=['a'], as_dict=True)
    .keys()
)[0]))
# <class 'int'> # bad



```

### Issue description

IMO, the return type should depend on the type of `by` not the length of `by`.

### Expected behavior

when `by` is a list, I except a tuple as key in the dictionary, even if the length of `by` < 1.

By the way, if `by` is a empty list, we could return dict with one element: {tuple(), df} instead of raising an error.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by orlp** [comment] 2023-10-06 15:31
I don't necessarily think this is doing the wrong thing here.

**Comment by gab23r** [comment] 2023-10-06 15:39
Really, you don't think that the type of the output should be determined by the type of the inputs ( no matter of the data itself ) ?

**Comment by cjackal** [comment] 2023-10-06 18:35
Most `polars` projection-related functions accept iterables and unwraps them, e.g. `.select`, `.drop`, `.group_by`, ... I think current behavior of `.partition_by` gives better API consistency.

BTW, this issue does not look like a bug report, the `bug` tag is misleading.

**Comment by gab23r** [comment] 2023-10-06 18:38
I can understand your point, In my use case I have a generic function that performs checks on my data per partition. I had to introduce a special case if my data had only one partition key, which was a bit surprising.

**Comment by ritchie46** [comment] 2023-10-07 05:54
I think I will close this as this intended behaviour.

**Closed by ritchie46** 2023-10-07 05:54 UTC
Labels: bug, python

**Comment by CaselIT** [comment] 2024-01-08 10:59
In the other issue that seems to ask something similar to this one https://github.com/pola-rs/polars/issues/13371 we noticed that the same baheviour happens also when using selectors.

See my comment here https://github.com/pola-rs/polars/issues/13371
