### ISSUE TITLE
`CsvWriter` doesn't properly escape strings

### ISSUE THREAD

**Issue by rben01** [pola-rs/polars#2907] opened 2022-03-16 04:49 UTC
#### What language are you using?

Rust

#### Which feature gates did you use?

```	
polars = { version = "0.20.0", features = [
	"csv-file",
	"dtype-struct",
	"json",
	"lazy",
	"strings",
	"temporal",
] }
```

#### What version of polars are you using?

`0.20.0`

#### What operating system are you using polars on?

macOS 12.3

#### What language version are you using
Rust 1.59.0

#### Describe your bug.

When a DataFrame has Utf8 columns that contain text that requires escaping, `CsvWriter` does not escape it correctly, leading to a malformed CSV file.

#### What are the steps to reproduce the behavior?

```
let mut df = DataFrame::new(vec![
	Series::new("a", [r#"funky string#1""""#, "\"\"funky\nstring#2\""]),
	Series::new("b", [",", ",,\n,,"]),
])?;

let out_file = OpenOptions::new()
	.create(true)
	.truncate(true)
	.write(true)
	.open("out.csv")?;

CsvWriter::new(out_file).has_header(true).finish(&mut df)?;
```

#### What is the actual behavior?

`out.csv`:
```csv
a,b
"funky string#1"""""",",
""""funky
string#2"",,,
,,
```

Here is a screenshot of how that's interpreted by Excel:

<img width="214" alt="image" src="https://user-images.githubusercontent.com/766670/158518409-fa3c602b-abc3-480b-9cbf-3ef880076a3f.png">

#### What is the expected behavior?

If I use Polars's `JsonWriter` to write to JSON and then use Python pandas to read that JSON into a DataFrame `df` and then call `df.to_csv("out2.csv", index=False)`, I get the desired output:

`out2.csv`:
```csv
a,b
"funky string#1""""""",","
"""""funky
string#2""",",,
,,"
```

which Excel interprets as the following:

<img width="169" alt="image" src="https://user-images.githubusercontent.com/766670/158518365-2326a98c-3d6d-4e1b-b43d-316a5cc91f05.png">

For completeness, here's the JSON produced by `JsonWriter` (after prettification):

```json
[
  {
    "a": "funky string#1\"\"\"",
    "b": ","
  },
  {
    "a": "\"\"funky\nstring#2\"",
    "b": ",,\n,,"
  }
]
```

**Comment by ritchie46** [comment] 2022-03-16 06:45
Thanks. Duplicate of #2892

**Closed by ritchie46** 2022-03-16 06:45 UTC
Labels: bug
