### ISSUE TITLE
Selecting columns by boolean condition

### ISSUE THREAD

**Issue by linusheinz** [pola-rs/polars#12612] opened 2023-11-21 22:22 UTC
### Description

I was looking for a way to drop all null columns and the Docs recommend 

`df[[s.name for s in df if not (s.null_count() == df.height)]]`

which seems very elaborate for a mundane task. 
I would find it very helpful to have column selection based on boolean filters.
Something along the lines: 
```
import polars.selectors as cs
df.drop(cs.boolean_filter(pl.all().is_null().all()))
```

**Comment by deanm0000** [comment] 2023-11-21 22:32
duplicate of [this](https://github.com/pola-rs/polars/issues/6895)

TLDR: It can't happen because select only knows about the schema not the data.

**Closed** 2023-11-22 10:01 UTC
Labels: enhancement
