### ISSUE TITLE
Incorrect PolarsInefficientMapWarning for object columns

### ISSUE THREAD

**Issue by Insomniac66** [pola-rs/polars#13246] opened 2023-12-25 17:00 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from pathlib import Path
import polars as pl

df = pl.DataFrame({
    'number': [ 1, 2, 3 ],
    'filepath': [ Path('1.txt'), Path('2.txt'), Path('3.txt') ]
})

df.with_columns(pl.col('filepath').map_elements(str))
```
Which produces the following warning:
```
PolarsInefficientMapWarning: 
Expr.map_elements is significantly slower than the native expressions API.
Only use if you absolutely CANNOT implement your logic otherwise.
Replace this expression...
  - pl.col("filepath").map_elements(str)
with this one instead:
  + pl.col("filepath").cast(pl.Utf8)

  df.with_columns(pl.col('filepath').map_elements(str))
```

### Issue description

I have a dataframe containing a column of `pathlib.Path` type objects, which in turn has the polars type `object`. I am trying to turn these into strings so I may work with them from polars.

This warning shown is incorrect, since the suggested code (which I had intuitively tried first) produces a compute error (`ComputeError: cannot cast 'Object' type`).

### Expected behavior

Either the suggested fix (`.cast(pl.Utf8)`) ought to work or there should be no warning.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment] 2024-01-23 13:05
Duplicate of #10269

**Closed by stinodego** 2024-01-23 13:05 UTC
Labels: bug, python, P-low
