### ISSUE TITLE
`datetime_range` throws an exception when `start` or `end` is an ambiguous local time

### ISSUE THREAD

**Issue by michelbl** [pola-rs/polars#12989] opened 2023-12-11 14:14 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import datetime
from zoneinfo import ZoneInfo

import polars as pl

a = pl.datetime_range(
    start=datetime(2023, 10, 29, 0, tzinfo=ZoneInfo("Europe/Paris")),
    end=datetime(2023, 10, 29, 3, tzinfo=ZoneInfo("Europe/Paris")),
    interval="30m",
    closed="left",
    time_unit="ms",
    eager=True,
)
# OK

b = pl.datetime_range(
    start=datetime(2023, 10, 29, 1, tzinfo=ZoneInfo("Europe/Paris")),
    end=datetime(2023, 10, 29, 2, fold=0, tzinfo=ZoneInfo("Europe/Paris")),
    interval="30m",
    closed="left",
    time_unit="ms",
    eager=True,
)
# Traceback (most recent call last):
#   File "/home/michel/tech/dsconnect-natgas/backend/components/dsflow/notebooks/polars_bug_report.py", line 16, in <module>
#     b = pl.datetime_range(
#         ^^^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/functions/range/datetime_range.py", line 193, in datetime_range
#     return F.select(result).to_series()
#            ^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/functions/lazy.py", line 1794, in select
#     return pl.DataFrame().select(*exprs, **named_exprs)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/dataframe/frame.py", line 7791, in select
#     return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/utils/deprecation.py", line 100, in wrapper
#     return function(*args, **kwargs)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1788, in collect
#     return wrap_df(ldf.collect())
#                    ^^^^^^^^^^^^^
# polars.exceptions.ComputeError: datetime '2023-10-29 02:00:00' is ambiguous in time zone 'Europe/Paris'. Please use `ambiguous` to tell how it should be localized.

c = pl.datetime_range(
    start=datetime(2023, 10, 29, 2, fold=0, tzinfo=ZoneInfo("Europe/Paris")),
    end=datetime(2023, 10, 29, 3, tzinfo=ZoneInfo("Europe/Paris")),
    interval="30m",
    closed="left",
    time_unit="ms",
    eager=True,
)
# Traceback (most recent call last):
#   File "/home/michel/tech/dsconnect-natgas/backend/components/dsflow/notebooks/polars_bug_report.py", line 45, in <module>
#     c = pl.datetime_range(
#         ^^^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/functions/range/datetime_range.py", line 193, in datetime_range
#     return F.select(result).to_series()
#            ^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/functions/lazy.py", line 1794, in select
#     return pl.DataFrame().select(*exprs, **named_exprs)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/dataframe/frame.py", line 7791, in select
#     return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/utils/deprecation.py", line 100, in wrapper
#     return function(*args, **kwargs)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1788, in collect
#     return wrap_df(ldf.collect())
#                    ^^^^^^^^^^^^^
# polars.exceptions.ComputeError: datetime '2023-10-29 02:00:00' is ambiguous in time zone 'Europe/Paris'. Please use `ambiguous` to tell how it should be localized.

d = pl.datetime_range(
    start=datetime(2023, 10, 29, 2, fold=1, tzinfo=ZoneInfo("Europe/Paris")),
    end=datetime(2023, 10, 29, 3, tzinfo=ZoneInfo("Europe/Paris")),
    interval="30m",
    closed="left",
    time_unit="ms",
    eager=True,
)
# Traceback (most recent call last):
#   File "/home/michel/tech/dsconnect-natgas/backend/components/dsflow/notebooks/polars_bug_report.py", line 74, in <module>
#     d = pl.datetime_range(
#         ^^^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/functions/range/datetime_range.py", line 193, in datetime_range
#     return F.select(result).to_series()
#            ^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/functions/lazy.py", line 1794, in select
#     return pl.DataFrame().select(*exprs, **named_exprs)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/dataframe/frame.py", line 7791, in select
#     return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/utils/deprecation.py", line 100, in wrapper
#     return function(*args, **kwargs)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/michel/.cache/pypoetry/virtualenvs/venv-name/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1788, in collect
#     return wrap_df(ldf.collect())
#                    ^^^^^^^^^^^^^
# polars.exceptions.ComputeError: datetime '2023-10-29 02:00:00' is ambiguous in time zone 'Europe/Paris'. Please use `ambiguous` to tell how it should be localized.
```

### Log output

see above

### Issue description

When `pl.datetime_range` is provided a time bound that is an ambiguous local time, it raises an exception.

For example, 2023-10-29-02:00:00 Europe/Paris represents two instants : 2023-10-29-02:00:00 CEST and 2023-10-29-02:00:00 CET.

Datetime ranges that contain ambiguous local times (but whose bouds are not ambiguous) are handled correctly, giving the false impression that local times are handled correctly.

### Expected behavior

Since ambiguous local times are disambiguated using the fold attribute introduced by PEP 495, there is no reason to throw an exception.

If `pl.datetime_range` support for local timezones is not planned, then I would expect `pl.datetime_range` to throw if any local datetime is passed.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-6.2.0-37-generic-x86_64-with-glibc2.35
Python:               3.11.4 (main, Jun 26 2023, 15:13:33) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.3
pyarrow:              11.0.0
pydantic:             2.5.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.23
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment] 2023-12-11 14:26
thanks @michelbl for the report

closing as a duplicate of https://github.com/pola-rs/polars/issues/11713 , there's a suggested workaround there (I would like to fix this, just haven't got round to it)

**Closed by MarcoGorelli** 2023-12-11 14:26 UTC
Labels: bug, python
