### ISSUE TITLE
90 Performance Tests: JoinTable@BillionRows Fails (No Steaming Method)

### ISSUE THREAD

**Issue by financialclose** [pola-rs/polars#8231] opened 2023-04-14 15:29 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I conducted a performance test of Polars dataframe software. I ran 90 tests for every set of tests (5 tests of a software using same query function “Distinct”, “GroupBy” and “JoinTable”), and rebooted the machine after each set of tests. During the test, I noticed that Polars could not complete the 1Billion Rows test for JoinTable and returned an error “memory allocation of 624658120 bytes failed”. It may be due to the script not being able to implement streaming similar to “Distinct” and “GroupBy”. For more detailed information on the tests, please refer to a file "PolarsVsPeaksBenchmark.xlsx" (https://github.com/financialclose/benchmarking/blob/main/PolarsVsPeaksBenchmark.xlsx) from this account https://github.com/financialclose/benchmarking

### Reproducible example

```python
import polars as pl
import time
import pathlib
s = time.time()

transaction = pl.read_csv("Input/1000MillionRows.CSV")            
master = pl.read_csv("Input/Master.CSV") 
joined_table = transaction.join(master, on=["Ledger","Account","Project"], how="inner")

joined_table.write_csv("Output/Polars-JoinTable1000M.csv")

e = time.time()
print("Polars JoinTable 1000M Time = {}".format(e-s))
```

### Expected behavior

Please refer to https://github.com/financialclose/benchmarking

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by ritchie46** [comment] 2023-04-15 11:07
Aren't you just going OOM?

**Comment by financialclose** [comment] 2023-04-15 13:48
I use Polars Version 0.17.2

**Comment by financialclose** [comment] 2023-04-15 13:56
Installing collected packages: polars
Successfully installed polars-0.17.2

C:\Users\85292>d:

D:\>cd benchmark

D:\Benchmark>python jointable1000M.py
memory allocation of 624658120 bytes failed

**Comment by ritchie46** [comment] 2023-04-15 14:06
Yes,  my point is. It is not a bug to go out of memory. You are not using the streaming API.

**Comment by financialclose** [comment] 2023-04-15 14:39
I have tried below setting similar to groupby, also fail.

D:\Benchmark>python jointable1000M.py
memory allocation of memory allocation of 624658120memory allocation of 624658120 bytes failed
memory allocation of  bytes failed
624658120

import polars as pl
import time
import pathlib
s = time.time()

transaction = pl.read_csv("Input/1000MillionRows.CSV")            
master = pl.read_csv("Input/Master.CSV") 
joined_table = transaction.join(master, on=["Ledger","Account","Project"], how="inner")

a = joined_table.collect(streaming=True)
path: pathlib.Path = "Output/Polars-JoinTable1000M.csv"
a.write_csv(path, separator=",")

e = time.time()
print("Polars JoinTable 1000M Time = {}".format(e-s))

**Comment by financialclose** [comment] 2023-04-15 14:45
I can share my experience with you deal with script design - standardise for different commands:
If input file demand for streaming, use input filename instead of table name,
if output file demand for streaming, use output filename instead of table name.
So jointable required input and output are using file name as the output file is very large.

Distinct{1000MillionRows.csv | Ledger, Account, PartNo,Project,Contact,Unit Code, D/C,Currency ~ Table}
instead of
ReadFile{1000MillionRows.csv ~ Table}
Distinct{Table | Ledger, Account, PartNo,Project,Contact,Unit Code, D/C,Currency ~ Table2}
   where Table, Table2 are in-memory table

GroupBy{1000MillionRows.CSV | Ledger, Account, PartNo,Project,Contact,Unit Code, D/C,Currency =>  
Count() Max(Quantity) Min(Quantity) Sum(Quantity) ~ Table}

JoinKeyValue{1000MillionRows.csv | Ledger,Account,Project => AllMatch(KeyValue) ~ Peaks-JoinTable1000M.csv}

**Comment by ritchie46** [comment] 2023-04-18 06:56
I will close this for now as we know we can hit OOM and we are still working on the streaming engine.

**Closed by ritchie46** 2023-04-18 06:56 UTC
Labels: bug, python

**Comment by hkpeaks** [comment] 2023-04-22 13:29
Since I am busy to construct my new github, forget to follow up this.

Seem the help is on this page "Sinking to a File: Although streaming allows you to process larger than memory datasets the output DataFrame must still fit in memory." https://pola-rs.github.io/polars-book/user-guide/lazy-api/streaming.html , I will try it again. But this kind of steaming is memory size dependent. 

I am willing to discuss with you directly using linkedin message, so I can let you understand how to implement real streaming for JoinTable. I think most difficulty for steaming is billion rows sorting using little memory, now I am planning to make this happen.

**Comment by hkpeaks** [comment] 2023-04-24 11:28
I have convert the billion rows csv file to parquet file format, then do jointable by this parquet file, the result is out of memory.
I do not know how to config streaming for parquet format.

import polars as pl
import time
import pathlib
s = time.time()

transaction = pl.read_parquet('Input/1000MILLION-ROWS.parquet')
master = pl.read_csv("Input/MASTER.CSV") 
joined_table = transaction.join(master, on=["Ledger","Account","Project"], how="inner")
joined_table.write_parquet("Output/joined_table-Polars.parquet")

e = time.time()
print("Polars JoinTable Time = {}".format(e-s))

D:\Go>python jointable.py
Traceback (most recent call last):
  File "D:\Go\jointable.py", line 6, in <module>
    transaction = pl.read_parquet('Input/1000MILLION-ROWS.parquet')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\85292\AppData\Local\Programs\Python\Python311\Lib\site-packages\polars\io\parquet\functions.py", line 124, in read_parquet
    return pli.DataFrame._read_parquet(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\85292\AppData\Local\Programs\Python\Python311\Lib\site-packages\polars\dataframe\frame.py", line 861, in _read_parquet
    self._df = PyDataFrame.read_parquet(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
exceptions.ArrowErrorException: ExternalFormat("File out of specification: underlying IO error: Allocation error : not enough memory")

**Comment by hkpeaks** [comment] 2023-09-10 03:36
Having the new function "sink_csv", now not only solve Jointable for 1 Billion-row, also pass a test for 10 Billion-row (Input 231GB, Output 389GB). Noticed if script without GroupBy/Distinct, your system will not use temp file in boot drive.
If using temp file is necessary, suggest to clean it for every starting process. 

import polars as pl
from time import time
from datetime import datetime

start_time = datetime.now()

master = pl.scan_csv("Inbox/Master.csv")

fact_table = pl.scan_csv("Inbox/10000M-Fact.csv")

result = fact_table.join(master, on=["Product","Style"], 
                         how="inner").with_columns((
    pl.col("Quantity") * pl.col("Unit_Price")).alias("Amount"))

result.sink_csv("Outbox/PolarsJoinResult.csv")

elapsed = datetime.now() - start_time
print(f"\nPolars InnerJoin Duration (in second): {
    elapsed.total_seconds():.3f}")
