### ISSUE TITLE
operations by row

### ISSUE THREAD

**Issue by wangjiawen2013** [pola-rs/polars#11756] opened 2023-10-16 05:28 UTC
### Description

Hi,

Although hsum()/hmin()/hmax()/hmeans() can aggregate the column horizontally, I cannot find hmedian()/hvar()/hstd()/hquantile(), how to calculate median/var/std/quantile and scale by row ?

Besides, It's easy to divide a dataframe by a series of the same length vertically, while how to divide a dataframe by a series of the same length horizontal ?

**Comment by stinodego** [comment] 2023-10-16 09:22
Duplicate of #9966

**Closed by stinodego** 2023-10-16 09:22 UTC
Labels: documentation
