### ISSUE TITLE
struct selector

### ISSUE THREAD

**Issue by Arengard** [pola-rs/polars#17401] opened 2024-07-03 13:36 UTC
### Description

df = pl.DataFrame({"name": ["John", "Doe", "Jane"], "age": [23, 45, 34]}).with_columns(struct = pl.struct(pl.all()))
print(df)

#this is not working
print(df.select(cs.by_dtype(pl.Struct)))

#could be
df.select(cs.struct)

**Comment by alexander-beedie** [comment] 2024-07-03 13:54
Yup, we're aware you can't use selectors with compound types (you need to specify the full type, including nested fields), and there's at least one open issue on it (mentioning List rather than Struct, but it's the same root cause so I'll close this out in favour of the existing issue) 👌

**Closed by alexander-beedie** 2024-07-03 13:54 UTC
Labels: enhancement

**Comment by cmdlineluser** [comment] 2024-07-03 17:48
The relevant issue:

- https://github.com/pola-rs/polars/issues/15489
