### ISSUE TITLE
Suggestion to update the UDF documentation

### ISSUE THREAD

**Issue by Chuck321123** [pola-rs/polars#12912] opened 2023-12-06 12:13 UTC
### Description

So by reading the documentation I'm still struggling on how I would implement longer UDF functions from python to polars. Would be nice if one or several examples could be dropped. Also in pandas, I used ```transform``` a lot compared to apply and map as you could do vectorized UDF operations similar to this: ```df.groupby("Group")["Relevant_Column"].transform(My_UDF_function)```. How would this work in polars if the UDF functions become slightly advanced? Would be nice to update the documentation a bit and see more examples of this

### Link
https://pola-rs.github.io/polars/user-guide/expressions/user-defined-functions/

_No response_

**Comment by MarcoGorelli** [comment] 2023-12-06 12:19
could you show an example of a udf you'd like to use?

**Comment by Chuck321123** [comment] 2023-12-06 12:34
Unfortunately, I don't have any now. I do, however, have a simpler UDF that revolves third-party packages. Lets take this fictive example: ```python
import Thirdpartypackage as tp

df["New_Col"] = Df.groupby("Group")["Relevant_Column"].transform(lambda x: tp.tp_attribute(necessary_variable = x, optional_variable = 2))
``` Would for example be nice to extend the documentations around how one would implement stuff like this

**Comment by MarcoGorelli** [comment] 2023-12-06 17:08
thanks - have you looked at https://pola-rs.github.io/polars/user-guide/migration/pandas/#pandas-transform ? does this answer your question?

(btw, note that if you're running a third party package with a lambda, then pandas transform won't be vectorised either)

**Comment by deanm0000** [comment] 2023-12-06 18:07
One thing to note is how powerful using numba's guvectorize is for making UDFs since they are vectorized ufuncs.

**Comment by MarcoGorelli** [comment] 2023-12-06 19:45
thanks - what do you mean by 'no luck'? could you make a reproducible example please

**Comment by zaa730Sight** [comment] 2023-12-06 19:55
> One thing to note is how powerful using numba's guvectorize is for making UDFs since they are vectorized ufuncs.

Strongly agree with this. That being said, for heavy usage the syntax gets kind of clunky. For users that know what they're doing however, I suspect the Polar's team would rather steer them into writing native Rust kernels with the py03-polars extension.

But all in all, I find it hard to beat the rapid prototyping & performance, all from a single python environment that  Numba guvectorize + Polars(including the Lazyframe eval) can get you. There are some rough edges with this though.

**Comment by Chuck321123** [comment] 2023-12-06 20:21
@deanm0000 I tried, and unfortunately, it didn't work. @MarcoGorelli, here is a simple reproductive example:
```
import pandas as pd
import numpy as np
import pandas_ta as ta
import polars as pl
np.random.seed(42)
df = pd.DataFrame({
    'Group': np.random.choice(['A', 'B', 'C'], size=50),
    'Values': np.random.rand(50) 
})
df = df.sort_values(by='Group')
df["Moving_Average"] = (df.groupby('Group')["Values"].transform(lambda x: ta.sma(close=x, length=2))).bfill()
# Alternative:
def My_UDF_Function(x):
    return ta.sma(close=x, length=2)
df["MA2"] = df.groupby('Group')["Values"].transform(My_UDF_Function).bfill()
```. Keep in mind that you need to do ```pip install pandas-ta``` first. I already know this can be done in polars by using the rolling function, but thought of leaving an example here

**Comment by cmdlineluser** [comment] 2023-12-06 20:58
`.map_batches()` is not "group aware", it needs to be `.map_elements()`

It is mentioned in the **Notes** section of the docs, but perhaps it could be made clearer.

> If you are looking to map a function over a window function or group_by context, refer to func:`map_elements` instead.

(Looks like there is also some formatting issue with the rst file?)

**Comment by MarcoGorelli** [comment] 2023-12-06 21:03
looks to me like `pandas-ta` specifically wants a pandas series - not a polars series, and not a numpy array, it won't work with anything else:
```python
In [42]: ta.sma(dfpl['Values'], length=2)

In [43]: ta.sma(dfpl['Values'].to_numpy(), length=2)

In [44]: ta.sma(pd.Series(dfpl['Values']), length=2)
Out[44]:
0          NaN
1     0.795927
2     0.643506
3     0.690988
4     0.525113
5     0.267241
6     0.262692
7     0.494509
8     0.680310
9     0.742702
10    0.762478
11    0.646630
12    0.389337
13    0.055688
14    0.333522
15    0.333357
16    0.090452
17    0.220633
18    0.362725
19    0.410134
20    0.665995
21    0.678027
22    0.531861
23    0.698057
24    0.826965
25    0.660905
26    0.422452
27    0.240534
28    0.102339
29    0.347099
30    0.375864
31    0.235960
32    0.545532
33    0.841617
34    0.879748
35    0.766130
36    0.498510
37    0.551201
38    0.502415
39    0.153784
40    0.384721
41    0.589381
42    0.424279
43    0.496428
44    0.431987
45    0.451654
46    0.786145
47    0.776003
48    0.384494
49    0.283826
Name: SMA_2, dtype: float64
```
so, barring converting to pandas (or requesting that they support polars) I'm not sure there's much that can be done here

**Comment by deanm0000** [comment] 2023-12-06 22:09
Is this similar enough?

https://stackoverflow.com/questions/77160103/exponential-moving-average-ema-calculations-in-polars-dataframe

**Comment by mkleinbort-ic** [comment] 2023-12-07 12:35
For reference, here is a good example of `nb.guvectorize`

https://stackoverflow.com/questions/77523657/how-do-you-condense-long-recursive-polars-expressions/77525171?noredirect=1#comment136683582_77525171

But going back to your question - have you tried just using `.map_elements` on the list of values itself?


### Polars code
```python


df = pl.DataFrame({
    'Group': np.random.choice(['A', 'B', 'C'], size=50),
    'Values': np.random.rand(50) 
})

df1 = df.group_by('Group').agg(pl.col('Values'))
# This is what we have so far:

# shape: (3, 2)
# ┌───────┬──────────────────────────────────┐
# │ Group ┆ Values                           │
# │ ---   ┆ ---                              │
# │ str   ┆ list[f64]                        │
# ╞═══════╪══════════════════════════════════╡
# │ C     ┆ [0.035229, 0.925109, … 0.297392] │
# │ A     ┆ [0.789259, 0.004903, … 0.56967]  │
# │ B     ┆ [0.917179, 0.396942, … 0.962115] │
# └───────┴──────────────────────────────────┘

df2 = df1.with_columns(**{
    'Moving Average': pl.col('Values').map_elements(lambda x: ....) # Use your UDF that takes in list of values here
})

# Then an explode to have it in the original format.

**Comment by mkleinbort-ic** [comment] 2023-12-07 13:34
> The issue, as far as I can tell, is that pandas-ta only accepts pandas series, and nothing else (not even numpy array)

Can't that be fixed with code like:

```python
def pandas_da_wrapper(x:list)->pd.Series:
     return pd.Series(x)

df2 = df1.with_columns(**{
     'Moving Average': pl.col('Values').map_elements(lambda x: ta.sma(pandas_da_wrapper(x), lenght=2))
})
```

**Comment by MarcoGorelli** [comment] 2023-12-07 13:51
You'd need to then convert back to Polars

This works:
```python
(
    dfpl.with_columns(
        MA2=pl.col("Values")
        .map_batches(lambda x: pl.Series(ta.sma(x.to_pandas(), length=2)))
        .fill_null(strategy="backward")
        .over("Group")
    )
)
```

**Comment by Chuck321123** [comment] 2023-12-07 14:54
Thanks for the input. Ye, I didn't think the package explicitly needed a pandas series @MarcoGorelli to work. However, i tried you solution and it worked, and surprisingly with a ~30% better performance on larger datasets.

**Comment by cmdlineluser** [comment] 2023-12-07 15:18
The last example uses `.map_batches(` so I don't think it's equivalent.

(It's not generating per-group values.)

**Comment by MarcoGorelli** [comment] 2023-12-07 15:25
it's using `map_batches`, followed by `over`, so it should be equivalent. at least, if I try it, I get the same result:

(sorry for the long-ish output)
```python
In [58]: import pandas as pd
    ...: import numpy as np
    ...: import pandas_ta as ta
    ...: import polars as pl
    ...: np.random.seed(42)
    ...: df = pd.DataFrame({
    ...:     'Group': np.random.choice(['A', 'B', 'C'], size=50),
    ...:     'Values': np.random.rand(50)
    ...: })
    ...: df = df.sort_values(by='Group')
    ...: df["Moving_Average"] = (df.groupby('Group')["Values"].transform(lambda x: ta.sma(close=
    ...: x, length=2))).bfill()
    ...: # Alternative:
    ...: def My_UDF_Function(x):
    ...:     return ta.sma(close=x, length=2)
    ...: df["MA2"] = df.groupby('Group')["Values"].transform(My_UDF_Function).bfill()

In [59]: dfpl = pl.from_pandas(df.drop('MA2', axis=1))

In [60]: (
    ...:     dfpl.with_columns(
    ...:         MA2=pl.col("Values")
    ...:         .map_batches(lambda x: pl.Series(ta.sma(x.to_pandas(), length=2)))
    ...:         .fill_null(strategy="backward")
    ...:         .over("Group")
    ...:     )
    ...: )
Out[60]:
shape: (50, 4)
┌───────┬──────────┬────────────────┬──────────┐
│ Group ┆ Values   ┆ Moving_Average ┆ MA2      │
│ ---   ┆ ---      ┆ ---            ┆ ---      │
│ str   ┆ f64      ┆ f64            ┆ f64      │
╞═══════╪══════════╪════════════════╪══════════╡
│ A     ┆ 0.844534 ┆ 0.795927       ┆ 0.795927 │
│ A     ┆ 0.74732  ┆ 0.795927       ┆ 0.795927 │
│ A     ┆ 0.539692 ┆ 0.643506       ┆ 0.643506 │
│ A     ┆ 0.842285 ┆ 0.690988       ┆ 0.690988 │
│ A     ┆ 0.207942 ┆ 0.525113       ┆ 0.525113 │
│ A     ┆ 0.326541 ┆ 0.267241       ┆ 0.267241 │
│ A     ┆ 0.198842 ┆ 0.262692       ┆ 0.262692 │
│ A     ┆ 0.790176 ┆ 0.494509       ┆ 0.494509 │
│ A     ┆ 0.570444 ┆ 0.68031        ┆ 0.68031  │
│ A     ┆ 0.91496  ┆ 0.742702       ┆ 0.742702 │
│ A     ┆ 0.609997 ┆ 0.762478       ┆ 0.762478 │
│ A     ┆ 0.683264 ┆ 0.64663        ┆ 0.64663  │
│ A     ┆ 0.09541  ┆ 0.389337       ┆ 0.389337 │
│ A     ┆ 0.015966 ┆ 0.055688       ┆ 0.055688 │
│ A     ┆ 0.651077 ┆ 0.333522       ┆ 0.333522 │
│ B     ┆ 0.015636 ┆ 0.090452       ┆ 0.333357 │
│ B     ┆ 0.165267 ┆ 0.090452       ┆ 0.090452 │
│ B     ┆ 0.275999 ┆ 0.220633       ┆ 0.220633 │
│ B     ┆ 0.449451 ┆ 0.362725       ┆ 0.362725 │
│ B     ┆ 0.370818 ┆ 0.410134       ┆ 0.410134 │
│ B     ┆ 0.961172 ┆ 0.665995       ┆ 0.665995 │
│ B     ┆ 0.394882 ┆ 0.678027       ┆ 0.678027 │
│ B     ┆ 0.668841 ┆ 0.531861       ┆ 0.531861 │
│ B     ┆ 0.727272 ┆ 0.698057       ┆ 0.698057 │
│ B     ┆ 0.926659 ┆ 0.826965       ┆ 0.826965 │
│ B     ┆ 0.39515  ┆ 0.660905       ┆ 0.660905 │
│ B     ┆ 0.449754 ┆ 0.422452       ┆ 0.422452 │
│ B     ┆ 0.031313 ┆ 0.240534       ┆ 0.240534 │
│ B     ┆ 0.173365 ┆ 0.102339       ┆ 0.102339 │
│ B     ┆ 0.520834 ┆ 0.347099       ┆ 0.347099 │
│ C     ┆ 0.230894 ┆ 0.23596        ┆ 0.375864 │
│ C     ┆ 0.241025 ┆ 0.23596        ┆ 0.23596  │
│ C     ┆ 0.850039 ┆ 0.545532       ┆ 0.545532 │
│ C     ┆ 0.833195 ┆ 0.841617       ┆ 0.841617 │
│ C     ┆ 0.926301 ┆ 0.879748       ┆ 0.879748 │
│ C     ┆ 0.60596  ┆ 0.76613        ┆ 0.76613  │
│ C     ┆ 0.391061 ┆ 0.49851        ┆ 0.49851  │
│ C     ┆ 0.711342 ┆ 0.551201       ┆ 0.551201 │
│ C     ┆ 0.293488 ┆ 0.502415       ┆ 0.502415 │
│ C     ┆ 0.01408  ┆ 0.153784       ┆ 0.153784 │
│ C     ┆ 0.755361 ┆ 0.384721       ┆ 0.384721 │
│ C     ┆ 0.423401 ┆ 0.589381       ┆ 0.589381 │
│ C     ┆ 0.425156 ┆ 0.424279       ┆ 0.424279 │
│ C     ┆ 0.5677   ┆ 0.496428       ┆ 0.496428 │
│ C     ┆ 0.296274 ┆ 0.431987       ┆ 0.431987 │
│ C     ┆ 0.607034 ┆ 0.451654       ┆ 0.451654 │
│ C     ┆ 0.965255 ┆ 0.786145       ┆ 0.786145 │
│ C     ┆ 0.586751 ┆ 0.776003       ┆ 0.776003 │
│ C     ┆ 0.182236 ┆ 0.384494       ┆ 0.384494 │
│ C     ┆ 0.385417 ┆ 0.283826       ┆ 0.283826 │
└───────┴──────────┴────────────────┴──────────┘

In [61]: df
Out[61]:
   Group    Values  Moving_Average       MA2
24     A  0.844534        0.795927  0.795927
25     A  0.747320        0.795927  0.795927
26     A  0.539692        0.643506  0.643506
15     A  0.842285        0.690988  0.690988
12     A  0.207942        0.525113  0.525113
20     A  0.326541        0.267241  0.267241
38     A  0.198842        0.262692  0.262692
40     A  0.790176        0.494509  0.494509
21     A  0.570444        0.680310  0.680310
44     A  0.914960        0.742702  0.742702
5      A  0.609997        0.762478  0.762478
4      A  0.683264        0.646630  0.646630
47     A  0.095410        0.389337  0.389337
1      A  0.015966        0.055688  0.055688
43     A  0.651077        0.333522  0.333522
33     B  0.015636        0.090452  0.090452
32     B  0.165267        0.090452  0.090452
30     B  0.275999        0.220633  0.220633
46     B  0.449451        0.362725  0.362725
48     B  0.370818        0.410134  0.410134
23     B  0.961172        0.665995  0.665995
35     B  0.394882        0.678027  0.678027
49     B  0.668841        0.531861  0.531861
19     B  0.727272        0.698057  0.698057
18     B  0.926659        0.826965  0.826965
17     B  0.395150        0.660905  0.660905
16     B  0.449754        0.422452  0.422452
14     B  0.031313        0.240534  0.240534
7      B  0.173365        0.102339  0.102339
22     B  0.520834        0.347099  0.347099
2      C  0.230894        0.235960  0.235960
3      C  0.241025        0.235960  0.235960
45     C  0.850039        0.545532  0.545532
6      C  0.833195        0.841617  0.841617
42     C  0.926301        0.879748  0.879748
41     C  0.605960        0.766130  0.766130
8      C  0.391061        0.498510  0.498510
39     C  0.711342        0.551201  0.551201
36     C  0.293488        0.502415  0.502415
37     C  0.014080        0.153784  0.153784
10     C  0.755361        0.384721  0.384721
34     C  0.423401        0.589381  0.589381
11     C  0.425156        0.424279  0.424279
13     C  0.567700        0.496428  0.496428
31     C  0.296274        0.431987  0.431987
29     C  0.607034        0.451654  0.451654
28     C  0.965255        0.786145  0.786145
27     C  0.586751        0.776003  0.776003
9      C  0.182236        0.384494  0.384494
0      C  0.385417        0.283826  0.283826
```

**Comment by cmdlineluser** [comment] 2023-12-07 15:47
Yeah, I mentioned it earlier: https://github.com/pola-rs/polars/issues/12912#issuecomment-1843680282

`map_batches` always passes the full column, it doesn't do groups.

> If you are looking to map a function over a window function or group_by context, refer to func:map_elements instead.

(The distinction was perhaps clearer with the previous names of `map` vs. `apply` because one could think of a "group" as a "batch")

```python
import pandas_ta as ta
import polars as pl

df = pl.DataFrame({
   "Group":  ["A", "A", "B", "C", "C", "C"],
   "Values": [1, 2, 3, 4, 5, 6]
})
```
```python
df.with_columns(
   MA2=pl.col("Values")
   .map_batches(lambda x: [print(x), pl.Series(ta.sma(x.to_pandas(), length=2))][1])
   .over("Group")
)
# shape: (6,)
# Series: 'Values' [i64]
# [
# 	1
# 	2
# 	3
# 	4
# 	5
# 	6
# ]
# shape: (6, 3)
# ┌───────┬────────┬──────┐
# │ Group ┆ Values ┆ MA2  │
# │ ---   ┆ ---    ┆ ---  │
# │ str   ┆ i64    ┆ f64  │
# ╞═══════╪════════╪══════╡
# │ A     ┆ 1      ┆ null │
# │ A     ┆ 2      ┆ 1.5  │
# │ B     ┆ 3      ┆ 2.5  │
# │ C     ┆ 4      ┆ 3.5  │
# │ C     ┆ 5      ┆ 4.5  │
# │ C     ┆ 6      ┆ 5.5  │
# └───────┴────────┴──────┘
```

```python
df.with_columns(
   MA2=pl.col("Values")
   .map_elements(lambda x: [print(x), pl.Series(ta.sma(x.to_pandas(), length=2))][1])
   .over("Group")
)
# shape: (2,)
# Series: '' [i64]
# [
# 	1
# 	2
# ]
# shape: (1,)
# Series: '' [i64]
# [
# 	3
# ]
# shape: (3,)
# Series: '' [i64]
# [
# 	4
# 	5
# 	6
# ]
# shape: (6, 3)
# ┌───────┬────────┬──────┐
# │ Group ┆ Values ┆ MA2  │
# │ ---   ┆ ---    ┆ ---  │
# │ str   ┆ i64    ┆ f64  │
# ╞═══════╪════════╪══════╡
# │ A     ┆ 1      ┆ null │
# │ A     ┆ 2      ┆ 1.5  │
# │ B     ┆ 3      ┆ null │
# │ C     ┆ 4      ┆ null │
# │ C     ┆ 5      ┆ 4.5  │
# │ C     ┆ 6      ┆ 5.5  │
# └───────┴────────┴──────┘
```

**Comment by deanm0000** [comment] 2023-12-14 21:35
I petitioned for [this](https://github.com/pola-rs/polars/issues/12941) one to be reopened. It really seems like map_batches ought to "turn in to" map_elements when it's an over/agg.

**Comment by MarcoGorelli** [comment] 2023-12-16 09:08
Thanks all for your comments!

Right, so going back to the original example, the solution is indeed to use `map_elements` (not `map_batches`!) followed by `over`:

```python
import pandas as pd
import numpy as np
import pandas_ta as ta
import polars as pl
from polars.testing import assert_series_equal
np.random.seed(42)
df = pd.DataFrame({
    'Group': np.random.choice(['A', 'B', 'C'], size=50),
    'Values': np.random.rand(50)
})
df = df.sort_values(by='Group')
df["Moving_Average"] = (df.groupby('Group')["Values"].transform(lambda x: ta.sma(close=x, length=2))).bfill()
# Alternative:
def My_UDF_Function(x):
    return ta.sma(close=x, length=2)

dfpl = pl.from_pandas(df)

dfpl = (
    dfpl.with_columns(
        MA2=pl.col("Values")
        .map_elements(lambda x: pl.Series(ta.sma(x.to_pandas(), length=2)))
        .fill_null(strategy="backward")
        .over("Group")
    )
)

df["MA2"] = df.groupby('Group')["Values"].transform(My_UDF_Function).bfill()

dfpl = dfpl.with_columns(
    pandas_MA2=pl.from_pandas(df['MA2'])
)
assert_series_equal(dfpl['MA2'], dfpl['pandas_MA2'], check_names=False)
```

I'll try to update the docs

**Comment by Mickychen00** [comment] 2023-12-18 22:15
The user guide's UDF page is still to be uodated. Current version talks about map and apply these two outdated functions.

**Closed** 2024-12-09 20:30 UTC
Labels: documentation
