### ISSUE TITLE
Panic if creating DataFrame with dict with np.float32 values

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#8242] opened 2023-04-14 21:02 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I can create a DataFrame from a dict with float values, but not numpy floats.

I think this has happened since 0.17

### Reproducible example

```python
import polars as pl
impot numpy as np
# This works
py_dict = {'a':float(1)}
pl.DataFrame(py_dict)
# Doesn't work
np_dict = {'a':np.float32(1)}
pl.DataFrame(np_dict)
```

### Expected behavior

For both to create a df

### Installed versions

<details>

```
---Version info---
Polars: 0.17.2
Index type: UInt32
Platform: Linux-5.10.104-linuxkit-x86_64-with-glibc2.28
Python: 3.10.1 (main, Dec 21 2021, 09:50:13) [GCC 8.3.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: 0.3.1
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>```

</details>

**Comment by avimallu** [comment] 2023-04-15 11:35
Duplicate of #8242.

**Closed** 2023-04-15 18:41 UTC
Labels: bug, python
