### ISSUE TITLE
Inconsistent behavior between sum and mean on empty set

### ISSUE THREAD

**Issue by paladin158** [pola-rs/polars#10418] opened 2023-08-10 23:35 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [None, None, None], "b": [1, 1, 1]})

df.select([pl.sum("a").alias("a_sum"), pl.mean("a").alias("a_mean")])
df.groupby("b").agg([pl.sum("a").alias("a_sum"), pl.mean("a").alias("a_mean")])
```

### Issue description

Currently (after #9894), `pl.sum` returns `0` whereas `pl.mean` returns `null` in both `select` and `aggregation` contexts.

Are they inconsistent because `mean = sum / n`? So, I would expect `sum` and `mean` have the same consistent behavior.

Also, it seems like the convention/default here is `sum` returns `0` for all `None` values. But, sometimes it would be desirable to have `sum` returning `None` for all `None` values.

Is there a way to achieve this behavior? Or we can add an option (return `None` when all `None`) to `pl.sum`?

### Expected behavior

- `sum` and `mean` have the same consistent behavior.
- add an option (return `None` when all `None`) to `pl.sum`.

### Installed versions

<details>

```
0.18.13
```

</details>

**Comment by reswqa** [comment] 2023-08-11 04:30
I'm not sure let mean = 0 for empty set is well-defined? (it should have been divided by 0) 🤔. But I don't have a strong tendency. If we decide to do so, I am willing to submit a PR.

**Comment by ritchie46** [comment] 2023-08-11 05:02
It should either be null or NaN as we cannot divide by 0. The mean of an empty set not defined. I think returning null is reasonable.

**Comment by erinov1** [comment] 2023-08-11 05:19
> 
> > add an option (return None when all None) to pl.sum.
> 
> The sum of an empty set is 0. Which makes the set filled with nulls also well defined as 0.

The problem is that polars implicitly identifies nulls with missing values in certain cases, for example, a left join where the keys of the right table are a strict subset of those of the left. The joined table will contain nulls, but the scientific interpretation may be that you missing an entire set of observations. Concluding that some sum is zero may not be the correct interpretation if what you really want to say is "I have no idea what the sum is, because I was unable to collect any observations for this group."

**Comment by ritchie46** [comment] 2023-08-11 06:26
> (I also think it would useful to have an option to return null for the sum of all-null columns.)

If you want that, you can write that:

```
pl.when(col(..).null_count() == count()).then(None).otherwise(col(..).sum())
```

**Comment by paladin158** [comment] 2023-08-11 09:00
> > (I also think it would useful to have an option to return null for the sum of all-null columns.)
> 
> If you want that, you can write that:
> 
> ```
> pl.when(col(..).null_count() == count()).then(None).otherwise(col(..).sum())
> ```

But, this can only be used in `select` context, right? I think there will be a warning issued if it is used in `groupby` context.

**Comment by orlp** [comment] 2023-08-14 10:42
I am closing this because it is not inconsistent. The sum of an empty set is 0, the mean of an empty set is undefined.

> But, this can only be used in select context, right? I think there will be a warning issued if it is used in groupby context.

I don't see a warning:

```python
>>> null_sum = lambda col: pl.when(pl.col(col).null_count() == pl.count()).then(None).otherwise(pl.sum(col))
>>> df.groupby("b").agg([null_sum("a").alias("a_sum"), pl.mean("a").alias("a_mean")])
shape: (1, 3)
┌─────┬───────┬────────┐
│ b   ┆ a_sum ┆ a_mean │
│ --- ┆ ---   ┆ ---    │
│ i64 ┆ f32   ┆ f32    │
╞═════╪═══════╪════════╡
│ 1   ┆ null  ┆ null   │
└─────┴───────┴────────┘
```

**Closed by orlp** 2023-08-14 10:42 UTC
Labels: bug, python
