### ISSUE TITLE
`Expr.is_in` fails or gives wrong result with None on Boolean type

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#12794] opened 2023-11-30 10:00 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python


pl.DataFrame({'bool': [True, False, None]}).filter(pl.col('bool').is_in([None]))
# InvalidOperationError: `is_in` cannot check for Float32 values in Boolean data

pl.DataFrame({'bool': [True, False, None]}).filter(pl.col('bool').is_in([None, True]))
# shape: (1, 1)
# ┌──────┐
# │ bool │
# │ ---  │
# │ bool │
# ╞══════╡
# │ true │
# └──────┘

```

### Issue description

In the snippet above, the first line fails and should not, if we change `.is_in([None])` by `.eq(None)` it works as expected. The second line gives a wrong result, as I would expect 2 rows

### Expected behavior

```
pl.DataFrame({'bool': [True, False, None]}).filter(pl.col('bool').is_in([None]))
# shape: (1, 1)
# ┌──────┐
# │ bool │
# │ ---  │
# │ bool │
# ╞══════╡
# │ null │
# └──────┘

pl.DataFrame({'bool': [True, False, None]}).filter(pl.col('bool').is_in([True, None]))
# shape: (2, 1)
# ┌───────┐
# │ bool  │
# │ ---   │
# │ bool  │
# ╞═══════╡
# │ true  │
# │ null  │
# └───────┘


```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.18
Index type:           UInt32
Platform:             Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.17
Python:               3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.0
openpyxl:             <not installed>
pandas:               2.1.3
pyarrow:              13.0.0
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.49
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

</details>

**Comment by gab23r** [comment] 2023-11-30 10:07
Just realized that it is linked to #11669, but not totally a duplicated, for me this bevahior is not correct:

```
pl.DataFrame({'bool': [True, False, None]}).filter(pl.col('bool').is_in([None, True]))
# shape: (1, 1)
# ┌──────┐
# │ bool │
# │ ---  │
# │ bool │
# ╞══════╡
# │ true │
# └──────┘


```

**Comment by orlp** [comment] 2023-11-30 11:30
> In the snippet above, the first line fails and should not, if we change .is_in([None]) by .eq(None) it works as expected. 

A nitpick, in the next version `.eq(None)` would give a warning telling you to use `.is_null()`, because comparisons with nulls always propagate the null (and thus == None always results in null).

**Comment by orlp** [comment] 2023-11-30 12:11
@gab23r This is a dupe of https://github.com/pola-rs/polars/issues/11669. Your 'incorrect' behavior is in fact correct, the `is_in` returns `null` when the left hand side is `null` (and this is intended and matches SQL behavior). `filter` never matches on `null`s.

If you want nulls to match you can always explicitly write it:

```python
.filter(pl.col('bool').is_in(res) | pl.col('bool').is_null())
```

**Closed** 2023-11-30 12:11 UTC
Labels: bug, python
