### ISSUE TITLE
Progress bar for map or apply polars-python functions.

### ISSUE THREAD

**Issue by mmejai** [pola-rs/polars#7601] opened 2023-03-17 07:16 UTC
### Problem description

I wish if it was possible to add, like in Pandas, a progress bar or an integration with python [tqdm module](https://pypi.org/project/tqdm/) for the map and apply functions. 
Pandas already integrates these features.
Many thanks.

**Comment by ritchie46** [comment] 2023-03-17 09:44
Duplicate of #4654. Let's keep the discussion there.

**Closed by ritchie46** 2023-03-17 09:44 UTC
Labels: enhancement
