### ISSUE TITLE
.apply not function correctly

### ISSUE THREAD

**Issue by dafardevloper** [pola-rs/polars#2999] opened 2022-03-29 07:25 UTC
#### What language are you using?

Python

#### What version of polars are you using?

polars 0.13.15

#### What operating system are you using polars on?

Edition: Windows 10 Pro | Version: 21H2 | OS build : 19044.1620 

#### What language version are you using

Python 3.10.4

#### Describe your bug.

.apply not understanding when to stop, 

#### What are the steps to reproduce the behavior?

simply print output in a specific format using .apply() 

Please use code instead of images, we don't like typing.

```Python
def set_print_warehouse(each_row:tuple)->str:
    (incoming_date,incomingStock,epdn,deliveryInDays,warehouses) = each_row
    moreQtyDate = incoming_date.strftime("%d-%m-%Y")
    return print(f";{epdn};{warehouses};{deliveryInDays};{moreQtyDate};{incomingStock};forceInStock")

Incmoing_product.apply(set_print_warehouse)
```
Output example
;UCTR4299;scm_warehouse_w;30;31-03-2022;7;forceInStock
;UCTR0536;scm_warehouse_w;30;31-03-2022;7;forceInStock
;UCTR4659;scm_warehouse_w;30;31-03-2022;7;forceInStock
;UCTR0548;scm_warehouse_w;30;31-03-2022;7;forceInStock

error message at the end
Incmoing_product.apply(set_print_warehouse)
File "C:\Users\Namrata\AppData\Local\Programs\Python\Python310\lib\site-packages\polars\internals\frame.py", line 3463, in apply
    out, is_df = self._df.apply(f, return_dtype, inference_size)
RuntimeError: BindingsError: "Could not determine output type"

**Comment by ritchie46** [comment] 2022-03-29 18:24
You are returning a `print` function call? That is returning `None`.

**Comment by ritchie46** [comment] 2022-03-30 08:33
I am closing this as this is not a bug in our side.

**Closed by ritchie46** 2022-03-30 08:33 UTC
Labels: bug
