### ISSUE TITLE
`expr.str().strptime()` panics if `ambiguous` is of wrong type

### ISSUE THREAD

**Issue by rben01** [pola-rs/polars#13386] opened 2024-01-02 18:15 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let df = df!["date" => ["2024-01-01"]]
        .unwrap()
        .lazy()
        .with_column(col("date").str().strptime(
            DataType::Datetime(TimeUnit::Milliseconds, None),
            StrptimeOptions {
                format: Some("%Y-%m-%d".to_owned()),
                ..Default::default()
            },
            lit(false),
        ));

    println!("{:?}", df.collect()?);

    Ok(())
}
```

### Log output

```shell
run StackExec
thread 'main' panicked at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/dsl/function_expr/strings.rs:621:33:
called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("invalid series dtype: expected `String`, got `bool`"))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1077:23
   4: polars_plan::dsl::function_expr::strings::to_datetime
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/dsl/function_expr/strings.rs:621:22
   5: polars_plan::dsl::function_expr::strings::strptime
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/dsl/function_expr/strings.rs:556:13
   6: polars_plan::dsl::function_expr::strings::<impl core::convert::From<polars_plan::dsl::function_expr::strings::StringFunction> for polars_plan::dsl::expr_dyn_fn::SpecialEq<alloc::sync::Arc<dyn polars_plan::dsl::expr_dyn_fn::SeriesUdf>>>::from::{{closure}}
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/dsl/function_expr/mod.rs:719:13
   7: <F as polars_plan::dsl::expr_dyn_fn::SeriesUdf>::call_udf
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.36.2/src/dsl/expr_dyn_fn.rs:84:9
   8: polars_lazy::physical_plan::expressions::apply::ApplyExpr::eval_and_flatten
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.36.2/src/physical_plan/expressions/apply.rs:122:28
   9: <polars_lazy::physical_plan::expressions::apply::ApplyExpr as polars_lazy::physical_plan::expressions::PhysicalExpr>::evaluate
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.36.2/src/physical_plan/expressions/apply.rs:313:16
  10: polars_lazy::physical_plan::executors::projection_utils::run_exprs_seq::{{closure}}
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.36.2/src/physical_plan/executors/projection_utils.rs:164:29
  11: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/adapters/map.rs:91:28
  12: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/traits/iterator.rs:2462:21
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/adapters/map.rs:117:9
  14: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/adapters/mod.rs:199:9
  15: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/traits/iterator.rs:2524:9
  16: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/adapters/mod.rs:182:14
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  18: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/vec/spec_from_iter.rs:33:9
  19: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/vec/mod.rs:2753:9
  20: core::iter::traits::iterator::Iterator::collect
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/traits/iterator.rs:2054:9
  21: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1934:51
  22: core::iter::adapters::try_process
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/adapters/mod.rs:168:17
  23: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1934:9
  24: core::iter::traits::iterator::Iterator::collect
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/traits/iterator.rs:2054:9
  25: polars_lazy::physical_plan::executors::projection_utils::run_exprs_seq
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.36.2/src/physical_plan/executors/projection_utils.rs:164:5
  26: polars_lazy::physical_plan::executors::projection_utils::evaluate_physical_expressions
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.36.2/src/physical_plan/executors/projection_utils.rs:211:9
  27: polars_lazy::physical_plan::executors::stack::StackExec::execute_impl
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.36.2/src/physical_plan/executors/stack.rs:18:19
  28: <polars_lazy::physical_plan::executors::stack::StackExec as polars_lazy::physical_plan::executors::executor::Executor>::execute
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.36.2/src/physical_plan/executors/stack.rs:72:13
  29: polars_lazy::frame::LazyFrame::collect
             at /Users/rben01/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.36.2/src/frame/mod.rs:668:19
  30: scratchpad::main
             at ./src/main.rs:22:22
  31: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Issue description

`ambiguous` is an `Expr` (whose significance I do not understand and is not documented). It is, evidently, supposed to be of type `String`, but if you pass the wrong type then polars panics.

https://github.com/pola-rs/polars/blob/58b0da8bc31d71d21be8782c5013747516652f81/crates/polars-plan/src/dsl/function_expr/strings.rs#L621

### Expected behavior

I think that Polars should not panic on an `Expr` of the wrong type, but should instead return a `PolarsError`.

### Installed versions

```toml
polars = { version = "0.36.*", features = ["lazy", "strings"] }
```

**Comment by mcrumiller** [comment] 2024-01-02 18:30
There's a bit more on the `ambiguous` parameter in the [Python API doc](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.str.strptime.html):

> **ambiguous**
> Determine how to deal with ambiguous datetimes:
> `'raise'` (default): raise
> `'earliest'`: use the earliest datetime
> `'latest'`: use the latest datetime

**Comment by MarcoGorelli** [comment] 2024-01-02 18:30
thanks for the report - have opened a PR about the panic, the docs clarification is a dupe of https://github.com/pola-rs/polars/issues/11580

**Closed** 2024-01-03 07:24 UTC
Labels: bug, rust
