### ISSUE TITLE
Out of Memory for `pl.scan_delta` and `fetch()`

### ISSUE THREAD

**Issue by hristo-mavrodiev** [pola-rs/polars#7337] opened 2023-03-04 13:49 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

On large dataset the `fetch()` function is failing to get the first rows
![image](https://user-images.githubusercontent.com/61916767/222905980-89998edc-e3cb-4264-991d-2c804c4909e2.png)

Same for head()
![image](https://user-images.githubusercontent.com/61916767/222906031-10730d5a-846b-4ed4-803c-6ab5c11867c0.png)

PS: It's working fine on `scan_parquet()`

### Reproducible example

```python
import polars as pl
nested_parsed_df = pl.scan_delta('my_delta_lake_folder')

nested_parsed_df.fetch(2)  -> Leads to Out of Memory
nested_parsed_df.head(n=10).collect(streaming=True) -> Leads to Out of Memory
```

### Expected behavior

Fetch first two rows

### Installed versions

<details>

```
---Version info---
Polars: 0.16.10
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 11.0.0
pandas: <not installed>
numpy: 1.24.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <version not detected>
matplotlib: <not installed>
```
PS: from pip freeze the deltalake version is deltalake==0.7.0
</details>

**Comment by dominikpeter** [comment] 2023-03-04 20:36
I think the problem is in delta-rs as it is not supporting LIMIT pushdowns:
[Support LIMIT pushdown in scans #982](https://github.com/delta-io/delta-rs/issues/982)

**Comment by wjones127** [comment] 2023-03-07 22:44
`scan_delta` just calls `scan_pyarrow_dataset`, so you really just need to be able to push down to the PyArrow dataset. It has a `head()` method on the scanner, which should do what you want ([docs](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Scanner.html#pyarrow.dataset.Scanner.head)).

Right now when reading a dataset, you load everything into memory with `.to_table()`:

https://github.com/pola-rs/polars/blob/4feab6d25d755179c5f8e27d6b7086319701e054/py-polars/polars/internals/anonymous_scan.py#L57

So that's probably why you are getting OOM.

**Comment by dominikpeter** [comment] 2023-03-08 07:20
@ritchie46 would it be possible to pushdown the `limit` to the `_scan_pyarrow_dataset_impl`?

**Comment by ritchie46** [comment] 2023-03-08 08:33
Yes. Just needs to be implemented.

**Comment by chitralverma** [comment] 2023-03-17 21:55
@ritchie46 not sure if this has been done by you or some other contributors, but for a big local delta table, with the latest `scan_delta` changes I see that limit has an instant effect and it seems to be pushed down.

the `n_rows` in fetch however is not working for me atleast.

**Comment by chitralverma** [comment] 2023-03-18 04:17
found it.

https://github.com/pola-rs/polars/pull/7570

**Comment by marvinbernhardt** [comment] 2023-08-16 08:43
> I think this issue can also be closed now.

Wait, should I not experience this problem at version 0.18.15 using scan_delta() and fetch()? Because I think I do (no OOM, but it takes much longer than I would expect for 2 rows).

**Comment by stinodego** [comment] 2023-10-14 13:51
> > I think this issue can also be closed now.
> 
> Wait, should I not experience this problem at version 0.18.15 using scan_delta() and fetch()? Because I think I do (no OOM, but it takes much longer than I would expect for 2 rows).

If that is the case, please open a new issue with a reproducible example. I'll close this for now.

**Closed by stinodego** 2023-10-14 13:51 UTC
Labels: bug, python, blocked
