### ISSUE TITLE
Filteration applied from an inactive `then` clause.

### ISSUE THREAD

**Issue by noam-delfina** [pola-rs/polars#12354] opened 2023-11-09 21:27 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({
  'a': [False, False],
  'b': [False, True],
})

df.select(
  pl.when(pl.col('a').any())
  .then(pl.col('a').filter(pl.col('a')).first())
  .otherwise(pl.col('b').last())
)
```

### Log output

```shell
shape: (0, 1)
┌──────┐
│ a    │
│ ---  │
│ bool │
╞══════╡
└──────┘
```

### Issue description

Incorrect output. Correct output can be achieved by altering the `then` call in the above statement as:

```python
df.select(
  pl.when(pl.col('a').any())
  .then(pl.lit('literal'))
  .otherwise(pl.col('b').last())
)
```

The `then` call to the first `when` object should not affect the output of the expression if the first `when` condition is not met.

### Expected behavior

```
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ true    │
└─────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-5.19.16-76051916-generic-x86_64-with-glibc2.36
Python:              3.11.6 (main, Nov  1 2023, 13:45:43) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.10.0
gevent:              <not installed>
matplotlib:          3.8.1
numpy:               1.26.1
openpyxl:            <not installed>
pandas:              2.1.2
pyarrow:             14.0.0
pydantic:            1.10.13
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.23
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by mcrumiller** [comment] 2023-11-09 22:03
The issue is probably because your two branches in the when/then don't produce the same size results. Remember that all branches are evaluated, and the when/then is later applied to the result to pick and choose from the appropriate branch. In this case:

```
  .then(pl.col('a').filter(pl.col('a')).first())
)
```
returns nothing, because since column `a` is alwasy false, then `.filter(pl.col('a'))` returns no elements.

This is probably still a bug, I just wanted to point this out.

**Comment by noam-delfina** [comment] 2023-11-09 22:16
@mcrumiller Thanks for the response, I appreciate your perspective. I understand your point. 

Unfortunately in my application I can't guarantee at development time that all branches will always return results of the same size (though I can guarantee that each branch will return a result of size 1 _if it is selected_).

**Comment by ritchie46** [comment] 2023-11-12 13:33
This is fixed by `first/last` always returning a value now.

**Closed by ritchie46** 2023-11-12 13:33 UTC
Labels: bug, python
