### ISSUE TITLE
Enable handling non-existent times in expr.dt.replace_time_zone

### ISSUE THREAD

**Issue by frodepaaske** [pola-rs/polars#11579] opened 2023-10-06 23:20 UTC
### Description

This feature request proposes that the 'dt.replace_time_zone' method is updated with a 'non-existent' parameter that enables the method to handle non-existent time-stamps. Currently, Polars raises  an error when trying to parse such time stamps. This is to make the method similar to the Pandas Series.tz_localize method which will allow for greater interoperability between the 2 libraries.  

Example of non-existent time stamp:

Time Zone: Europe/Copenhagen
2023-03-26 02:30:00 (time moved from 02:00 to 03:00 due to DST).

**Comment by MarcoGorelli** [comment] 2023-10-07 07:21
thanks for the request - this came up here too https://github.com/pola-rs/polars/issues/10090#issuecomment-1676164681

not the simplest, as I don't think there's a built-in way to do this in Chrono, but I'll see what can be done

**Comment by alexander-beedie** [comment] 2023-10-07 08:22
> This is probably a good use-case for Hypothesis tests

Definitely :))

**Comment by MarcoGorelli** [comment] 2023-10-07 09:53
🤔 not sure about adding an extra argument, it would be nice to just have a single dst-related argument that handles everything

furthermore, adding `non_existent` would mean that for `truncate` there would need to be quaternary expression 😱 

Maybe `'ambiguous'` should take
- 'earliest'
- 'latest'
- 'offset_by_1h'  # for non-existent datetimes, shift by this offset before localizing
- 'raise'

and be renamed to `dst_rule`. This would be another renaming of the argument (😩), so it's probably important to get it right here to avoid testing users' patience

@frodepaaske just out of interest, how do you handle this in pandas? Which argument would you pass to `tz_localize` for localizing `'2023-03-26 02:30:00`' in your time zone?

**Comment by frodepaaske** [comment] 2023-10-07 12:10
@MarcoGorelli This is how I would usually handle them in Pandas. Given that data I work with usually comes from a database where all dates are stored in a specific timezone, it is easy to just pass the 'nonexistent' parameter to the 'tz_localize' method in Pandas. I've shown some different examples in the code below. Hope this is of any help :) From a user perspective it is nice to have both the 'ambiguous' and 'nonexistent' parameter available in the same method.




```
import pandas as pd


# Create input data
non_existent_date = ['2023-03-26 02:30:00', '2024-03-31 02:45:00']

ambiguous_dates = ['2023-10-29 02:30:00', '2024-10-27 02:45:00']

time_zone = 'Europe/Copenhagen'

# DF for non-existent times
non_existent_df = pd.DataFrame(data=non_existent_date, columns=['Date'], dtype='datetime64[ns]').assign(Type='nonexistent')

non_existent_df['shift_forward_date'] = non_existent_df['Date'].dt.tz_localize(tz=time_zone, nonexistent='shift_forward')

non_existent_df['shift_backward_date'] = non_existent_df['Date'].dt.tz_localize(tz=time_zone, nonexistent='shift_backward')

# DF for ambiguous

ambiguous_df = pd.DataFrame(data=ambiguous_dates, columns=['Date'], dtype='datetime64[ns]').assign(Type='ambiguous')

ambiguous_df['ambiguous_true'] = ambiguous_df['Date'].dt.tz_localize(tz=time_zone, ambiguous=True)

ambiguous_df['ambiguous_false'] = ambiguous_df['Date'].dt.tz_localize(tz=time_zone, ambiguous=False)

df = pd.concat([non_existent_df, ambiguous_df])



|    | Date                | Type        | shift_forward_date        | shift_backward_date                 | ambiguous_true            | ambiguous_false           |
|---:|:--------------------|:------------|:--------------------------|:------------------------------------|:--------------------------|:--------------------------|
|  0 | 2023-03-26 02:30:00 | nonexistent | 2023-03-26 03:00:00+02:00 | 2023-03-26 01:59:59.999999999+01:00 | NaT                       | NaT                       |
|  1 | 2024-03-31 02:45:00 | nonexistent | 2024-03-31 03:00:00+02:00 | 2024-03-31 01:59:59.999999999+01:00 | NaT                       | NaT                       |
|  0 | 2023-10-29 02:30:00 | ambiguous   | NaT                       | NaT                                 | 2023-10-29 02:30:00+02:00 | 2023-10-29 02:30:00+01:00 |
|  1 | 2024-10-27 02:45:00 | ambiguous   | NaT                       | NaT                                 | 2024-10-27 02:45:00+02:00 | 2024-10-27 02:45:00+01:00 |
```

**Comment by deanm0000** [comment] 2023-10-07 13:02
I'll be there contrarian and say it should error and that should be it.

That said, please, if you add this feature, keep erroring as the default behavior and make the guessing opt-in with a parameter. 

I don't think it should be part of the ambiguous parameter. If someone has a year of data then they might have both the missing hour and the repeating hour to deal with and what to do with one doesn't necessarily correlate to the other.

Tangentially, I'm actually surprised at the proposed guesses. When I deal with non existent times it's either my fault for not localizing before adding/subtracting time or the source skipped the wrong hour.  For example, they'll have 2:15, 2:30, 2:45 but not 3:15, etc so I'll move those up to 3:15, 3:30, 3:45. Mostly it's the former though.

**Comment by MarcoGorelli** [comment] 2023-10-07 13:42
I might not have expressed myself clearly, sorry - the default would still be to raise, the issue is just about adding an option to be able to "roll forward" or "roll backward" to the next / previous valid datetime
There certainly wouldn't be any guessing

Thanks for your comment though, I think I agree with "it should error and that should be it":
- For ambiguous datetimes, these are bound to happen, and you need a way to say which one you meant
- But for non-existent datetimes they indicate an error in the data, and so should probably be resolved prior to doing any further work

**Comment by MarcoGorelli** [comment] 2023-10-07 13:44
Is pandas even correct here?
```python
In [19]: pd.to_datetime(['2020-03-29T02:00']).tz_localize('Europe/London', nonexistent='shift_forward')
Out[19]: DatetimeIndex(['2020-03-29 02:00:00+01:00'], dtype='datetime64[ns, Europe/London]', freq=None)

In [20]: pd.to_datetime(['2020-03-29T01:00']).tz_localize('Europe/London', nonexistent='shift_forward')
Out[20]: DatetimeIndex(['2020-03-29 03:00:00+01:00'], dtype='datetime64[ns, Europe/London]', freq=None)
```

For some reason 1am shifts forwards to 3am, even though 2am is valid 🤔 This leads me to believe that people aren't actually using this argument much, so maybe it doesn't need porting over at all?

**Comment by MarcoGorelli** [comment] 2023-10-08 11:23
Having slept on this, I suggest this just be closed for now, because:
- whereas ambiguous datetimes are a fact of life, non-existent ones indicate a data error which should probably be cleaned by the user
- the "non-existent" counterpart in pandas seems quite buggy, suggesting it's not being used all that much
- there's no built-in way to do this with Chrono, so it would require adding complexity within Polars - and given the above, I'm not sure it's warranted

It's said that in open source 'no' is temporary but 'yes' is forever, so...I suggest this not be supported for now. Can always revisit in the future if more requests and use cases come in

Closing then, but thanks for the suggestion (and all for input!)

**Comment by frodepaaske** [comment] 2023-10-08 16:59
Thank you for taking the time and putting in the effort to look into this :)

**Comment by MarcoGorelli** [comment] 2023-10-09 08:20
Having slept on this again, maybe there should be:
```python
non_existent: Literal['raise', 'null'] = 'raise'
```

If you pass `'raise'` (default, and current behaviour), then non-existent times will raise. But if you pass 'null', then they will become `None`

I think this could just be a single argument, it wouldn't need expressifying

So, this would
- enable you to not have your dataset blow up because of a data error (just pass `non_existent='null'` and deal with it later)
- the default behaviour would still be "blow up in your face"
- it shouldn't add too much complexity to the code

Sound reasonable?

**Comment by stinodego** [comment] 2023-10-14 19:16
Sounds reasonable to me!

**Closed** 2024-03-18 11:38 UTC
Labels: enhancement, A-timeseries, accepted
