### ISSUE TITLE
non strict columns selection when specifying column names

### ISSUE THREAD

**Issue by kbzsl** [pola-rs/polars#16219] opened 2024-05-14 12:52 UTC
### Description

The `ColumnNotFoundError` error is thrown when a column is missing from the provided column list. 

There can be situations when having optional columns; in these cases having a non-strict column selection would simplify the code.  
(as workaround I am using list comprehension to remove the non-existing columns from the column list before the `.select()`)

Something like `cs.any_of()` (inspired by [tidyselect](https://tidyselect.r-lib.org/reference/all_of.html)).

**Comment by alexander-beedie** [comment] 2024-05-14 21:14
Looks like https://github.com/pola-rs/polars/pull/15028 would handle this; currently pending merge 👌

**Comment by stinodego** [comment] 2024-05-15 08:53
Duplicate of #15028

**Closed by stinodego** 2024-05-15 08:53 UTC
Labels: enhancement
