### ISSUE TITLE
list.to_array() unexpected behavior

### ISSUE THREAD

**Issue by echrstnn** [pola-rs/polars#16922] opened 2024-06-13 09:50 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
>>> df
shape: (3, 1)
┌──────────────────────────┐
│ a                        │
│ ---                      │
│ list[f64]                │
╞══════════════════════════╡
│ [-32.611773, -32.593231] │
│ [-32.608927, -32.596912] │
│ [-32.603954, -32.597997] │
└──────────────────────────|
 
>>> df.select(pl.col('a').list.len())
shape: (3, 1)
┌─────┐
│ a   │
│ --- │
│ u32 │
╞═════╡
│ 2   │
│ 2   │
│ 2   │
└─────┘

>>> df.select(pl.col('a').list.to_array(2))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.local/lib/python3.9/site-packages/polars/dataframe/frame.py", line 8461, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
  File "/home/user/.local/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1967, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.ComputeError: not all elements have the specified width 2
```

### Issue description

I have a simple dataframe of lists of 2 elements. I want to transform the `list[f64]` column to an `array[f64, 2]` column. I have an error saying that not all rows are lists of length 2; but it is not true.

Moreover, when I truncate the lists to 99 elements, my dataframe doesn't change (expected):

 

```
>>> df.select(pl.col('a').list.head(99)) == df
shape: (3, 1)
┌──────┐
│ a    │
│ ---  │
│ bool │
╞══════╡
│ true │
│ true │
│ true |
└──────┘
```

 
But the `to_array` operation is now working, which is very strange as the dataframe is the same as before:

 

```
>>> df.select(pl.col('a').list.head(99).list.to_array(2))
shape: (3, 1)
┌──────────────────────────┐
│ a                        │
│ ---                      │
│ array[f64, 2]            │
╞══════════════════════════╡
│ [-32.611773, -32.593231] │
│ [-32.608927, -32.596912] │
│ [-32.603954, -32.597997] │
└──────────────────────────┘
```

 

 

 

 

 

### Expected behavior

The `to_array` operation should work in both cases.

### Installed versions

<details>

```
--------Version info---------

Polars:               0.20.31
Index type:           UInt32
Platform:             Linux-5.14.0
Python:               3.9.18 (main, Sep  7 2023, 00:00:00)
----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               0.10.0
matplotlib:           3.7.5
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                2.2.2+cu121
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment] 2024-06-13 13:32
I cannot reproduce this.

```python
import polars as pl

values = [
    [-32.611773, -32.593231],
    [-32.608927, -32.596912],
    [-32.603954, -32.597997],
]
df = pl.Series("a", values).to_frame()
res = df.select(pl.col("a").list.to_array(2))
print(res)
```
```
shape: (3, 1)
┌──────────────────────────┐
│ a                        │
│ ---                      │
│ array[f64, 2]            │
╞══════════════════════════╡
│ [-32.611773, -32.593231] │
│ [-32.608927, -32.596912] │
│ [-32.603954, -32.597997] │
└──────────────────────────┘
```

**Comment by stinodego** [comment] 2024-06-14 06:32
Closing as "cannot reproduce" until this gets some more info.

**Closed by stinodego** 2024-06-14 06:32 UTC
Labels: bug, python

**Comment by echrstnn** [comment] 2024-06-14 07:05
Data comes from a complex pipeline so it's difficult to provide a MRE. Anyway, it seems related to https://github.com/pola-rs/polars/issues/16693 and switching to pre-release 1.0 fixes the problem
