### ISSUE TITLE
Unpredictable behavior with slice

### ISSUE THREAD

**Issue by Mintactus** [pola-rs/polars#13216] opened 2023-12-23 05:25 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

- Bug report - Polars 0.20.2 Python 3.11.6

```
import polars as pl

data = pl.DataFrame(
    {
        "prospect": ["a", "a", "a", "a", "b", "b"],
        "value": [1, 2, 3, 4, 5, 6],
    }
)

data = (
    data.group_by("prospect")
    .agg("value")
    .select(
        pl.col("value").slice(0, 1), pl.col("value").slice(0, 1).alias("sliced_value")
    )
)
print(data)
```

### Log output

```shell
shape: (1, 2)
┌───────────┬──────────────┐
│ value     ┆ sliced_value │
│ ---       ┆ ---          │
│ list[i64] ┆ list[i64]    │
╞═══════════╪══════════════╡
│ [5, 6]    ┆ [5, 6]       │
└───────────┴──────────────┘


shape: (1, 2)
┌─────────────┬──────────────┐
│ value       ┆ sliced_value │
│ ---         ┆ ---          │
│ list[i64]   ┆ list[i64]    │
╞═════════════╪══════════════╡
│ [1, 2, … 4] ┆ [1, 2, … 4]  │
└─────────────┴──────────────┘
```

### Issue description

This code will sometimes generate different result for each execution, slice will work, slice will not, slice will work then will not...

### Expected behavior

Having the same output for the exact same code each time i run it

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-6.1.66-060166-generic-x86_64-with-glibc2.35
Python:               3.11.6 (main, Nov 20 2023, 20:40:26) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.1
openpyxl:             <not installed>
pandas:               2.1.2
pyarrow:              12.0.1
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.23
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
None
```

</details>

**Comment by avimallu** [comment] 2023-12-23 06:49
This is by design. `group_by` doesn't guarantee the order of the grouping by default, so when you run `slice`, it depends on what the order of groups the operation has landed on in that run. Use `maintain_order=True` to get reproducible results (note that this will be slower, which is why `False` is default in the first place).

**Closed** 2023-12-23 07:13 UTC
Labels: bug, invalid, python
