### ISSUE TITLE
I think PanicException should be a subclass of Exception

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#5607] opened 2022-11-23 16:15 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I think `PanicException` should be a subclass of python's `Exception` class:

Consider this code:

```
try:
    df = pl.DataFrame({'x':['Some text']})
    df/0
except:
    print('''Don't be silly''')
```

This prints the `Don't be silly` string. 

However, 

```
try:
    df = pl.DataFrame({'x':['Some text']})
    df/0
except Exception:
    print('''Don't be silly''')
```

results in the `PanicException` being raised. 

There are very few exceptions in python that are not caught by `Exception`, with `KeyboardInterrupt` being the only one I know to be relevant. 

From the Python documentation: https://docs.python.org/3/library/exceptions.html#:~:text=exception%20Exception,be%20derived%20from%20this%20class.

> exception Exception
All built-in, non-system-exiting exceptions are derived from this class. All user-defined exceptions should also be derived from this class.

### Reproducible example

```python
import polars as pl 
try:
    df = pl.DataFrame({'x':['Some text']})
    df/0
except Exception:
    print('''Don't be silly''')
```
```


### Expected behavior

Exception should catch PanicException

### Installed versions

<details>

```
---Version info---
Polars: 0.14.31
Index type: UInt32
Platform: Windows-10-10.0.22000-SP0
Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.5.1
numpy: 1.22.4
fsspec: 2022.8.2
connectorx: 0.3.1
xlsx2csv: <not installed>
matplotlib: 3.6.2```

</details>

**Comment by mcrumiller** [comment] 2022-11-23 18:38
This is a duplicate of #5606, which was raised one hour earlier.

**Closed** 2022-11-23 19:08 UTC
Labels: bug, python
