### ISSUE TITLE
Parsing error when trying to use numeric field to create a new field

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#10428] opened 2023-08-11 12:40 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
import polars as pl
df = pl.DataFrame({'PROD':['apple','banana','peach'],
                   'VALUE':[12,13,14]})

df.with_row_count(name="RN", offset=1
                  ).with_columns(ID=pl.lit('MY_')+str(pl.col('RN'))
                                 )

```

### Issue description

In the ID column it returns the constant MY_col("RN"),
instead of the MY_1, MY_2, MY_3 values.

### Expected behavior

Return MY_1, MY_2, MY_3 values

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.13
Index type:          UInt32
Platform:            Linux-4.18.0-372.51.1.el8_6.x86_64-x86_64-with-glibc2.28
Python:              3.9.13 (main, Oct 13 2022, 21:15:33) 
[GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.0.0
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2022.02.0
matplotlib:          3.7.2
numpy:               1.21.6
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          1.4.27
xlsx2csv:            <not installed>
xlsxwriter:          3.1.2
```

</details>

**Comment by cmdlineluser** [comment] 2023-08-11 13:25
The issue is you're using Python's `str()` which is "stringifying" the `pl.col()` expression.

```python
>>> str(pl.col("foo"))
'col("foo")'
```
If you want to change the actual type of the column, you can `.cast()`
```python
ID=pl.lit('MY_')+pl.col('RN').cast(pl.Utf8)
```

**Comment by alexander-beedie** [comment] 2023-08-13 04:33
Closing; the `str` value of an expression is not the same as _casting_ the expression to string ;)
```python
df.with_row_count(
    name="RN",
    offset=1,
).with_columns( 
    ID=pl.lit('MY_') + pl.col('RN').cast(pl.Utf8),
)
# shape: (3, 4)
# ┌─────┬────────┬───────┬──────┐
# │ RN  ┆ PROD   ┆ VALUE ┆ ID   │
# │ --- ┆ ---    ┆ ---   ┆ ---  │
# │ u32 ┆ str    ┆ i64   ┆ str  │
# ╞═════╪════════╪═══════╪══════╡
# │ 1   ┆ apple  ┆ 12    ┆ MY_1 │
# │ 2   ┆ banana ┆ 13    ┆ MY_2 │
# │ 3   ┆ peach  ┆ 14    ┆ MY_3 │
# └─────┴────────┴───────┴──────┘
```

**Closed by alexander-beedie** 2023-08-13 04:33 UTC
Labels: bug, invalid, python
