### ISSUE TITLE
join crashes the kernel

### ISSUE THREAD

**Issue by ithakis** [pola-rs/polars#6344] opened 2023-01-20 15:26 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I have 2 datasets, df1 of size 3GB and df2 of size 291MB, and more than 200GB of free memory. When I 
`df3 = df1.join(df2, on="tradedate", how="left") ` 
My kernel crashes and I get the following error:

`warn 15:57:15.467: StdErr from Kernel Process memory allocation of 2333802496 bytes failed

error 15:57:20.465: Disposing session as kernel process died ExitCode: 3221226505, Reason: c:\Users\Alexander\miniforge3\envs\ML1\lib\site-packages\traitlets\traitlets.py:2392: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
c:\Users\Alexander\miniforge3\envs\ML1\lib\site-packages\traitlets\traitlets.py:2346: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '871368ba-ed48-424b-9ce6-3774c05964f6' instead of 'b"871368ba-ed48-424b-9ce6-3774c05964f6"'.
  warn(
memory allocation of 2333802496 bytes failed
`

### Reproducible example

```python
df3 = df1.join(df2, on="tradedate", how="left")
```

### Expected behavior

warn 15:57:15.467: StdErr from Kernel Process memory allocation of 2333802496 bytes failed

error 15:57:20.465: Disposing session as kernel process died ExitCode: 3221226505, Reason: c:\Users\Alexander\miniforge3\envs\ML1\lib\site-packages\traitlets\traitlets.py:2392: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
c:\Users\Alexander\miniforge3\envs\ML1\lib\site-packages\traitlets\traitlets.py:2346: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '871368ba-ed48-424b-9ce6-3774c05964f6' instead of 'b"871368ba-ed48-424b-9ce6-3774c05964f6"'.
  warn(
memory allocation of 2333802496 bytes failed

### Installed versions

python = 3.9.13
polars  = 0.15.14

**Comment by ritchie46** [comment] 2023-01-20 15:29
Does the dataset have many duplicates in the keys?

**Comment by ithakis** [comment] 2023-01-20 15:30
df1 has a lot of duplicates of the same tradedate, yeah. But this is by design

**Comment by ritchie46** [comment] 2023-01-20 15:36
Yes, but a join does an MxN match for every duplicate value. So the ouput table does not fit into memory.

You could try lazy and then `sink_ipc` or sink_parquet` to spill the output to disk.

**Comment by ithakis** [comment] 2023-01-20 15:39
Can you please provide an example for sink_ipc or sink_parquet since I havent used them before? 

Thank you very much for your answer. I didn't know that.

**Comment by ritchie46** [comment] 2023-01-20 15:57
```python
(df1.lazy()
   .join(df2.lazy(), on="tradedate", how="left")
   .sink_ipc("my_large_file.arrow")
)
```

You can also trigger the streaming engine with `collect(streaming=True)`, but in this case your output would be too large.

**Comment by ritchie46** [comment] 2023-01-21 13:35
I will close this as going OOM is not a bug on our side.

**Closed by ritchie46** 2023-01-21 13:35 UTC
Labels: bug, python

**Comment by ithakis** [comment] 2023-01-25 10:13
I updated polars to 0.15.16 and run:

```df2 = (df1.lazy()
   .join(df2.lazy(), on="tradedate", how="left")
   .sink_ipc("my_large_file.arrow")
)```

I still get the following error though:

```
warn 11:02:37.262: StdErr from Kernel Process memory allocation of 3680501760 bytes failed
memory allocation of 3384803328 bytes failed

error 11:02:44.016: Disposing session as kernel process died ExitCode: 3221226505, Reason: c:\Users\Alexander\miniforge3\envs\ML1\lib\site-packages\traitlets\traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
c:\Users\Alexander\miniforge3\envs\ML1\lib\site-packages\traitlets\traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'deea84bb-0806-436f-a998-097e052b70a2' instead of 'b"deea84bb-0806-436f-a998-097e052b70a2"'.
  warn(
memory allocation of 3680501760 bytes failed
memory allocation of 3384803328 bytes failed
```

**Comment by ritchie46** [comment] 2023-01-25 10:28
Can you make an MWE then? Then I can take a look.
