### ISSUE TITLE
GPU leveraging

### ISSUE THREAD

**Issue by albinocordeiro** [pola-rs/polars#12358] opened 2023-11-10 06:04 UTC
### Description

Introduce ways to leverage GPUs. There should be a seamless way for non-expert users and but optional flexibility so expert users can maximize gains.

**Comment by MarcoGorelli** [comment] 2023-11-10 07:15
thanks for the issue, closing as dupe of https://github.com/pola-rs/polars/issues/5978

**Closed by MarcoGorelli** 2023-11-10 07:15 UTC
Labels: enhancement
