### ISSUE TITLE
Add pl.Expr.cut method - identical to pl.Series.cut

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#9389] opened 2023-06-15 18:03 UTC
### Problem description

I noticed there is no easy way to bin continuious data into ranges using polars. 

Consider 

```python
df = pl.DataFrame({'x':np.linspace(0,100,101)})


# This works great:
(df['x']
    .cut([25,50,75]) # <- this is the important part
    .take_every(20)
    .pipe(print)
)
shape: (6, 3)
┌───────┬─────────────┬──────────────┐
│ x     ┆ break_point ┆ category     │
│ ---   ┆ ---         ┆ ---          │
│ f64   ┆ f64         ┆ cat          │
╞═══════╪═════════════╪══════════════╡
│ 0.0   ┆ 25.0        ┆ (-inf, 25.0] │
│ 20.0  ┆ 25.0        ┆ (-inf, 25.0] │
│ 40.0  ┆ 50.0        ┆ (25.0, 50.0] │
│ 60.0  ┆ 75.0        ┆ (50.0, 75.0] │
│ 80.0  ┆ inf         ┆ (75.0, inf]  │
│ 100.0 ┆ inf         ┆ (75.0, inf]  │
└───────┴─────────────┴──────────────┘

# This does not work
(df
   .with_columns(
        x_binned = pl.col('x').cut([25,50,75])
   )
   .take_every(20)
   .pipe(print)
)
>>> AttributeError: 'Expr' object has no attribute 'cut'
```

Overall I think `.cut` would be a nice method to have, and worth adding to the api.

**Comment by mcrumiller** [comment] 2023-06-15 20:38
Duplicate of #8551, #8870. This is a pretty often-requested feature.

**Comment by zundertj** [comment] 2023-06-18 11:12
This is a valid request, but closing in favor of #8551 to keep the issue tracker tidy. Please upvote and/or comment there.

**Closed by zundertj** 2023-06-18 11:12 UTC
Labels: enhancement

**Comment by stevenlis** [comment] 2023-07-14 20:58
@mcrumiller Is there any reason the param is `breaks` in expr but `bins` in series method? Maybe they should be consistent.

**Comment by mcrumiller** [comment] 2023-07-15 18:31
@stevenlis they definitely should be consistent, you're right.
