### ISSUE TITLE
Polars to_arrow returns large_string

### ISSUE THREAD

**Issue by EnricoMi** [pola-rs/polars#5497] opened 2022-11-14 08:54 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Creating a Polars DataFrame from an Arrow table and going back to Arrow should return the identical schema. However, `polars.from_arrow(table).to_arrow()` changes the type of strings from `string` to `large_string`.

Is there a way to control this? Is there a reason for relaxing the type of string columns?

### Reproducible example

```python
import polars
import pyarrow

table = pyarrow.table([["foo"]], names=["bar"])

print(table.schema)
bar: string

print(polars.from_arrow(table).to_arrow().schema)
bar: large_string
```

### Expected behavior

assert(polars.from_arrow(table).to_arrow().schema == table.schema)

### Installed versions

<details>

```
>>> pl.show_versions()
---Version info---
Polars: 0.14.27
Index type: UInt32
Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.3
numpy: 1.23.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.2.2

>>> pa.show_versions()
pyarrow version info
--------------------
Package kind              : python-wheel-manylinux2014
Arrow C++ library version : 8.0.0   
Arrow C++ compiler        : GNU 10.2.1
Arrow C++ compiler flags  :  -fdiagnostics-color=always -O3 -DNDEBUG
Arrow C++ git revision    : c3d031250a7fdcfee5e576833bf6f39097602c30
Arrow C++ git description :         
Arrow C++ build type      : release 
```

</details>

**Comment by ritchie46** [comment] 2022-11-14 09:38
That's expected. Polars does not support the small string, so it coerces to large string. You can downcast again in pyarrow if you want to maintain small string data.

**Comment by EnricoMi** [comment] 2022-11-14 09:47
I see. I think, documentation can be improved here. Method `polars.from_arrow` [says](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.from_arrow.html#polars.from_arrow)

    This operation will be zero copy for the most part. Types that are not supported by Polars may be cast
    to the closest supported type.

A complete table with unsupported Arrow types and their closest supported type would be helpful here.

Type `polars.Utf8` [does not mention](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Utf8.html#polars.Utf8) that it is a Arrow `large_string` internally.

**Comment by EnricoMi** [comment] 2022-11-14 09:48
Happy to relabel this issue with `question` and `docs` labels.

**Comment by ritchie46** [comment] 2022-11-14 09:53
We do mention it in the User Guide: https://pola-rs.github.io/polars-book/user-guide/datatypes.html.

Could you make a PR id you feel our docs can be improved?

**Comment by ritchie46** [comment] 2022-11-15 07:35
I will close this as this is documented and not a bug on our side.

**Closed by ritchie46** 2022-11-15 07:35 UTC
Labels: bug, python
