### ISSUE TITLE
`melt()`: Support melting multiple observations per row

### ISSUE THREAD

**Issue by mgirlich** [pola-rs/polars#15279] opened 2024-03-25 10:53 UTC
### Description

```python
household = pl.from_repr("""
┌────────┬────────────┬────────────┬─────────────┬─────────────┐
│ family ┆ dob_child1 ┆ dob_child2 ┆ name_child1 ┆ name_child2 │
│ ---    ┆ ---        ┆ ---        ┆ ---         ┆ ---         │
│ i64    ┆ str        ┆ str        ┆ str         ┆ str         │
╞════════╪════════════╪════════════╪═════════════╪═════════════╡
│ 1      ┆ 1998-11-26 ┆ 2000-01-29 ┆ Susan       ┆ Jose        │
│ 2      ┆ 1996-06-22 ┆ null       ┆ Mark        ┆ null        │
│ 3      ┆ 2002-07-11 ┆ 2004-04-05 ┆ Sam         ┆ Seth        │
│ 4      ┆ 2004-10-10 ┆ 2009-08-27 ┆ Craig       ┆ Khai        │
│ 5      ┆ 2000-12-05 ┆ 2005-02-28 ┆ Parker      ┆ Gracie      │
└────────┴────────────┴────────────┴─────────────┴─────────────┘
""")
(
    household
    .melt(id_vars="family")
    .filter(pl.col("value").is_not_null())
    .with_columns(
        child=pl.col("variable").str.extract("(.*)_(.*)", 2),
        variable=pl.col("variable").str.extract("(.*)_(.*)", 1)
    ).
    pivot(
        values="value",
        index=["family", "child"],
        columns="variable",
    )
    .sort(["family", "child"])
)

# results in
# ┌────────┬────────┬────────────┬────────┐
# │ family ┆ child  ┆ dob        ┆ name   │
# │ ---    ┆ ---    ┆ ---        ┆ ---    │
# │ i64    ┆ str    ┆ str        ┆ str    │
# ╞════════╪════════╪════════════╪════════╡
# │ 1      ┆ child1 ┆ 1998-11-26 ┆ Susan  │
# │ 1      ┆ child2 ┆ 2000-01-29 ┆ Jose   │
# │ 2      ┆ child1 ┆ 1996-06-22 ┆ Mark   │
# │ 3      ┆ child1 ┆ 2002-07-11 ┆ Sam    │
# │ 3      ┆ child2 ┆ 2004-04-05 ┆ Seth   │
# │ 4      ┆ child1 ┆ 2004-10-10 ┆ Craig  │
# │ 4      ┆ child2 ┆ 2009-08-27 ┆ Khai   │
# │ 5      ┆ child1 ┆ 2000-12-05 ┆ Parker │
# │ 5      ┆ child2 ┆ 2005-02-28 ┆ Gracie │
# └────────┴────────┴────────────┴────────┘
```

It would be great if this could be done via something like

```python
(
    household
    .melt(
        id_vars="family",
        variable_name=[pl.MeltValue, "child"],
        variable_pattern="(.*)_(.*)",
    )
)
```

(This feature is basically what the R function tidyr::pivot_longer() can do. You can find some more background on this functionality in [this vignette](https://tidyr.tidyverse.org/articles/pivot.html#multiple-observations-per-row))

This is also related to https://github.com/pola-rs/polars/issues/15276, a request to add `variable_pattern` and support an iterable for `variable_name`.

**Comment by avimallu** [comment] 2024-03-25 13:03
Broadly a duplicate of https://github.com/pola-rs/polars/issues/8903.

**Comment by deanm0000** [comment] 2024-04-02 06:24
closing in favor of https://github.com/pola-rs/polars/issues/8903

**Closed by deanm0000** 2024-04-02 06:24 UTC
Labels: enhancement
