### ISSUE TITLE
Slowdown of up to 2x compared to NumPy / Pandas in division operator

### ISSUE THREAD

**Issue by liufeimath** [pola-rs/polars#17414] opened 2024-07-04 01:04 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I have the following test code with time measures:
```python
import time
import polars as pl
import pandas as pd
import numpy as np

n = 10_000_000
np_arrs = {"x": np.random.rand(n), "y": np.random.rand(n)}
pl_df = pl.DataFrame(np_arrs)
pd_df = pd.DataFrame(np_arrs)

t0 = time.time()
z = np_arrs["x"] / np_arrs["y"]
t1 = time.time()
print(f"time cost: {round((t1 - t0) * 1000)} ms")  # 20 ms

t0 = time.time()
z = pl_df["x"] / pl_df["y"]
t1 = time.time()
print(f"time cost: {round((t1 - t0) * 1000)} ms")  # 42 ms

t0 = time.time()
z = pd_df["x"] / pd_df["y"]
t1 = time.time()
print(f"time cost: {round((t1 - t0) * 1000)} ms")  # 18 ms
```
It's bizarre to me that polars is about 2x slow. Does anyone know why?

My test environments:
- computer: MBP 2020, 13inch, 2GHz 4-core i5, 16GB mem
- python: 3.12.3
- numpy: 1.26.4
- pandas: 2.2.2
- polars: 1.0.0

I have this question originally posted on [stackoverflow](https://stackoverflow.com/questions/78687685/why-is-my-polars-slower-than-pandas-in-simple-column-divisions). The user [jqurious](https://stackoverflow.com/users/19355181/jqurious) pointed out it could be faster by (and it did):
`z = pl_df.lazy().select(pl.col.x / pl.col.y).collect(streaming=True)`
without `streaming=True`, it'll fall back to the old 40ms~50ms time cost.

Hence the question: what should I do to "make it right" in such basic operations?

### Issue description

Polars is 2x slower than pandas in basic column-wise operations (two-column division in this specific test case).

### Expected behavior

Polars should have comparable speed v.s. pandas and numpy in such simple operations.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0
Index type:           UInt32
Platform:             macOS-13.6.7-x86_64-i386-64bit
Python:               3.12.3 (v3.12.3:f6650f9ad7, Apr  9 2024, 08:18:48) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.7.4
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                2.2.2
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by liufeimath** [comment] 2024-07-04 11:42
@orlp Sure. Here's what I see:
```
numpy 1.7664612449007109
polars 3.8596145160263404
polars (lazy query) 1.6810565140331164
pandas 1.7963620449882
```

**Comment by orlp** [comment] 2024-07-04 12:43
@liufeimath We can't reproduce on Apple M2 but can on an Intel laptop, we'll take a look at it.

**Comment by liufeimath** [comment] 2024-07-04 13:34
@orlp Thanks! Another info worth noting:
I eyeballed the CPU occupancy in osx activity monitor (after changed number (of measures) to 1000 so that I have longer time for a stable eyeball results):

- np costs 100% CPU consistently (1 core)
- pl default costs 100% CPU consistently
- pl lazy + stream costs 400% CPU consistently (so it uses all my cores)
- pd costs 100% CPU consistently (which behaves like a simple wrapper over numpy in this plain test case)

I have another intel laptop (linux) showing similar results, i.e. single core pl costs about 2x time v.s. np. Can it be the boolean indicator array operation cost? But that should be simd bit operations and very fast right? Also it looks like the lazy+stream performance boost comes from multithreading.

**Comment by liufeimath** [comment] 2024-07-04 13:37
Ah here's another guess: my computer is so old that the cpu simd instruction sets are not-at-all up to date. So it has to use some naive bit operations which is as slow as f64 divisions (though that sounds really slow).

**Comment by coastalwhite** [comment] 2024-07-04 16:29
We looked at this a bit today and I can reproduce this on my machine. We haven't found the exact reason yet. We'll do some more digging.

**Comment by s-banach** [comment] 2024-07-04 16:30
For reference on my zen4 processor:
```
numpy 1.1182205999502912
polars 0.7442328999750316
polars (lazy query) 0.6784979000221938
pandas 0.7861381999682635
```

**Comment by Chuck321123** [comment] 2024-07-05 23:39
I get opposite results on i7 13700H
```
26.4 ms ± 1.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
10.5 ms ± 521 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
23.4 ms ± 943 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by coastalwhite** [comment] 2024-07-08 10:24
It seems as if for some reason the Polars implementation is causing a whole load of page faults on Intel processors. I am not quite sure why. If we completely isolate the loops:

```rust
use polars::prelude::NamedFromOwned;
use polars::series::Series;
use rand::Rng;

const ARRAY_SIZE: usize = 10_000_000;
const NUM_LOOPS: usize = 500;

#[inline(never)]
fn run_loops(a: &Series, b: &Series) {
    let start_time = std::time::SystemTime::now();

    for _ in 0..NUM_LOOPS {
        use std::ops::Div;
        let result = a.div(b);
        let result = result.unwrap();
        _ = std::hint::black_box(result);
    }

    let duration = start_time.elapsed().unwrap();

    println!("time: {}s", duration.as_secs_f32());
}

fn main() {
    let mut a: Vec<f64> = Vec::with_capacity(ARRAY_SIZE);
    let mut b: Vec<f64> = Vec::with_capacity(ARRAY_SIZE);

    unsafe {
        a.set_len(ARRAY_SIZE);
        b.set_len(ARRAY_SIZE);
    }

    let mut rng = rand::thread_rng();

    rng.fill(&mut a[..]);
    rng.fill(&mut b[..]);

    let a = Series::from_vec("a", a);
    let b = Series::from_vec("b", b);

    run_loops(&a, &b);
}
```

```
sudo perf stat -e dTLB-load-misses,page-faults ./target/release-with-debug/polars-divloop
time: 21.96687s

 Performance counter stats for './target/release-with-debug/polars-divloop':

        22,569,652      cpu_atom/dTLB-load-misses/                                              (0.34%)
         1,505,594      cpu_core/dTLB-load-misses/                                              (99.66%)
         9,805,232      page-faults

      22.154435210 seconds time elapsed

       6.539028000 seconds user
      15.522541000 seconds sys
```

And as reference:

```rust
use std::mem::MaybeUninit;

const SIZE: usize = 10_000_000;
const REPEATS: usize = 500;

type T = f64;
type L = T;
type R = T;
type O = T;

fn op(l: T, r: T) -> T {
    l / r
}

#[inline(never)]
unsafe fn polars(left: *const L, right: *const R, out: *mut O, len: usize) {
    // This function unrolls manually a result of issue #17414. Here, OLP and GB found that the
    // loop was not properly unrolling on Intel AVX2. We tried several code unrolling techniques
    // and this variant generated good assembly.
    //
    // These blocksizes are based on AVX2 with 16 blocksize for f64, it seems to unroll the loop 4
    // times.
    let block_size = match std::mem::size_of::<O>() {
        0..=1 => 64,
        2 => 32,
        3..=4 => 16,
        5..=8 => 8,
        9..=16 => 4,
        _ => 1,
    };

    // We use a temporary stack buffer so the compiler can read block_size values in a row without
    // worrying our write-back to out overlaps with those reads.
    //
    // This buffer needs to have the size of the maximum block_size.
    let mut buf: [MaybeUninit<T>; 64] = [(); 64].map(|_| MaybeUninit::uninit());
    let mut offset = 0;
    while offset + block_size <= len {
        let buf_chunk = &mut buf[0..block_size];
        let left_chunk = core::slice::from_raw_parts(left.add(offset), block_size);
        let right_chunk = core::slice::from_raw_parts(right.add(offset), block_size);
        for i in 0..block_size {
            buf_chunk[i] = MaybeUninit::new(op(left_chunk[i], right_chunk[i]));
        }

        core::ptr::copy_nonoverlapping(buf_chunk.as_ptr().cast(), out.add(offset), block_size);
        offset += block_size;
    }

    while offset < len {
        let ret = op(left.add(offset).read(), right.add(offset).read());
        out.add(offset).write(ret);
        offset += 1;
    }
}

fn main() {
    let mut left: Vec<T> = Vec::with_capacity(SIZE);
    let mut right: Vec<T> = Vec::with_capacity(SIZE);
    let mut out: Vec<T> = Vec::with_capacity(SIZE);

    for i in 0..SIZE {
        left.push(((i * 23) % 101) as T);
        right.push(((i * 7) % 31) as T);
    }

    let start = std::time::SystemTime::now();

    for _ in 0..REPEATS {
        unsafe { polars(left.as_ptr(), right.as_ptr(), out.as_mut_ptr(), SIZE) };
        unsafe { out.set_len(SIZE) };
        std::hint::black_box(&out);
    }

    let elapsed = start.elapsed().unwrap();

    println!("time: {:.02}s", elapsed.as_secs_f32());
}
```

```
sudo perf stat -e dTLB-load-misses,page-faults ./target/release/divloop
time: 7.07s

 Performance counter stats for './target/release/divloop':

         8,666,881      cpu_atom/dTLB-load-misses/                                              (0.16%)
         5,056,767      cpu_core/dTLB-load-misses/                                              (99.84%)
            58,669      page-faults

       7.199732690 seconds time elapsed

       7.052191000 seconds user
       0.119500000 seconds sys
```

You can see the that whole difference is the time spend in `sys` so probably resolving the page faults. Very, very peculiar.

**Comment by coastalwhite** [comment] 2024-07-08 15:17
Quite a rabbit-hole later and we are pretty confident in a theory as to why this is happening, but we don't really have a solution to the problem.

Since this is such a large array operation, the hardware prefetchers are very, very important to performing this fast. It seems, however, that Intel chips don't perform that well at prefetching for three simultaneous linear scans. ARM and AMD seem to be better in that respect. We also don't currently use huge pages, which exacerbates this problem and is probably why NumPy and Pandas faster here.

Again, some of this is from experimentation and some is from speculation.

I am leaving this issue open as a reference, but I am not 100% sure we are every going to resolve this apart from possibly adding huge pages in the future.

**Comment by ritchie46** [comment] 2024-08-12 16:02
fixed by https://github.com/pola-rs/polars/pull/18148

**Closed by ritchie46** 2024-08-12 16:02 UTC
Labels: python, performance, reference

**Comment by liufeimath** [comment] 2024-08-13 09:56
> fixed by #18148

Many thanks for the fix! When do we expect this released so that I can test it?

**Comment by liufeimath** [comment] 2024-08-15 06:55
@ritchie46 I'm testing with `1.5.0` where the fix is supposed to be included based on the commit log. However I don't see any improvements. I tested with the previous code snippet:
```python
from timeit import timeit
import polars as pl
import pandas as pd
import numpy as np

n = 10_000_000
np_arrs = {"x": np.random.rand(n), "y": np.random.rand(n)}
pl_df = pl.DataFrame(np_arrs)
pd_df = pd.DataFrame(np_arrs)

print("numpy", timeit(lambda: np_arrs["x"] / np_arrs["y"], number=100))
print("polars", timeit(lambda: pl_df["x"] / pl_df["y"], number=100))
print("polars (lazy query)", timeit(lambda: pl_df.lazy().select(pl.col.x / pl.col.y).collect(streaming=True), number=100))
print("pandas", timeit(lambda: pd_df["x"] / pd_df["y"], number=100))
```
and I'm seeing similar results:
```
numpy 1.8230175760036218
polars 3.8913753919987357
polars (lazy query) 1.6485352070012596
pandas 1.8605419789964799
```

**Comment by cmdlineluser** [comment] 2024-08-15 07:32
@liufeimath Does anything change with the `_RJEM_MALLOC_CONF` settings from https://github.com/pola-rs/polars/issues/18088#issuecomment-2278511531
```
_RJEM_MALLOC_CONF="background_thread:true,dirty_decay_ms:500,muzzy_decay_ms:-1"
```

**Comment by liufeimath** [comment] 2024-08-15 08:35
> @liufeimath Does anything change with the `_RJEM_MALLOC_CONF` settings from [#18088 (comment)](https://github.com/pola-rs/polars/issues/18088#issuecomment-2278511531)
> 
> ```
> _RJEM_MALLOC_CONF="background_thread:true,dirty_decay_ms:500,muzzy_decay_ms:-1"
> ```

Yes. It resolves the issue. To make sure I'm doing it right, let me list in details my test steps below:

1. start an ipython shell with the env var, by: `_RJEM_MALLOC_CONF="background_thread:true,dirty_decay_ms:500,muzzy_decay_ms:-1" ipython`
2. run the [test code](https://github.com/pola-rs/polars/issues/17414#issuecomment-2290777132) above

Now I see this:
```
<jemalloc>: option background_thread currently supports pthread only
numpy 1.9955631760021788
polars 1.4676521660003345
polars (lazy query) 0.7916534629985108
pandas 2.0349335220016656
```
polars is even faster (notably) than numpy now.

btw, can you add a right-double-quote (currently missing) in your [original comment](https://github.com/pola-rs/polars/issues/18088#issuecomment-2278511531) so people don't get confused? Thanks!

**Comment by orlp** [comment] 2024-08-15 08:42
@liufeimath Can you try two things for me?

1. The benchmark with `n = 10**6`?
2. Post the output of `_RJEM_MALLOC_CONF="stats_print:true" python -c "import polars as pl; pl.show_versions()"`

Either way, we've concluded that this difference is nothing to do with the actual arithmetic kernels being slower, but everything to do with the allocator, and that the `timeit` benchmark kind of exposes a very peculiar thing of it.

In one iteration of the benchmark you compute `pl_df["x"] / pl_df["y"]`, which creates a new array in memory. Then this immediately gets dropped, and right after you again compute `pl_df["x"] / pl_df["y"]` again. Some allocators will keep the memory around from the first iteration around for re-use, ours (jemallocator) doesn't do this above a certain size with certain parameters and immediately releases it to the OS in a way that causes a lot of page faults if you then allocate it again.

**Comment by orlp** [comment] 2024-08-15 08:48
@liufeimath Another I noticed from your reproduction steps, is that you wrote `ipython` as a command directly. If you use `ipython` then it will take your global `ipython`, not the one from your `venv`. If you have installed polars 1.5.0 in your `venv` you need to use `python -m IPython` to start it.

**Comment by liufeimath** [comment] 2024-08-15 08:56
> @liufeimath Can you try two things for me?
> 
> 1. The benchmark with `n = 10**6`?
> 2. Post the output of `_RJEM_MALLOC_CONF="stats_print:true" python -c "import polars as pl; pl.show_versions()"`
> 
> Either way, we've concluded that this difference is nothing to do with the actual arithmetic kernels being slower, but everything to do with the allocator, and that the `timeit` benchmark kind of exposes a very peculiar thing of it.
> 
> In one iteration of the benchmark you compute `pl_df["x"] / pl_df["y"]`, which creates a new array in memory. Then this immediately gets dropped, and right after you again compute `pl_df["x"] / pl_df["y"]` again. Some allocators will keep the memory around from the first iteration around for re-use, ours (jemallocator) doesn't do this above a certain size with certain parameters and immediately releases it to the OS in a way that causes a lot of page faults if you then allocate it again.

Sure.

#### Benchmark with n=1e6
It shows that polars has better performance in both the with and without that env var.
without the _RJEM_MALLOC_CONF setting:
```
numpy 0.1790373779949732
polars 0.1273345449953922
polars (lazy query) 0.10891474499658216
pandas 0.21069722399988677
```
with the _RJEM_MALLOC_CONF setting:
```
numpy 0.16956399199989391
polars 0.12949085899890633
polars (lazy query) 0.1106279320010799
pandas 0.18982984700414818
```

#### the output of `_RJEM_MALLOC_CONF="stats_print:true" python -c "import polars as pl; pl.show_versions()"`
```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             macOS-13.6.7-x86_64-i386-64bit
Python:               3.12.3 (v3.12.3:f6650f9ad7, Apr  9 2024, 08:18:48) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.10.0
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.7.4
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                2.2.2
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
___ Begin jemalloc statistics ___
Version: "5.3.0-0-g54eaed1d8b56b1aa528be3bdd1877e59c56fa90c"
Build-time option settings
  config.cache_oblivious: true
  config.debug: false
  config.fill: true
  config.lazy_lock: false
  config.malloc_conf: "dirty_decay_ms:500,muzzy_decay_ms:-1"
  config.opt_safety_checks: false
  config.prof: false
  config.prof_libgcc: false
  config.prof_libunwind: false
  config.stats: true
  config.utrace: false
  config.xmalloc: false
Run-time option settings
  opt.abort: false
  opt.abort_conf: false
  opt.cache_oblivious: true
  opt.confirm_conf: false
  opt.retain: false
  opt.dss: "secondary"
  opt.narenas: 32
  opt.percpu_arena: "disabled"
  opt.oversize_threshold: 8388608
  opt.hpa: false
  opt.hpa_slab_max_alloc: 65536
  opt.hpa_hugification_threshold: 1992294
  opt.hpa_hugify_delay_ms: 10000
  opt.hpa_min_purge_interval_ms: 5000
  opt.hpa_dirty_mult: "0.25"
  opt.hpa_sec_nshards: 4
  opt.hpa_sec_max_alloc: 32768
  opt.hpa_sec_max_bytes: 262144
  opt.hpa_sec_bytes_after_flush: 131072
  opt.hpa_sec_batch_fill_extra: 0
  opt.metadata_thp: "disabled"
  opt.mutex_max_spin: 600
  opt.dirty_decay_ms: 500 (arenas.dirty_decay_ms: 500)
  opt.muzzy_decay_ms: -1 (arenas.muzzy_decay_ms: -1)
  opt.lg_extent_max_active_fit: 6
  opt.junk: "false"
  opt.zero: false
  opt.tcache: true
  opt.tcache_max: 32768
  opt.tcache_nslots_small_min: 20
  opt.tcache_nslots_small_max: 200
  opt.tcache_nslots_large: 20
  opt.lg_tcache_nslots_mul: 1
  opt.tcache_gc_incr_bytes: 65536
  opt.tcache_gc_delay_bytes: 0
  opt.lg_tcache_flush_small_div: 1
  opt.lg_tcache_flush_large_div: 1
  opt.thp: "not supported"
  opt.stats_print: true
  opt.stats_print_opts: ""
  opt.stats_print: true
  opt.stats_print_opts: ""
  opt.stats_interval: -1
  opt.stats_interval_opts: ""
  opt.zero_realloc: "alloc"
Arenas: 33
Quantum size: 16
Page size: 4096
Maximum thread-cached size class: 32768
Number of bin size classes: 36
Number of thread-cache bin size classes: 41
Number of large size classes: 196
Allocated: 621408, active: 724992, metadata: 3650544 (n_thp 0), resident: 4284416, mapped: 7016448, retained: 0
Count of realloc(non-null-ptr, 0) calls: 0
Background threads: 0, num_runs: 0, run_interval: 0 ns
                           n_lock_ops (#/sec)       n_waiting (#/sec)      n_spin_acq (#/sec)  n_owner_switch (#/sec)   total_wait_ns   (#/sec)     max_wait_ns  max_n_thds
background_thread                   0       0               0       0               0       0               0       0               0         0               0           0
max_per_bg_thd                      0       0               0       0               0       0               0       0               0         0               0           0
ctl                                 2       0               0       0               0       0               1       0               0         0               0           0
prof                                0       0               0       0               0       0               0       0               0         0               0           0
prof_thds_data                      0       0               0       0               0       0               0       0               0         0               0           0
prof_dump                           0       0               0       0               0       0               0       0               0         0               0           0
prof_recent_alloc                   0       0               0       0               0       0               0       0               0         0               0           0
prof_recent_dump                    0       0               0       0               0       0               0       0               0         0               0           0
prof_stats                          0       0               0       0               0       0               0       0               0         0               0           0
arenas[0]:
assigned threads: 1
uptime: 18833751757
dss allocation precedence: "disabled"
decaying:  time       npages       sweeps     madvises       purged
   dirty:   500            0            1            1            8
   muzzy:   N/A            0            0            0            0
                            allocated         nmalloc   (#/sec)         ndalloc   (#/sec)       nrequests   (#/sec)           nfill   (#/sec)          nflush   (#/sec)
small:                         510816            1233        68               0         0             833        46              24         1              36         2
large:                         110592               4         0               1         0               5         0               4         0              15         0
total:                         621408            1237        68               1         0             838        46              28         1              51         2
                                     
active:                        724992
mapped:                       7016448
retained:                           0
base:                         3553264
internal:                       97280
metadata_thp:                       0
tcache_bytes:                  477784
tcache_stashed_bytes:               0
resident:                     4284416
abandoned_vm:                       0
extent_avail:                       0
                           n_lock_ops (#/sec)       n_waiting (#/sec)      n_spin_acq (#/sec)  n_owner_switch (#/sec)   total_wait_ns   (#/sec)     max_wait_ns  max_n_thds
large                               2       0               0       0               0       0               1       0               0         0               0           0
extent_avail                       68       3               0       0               0       0               4       0               0         0               0           0
extents_dirty                      69       3               0       0               0       0               4       0               0         0               0           0
extents_muzzy                      67       3               0       0               0       0               3       0               0         0               0           0
extents_retained                   67       3               0       0               0       0               3       0               0         0               0           0
decay_dirty                         5       0               0       0               0       0               2       0               0         0               0           0
decay_muzzy                         2       0               0       0               0       0               1       0               0         0               0           0
base                              109       6               0       0               0       0               3       0               0         0               0           0
tcache_list                         6       0               0       0               0       0               2       0               0         0               0           0
hpa_shard                           0       0               0       0               0       0               0       0               0         0               0           0
hpa_shard_grow                      0       0               0       0               0       0               0       0               0         0               0           0
hpa_sec                             0       0               0       0               0       0               0       0               0         0               0           0
bins:           size ind    allocated      nmalloc (#/sec)      ndalloc (#/sec)    nrequests   (#/sec)  nshards      curregs     curslabs  nonfull_slabs regs pgs   util       nfills (#/sec)     nflushes (#/sec)       nslabs     nreslabs (#/sec)      n_lock_ops (#/sec)       n_waiting (#/sec)      n_spin_acq (#/sec)  n_owner_switch (#/sec)   total_wait_ns   (#/sec)     max_wait_ns  max_n_thds
                   8   0          800          100       5            0       0          276        15        1          100            1              0  512   1  0.195            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                  16   1         1600          100       5            0       0           54         3        1          100            1              0  256   1  0.390            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                  32   2         3200          100       5            0       0          173         9        1          100            1              0  128   1  0.781            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                  48   3         4800          100       5            0       0           14         0        1          100            1              0  256   3  0.390            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                  64   4         4096           64       3            0       0           59         3        1           64            1              0   64   1      1            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                  80   5         8000          100       5            0       0            4         0        1          100            1              0  256   5  0.390            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                  96   6         9600          100       5            0       0            1         0        1          100            1              0  128   3  0.781            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                     ---
                 128   8         4096           32       1            0       0           91         5        1           32            1              0   32   1      1            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                 160   9        16000          100       5            0       0           38         2        1          100            1              0  128   5  0.781            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                 192  10        12288           64       3            0       0           14         0        1           64            1              0   64   3      1            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                 224  11        22400          100       5            0       0           39         2        1          100            1              0  128   7  0.781            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                 256  12         4096           16       0            0       0           17         0        1           16            1              0   16   1      1            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                 320  13        20480           64       3            0       0            8         0        1           64            1              0   64   5      1            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                 384  14        12288           32       1            0       0            2         0        1           32            1              0   32   3      1            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                 448  15        28672           64       3            0       0            6         0        1           64            1              0   64   7      1            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                 512  16         5120           10       0            0       0           10         0        1           10            2              0    8   1  0.625            1       0            1       0            2            0       0               8       0               0       0               0       0               2       0               0         0               0           0
                     ---
                 768  18        12288           16       0            0       0            1         0        1           16            1              0   16   3      1            1       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                     ---
                1024  20        10240           10       0            0       0            9         0        1           10            3              0    4   1  0.833            1       0            1       0            3            0       0               9       0               0       0               0       0               2       0               0         0               0           0
                     ---
                2048  24        20480           10       0            0       0            6         0        1           10            5              0    2   1      1            1       0            1       0            5            0       0              11       0               0       0               0       0               2       0               0         0               0           0
                2560  25        25600           10       0            0       0            1         0        1           10            2              0    8   5  0.625            1       0            1       0            2            0       0               8       0               0       0               0       0               2       0               0         0               0           0
                3072  26         3072            1       0            0       0            1         0        1            1            1              0    4   3  0.250            0       0            1       0            1            0       0               7       0               0       0               0       0               2       0               0         0               0           0
                3584  27        35840           10       0            0       0            1         0        1           10            2              0    8   7  0.625            1       0            1       0            2            0       0               8       0               0       0               0       0               2       0               0         0               0           0
                4096  28        40960           10       0            0       0            4         0        1           10           10              0    1   1      1            1       0            1       0           10            0       0              16       0               0       0               0       0               2       0               0         0               0           0
                     ---
                8192  32        81920           10       0            0       0            2         0        1           10           10              0    1   2      1            1       0            1       0           10            0       0              16       0               0       0               0       0               2       0               0         0               0           0
                     ---
               12288  34       122880           10       0            0       0            2         0        1           10           10              0    1   3      1            1       0            1       0           10            0       0              16       0               0       0               0       0               2       0               0         0               0           0
                     ---
large:          size ind    allocated      nmalloc (#/sec)      ndalloc (#/sec)    nrequests (#/sec)  curlextents
               16384  36        16384            1       0            0       0            2       0            1
                     ---
               28672  39        28672            2       0            1       0            2       0            1
                     ---
               65536  44        65536            1       0            0       0            1       0            1
                     ---
extents:        size ind       ndirty        dirty       nmuzzy        muzzy    nretained     retained       ntotal        total
                     ---
Bytes in small extent cache: 0
HPA shard stats:
  Purge passes: 0 (0 / sec)
  Purges: 0 (0 / sec)
  Hugeifies: 0 (0 / sec)
  Dehugifies: 0 (0 / sec)

  In full slabs:
      npageslabs: 0 huge, 0 nonhuge
      nactive: 0 huge, 0 nonhuge 
      ndirty: 0 huge, 0 nonhuge 
      nretained: 0 huge, 0 nonhuge 
  In empty slabs:
      npageslabs: 0 huge, 0 nonhuge
      nactive: 0 huge, 0 nonhuge 
      ndirty: 0 huge, 0 nonhuge 
      nretained: 0 huge, 0 nonhuge 

                size ind npageslabs_huge    nactive_huge     ndirty_huge  npageslabs_nonhuge     nactive_nonhuge      ndirty_nonhuge   nretained_nonhuge
                     ---
--- End jemalloc statistics ---
```

**Comment by liufeimath** [comment] 2024-08-15 09:00
> In one iteration of the benchmark you compute `pl_df["x"] / pl_df["y"]`, which creates a new array in memory. Then this immediately gets dropped, and right after you again compute `pl_df["x"] / pl_df["y"]` again. Some allocators will keep the memory around from the first iteration around for re-use, ours (jemallocator) doesn't do this above a certain size with certain parameters and immediately releases it to the OS in a way that causes a lot of page faults if you then allocate it again.

This explanation makes sense. Thanks!

> @liufeimath Another I noticed from your reproduction steps, is that you wrote `ipython` as a command directly. If you use `ipython` then it will take your global `ipython`, not the one from your `venv`. If you have installed polars 1.5.0 in your `venv` you need to use `python -m IPython` to start it.

My test environment are pretty simple: I only use one global python environment and there's no venv involved. So it's OK. To make sure, I also verified by `pl.__version__` in the ipython shell that it is using `1.5.0`.

**Comment by liufeimath** [comment] 2024-08-15 09:07
I also verified with the original "one iteration" [test code](https://github.com/pola-rs/polars/issues/17414#issue-2389728523) (with a larger size of n=1e8, to make the "one shot" test more reproducible), where numpy, polars and pandas all show comparable results (about 400ms on my poor old macbook pro for all three package). So yes I think the issue is gone.

**Comment by orlp** [comment] 2024-08-15 09:13
@liufeimath The one thing I can't explain is why for `n = 10**8` in the iterated benchmark you see a difference between specifying `_RJEM_MALLOC_CONF="background_thread:true,dirty_decay_ms:500,muzzy_decay_ms:-1"` and not specifying it with Polars 1.5.0, because that should already be specified by default, and `stats_print` confirms this is the case.

**Comment by cmdlineluser** [comment] 2024-08-15 09:20
I know it says `background_thread` is unsupported on macOS, but it does seem to be what is affecting the timing difference.

I was testing on an older intel mac that cannot be updated and it displayed similar behaviour:

```shell
$ _RJEM_MALLOC_CONF="background_thread:false" python3 17414.py 1e7
pl.__version__='1.5.0'
numpy 4.370252866996452
polars 7.3450093229766935
polars (lazy query) 2.363016178016551
pandas 3.0199743050616235
```

```shell
$ _RJEM_MALLOC_CONF="background_thread:true" python3 17414.py 1e7
<jemalloc>: option background_thread currently supports pthread only
pl.__version__='1.5.0'
numpy 4.356235126033425
polars 2.6600036510499194
polars (lazy query) 1.4290305509930477
pandas 2.964707631035708
```

**Comment by orlp** [comment] 2024-08-15 09:26
@cmdlineluser That is very strange, but I feel like that should be fixed upstream in either `jemallocator` or `jemalloc`.
