### ISSUE TITLE
Expr `.implode().get().over()`   has strange results.

### ISSUE THREAD

**Issue by PierXuY** [pola-rs/polars#18228] opened 2024-08-16 07:27 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    'type': ['water','fire','water']
})
out1 = df.select(
    pl.col('type').implode().get(0).over("type")
)
print(out1)
# shape: (3, 1)
# ┌───────┐
# │ type  │
# │ ---   │
# │ str   │
# ╞═══════╡
# │ water │
# │ fire  │
# │ water │
# └───────┘

## -------------------
df = pl.DataFrame({
    'type': ['water','water','fire']
})
out2 = df.select(
    pl.col('type').implode().get(0).over("type")
)
print(out2)
# Just adjusted the order of values
# OutOfBoundsError: gather indices are out of bounds

##-------------------
df = pl.DataFrame({
    'type': ['a','a','b']
})
out3 = df.select(
    pl.col('type').implode().get(0).over("type")
)
print(out3)
# Just modified the content
# OutOfBoundsError: gather indices are out of bounds
```

### Issue description

I just changed the content or order of the values ​​and the error occurred.

By the way, is the result of out1 reasonable? How to interpret this result?
out1:
```
shape: (3, 1)
┌───────┐
│ type  │
│ ---   │
│ str   │
╞═══════╡
│ water │
│ fire  │
│ water │
└───────┘
```
(The above questions are all based on the research and study of polars Expr, not out of actual needs.  Hope polars can be more perfect.)

### Expected behavior

Fix the bug and expect an explanation of the above results.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  1.1.0
cloudpickle:          3.0.0
connectorx:           0.3.3
deltalake:            0.19.0
fastexcel:            0.11.5
fsspec:               2024.6.1
gevent:               24.2.1
great_tables:         0.10.0
hvplot:               0.10.0
matplotlib:           3.9.2
nest_asyncio:         1.6.0
numpy:                2.0.1
openpyxl:             3.1.5
pandas:               2.2.2
pyarrow:              17.0.0
pydantic:             2.8.2
pyiceberg:            0.7.0
sqlalchemy:           2.0.32
torch:                <not installed>
xlsx2csv:             0.8.3
xlsxwriter:           3.2.0
```

</details>

**Comment by cmdlineluser** [comment] 2024-08-16 09:03
I'm guessing it is supposed to raise an InvalidOperationError?

Everything else I've tried raises:

```python
df.select(pl.col('type').implode().first().over("type"))
# InvalidOperationError: 'implode' followed by an aggregation is not allowed
```

```python
df.select(pl.col('type').implode().slice(0, 1).over("type"))
# InvalidOperationError: 'implode' followed by a slice during aggregation is not allowed
```

**Comment by PierXuY** [comment] 2024-08-16 09:11
If the `.implode.method.over` operation is not allowed #18225, an InvalidOperationError should indeed be raised.
Until then, I thought this was a bug since earlier versions allowed similar operations.

I don't know the underlying reason why this operation is not allowed, but if it is allowed, the expression will be more flexible to write.

**Comment by ritchie46** [comment] 2024-08-16 09:15
I will close this as duplicate of https://github.com/pola-rs/polars/issues/18225

**Closed by ritchie46** 2024-08-16 09:15 UTC
Labels: bug, python, needs triage
