### ISSUE TITLE
Unable to acquire lock in mp when using try_parse_dates in read_csv

### ISSUE THREAD

**Issue by misantroop** [pola-rs/polars#7817] opened 2023-03-27 18:37 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I've spent a good few days isolating this. Seems when using try_parse_dates in read_csv and using multiprocessing.Pool, mp cannot acquire lock. When using pd.read_csv in pl_runner, it works without fault.

### Reproducible example

```python
import polars as pl
import multiprocessing as mp

pl.read_csv(
        source=f"https://people.sc.fsu.edu/~jburkardt/data/csv/cities.csv",
        try_parse_dates=True,
        skip_rows=0,
        sep=',',
)

def pl_runner(item):
    return pl.read_csv(
        source=f"https://people.sc.fsu.edu/~jburkardt/data/csv/cities.csv",
        try_parse_dates=True,
        skip_rows=0,
        sep=',',
    )

with mp.Pool() as pool:
    for df in pool.imap_unordered(pl_runner, [1]):
        print(df)
```

### Expected behavior

CSV loaded.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.16
Index type: UInt32
Platform: Linux-5.15.94-1-MANJARO-x86_64-with-glibc2.37
Python: 3.10.6 (main, Oct 18 2022, 08:46:38) [GCC 12.1.1 20220730]
---Optional dependencies---
numpy: 1.24.2
pandas: 2.0.0rc1
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by zundertj** [comment] 2023-03-27 19:49
See [https://pola-rs.github.io/polars-book/user-guide/howcani/multiprocessing.html](https://pola-rs.github.io/polars-book/user-guide/howcani/multiprocessing.html) and in particular the last paragraph.

**Comment by ritchie46** [comment] 2023-03-28 06:27
I will close this as this is not a bug on our side

**Closed by ritchie46** 2023-03-28 06:27 UTC
Labels: bug, python
