### ISSUE TITLE
Why jupyterlab polars death, not any action?

### ISSUE THREAD

**Issue by cfkstat** [pola-rs/polars#6930] opened 2023-02-16 13:15 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Why jupyterlab polars death, not any action?

### Reproducible example

```python
Why jupyterlab polars death, not any action?
```

### Expected behavior

Why jupyterlab polars death, not any action?

### Installed versions

Why jupyterlab polars death, not any action?

**Comment by ritchie46** [comment] 2023-02-16 13:22
Can you fill in the form?

**Comment by cfkstat** [comment] 2023-02-16 14:17
not any error output，

**Comment by mcrumiller** [comment] 2023-02-16 16:05
@cfkstat you have to provide more information:

* "death" doesn't make sense, we're talking about computers. What is dying?
* What is "jupyterlab polars"?
* What "action" are you referring to?
* Why are your Issue description, Reproducible example, Expected behavior, and Installed versions all the same badly-formed sentence? Did you just copy and paste the same sentence?

If you want the people here to make the effort to help you, please make an effort when asking for help.

**Comment by cfkstat** [comment] 2023-02-17 06:38
When I was running more than 50gb of memory, one cell would run for a very long time, but the background processes showed that the CPU was not running, and when I tried to stop the cell, jupyterlab couldn't stop either. The company's internal network, information can not attempt to output.

**Comment by cfkstat** [comment] 2023-02-17 06:44
When I was running more than 50gb of memory, one cell would run for a very long time, but the background processes showed that the CPU was not running, and when I tried to stop the cell, jupyterlab couldn't stop either. The company's internal network, information can not attempt to output.

**Comment by ritchie46** [comment] 2023-02-17 07:59
You must do some effort to create an example we can reproduce. If you cannot provide one, we cannot help you.

**Comment by 2-5** [comment] 2023-02-17 13:04
I have encountered something similar to what OP is reporting: basically, some Polars actions are not Ctrl+C interruptible. Jupyter notebooks send a Ctrl+C signal to the kernel to interrupt it.

For example, `df.write_parquet()` doesn't process Ctrl+C until it's done. Repro: call `df.write_parquet(compression="zstd", compression_level=22)` with a large dataframe from a notebook and press the notebook interrupt button. It will not work until the file is completely written. This is arguably a `pyarrow` problem, not sure if Ctrl+C is ignored by regular Polars ops (joins, ...)

**Comment by ritchie46** [comment] 2023-02-17 13:10
See #https://github.com/pola-rs/polars/issues/2687 for discussion on keyboard interupts.

**Comment by zundertj** [comment] 2023-02-18 10:44
To OP, when you report problems, it is really important to give sufficient information, so anyone willing to help, and thus invest their time into the problem you are running into, does not have to second guess what the issue is, but focus on the problem at hand. Many people here are willing to help (see the responses above), but you should also be willing to help them. To help you to in achieving that, we have set up the forms so you know what details are needed. 

Copy-pasting the same unhelpful description in all boxes, and posting multiple unhelpful responses to questions for more information is a clear sign you are not willing to help others to help you. That is ok, totally fine, but please do not create an issue in that case, as it will only cause lost time for everyone involved. Thus I am closing this issue. You are always welcome to create a new issue when you are willing to help.

**Closed by zundertj** 2023-02-18 10:44 UTC
Labels: bug, python
