### ISSUE TITLE
Number Handling

### ISSUE THREAD

**Issue by hkpeaks** [pola-rs/polars#8693] opened 2023-05-05 15:56 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Data 
Text,Base Amount
T(2834.59121),(2834.59121)
T232a23.77211,23a223.77211
T9597.8,9597.8
T4276,4276
T19369.72212,19369.72212
T0,0
T-1,-1
T-1.21,-1.21
T-1021.221,-1021.221
T(1021.221),(1021.221)

Result

Text,Base Amount(Sum)
T0,
T-1,
T-1021.221,
T-1.21,
T9597.8,
T(2834.59121),
T19369.72212,
T4276,
T232a23.77211,
T(1021.221),

### Reproducible example

```python
import polars as pl
import time
import pathlib

q = (
     pl.scan_csv("Floating.csv")      
     .groupby(by=["Text"])
    .agg([           
        pl.sum('Base Amount').alias('Base Amount(Sum)'),        
    ])) 

a = q.collect()
path: pathlib.Path = "Output/Polars-GroupBy.csv"
a.write_csv(path)
```

### Expected behavior

Expected Results

TEXT,Sum(Base Amount)
T(2834.59121),-2834.5912100000005
T232a23.77211,0
T9597.8,9597.8
T4276,4276
T19369.72212,19369.722120000002
T0,0
T-1,-1
T-1.21,-1.21
T-1021.221,-1021.221
T(1021.221),-1021.221

### Installed versions

<details>

```
polars-0.17.11.dist-info
```

</details>

**Comment by cmdlineluser** [comment] 2023-05-05 16:47
You would have to strip out the `()` and cast the column first, no?
```
import polars as pl

csv = b"""
Text,Base Amount
T(2834.59121),(2834.59121)
T232a23.77211,23a223.77211
T9597.8,9597.8
T4276,4276
T19369.72212,19369.72212
T0,0
T-1,-1
T-1.21,-1.21
T-1021.221,-1021.221
T(1021.221),(1021.221)
"""

df = pl.read_csv(csv.strip())

# shape: (10, 2)
# ┌───────────────┬──────────────┐
# │ Text          ┆ Base Amount  │
# │ ---           ┆ ---          │
# │ str           ┆ str          │
# ╞═══════════════╪══════════════╡
# │ T(2834.59121) ┆ (2834.59121) │
# │ T232a23.77211 ┆ 23a223.77211 │
# │ T9597.8       ┆ 9597.8       │
# │ T4276         ┆ 4276         │
# │ …             ┆ …            │
# │ T-1           ┆ -1           │
# │ T-1.21        ┆ -1.21        │
# │ T-1021.221    ┆ -1021.221    │
# │ T(1021.221)   ┆ (1021.221)   │
# └───────────────┴──────────────┘
```
```
df.with_columns(
   pl.col("Base Amount").str.strip("()").cast(pl.Float64, strict=False)
)

# shape: (10, 2)
# ┌───────────────┬─────────────┐
# │ Text          ┆ Base Amount │
# │ ---           ┆ ---         │
# │ str           ┆ f64         │
# ╞═══════════════╪═════════════╡
# │ T(2834.59121) ┆ 2834.59121  │
# │ T232a23.77211 ┆ null        │
# │ T9597.8       ┆ 9597.8      │
# │ T4276         ┆ 4276.0      │
# │ …             ┆ …           │
# │ T-1           ┆ -1.0        │
# │ T-1.21        ┆ -1.21       │
# │ T-1021.221    ┆ -1021.221   │
# │ T(1021.221)   ┆ 1021.221    │
# └───────────────┴─────────────┘
```

**Comment by hkpeaks** [comment] 2023-05-06 00:08
Since my code can parse the dataset directly from https://github.com/hkpeaks/peaks-framework/tree/main/CodeSample, I was not aware that I should do cleaning before running groupby. I prepared this code to cover (123,456.789). This number pattern occurs very frequently in accounting.

**Comment by ritchie46** [comment] 2023-05-06 06:21
This is not a bug. Polars doesn't make those assumptions for you. You indeed need to clean your data. Our csv reader doesn't include business logic.

**Comment by hkpeaks** [comment] 2023-05-07 02:54
If the data includes negative values represented by (), it will affect your performance measure as an extra data cleansing step is required. Additionally, if a test requires the output number of records for the filter function, Polars requires a separate defined count function. Please note that this significantly increases the time required. This is why I have not yet published a detail benchmark of filter function for Polars and Peaks after JoinTable. If you solve this issue, please let me know so I can publish the benchmark with comparable performance.

After implementing a direct method to convert bytearray to float64 in my software, I was able to increase processing speed and clean numerical data at the same time. I used Bing chat to convert it from Golang to 19 programming languages including Rust. Source code: https://github.com/hkpeaks/peaks-framework/tree/main/ByteArray2Float64

**Comment by hkpeaks** [comment] 2023-05-07 04:25
if in the middle of a numerical column, having only few number which is floating point, the processing resulting

D:\Benchmark>python groupby.py
Traceback (most recent call last):
  File "D:\Benchmark\groupby.py", line 16, in <module>
    a = q.collect()
        ^^^^^^^^^^^
  File "C:\Users\85292\AppData\Local\Programs\Python\Python311\Lib\site-packages\polars\lazyframe\frame.py", line 1604, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
exceptions.ComputeError: Could not parse `799.123` as dtype `i64` at column 'Quantity' (column number 8).
The current offset in the file is 36081032 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `799.123` to the `null_values` list.

Seem need more configuration. So now I know that why your GroupBy is faster than my expectation. 
I will follow this tradition in my app, but will maintain default type float64, user can boost performance if they override default data type for particular numerical column.

**Comment by hkpeaks** [comment] 2023-05-08 01:18
I have done for this enhancement for my app. Still slower than your GroupBy. And I have tested for 4 jobs run concurrently using your GroupBy, it is surprising the performance is out of my expectation. So Rust programming lanauge draw my attention in managing concurrent jobs.

**Comment by zundertj** [comment] 2023-06-04 18:16
As said, this is outside the scope of the project. Closing.

**Closed by zundertj** 2023-06-04 18:16 UTC
Labels: wontfix, python
