### ISSUE TITLE
ComputeError: Syntax at character 0

### ISSUE THREAD

**Issue by tooptoop4** [pola-rs/polars#17985] opened 2024-08-01 07:28 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.read_json(BytesIO(obj['Body'].read()))

```

### Log output

```shell
/opt/conda/lib/python3.9/site-packages/polars/io/json/read.py in read_json(source, schema, schema_overrides, infer_schema_length)
     94         source = normalize_filepath(source)
     95 
---> 96     pydf = PyDataFrame.read_json(
     97         source,
     98         infer_schema_length=infer_schema_length,

ComputeError: Syntax at character 0
```

### Issue description

my json file contains a SOH control character in it

### Expected behavior

json is read

### Installed versions

1.3.0

**Comment by ritchie46** [comment] 2024-08-01 08:22
Can you make a full reproducable example?  We miss the json data.

**Comment by deanm0000** [comment] 2024-08-01 18:28
They mention having an SOH control character in it which, according to [this](https://www.eso.org/~ndelmott/ascii.html) is `chr(1)` so my first guess is they have something like:

```
some_dict={'a':[1]}

def mystery_json_maker(some_dict):
    valid_json=json.dumps(some_dict)
    invalid_char_prepend=chr(1) + valid_json
    return BytesIO(bytes(invalid_char_prepend, 'ascii'))
```

This isn't exactly right because when I put that output into pl.read_json I get `ComputeError: InternalError(TapeError) at character 0 ('')`

If I do

```
for i in range(128):
    def mystery_json_maker(some_dict):
        valid_json=json.dumps(some_dict)
        invalid_char_prepend=chr(i) + valid_json
        return BytesIO(bytes(invalid_char_prepend, 'ascii'))
    try:
        pl.read_json(mystery_json_maker(some_dict))
    except pl.exceptions.ComputeError as err:
        if "Syntax at character" in f"{err}":
            print(chr(i))
```

then it turns out the only 2 characters that bring up Syntax at character are `"` or `[`.

OP I'd say this is not a bug and you just have invalid json.

Try to do

```
df = pl.read_json(BytesIO(obj['Body'].read()[1:]))
```

or I'm guessing your source has an erroneous double quote at the end too so if that doesn't work then

```
df = pl.read_json(BytesIO(obj['Body'].read()[1:-1]))
```

I'm going to close this but if I'm mistaken and you have a repro it can always be reopened.

**Closed by deanm0000** 2024-08-01 18:28 UTC
Labels: bug, python, needs repro

**Comment by tooptoop4** [comment] 2024-08-01 18:47
{"thing":"ab**SOH**c"}   actual SOH character instead of string SOH

**Comment by wence-** [comment] 2024-08-02 09:41
I presume you have json that is: `{"key": "value\x01with control character"}`. This is invalid json, according to the spec. See https://ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf (section 9, page 4). Quoting (emphasis mine):

> A string is a sequence of Unicode code points wrapped with quotation marks (U+0022). All code points may be placed within the quotation marks **except for the code points that must be escaped**: quotation mark (U+0022), reverse solidus (U+005C), and the **control characters U+0000 to U+001F**.

`\x01` (or `U+0001` if you will) is a control character, so if it is placed as is in a literal string, then your string is not valid json. If you want to embed such a character, you need to encode it as `\u0001`.

```
import polars as pl
import io

bad = io.StringIO('{"key": "value \x01 with control"}')

pl.read_json(bad) # => errors

good = io.StringIO('{"key": "value \\u0001 with control"}')

pl.read_json(good) # parses correctly
```
