### ISSUE TITLE
Using `over()` with `mode()` fails.

### ISSUE THREAD

**Issue by abdullah-ahmad-dx** [pola-rs/polars#19764] opened 2024-11-13 15:24 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
    let df = DataFrame::new(vec![
        Column::new(
            "uniqueid".into(),
            vec![
                "X1", "X2", "X3", "Y1", "Y2", "Y3", "X1", "X2", "X3", "Y1", "Y2", "Y3", "X1", "X2",
                "X3", "Y1", "Y2", "Y3",
            ],
        ),
        Column::new(
            "thresholds".into(),
            vec![
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0,
                2.0, 2.0,
            ],
        ),
        Column::new(
            "groupid".into(),
            vec![
                "X", "X", "X", "Y", "Y", "Y", "X", "X", "X", "Y", "Y", "Y", "X", "X", "X", "Y",
                "Y", "Y",
            ],
        ),
        Column::new(
            "data1".into(),
            vec![1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0],
        ),
        Column::new(
            "data2".into(),
            vec![1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0],
        ),
    ])
    .unwrap();

    let lf = df.drop("uniqueid").unwrap().lazy();

    println!("{}", df);

    let df_mode = match lf
        .with_column(
            col("^data[0-9]*$")
                .mode()
                .over([col("thresholds"), col("groupid")]),
        )
        .collect() {
        Ok(df) => df,
        Err(e) => panic!("{}", e),
    };

```

I've left the `uniqueid` column in to demonstrate the type of aggregation I'm attempting to perform.

### Log output

```shell
the length of the window expression did not match that of the group

Error originated in expression: 'col("data1").mode().over([col("thresholds"), col("groupid")])'
```

### Issue description

I would expect the data columns to be replaced with the modes over each set of group IDs in each set of thresholds.
The reason I think this is an issue is that operation works elsewhere (e.g. with `mean()`).
I don't know why this wouldn't work with `mode()`.

### Expected behavior

This code works. Maybe the above error is expected behaviour and I just don't understand why that's the case.

```rust
    let df = DataFrame::new(vec![
        Column::new(
            "uniqueid".into(),
            vec![
                "X1", "X2", "X3", "Y1", "Y2", "Y3", "X1", "X2", "X3", "Y1", "Y2", "Y3", "X1", "X2",
                "X3", "Y1", "Y2", "Y3",
            ],
        ),
        Column::new(
            "thresholds".into(),
            vec![
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0,
                2.0, 2.0,
            ],
        ),
        Column::new(
            "groupid".into(),
            vec![
                "X", "X", "X", "Y", "Y", "Y", "X", "X", "X", "Y", "Y", "Y", "X", "X", "X", "Y",
                "Y", "Y",
            ],
        ),
        Column::new(
            "data1".into(),
            vec![1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0],
        ),
        Column::new(
            "data2".into(),
            vec![1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0],
        ),
    ])
    .unwrap();

    let lf = df.drop("uniqueid").unwrap().lazy();

    let df_mode_working = match lf
        .with_column(
            col("^data[0-9]*$")
                .mode()
                .over_with_options([col("thresholds"), col("groupid")], None, WindowMapping::Join),
        )
        .explode([col("^data[0-9]*$")])
        .collect() {
        Ok(df) => df,
        Err(e) => panic!("{}", e),
    };
```

with the output:

| thresholds | groupid | data1 | data2 |
|------------|---------|-------|-------|
| 0.0        | X       | 1     | 1     |
| 0.0        | Y       | 0     | 0     |
| 2.0        | X       | 1     | 1     |
| 1.0        | X       | 1     | 0     |
| 1.0        | Y       | 0     | 0     |
| 2.0        | Y       | 0     | 0     |

I understand that the default behaviour for `WindowMapping` is `WindowMapping::GroupsToRows`. I'd like to avoid using `WindowMapping::Join` due to the operation being memory-intensive (as mentioned in the docs) and I'd want to scale this operation to much larger dataframes (on the order of 1E7 In height) while keeping it relatively performant. The crux of the issue is wondering why the default behaviour of `over()` doesn't work with `mode()`.

### Installed versions

<details>

`features = ["lazy", "mode", "regex"]`

</details>

**Comment by cmdlineluser** [comment] 2024-11-13 15:36
It's because `mode()` returns a list. 

There is an explanation here:

- https://github.com/pola-rs/polars/issues/19247#issuecomment-2416210920

`.mode().first().over()` can be used if you want a single value.

**Comment by abdullah-ahmad-dx** [comment] 2024-11-13 16:03
Apologies! I searched for a while for this issue and I couldn't find it. I suppose I was too focused on `mode()` and `over()` and not on using `over()` with operations that return lists. This solves my issue.

**Comment by orlp** [comment] 2024-11-14 08:51
Closing as duplicate of https://github.com/pola-rs/polars/issues/19247.

**Closed by orlp** 2024-11-14 08:51 UTC
Labels: bug, rust, needs triage
