### ISSUE TITLE
Bug / Misunderstanding about write_parquet and row_group_size

### ISSUE THREAD

**Issue by augcollet** [pola-rs/polars#12977] opened 2023-12-10 10:53 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Hello,

I'm facing an issue when I try to export "big" DataFrame (1 000 000 rows) to parquets. I'm not sure if it's a bug or if I misunderstand something, so I choosed to open an issue here instead of staskoverflow.

Here is a reproductible example : 

I just create a simple Polars DataFrame with size 1_000_000 x 10
![image](https://github.com/pola-rs/polars/assets/99130480/f79fa418-ab3a-479b-8e45-568d1de8bcfa)

I use write_parquet function with row_group_size=1000
![image](https://github.com/pola-rs/polars/assets/99130480/e3a929eb-d0c4-4f00-bd80-a9788b59e46b)

I expect to get ~1000 parquet files containing 1000 rows (1000*1000=1_000_000), but I get only one file : 
![image](https://github.com/pola-rs/polars/assets/99130480/361395ec-80ad-4c4d-a1ac-7bac2dfecd9e)

When I show nb_chunks after, I find the expected number of 1000 chunks : 
![image](https://github.com/pola-rs/polars/assets/99130480/8bb4753d-b15a-45c4-bf31-2f430510b919)
But it's not reflecting the number of parquet files.

### Issue description

More generally, it seems that regardless of the parameters, the export always results in a single parquet file.

### Expected behavior

What I expect (but maybe I misunderstand the behavior) : 

- Number of exported parquet files should be equal to nb_rows / row_group_size
- If I dont specify row_group_size, number of parquet files should be nb_rows / 512^2
- After writing parquets data, n_chunks() should be equal to the number of generated parquet files

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.18
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.9.2
gevent:               <not installed>
matplotlib:           3.8.0
numpy:                1.24.4
openpyxl:             3.1.2
pandas:               2.1.1
pyarrow:              13.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.22
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by MarcNuebel** [comment] 2023-12-10 12:25
This is intended behavior.

Row groups are just a logical partitioning of the data within a single file, as documented in the official documentation: https://parquet.apache.org/docs/concepts/

See DuckDBs documentation for a bit more information: https://duckdb.org/docs/data/parquet/tips.html

Similarly, n_chunks is just a logical partitioning of a single data structure in memory for Apache Arrow (Chunked Arrays): https://arrow.apache.org/docs/cpp/arrays.html.

**Comment by augcollet** [comment] 2023-12-10 12:44
Thank you for your quick answer and sorry for this misunderstanding. So the file itself benefits from the internal logical partitionning without having to effectively be divided into multiple files ?
I used to work with parquet files in Spark and I always get multiple parquets a after export, that's probably the origin of my confusion.

**Comment by MarcNuebel** [comment] 2023-12-10 13:21
Yes, exactly.
I do not know Spark but I can imagine it has to write to multiple files to parallelize over multiple machines while polars just runs on a single machine.

**Comment by augcollet** [comment] 2023-12-10 13:33
I think that even in single-node spark, each solicited core is writing its own file, so we always get multiple parquets except if we collect all data in same core before exporting.

In Polars, I'm not sure to understand in which case exacly an export will result in multiple parquet files (except the case of partition by column using pyarrow). Can anyone explain this to me?
Also, is there any benefit for having multiple parquet export files instead of an unique internally-partitionned parquet file ?

**Comment by augcollet** [comment] 2023-12-11 17:20
Thank you very much, this confirms what I started to understand from the first answers.

However, there remains one last question to fully complete my understanding (this will perhaps be useful to other people who have the same questions as me).

Concerning native multi-file export you say that Polars currently "lacks that direct functionality". Would implementing this feature represent a performance advantage? Or none? Or a non-significant improvement?

**Comment by ritchie46** [comment] 2023-12-12 06:35
I will close this as there is no bug here.

**Closed by ritchie46** 2023-12-12 06:35 UTC
Labels: bug, python
