### ISSUE TITLE
`pow`: return `Int64` for `Int64` ** `Int64`, and raise if exponent is negative integer?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#9051] opened 2023-05-26 10:28 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Currently, `pow` always returns `float` dtype

This came up here: https://github.com/data-apis/dataframe-api/issues/174

The Array API would return `int` for `int` to the power of `int`, and says that `int` to the power of something negative is implementation-dependent

One suggestion could be:
- `int_base_series.pow(int_exponent_series)` returns `int` dtype if `int_exponent_series` is all non-negative
- `int_base_series.pow(int_exponent_series)` raises if `int_exponent_series` contains negative numbers
- `float_base_series.pow(int_exponent_series)` returns `float` dtype
- `int_base_series.pow(float_exponent_series)` returns `float` dtype
- `float_base_series.pow(float_exponent_series)` returns `float` dtype

This is what pyarrow does:
```python

In [18]: pc.power(pa.array([1 ,2]), pa.array([1, 2]))
Out[18]:
<pyarrow.lib.Int64Array object at 0x7f75ea63d000>
[
  1,
  4
]

In [19]: pc.power(pa.array([1 ,2]), pa.array([-1, 2]))
---------------------------------------------------------------------------
ArrowInvalid: integers to negative integer powers are not allowed

In [20]: pc.power(pa.array([1 ,2]), pa.array([-1., 2.]))
Out[20]:
<pyarrow.lib.DoubleArray object at 0x7f75ea6e8460>
[
  1,
  4
]

In [21]: pc.power(pa.array([1. ,2.]), pa.array([-1, 2]))
Out[21]:
<pyarrow.lib.DoubleArray object at 0x7f75ea31f760>
[
  1,
  4
]

In [22]: pc.power(pa.array([1. ,2.]), pa.array([-1., 2.]))
Out[22]:
<pyarrow.lib.DoubleArray object at 0x7f75ea6ebf40>
[
  1,
  4
]
```

### Reproducible example

```python
In [13]: pl.Series([1,2,3]).pow(pl.Series([1,2,3]))
Out[13]:
shape: (3,)
Series: '' [f64]
[
        1.0
        4.0
        27.0
]
```

### Expected behavior

```python
shape: (3,)
Series: '' [i64]
[
        1
        4
        27
]
```
, like `pyarrow`

---

Note: this already was raised [here ](https://github.com/pola-rs/polars/issues/4796), but it looks like there wasn't much discussion, so I'm bringing it up again, hope it's OK

### Installed versions

<details>

```

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 2.0.1
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.6.1
pip              : 23.0.1
Cython           : None
pytest           : 7.3.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 12.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
None

```

</details>

**Comment by granthamtaylor** [comment] 2023-06-25 00:56
Not a contributor - just a bystander. 

I feel that this is expected behavior. Raising any integer to the power of an unsigned integer would result in the guarantee that the output should never be of a float - because that is not guaranteed here, it is implied that floats may be outputted instead.

I would say that raising floats to such large integer powers is much, much more common of any operation that raising 

It is odd to want to be able to raise some arbitrarily large integers to such large powers. Even 127^127, the largest possible combination of 8 bit signed integers, is not a meaningfully useful calculation.

It feels like this is expected behavior, it is such an impractical usage, and may be easily resolved by simply casting back into integers after the operation (or just using an unsigned integer as the power for better memory usage)

**Comment by orlp** [comment] 2023-08-03 11:50
I feel integer power should have a separate function, and that the default power function always returns a float. I think it's rather poor design to change the type of the output column based on the value of the exponent. It can lead to subtle breakage where suddenly a column becomes integer and later on floats are expected.

**Comment by MarcoGorelli** [comment] 2023-08-03 11:55
isn't this what already happens for, say, multiplication though?

e.g. multiplying an int column by an integer returns an integer, but multiplying an int column by a float returns a float

The return type would still be predictable, based on the rules defined above

**Comment by MarcoGorelli** [comment] 2023-08-10 09:04
Sorry, coming back to this, I'm not too keen on

>  if int_exponent_series is all non-negative

. Such a condition wouldn't be predictable for lazy execution, right?

How about:

- `uint_base_series.pow(uint_exponent_series)` returns `uint` dtype
- `int_base_series.pow(uint_exponent_series)` returns `int` dtype
- `int_base_series.pow(int_exponent_series)` returns `float` dtype
- `float_base_series.pow(int_exponent_series)` returns `float` dtype
- `int_base_series.pow(float_exponent_series)` returns `float` dtype
- `float_base_series.pow(float_exponent_series)` returns `float` dtype

**Comment by ritchie46** [comment] 2023-08-10 20:13
Yes output should be dependent on the schema, not on the data and same type arguments should produce the same type 👍

**Closed** 2023-12-02 07:23 UTC
Labels: bug, python, accepted
