### ISSUE TITLE
LazyFrame::sort is not stable even when multithreaded=false and maintain_order=true

### ISSUE THREAD

**Issue by mt-caret** [pola-rs/polars#9916] opened 2023-07-16 01:43 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
    #[test]
    fn lazy_sort_instability() {
        let dataset = CsvReader::from_path("../test/data/legislators-historical.csv")
            .unwrap()
            .finish()
            .unwrap();

        let mut prev: Option<DataFrame> = None;

        for _ in 0..1000 {
            let df = dataset
                .clone()
                .lazy()
                .groupby_stable(vec![col("state")])
                .agg(vec![
                    (col("party").eq(lit("Anti-Administration")))
                        .mean()
                        .alias("anti"),
                    (col("party").eq(lit("Pro-Administration")))
                        .mean()
                        .alias("pro"),
                ])
                .sort(
                    "pro",
                    SortOptions {
                        multithreaded: false,
                        maintain_order: true,
                        ..Default::default()
                    },
                )
                .limit(5)
                .collect()
                .unwrap();

            if let Some(prev) = prev {
                assert_eq!(df, prev);
            }
            prev = Some(df);
        }
    }
```

Resuts in:
```
---- tests::lazy_sort_instability stdout ----
thread 'tests::lazy_sort_instability' panicked at 'assertion failed: `(left == right)`
  left: `shape: (5, 3)
┌───────┬──────────┬──────┐
│ state ┆ anti     ┆ pro  │
│ ---   ┆ ---      ┆ ---  │
│ str   ┆ f64      ┆ f64  │
╞═══════╪══════════╪══════╡
│ OL    ┆ null     ┆ null │
│ PI    ┆ null     ┆ null │
│ DE    ┆ 0.010638 ┆ 0.0  │
│ MD    ┆ 0.0      ┆ 0.0  │
│ GA    ┆ 0.003195 ┆ 0.0  │
└───────┴──────────┴──────┘`,
 right: `shape: (5, 3)
┌───────┬──────────┬──────┐
│ state ┆ anti     ┆ pro  │
│ ---   ┆ ---      ┆ ---  │
│ str   ┆ f64      ┆ f64  │
╞═══════╪══════════╪══════╡
│ PI    ┆ null     ┆ null │
│ OL    ┆ null     ┆ null │
│ DE    ┆ 0.010638 ┆ 0.0  │
│ MD    ┆ 0.0      ┆ 0.0  │
│ GA    ┆ 0.003195 ┆ 0.0  │
└───────┴──────────┴──────┘`', src/lib.rs:245:17
```

### Issue description

Hello, when trying out some examples in the Polars User Guide: https://pola-rs.github.io/polars-book/user-guide/expressions/aggregation/#conditionals

I noticed that LazyFrame::sort seemed to be unstable even when maintain_order=true, which was surprising. Is this expected?

### Expected behavior

When passing maintain_order=true I expected a stable sort, even with respect to null values.

### Installed versions

<details>

```toml
features = [
    "approx_unique",
    "asof_join",
    "describe",
    "diagonal_concat",
    "dot_diagram",
    "dtype-date",
    "dtype-datetime",
    "dtype-i16",
    "dtype-i8",
    "dtype-u16",
    "dtype-u8",
    "horizontal_concat",
    "interpolate",
    "lazy",
    "list_eval",
    "parquet",
    "pivot",
    "random",
    "rank",
    "round_series",
    "semi_anti_join",
    "streaming",
    "timezones",
]
```

</details>

**Comment by avimallu** [comment] 2023-07-16 04:00
Did you also put `maintain_order=True` for the groupby operation? I see that the example in the user guide has two null values and two threes for the `pro` column.

**Comment by mt-caret** [comment] 2023-07-16 04:26
I'm not sure I understand; I'm calling `groupby_stable` instead of `groupby`. Is there an additional parameter I can tweak somewhere to specify order for the groupby?

**Comment by avimallu** [comment] 2023-07-16 04:27
Oh, my bad. I didn't see that.

**Comment by ritchie46** [comment] 2023-07-16 04:47
Yes we don't have a stable sort. You can add a row index to create a stable sort of you need it.

**Comment by stinodego** [comment] 2023-07-16 20:26
So this is not a bug. Ritchie has mentioned a workaround. I guess this could be seen as a feature request for a stable sort. Could you make a new feature request issue for that? I will close this one.

**Closed by stinodego** 2023-07-16 20:26 UTC
Labels: bug, rust
