### ISSUE TITLE
Error when passing directory path of hive-partitioned parquet dataset to `scan_parquet`

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#17362] opened 2024-07-02 14:40 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
tr = pl.scan_parquet(parq_path+"my_transaction")
tr.columns
```

### Log output

```shell
/tmp/1000780000/ipykernel_581/2428165798.py:1: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  tr.columns
Traceback (most recent call last):
  File "/tmp/1000780000/ipykernel_581/2428165798.py", line 1, in <module>
    tr.columns
  File "/opt/conda/envs/Python-3.9-Premium/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 454, in columns
    return self.collect_schema().names()
  File "/opt/conda/envs/Python-3.9-Premium/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 2146, in collect_schema
    return Schema(self._ldf.collect_schema())
polars.exceptions.ComputeError: parquet: File out of specification: The file must end with PAR1
```

### Issue description

Cannot read parquet columns.
If I add "/**/*.parquet" to the end of the file-path, then the columns are returned OK.

### Expected behavior

Not throw error, show list of coulmns

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0
Index type:           UInt32
Platform:             Linux-4.18.0-372.76.1.el8_6.x86_64-x86_64-with-glibc2.28
Python:               3.9.13 (main, Oct 13 2022, 21:15:33) 
[GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2022.02.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.5.5
numpy:                1.23.5
openpyxl:             3.0.9
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           1.4.27
torch:                1.10.2
xlsx2csv:             <not installed>
xlsxwriter:           3.2.0
```

</details>

**Comment by stinodego** [comment] 2024-07-02 15:23
Could you please add a reproducible example? We need to know what your file structure looks like.

**Comment by barak1412** [comment] 2024-07-02 18:23
@stinodego but `scan_parquet` never supported directory without glob pattern, am I wrong?

**Comment by stinodego** [comment] 2024-07-02 20:40
> @stinodego but `scan_parquet` never supported directory without glob pattern, am I wrong?

This is a new feature in Polars 1.0.0: https://github.com/pola-rs/polars/pull/17017

**Comment by ritchie46** [comment] 2024-07-03 07:32
Are there any non-parquet files in that directory?

**Comment by lmocsi** [comment] 2024-07-03 12:21
> Are there any non-parquet files in that directory?

Yes, there are *.crc files in every directory.

**Comment by jmakov** [comment] 2024-07-03 17:31
> Could you please add a reproducible example? We need to know what your file/folder structure looks like.

Same problem with polars upgrade. Dir struct is: `dataset/a/b/c/file.parquet`. The files are written with `.write_parquet(path_base, use_pyarrow=True, pyarrow_options=pyarrow_options)` where:
```python
partition_cols = ["a", "b", "c"]
    pyarrow_options = {"partition_cols": partition_cols,
                       "existing_data_behavior": "overwrite_or_ignore",
                       "basename_template": partition_name + "-{i}.parquet"}
```

**Comment by nameexhaustion** [comment] 2024-07-05 05:56
For directories that also contain non-parquet files, it is recommended use a glob pattern (e.g. `**/*.parquet`) to specify which files to scan. But I think we can improve the error message to explain that there were files with different file extensions.

@jmakov your issue is not related to this one, the default behavior hive partition parsing was updated and you need to pass `hive_partitioning=True` - see the section in the upgrade guide https://docs.pola.rs/releases/upgrade/1/#update-some-error-types-to-more-appropriate-variants

**Comment by nameexhaustion** [comment] 2024-07-05 06:04
Closing in favor of https://github.com/pola-rs/polars/issues/17436

**Comment by lmocsi** [comment] 2024-07-05 08:56
> For directories that also contain non-parquet files, it is recommended use a glob pattern (e.g. `**/*.parquet`) to specify which files to scan. But I think we can improve the error message to explain that there were files with different file extensions.

Would it be too much of a request to automatically go through the files in the folder structure and identify which ones are parquet files? Not by their extension, but by their header / magic bytes?

**Comment by ritchie46** [comment] 2024-07-05 09:27
This can be extremely expensive. We want to have the same behavior for cloud files and we certainly don't want to trigger a download of all magic bytes to resolve the hive partitions.

If you want a folder to be automatically seen as a partitioned dataset, it needs to adhere to some constraints.

**Comment by barak1412** [comment] 2024-07-05 09:50
@ritchie46 If I recalll correctly, spark generated an empty `_SUCCESS` file along the parquet files.
Could it be exception?

**Comment by ritchie46** [comment] 2024-07-05 13:05
Is there some documentation on that?

**Comment by barak1412** [comment] 2024-07-05 14:48
Here is an old similar issue regarding the generated `_SUCCESS` file - https://issues.apache.org/jira/browse/SPARK-13207
Here is an old Polars ticket that already explains the issue - https://github.com/pola-rs/polars/issues/14377

I coudn't find a formal statement in the Spark docs, but I found [this](https://tsaiprabhanj.medium.com/spark-success-file-1740b8a15692) medium post that explains the purpose of the `_SUCCESS` file.

**Comment by nameexhaustion** [comment] 2024-07-05 15:07
We can exclude empty files during path expansion, that sounds ok to me

**Closed** 2024-07-08 09:29 UTC
Labels: python, enhancement, A-io-partitioning
