### ISSUE TITLE
Exclusion of Null Values in Filtered Dataframe when using Literal Interpretation

### ISSUE THREAD

**Issue by ArjunHS** [pola-rs/polars#9329] opened 2023-06-10 18:31 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Issue Summary:
When applying a filter on a column in Polars, using the literal interpretation of the filter, null values in the column are currently being excluded from the filtered dataframe. This behavior was observed in version 0.18.0 and later releases.

Expected Behavior:
The expected behavior is that when applying a filter using the literal interpretation, the filter should include all values except for the specified value. This means that null values should not be excluded from the filtered dataframe.

Steps to Reproduce:

    Create a Polars DataFrame df with a column (column1) containing null values.
    Apply a filter on column1 using the literal interpretation, such as df = df.filter(pl.col(column1) != 'abc').

Actual Result:
After applying the filter, the resulting dataframe (df) does not include null values in column1. Only non-null values are present in the filtered dataframe.

Expected Result:
The expected result is that the filtered dataframe (df) should include both non-null values and null values in column1, as the literal interpretation of the filter implies that everything apart from the specified value should be included.

Additional Information:

    This issue has been observed in Polars version 0.18.0 and subsequent releases.
    The exclusion of null values in the filtered dataframe may lead to unexpected behavior and can cause data loss or incorrect analysis.

Proposed Solution:
To resolve this issue, the filter operation should be modified to include null values when using the literal interpretation. This would ensure consistency with the expected behavior and prevent unintended data exclusion.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({'a':[1,2,3,4,5, None],
                  'b':[6,7,8,9,10,11]})

filtered_df = df.filter(pl.col('a') != 1)


print(f"Before filter: {df}")
print(f"After filter: {filtered_df}")
```

### Expected behavior

In the given example:

The filtered dataframe excludes first row where column 'a'=1 which is expected behavior.
But it also excludes the last row where column 'a'= Null which is unexpected behavior.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.2
Index type:  UInt32
Platform:    Windows-10-10.0.19045-SP0
Python:      3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.23.5
pandas:      1.5.3
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2022.11.0
matplotlib:  3.7.0
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

```

</details>

**Comment by mcrumiller** [comment] 2023-06-10 19:13
This is a new common issue, so other polars members should keep an eye out for these.

@ArjunHS this is now expected behavior as per #9053. If you do `a == None` then `None` is returned, not `False`, as you can see from the following:

```
>>>pl.Series([None, 2, 3]) == pl.Series([1, 2, 3])
Series: '' [bool]
[
        null
        true
        true
]
```
Instead, you should use [`ne_missing`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/index.html), which returns False when a null is compared to a non-null:

```
>>>pl.Series([None, 2, 3]).ne_missing(pl.Series([9, 9, 9]))
Series: '' [bool]
[
        true
        true
        true
]
```

**Comment by ArjunHS** [comment] 2023-06-10 22:33
Thank you, @mcrumiller, for providing the explanation and pointing out the alternative **ne_missing** method.

While I understand the reasoning behind the change in filter behavior, my concern lies with the code readability and potential for unintentional data loss. The new behavior of excluding null values is implicit and not explicitly stated in the filter syntax.

In the line:
**filtered_df = df.filter((pl.col('a') != 1))**
the intention is to retrieve all values except for 1. However, it does not explicitly state "Do not exclude null values," leading to potential confusion and unintended data loss.

To ensure the inclusion of null values, we now need to modify the syntax as:
**filtered_df = df.filter((pl.col('a') != 1) | pl.col('a').is_null())**
While this solution works, it introduces additional complexity and affects the code readability.

Considering the potential impact on code maintainability and the risk of unintentional data loss, it would be beneficial to reconsider this change in behavior. Explicitly allowing or excluding null values within the filter syntax would improve clarity and help prevent unexpected results.

I would appreciate discussing this further and exploring possible alternatives that strike a balance between maintaining consistent behavior and ensuring code readability.

**Comment by avimallu** [comment] 2023-06-11 00:27
Let me try to contribute to the discussion.

`df.filter(pl.col('a') != 1)` does not mean **return all values except for 1**. In the simplest meaning, it says: **return all values that are not equal to 1**.

Consider `df.filter(pl.col('a') == 1)`. What do you want this to do? It can either:

1. Return the first and last row.
2. Return only the first row.

Obviously, `null` is not equal to `1`, so (1) cannot happen, and only (2) is sensible. But that means `~df.filter(pl.col('a') != 1)` **is not the same as** `df.filter(pl.col('a') == 1)`. I hope you can see why that is a problem.

> The new behavior of excluding null values is implicit

I would put forth that it is not. The `filter` function will return all rows that evaluate to `True`, and since any comparison will `null` propogates it, those rows will have `null` values. The earlier behavior was in fact, **implicitly including null values** (per my explanation above).

My key point is that the missing value may be 1, or it may not be. The point is that neither you, not the computer _knows_ that. Therefore, it cannot give a `True` or `False` for `null==1` or `null!=1`. That's why most other systems/languages behave the way Polars does now (see my examples in https://github.com/pola-rs/polars/issues/8182 for other languages). [Polars tries to stick to](https://github.com/pola-rs/polars/issues/8186#issuecomment-1509888316) (with even more discussion [here](https://github.com/pola-rs/polars/issues/5359)):

> Missing data is not a number and any operation on it remains missing.

It is possible to disagree with this, and create a case for the opposite. However, null value comparison behavior across languages has almost consistently agreed that they have to be propogated when compared, and now Polars too follows this behavior. However, unlike other languages, it also provides you `eq_missing` and `ne_missing` for when you want disagree with it :)

Hope all this helps. 

The current documentation does not reflect these two functions, but after https://github.com/pola-rs/polars/pull/9331 is merged, they will. For your reference, this is the code:

```py
def eq_missing(self, other: Any) -> Self:
    """
    Method equivalent of equality operator ``expr == other`` where `None` == None`.

    This differs from default ``eq`` where null values are propagated.

    Parameters
    ----------
    other
        A literal or expression value to compare with.

    """
    return self._from_pyexpr(self._pyexpr.eq_missing(self._to_expr(other)._pyexpr))
```

and

```py
def ne_missing(self, other: Any) -> Self:
    """
    Method equivalent of equality operator ``expr != other`` where `None` == None`.

    This differs from default ``ne`` where null values are propagated.

    Parameters
    ----------
    other
        A literal or expression value to compare with.

    """
    return self._from_pyexpr(self._pyexpr.neq_missing(self._to_expr(other)._pyexpr))
```

**Comment by ArjunHS** [comment] 2023-06-11 02:26
Hey @avimallu,

I completely agree with your points about excluding null values by default in comparison operations as it aligns well with the practices followed by other languages and libraries.

eq_missing and ne_missing will come in very handy going forward.
Appreciate your efforts in providing clarity on this matter.

**Closed** 2023-06-11 02:31 UTC
Labels: bug, python
