### ISSUE TITLE
Projection pushdown with hive partitions may not be respected

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#17104] opened 2024-06-21 06:48 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from pathlib import Path


root = Path(".env/data2")

dfs = [
    pl.DataFrame({"x": 1}),
    pl.DataFrame({"x": 2}),
]

paths = [
    root / "a=1/b=1/data.bin",
    root / "a=2/b=2/data.bin",
]

[
    [paths[i].parent.mkdir(exist_ok=True, parents=True), dfs[i].write_parquet(paths[i])]
    for i in range(len(dfs))
]

lf = pl.scan_parquet(root / "**/*.bin")
lf = lf.select("x", "a")

print(lf.collect())
```
Observe the `select` was not respected:
```python
shape: (2, 3)
┌─────┬─────┬─────┐
│ x   ┆ a   ┆ b   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 1   ┆ 1   │
│ 2   ┆ 2   ┆ 2   │
└─────┴─────┴─────┘
```

### Issue description

https://github.com/pola-rs/polars/pull/15573 removes the projection node after projection pushdown into the parquet reader, which reveals that the parquet reader was not applying the projection properly on the hive partition columns.

### Expected behavior

```python
shape: (2, 2)
┌─────┬─────┐
│ x   ┆ a   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 1   │
│ 2   ┆ 2   │
└─────┴─────┘
```

### Installed versions

main @ 8a6bf4bc58e7fed9b6728bad66e0590fccb11f0e

**Comment by deanm0000** [comment] 2024-06-21 14:43
duplicate of [this](https://github.com/pola-rs/polars/issues/15823) I put some notes in there that might be helpful.

**Comment by nameexhaustion** [comment] 2024-06-24 06:57
> duplicate of [this](https://github.com/pola-rs/polars/issues/15823) I put some notes in there that might be helpful.

Thanks for the triage!

**Closed** 2024-06-24 10:44 UTC
Labels: bug, python, regression, accepted, P-medium
