### ISSUE TITLE
Segmentation Fault creating large expression of when.then

### ISSUE THREAD

**Issue by slannez-fico** [pola-rs/polars#15211] opened 2024-03-21 14:31 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

frame = pl.DataFrame({"a": [1,2,3]})
e = pl.when(pl.col("a") < -1).then(-1)
N = 5000
for i in range(N):
  e = e.when(pl.col("a") < i).then(i)
print(frame.select(e))
```

### Log output

```shell
Python 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def test_large_when_then():
...     frame = pl.DataFrame({"a": [1,2,3]})
...     e = pl.when(pl.col("a") < -1).then(-1)
...     N = 5000
...     for i in range(N):
...         e = e.when(pl.col("a") < i).then(i)
...     print(frame.select(e))
... 
>>> import polars as pl
>>> test_large_when_then()
[1]    64931 segmentation fault  python3.10
```

### Issue description

We use when/then/otherwise to bucketize/partition a dataset. We are planning to support more than 5k classes, but it seems polars as a limitation right now, leading to segmentation fault when many when.then are combined.

### Expected behavior

We would expect polars to handle deep expressions of thousands of terms. If not, we would expect polars to provide meaningful error messages.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16
Index type:           UInt32
Platform:             macOS-14.4-arm64-arm-64bit
Python:               3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             1.10.5
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by slannez-fico** [comment] 2024-03-21 14:33
We also tried disabling optimization but it did not help:
```python
config = {"no_optimization": True, "_eager": True}
print(frame.select(e, **config))
```

**Comment by avimallu** [comment] 2024-03-21 15:50
There is no workaround to gracefully handling this - you're encountering a stackoverflow error. See: https://github.com/pola-rs/polars/issues/12268.

**Comment by mcrumiller** [comment] 2024-03-21 16:32
Is your data numeric, i.e. are you able to use [`cut`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.cut.html) instead a when/then chain? If so it will be much more performant.

**Comment by stinodego** [comment] 2024-03-21 22:03
Duplicate of #15211

**Closed by stinodego** 2024-03-21 22:03 UTC
Labels: bug, python, needs triage

**Comment by cmdlineluser** [comment] 2024-03-21 22:12
`pl.coalesce` and separate when/thens could also be a potential workaround depending on the exact requirements.

```python
def test_large_when_then():
     frame = pl.DataFrame({"a": [1,2,3]})
     N = 5000
     e = pl.coalesce(
         pl.when(pl.col("a") < i).then(i)
         for i in range(N)
     )
     print(frame.with_columns(choice = e))
 
import polars as pl
test_large_when_then()
```
```
shape: (3, 2)
┌─────┬────────┐
│ a   ┆ choice │
│ --- ┆ ---    │
│ i64 ┆ i32    │
╞═════╪════════╡
│ 1   ┆ 2      │
│ 2   ┆ 3      │
│ 3   ┆ 4      │
└─────┴────────┘
```
