### ISSUE TITLE
Conflict with s3fs 

### ISSUE THREAD

**Issue by clayms** [pola-rs/polars#5451] opened 2022-11-08 20:44 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Since version 0.14.25, perhaps earlier there is a conflict with the s3fs package.

Downgrading polars to 0.14.21 resolves the issue. 

`s3fs.__version__`:  `'2022.10.0'` 

See: https://github.com/fsspec/s3fs/issues/662

### Reproducible example

```python
import polars as pl
import s3fs

KEY = os.getenv('AWS_ACCESS_KEY_ID')
SECRET_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')

fs = s3fs.S3FileSystem(key=KEY, secret=SECRET_KEY)
fs.ls("s3://my-bucket")
```

### Expected behavior

list the files in S3.

With polars version =>0.14.25 installed, I get the following.

```python
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-4-9ec24d2dd6bc> in <cell line: 2>()
      1 fs = s3fs.S3FileSystem(key=KEY, secret=SECRET_KEY)
----> 2 fs.ls("s3://my-bucket")

/data/code-envs/python/polars/lib/python3.9/site-packages/fsspec/spec.py in ls(self, path, detail, **kwargs)
    338         dicts if detail is True.
    339         """
--> 340         raise NotImplementedError
    341 
    342     def _ls_from_cache(self, path):

NotImplementedError: 
```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.26
Index type: UInt32
Platform: Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.17
Python: 3.9.10 (main, Nov  6 2022, 22:00:36) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
---Optional dependencies---
pyarrow: <not installed>
pandas: 1.3.5
numpy: 1.23.4
fsspec: 2022.10.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment] 2022-11-09 10:19
@alexander-beedie I have got a hunch this is related to our import logic, could you take a look when you have time?

**Comment by ghuls** [comment] 2022-11-09 10:52
Does this work (moving polars as latest import)?
```python
import os
import s3fs
import polars

KEY = os.getenv('AWS_ACCESS_KEY_ID')
SECRET_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')

fs = s3fs.S3FileSystem(key=KEY, secret=SECRET_KEY)
fs.ls("s3://my-bucket")
```

**Comment by alexander-beedie** [comment] 2022-11-09 11:32
Hmm... this looks like an exotic interaction between the various moving parts; it can be fixed inside `s3fs` with a one-liner and no changes on our side (I just confirmed this, and will suggest it to them in case anyone else uses a `LazyLoader` with their project), but they shouldn't really _have_ to do that. I don't (yet) have a clear picture on how we can tweak the `LazyLoader`, as it appears to be tied-up in the subtleties of python's import machinery and dot-notation priority, but I'll try and come up with something! So, first I'll follow-up on the [s3fs](https://github.com/fsspec/s3fs/issues/662) issue and suggest the guard/fix that they can apply, and then I'll see what we can do locally.

**Comment by alexander-beedie** [comment] 2022-11-09 12:17
Ok, have made a suggestion on their side so they can handle anything similar, and will now dig-in further on ours; it doesn't appear to be a straightforward error (like the earlier lazy import issues which were oversights/bugs), so it might take a little more python-fu with the import machinery to address...

**Comment by alexander-beedie** [comment] 2022-11-09 12:41
@clayms: FYI, the following import order will work around the issue for now - the key is to explicitly import `fsspec` before polars:

```python
import fsspec  # << the key workaround 
import s3fs
import polars
```

The gremlin occurs as `fsspec` is lazy-loaded and `s3fs` imports directly from a submodule of `fsspec` _without_ importing the root - the submodules do actually load fine, but as you are experiencing there are apparently some unexpected side-effects...

**Comment by alexander-beedie** [comment] 2022-11-09 16:21
@ritchie46: Have reworked lazy loading again, with an even cleaner solution that is much less reliant on the (frankly baroque) machinery of `importlib`; have managed to avoid `sys.globals` completely, whether the underlying module exists or not. 

Am about to go back to re-validate against all previous issues to see if this is -finally- the _"one ring to rule them all, and in the darkness import them"_, and will submit a PR shortly if so.

**Comment by ritchie46** [comment] 2022-11-09 16:23
> @ritchie46: Have reworked lazy loading again, with an even cleaner solution that is much less reliant on the (frankly baroque) machinery of `importlib`; have managed to avoid `sys.globals` completely, whether the underlying module exists or not.
> 
> Am about to go back to re-validate against all previous issues to see if this is -finally- the _"one ring to rule them all, and in the darkness import them"_, and will submit a PR shortly if so.

Sounds great! I am curious what you came up with.

**Closed** 2022-11-10 07:35 UTC
Labels: bug, python
