### ISSUE TITLE
Does `map_batches` not map over groups with `over`?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#12941] opened 2023-12-07 15:34 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({'a': [1,1, 2], 'b': [4,5,6]})
df.with_columns(pl.col('b').map_batches(lambda x: x.shift()).over('a'))
```

### Issue description

If I run the above, I get
```python
In [11]: df = pl.DataFrame({'a': [1,1, 2], 'b': [4,5,6]})

In [12]: df.with_columns(pl.col('b').map_batches(lambda x: x.shift()).over('a'))
Out[12]:
shape: (3, 2)
┌─────┬──────┐
│ a   ┆ b    │
│ --- ┆ ---  │
│ i64 ┆ i64  │
╞═════╪══════╡
│ 1   ┆ null │
│ 1   ┆ 4    │
│ 2   ┆ 5    │
└─────┴──────┘
```

### Expected behavior

Is this right? I think I would have expected the same output as
```python
In [13]: df.with_columns(pl.col('b').shift().over('a'))
Out[13]:
shape: (3, 2)
┌─────┬──────┐
│ a   ┆ b    │
│ --- ┆ ---  │
│ i64 ┆ i64  │
╞═════╪══════╡
│ 1   ┆ null │
│ 1   ┆ 4    │
│ 2   ┆ null │
└─────┴──────┘
```

### Installed versions

<details>

```
In [14]: pl.show_versions()
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            0.9.0
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           3.7.1
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.3
pyarrow:              12.0.1
pydantic:             2.0.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.20
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

**Comment by MarcoGorelli** [comment] 2023-12-07 15:53
The docs do mention this (thanks @cmdlineluser , sorry for having missed this!), but it doesn't really "jump out" at you - should this even raise if it's not supported? It's easy to not notice it

https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.map_batches.html#polars.Expr.map_batches

**Comment by cmdlineluser** [comment] 2023-12-07 16:35
(I recall reading previously that it was supported for performance reasons for certain operations?)

I find the new names somewhat confusing as I also think of a "group" as a "batch".

As I understand it, `.apply` was renamed to `.map_elements` because its behaviour changes depending on the context.

Could aliases exist instead .e.g. `.map_rows` and `.map_groups` and just disallow `.map_rows` in a group context even though they are the same underlying function?

Is there an actual definition of what a `batch` is? (I always thought `.map` operated on the whole series/column?)

From https://github.com/pola-rs/polars/issues/10744#issuecomment-1694566055

> can be any batch polars decides to give the function

**Comment by avimallu** [comment] 2023-12-07 18:08
It looks like in the streaming case, `map_batches` doesn't give the whole column (from the same thread):

> This happens for instance in the streaming engine.

**Comment by deanm0000** [comment] 2023-12-07 22:59
It seems like `map_elements` turns into what `map_batches` should be when used with `over`

Suppose I have
```
def psum(x):
    print(x)
    return sum(x)
```

then I do:
```
df.select(pl.col('b').map_batches(psum))
shape: (3,)
Series: 'b' [i64]
[
	4
	5
	6
]
shape: (1, 1)
┌─────┐
│ b   │
│ --- │
│ i64 │
╞═════╡
│ 15  │
└─────┘
```

but:
```
df.select(pl.col('b').map_elements(psum))
4
ComputeError: TypeError: 'int' object is not iterable
```

So we see that `map_elements` hands just the 4 to our `psum` function and `sum` raises because it's a scalar.

Then we do

```
df.select(pl.col('b').map_batches(psum).over('a'))
shape: (3,)
Series: 'b' [i64]
[
	4
	5
	6
]
InvalidOperationError: output length of `map` (3) must be equal to the input length (1)
```

Using `over` doesn't break it up into groups at all but look what does

```
df.select(pl.col('b').map_elements(psum).over('a'))
shape: (2,)
Series: '' [i64]
[
	4
	5
]
shape: (1,)
Series: '' [i64]
[
	6
]

shape: (3, 1)
┌─────┐
│ b   │
│ --- │
│ i64 │
╞═════╡
│ 9   │
│ 9   │
│ 6   │
└─────┘
```

**Comment by ritchie46** [comment] 2023-12-13 07:54
I will close this one. As this works as expected.

**Closed by ritchie46** 2023-12-13 07:54 UTC
Labels: bug, python

**Comment by deanm0000** [comment] 2023-12-14 19:00
@ritchie46 Could you reconsider that it is working as expected? 

It really seems that the behavior of `map_batches` when it's in a window is silently wrong and that the behavior of `map_elements` should be substituted used for when `map_batches` is in a window or agg context.

Using just a bland `np.cumsum` for illustration (of course in real life use the polars `cum_sum`

Without an `over` this works as expected:
```
(df.with_columns(
    npcumsum = pl.col('b').map_batches(lambda x: (
        pl.Series(np.cumsum(x.to_numpy()))
        )),
    plcumsum = pl.col('b').cum_sum()
    ))
shape: (3, 4)
┌─────┬─────┬──────────┬──────────┐
│ a   ┆ b   ┆ npcumsum ┆ plcumsum │
│ --- ┆ --- ┆ ---      ┆ ---      │
│ i64 ┆ i64 ┆ i64      ┆ i64      │
╞═════╪═════╪══════════╪══════════╡
│ 1   ┆ 4   ┆ 4        ┆ 4        │
│ 1   ┆ 5   ┆ 9        ┆ 9        │
│ 2   ┆ 6   ┆ 15       ┆ 15       │
└─────┴─────┴──────────┴──────────┘
```

Now with `over('a')`

```
(df.with_columns(
    npcumsum = pl.col('b').map_batches(lambda x: (
        pl.Series(np.cumsum(x.to_numpy()))
        )).over('a'),
    plcumsum = pl.col('b').cum_sum().over('a')
    ))
shape: (3, 4)
┌─────┬─────┬──────────┬──────────┐
│ a   ┆ b   ┆ npcumsum ┆ plcumsum │
│ --- ┆ --- ┆ ---      ┆ ---      │
│ i64 ┆ i64 ┆ i64      ┆ i64      │
╞═════╪═════╪══════════╪══════════╡
│ 1   ┆ 4   ┆ 4        ┆ 4        │
│ 1   ┆ 5   ┆ 9        ┆ 9        │
│ 2   ┆ 6   ┆ 15       ┆ 6        │#map_batches silently ignored over
└─────┴─────┴──────────┴──────────┘
```

`map_batches` silently ignores the `over`

If `map_batches` is switched for `map_elements` then it works as I'd expect `map_batches` to work...

```
print(df.with_columns(
    npcumsum = pl.col('b').map_elements(lambda x: (
        pl.Series(np.cumsum(x.to_numpy()))
        )).over('a'),
    plcumsum = pl.col('b').cum_sum().over('a')
    ))
shape: (3, 4)
┌─────┬─────┬──────────┬──────────┐
│ a   ┆ b   ┆ npcumsum ┆ plcumsum │
│ --- ┆ --- ┆ ---      ┆ ---      │
│ i64 ┆ i64 ┆ i64      ┆ i64      │
╞═════╪═════╪══════════╪══════════╡
│ 1   ┆ 4   ┆ 4        ┆ 4        │
│ 1   ┆ 5   ┆ 9        ┆ 9        │
│ 2   ┆ 6   ┆ 6        ┆ 6        │
└─────┴─────┴──────────┴──────────┘
```
Ostensibly we can "just know" to switch out our `map_batches` for `map_elements` but suppose we write a wrapper

```
def npcumsum(x):
    return (x.map_batches(lambda x: (
        pl.Series(np.cumsum(x.to_numpy()))
        )))
```

then

```
### this works
df.with_columns(npcumsum(pl.col('b')))
### this silently ignores over
df.with_columns(npcumsum=npcumsum(pl.col('b')).over('a'))
```

**Comment by cmdlineluser** [comment] 2023-12-14 22:19
@deanm0000 The behaviour is documented (although it's only under `Notes:`)

> If you are looking to map a function over a window function or group_by context, refer to `map_elements` instead.

**Comment by deanm0000** [comment] 2023-12-15 02:55
My argument isn't about my naming preferences or ambiguity it's about functionality and consistency.

If I wrap a udf in a map_batches then it works for a whole column but then if you you put an `over` on it then it doesn't do anything different. It should at least raise in that situation so people don't get unexpected results.

To get expected results you have to change the map_batches to map_elements which means you can't wrap a custom function in a helper function like I showed with npcumsum and expect it to work in all situations.

The kind of function that you typically want to map_elements on don't make sense in a window because it operates one element at a time. So you might have a function that you use with map_elements but that function doesn't aggregate anything so it wouldn't even work in a group or window because then it's receiving a series input.

To sum up,

map_elements when not in group or window will give every value from a column one at a time to the function and expects the output of that function to be a value

map_elements when in a group or window will give the function a series for each of the groups in the window or group by and it expects the return of that function to be another series

I don't think there are many, if any, use cases for a single function to fit both these modes.

map_batches when not in a group by hands a series to the function and expects a series in return

map_batches when in a group by does the exact same thing as if it weren't in a window or group by.

While the documentation does say not to use map_batches in group by, it's inexplicable why these work this way.

The functionality would be more consistent and usable if map_batches, when in group or window, did what map_elements does and if map_elements in group by either raises or warns that map_elements isn't for aggregations.

**Comment by cmdlineluser** [comment] 2023-12-15 06:20
I found where this used to be explained, it was in the old version of the user guide:

<blockquote>

---

<sup>https://github.com/pola-rs/polars-book/blob/main/docs/user-guide/expressions/user-defined-functions.md#to-map-or-to-apply</sup>



- `map` follows the same rules in both the `select` and the `groupby` context

- Use cases for `map` in the `groupby` context are slim. They are only used for performance reasons, but can quite easily lead to incorrect results. Let me explain why.

---

</blockquote>

I think we are sort of saying the same thing, just in different ways.

> I don't think there are many, if any, use cases for a single function to fit both these modes.

This is why I was wondering if it could be `Expr.map_rows` and `Expr.map_groups` instead.

`.map_batches` in a groupby context could then warn and suggest `Expr.map_groups` instead. 

(The user could disable the warning if they want this behaviour.)

**Comment by deanm0000** [comment] 2023-12-15 13:14
My argument isn't about names, I'm completely agnostic about the names of the methods. My main argument is that if you have `pl.col('c').map_groups(some_func)` then it should just work when doing `pl.col('c').map_groups(some_func).over('d')`. It shouldn't silently, with no indication, give the same result as if there wasn't an `over`.  _[I know that the doc hint at not using in group_by or window but then it should error not ignore the group]_ I don't see a use case where the existing behavior is the desired behavior. If you want a function that ignores over then don't use over in the first place. What we have is a desire to use over and the actual behavior is to have to use a different method entirely. This breaks the ability to wrap UDFs in helper functions as I demonstrated earlier with my `npcumsum` example. I ask, is that _really_ what was intended?

To add to the above, there's *nearly* no use case where you'd have `pl.col('a').map_elements(some_func)` that would make sense as `pl.col('a').map_elements(some_func).over('b')`

**Comment by cmdlineluser** [comment] 2023-12-16 01:55
@kszlim Unfortunately, it was map_rows and map_groups instead of map_elements (due to its dual behaviours depending on context) - map_batches is still a different thing.

Perhaps [`pl.map_groups`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.map_groups.html#polars.map_groups) is a clearer example:

> Apply a custom/user-defined function (UDF) over the groups as a sub-DataFrame.

```python
df = pl.DataFrame({
    "group": [1, 1, 2],
    "a": [1, 3, 5],
    "b": [6, 7, 8]
})

df.with_columns(c = pl.map_groups(["a", "b"], lambda s: s[0] + s[1].sum()).over("group"))
# shape: (3, 4)
# ┌───────┬─────┬─────┬─────┐
# │ group ┆ a   ┆ b   ┆ c   │
# │ ---   ┆ --- ┆ --- ┆ --- │
# │ i64   ┆ i64 ┆ i64 ┆ i64 │
# ╞═══════╪═════╪═════╪═════╡
# │ 1     ┆ 1   ┆ 6   ┆ 14  │
# │ 1     ┆ 3   ┆ 7   ┆ 16  │
# │ 2     ┆ 5   ┆ 8   ┆ 13  │
# └───────┴─────┴─────┴─────┘
```

Without over `.over()` it does "map rows" 

```python
df.with_columns(c = pl.map_groups(["a", "b"], lambda s: s[0] + s[1].sum()))
# shape: (3, 4)
# ┌───────┬─────┬─────┬─────┐
# │ group ┆ a   ┆ b   ┆ c   │
# │ ---   ┆ --- ┆ --- ┆ --- │
# │ i64   ┆ i64 ┆ i64 ┆ i64 │
# ╞═══════╪═════╪═════╪═════╡
# │ 1     ┆ 1   ┆ 6   ┆ 22  │
# │ 1     ┆ 3   ┆ 7   ┆ 24  │
# │ 2     ┆ 5   ┆ 8   ┆ 26  │
# └───────┴─────┴─────┴─────┘
```

**Comment by ritchie46** [comment] 2023-12-21 19:02
It is hard for us to know if the map_batches is valid at runtime. Though we could add a flag that raises. Then the user can unset that flag of they really know what they are doing.

**Comment by MarcoGorelli** [comment] 2023-12-21 19:04
> Though we could add a flag that raises

this would be amazing and save a lot of users from shooting themselves in the foot in my opinion

**Comment by avimallu** [comment] 2023-12-21 19:06
+1 on the raise by default.
