### ISSUE TITLE
Cannot cast integer types to categorical

### ISSUE THREAD

**Issue by david-cortes** [pola-rs/polars#5155] opened 2022-10-10 16:29 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

If I try to cast an integer-type variable to categorical, it will throw an error. This for example would work correctly with pandas:
```python
import numpy as np, pandas as pd
pd.Series(np.arange(3)).astype("category")
```

### Reproducible example

```python
import numpy as np, polars as pl
pl.Series(np.arange(3)).cast(pl.Categorical)
```
```
---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In [1], line 2
      1 import numpy as np, polars as pl
----> 2 pl.Series(np.arange(3)).cast(pl.Categorical)

File ~/anaconda3/envs/py310/lib/python3.10/site-packages/polars/internals/series/utils.py:95, in call_expr.<locals>.wrapper(self, *args, **kwargs)
     93     expr = getattr(expr, namespace)
     94 f = getattr(expr, func.__name__)
---> 95 return s.to_frame().select(f(*args, **kwargs)).to_series()

File ~/anaconda3/envs/py310/lib/python3.10/site-packages/polars/internals/dataframe/frame.py:5243, in DataFrame.select(self, exprs)
   5206 def select(
   5207     self: DF,
   5208     exprs: str | pli.Expr | pli.Series | Sequence[str | pli.Expr | pli.Series],
   5209 ) -> DF:
   5210     """
   5211     Select columns from this DataFrame.
   5212 
   (...)
   5240 
   5241     """
   5242     return self._from_pydf(
-> 5243         self.lazy()
   5244         .select(exprs)
...
    904     common_subplan_elimination,
    905 )
--> 906 return pli.wrap_df(ldf.collect())

ComputeError: Strict conversion from Int64 to Categorical(None) failed for values [0, 1, 2]. If you were trying to cast Utf8 to Date, Time, or Datetime, consider using `strptime`.
```

### Expected behavior

Should cast the variable to categorical like pandas does.

### Installed versions

<details>

```
---Version info---
Polars: 0.14.18
Index type: UInt32
Platform: Linux-5.19.0-2-amd64-x86_64-with-glibc2.35
Python: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.0
numpy: 1.23.3
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment] 2022-10-10 17:01
This is not a bug. Polars doesn't have integer categoricals. Categoricals map to strings.

**Comment by slonik-az** [comment] 2022-10-10 20:49
There is no benefit to cast Integers to Categorical. A set of integers is already an Ordinal Categorical on its own.

**Comment by david-cortes** [comment] 2022-10-10 20:51
> There is no benefit to cast Integers to Categorical. A set of integers is already an Ordinal Categorical on its own.

There *is* a benefit since a categorical has a continuous numeration starting at zero, while arbitrary integers do not have that property.

**Comment by ritchie46** [comment] 2022-10-11 06:06
That seems like an implementation detail? Polars does not have the guarantee that categoricals are backed by exact increments of 1.

**Comment by datenzauberai** [comment] 2022-10-11 06:24
I support @ritchie46 here: it's an implementation detail one should not rely on. When you have a categorical feature saved as a string, the categorical type is an option to save memory and potentially speed-up some operations while maintaining the string name for outputs. There is hardly any benefit of doing this for integers.

However, some options that might suit your case are:

```{python}
df = pl.DataFrame({"id": [3650, 202, 202, 205, 3650]})
df.with_columns([
    pl.col("id").rank(method="dense").alias("pseudo_category_by_rank"),
    pl.col("id").cast(pl.Utf8).cast(pl.Categorical).alias("category_by_double_cast")
])
```

**Comment by slonik-az** [comment] 2022-10-11 09:38
I think this topic should be closed once and for all. Integer columns are __NOT__ Categoricals. Categoricals are final sets of strings (predefined or discovered during construction) that are cast to integer indexes as an optimization. They may (ordinal) or may not (nominal) have ordering. There is no arithmetic operations on categoricals. Integers, OTOH, are ordered and allow arithmetics -- totally different beast.

**Comment by ghuls** [comment] 2022-10-11 22:40
You can create ordinals for number quite easy if you really want.

```python
In [4]: pl.Config.set_tbl_rows(100)
Out[4]: polars.cfg.Config

In [13]: df = pl.DataFrame([pl.Series("a", [5,6,2,3,3,6,0,8,2,2,6]), pl.Series("b", [7,6,0,2,5,5,5,8,7,4,6])])

In [14]: df
Out[14]: 
shape: (11, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 5   ┆ 7   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 6   ┆ 6   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 0   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 2   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 3   ┆ 5   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 6   ┆ 5   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 0   ┆ 5   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 8   ┆ 8   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 7   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 2   ┆ 4   │
├╌╌╌╌╌┼╌╌╌╌╌┤
│ 6   ┆ 6   │
└─────┴─────┘

In [16]: df_with_ordinals =df.with_row_count(offset=0).with_columns([pl.col("row_nr").first().over(pl.col(x)).alias(f"{x}_ordinal") for x in ["a", "b"]])

In [16]: df_with_ordinals
Out[17]: 
shape: (11, 5)
┌────────┬─────┬─────┬───────────┬───────────┐
│ row_nr ┆ a   ┆ b   ┆ a_ordinal ┆ b_ordinal │
│ ---    ┆ --- ┆ --- ┆ ---       ┆ ---       │
│ u32    ┆ i64 ┆ i64 ┆ u32       ┆ u32       │
╞════════╪═════╪═════╪═══════════╪═══════════╡
│ 0      ┆ 5   ┆ 7   ┆ 0         ┆ 0         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 1      ┆ 6   ┆ 6   ┆ 1         ┆ 1         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2      ┆ 2   ┆ 0   ┆ 2         ┆ 2         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 3      ┆ 3   ┆ 2   ┆ 3         ┆ 3         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 4      ┆ 3   ┆ 5   ┆ 3         ┆ 4         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 5      ┆ 6   ┆ 5   ┆ 1         ┆ 4         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 6      ┆ 0   ┆ 5   ┆ 6         ┆ 4         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 7      ┆ 8   ┆ 8   ┆ 7         ┆ 7         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 8      ┆ 2   ┆ 7   ┆ 2         ┆ 0         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 9      ┆ 2   ┆ 4   ┆ 2         ┆ 9         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 10     ┆ 6   ┆ 6   ┆ 1         ┆ 1         │
└────────┴─────┴─────┴───────────┴───────────┘

In [20]: df_with_ordinals.sort(by="a_ordinal")
Out[20]: 
shape: (11, 5)
┌────────┬─────┬─────┬───────────┬───────────┐
│ row_nr ┆ a   ┆ b   ┆ a_ordinal ┆ b_ordinal │
│ ---    ┆ --- ┆ --- ┆ ---       ┆ ---       │
│ u32    ┆ i64 ┆ i64 ┆ u32       ┆ u32       │
╞════════╪═════╪═════╪═══════════╪═══════════╡
│ 0      ┆ 5   ┆ 7   ┆ 0         ┆ 0         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 1      ┆ 6   ┆ 6   ┆ 1         ┆ 1         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 5      ┆ 6   ┆ 5   ┆ 1         ┆ 4         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 10     ┆ 6   ┆ 6   ┆ 1         ┆ 1         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2      ┆ 2   ┆ 0   ┆ 2         ┆ 2         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 8      ┆ 2   ┆ 7   ┆ 2         ┆ 0         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 9      ┆ 2   ┆ 4   ┆ 2         ┆ 9         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 3      ┆ 3   ┆ 2   ┆ 3         ┆ 3         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 4      ┆ 3   ┆ 5   ┆ 3         ┆ 4         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 6      ┆ 0   ┆ 5   ┆ 6         ┆ 4         │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 7      ┆ 8   ┆ 8   ┆ 7         ┆ 7         │
└────────┴─────┴─────┴───────────┴───────────┘

```

**Comment by ritchie46** [comment] 2022-10-12 18:35
I will close this as this is not a bug and the desired behavior can already be accomplished as shown by @datenzauberai  and @ghuls.

**Closed by ritchie46** 2022-10-12 18:35 UTC
Labels: bug, python

**Comment by baggiponte** [comment] 2024-05-09 17:32
Hey there, sorry to necro bump this, but I saw that #13409 was merged and wanted to give my 2 cents.

I understand your reasoning, but I don't fully agree that "integer types cannot be categoricals". For example, HTTP response status codes or image ratios are.

I often find myself casting such columns to UTF8 and then to Categoricals. I did this for visualisation purposes, but I can see it could be useful for model fitting: for example, Gradient Boosted Regressors behave differently for categorical covariates and most implementations (including sklearn's) can perform such detection automatically based on the dtype.

Anyway, if casting an integer col to categorical would just pass via string dtypes anyway, I see why it should not be supported.

**Comment by ritchie46** [comment] 2024-05-09 17:45
In your case the integers go via `string` and integers, `1, 2, 3` will become strings `"1", "2", "3"`.

E.g. we map categories to strings. Not categories to integers. I think you should keep going via string cast as going directly via integer cast would be very unexpected. If we would succeed, I would expect categories to map to integers (which we don't have).
