### ISSUE TITLE
Error when using `pow` in groupby context

### ISSUE THREAD

**Issue by Teamon9161** [pola-rs/polars#4879] opened 2022-09-16 16:09 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

ComputeError when using `pow` in groupby context

```python
import polars as pl

df = pl.DataFrame({
    'group': [1, 1, 1],
    'a': [1, 2, 3]
})

df.groupby('group').agg(
    pl.lit(2).pow(pl.col('a')).sum()
)
```
Result:
```python
ComputeError: A 'map' functions output length must be equal to that of the input length. Consider using 'apply' in favor of 'map'.
```

### Reproducible Example

```python
see above
```

### Expected Behavior

```python
shape: (1, 2)
┌───────┬──────┐
│ group ┆ a    │
│ ---   ┆ ---  │
│ i64   ┆ f64  │
╞═══════╪══════╡
│ 1     ┆ 14.0 │
└───────┴──────┘
```

### Installed Versions

<details>
``` 
---Version info---
Polars: 0.14.11
Index type: UInt32
Platform: Windows-10-10.0.22000-SP0
Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.3.4
numpy: 1.22.3
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.7.8 ```
</details>

**Comment by KeremAslan** [comment] 2022-09-16 20:59
I don't think this is a bug. When using .`.pow()` the elements length need to match. So you can do `pl.lit(2).power(3)` or 

```python
df = pl.DataFrame({
    'group': [1, 1, 1],
    'a': [1, 2, 3]
})

df.with_column(pl.col("a").pow([1, 2, 3])

```

but not `pl.lit(2).pow([1, 2, 3])`  as they are not the same length and it isn't obvious how to take the power of 2 to 1, 2, 3. 

Instead I think that you want to do this

```python
(
    df
    .with_column(pl.lit(2).pow(pl.col("a")).alias("value"))
    .groupby("group")
    .agg(
        pl.col("value").sum()
    )
)

┌───────┬───────┐
│ group ┆ value │
│ ---   ┆ ---   │
│ i64   ┆ f64   │
╞═══════╪═══════╡
│ 1     ┆ 14.0  │
└───────┴───────┘

**Comment by Teamon9161** [comment] 2022-09-17 05:43
@KeremAslan Thanks for your response! But shouldn't `[1 ** 2,  2 ** 2, 3 ** 2]` and `[2 ** 1, 2 ** 2, 2 ** 3]` be similar? When using `col("a").pow(2)`, each element in `col("a")` is squared. I think that `2` in this case can also be broadcast to the shape of  `col("a")` within each group.

**Comment by KeremAslan** [comment] 2022-09-17 19:28
I am not sure I understand. Do you want to square each element of column `a` or take `2` to the power of each element in column `a`? The result for 1,2, 3 are the same, but not for n > 3. 

If you want to square each element in the aggregate you can do that as what you've already put:

```python
df.groupby('group').agg(
   pl.col("a").pow(2).sum()
)
```

**Comment by Teamon9161** [comment] 2022-09-18 06:18
@KeremAslan I'm sorry I didn't make it clear. I want to take `2` to the power of each element in column `a`. I think square each element of column `a` and take `2` to the power of each element in column `a` are similar, I don't quite understand why one works and the other doesn't. I hope that `pl.lit(2).pow(pl.col('a')).sum()` can also work fine.

**Comment by KeremAslan** [comment] 2022-09-18 11:36
Hmm actually yeah I think that's a valid question. 

If I change the operation  to e.g. `*`, it works:

```python
df.groupby('group').agg(
    (pl.lit(2) * pl.col("a")).sum()
)
```

**Comment by julio-34727** [comment] 2022-09-18 18:33
```python
import polars as pl

(
    pl.DataFrame({'group': [1, 1, 1], 'a': [1, 2, 3]})
    .groupby('group', maintain_order=True)
    .agg(pl.repeat(2, pl.count()).pow(pl.col('a')).sum().alias('a_r')
    # .with_column(pl.lit(2).pow(pl.col('a')).alias("a_r"))
    # .groupby('group'.agg(pl.col('a_r').sum())
)
shape: (1, 2)
┌───────┬──────┐
│ group ┆ a_r  │
│ ---   ┆ ---  │
│ i64   ┆ f64  │
╞═══════╪══════╡
│ 1     ┆ 14.0 │
└───────┴──────┘
```

And:
```python
(
    pl.DataFrame({'group': [1, 1, 2], 'a': [1, 2, 3]})
    .groupby('group', maintain_order=True)
    .agg(pl.repeat(2, pl.count()).pow(pl.col('a')).sum().alias('a_r'))
)
shape: (2, 2)
┌───────┬─────┐
│ group ┆ a_r │
│ ---   ┆ --- │
│ i64   ┆ f64 │
╞═══════╪═════╡
│ 1     ┆ 6.0 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2     ┆ 8.0 │
└───────┴─────┘
```

**Comment by ritchie46** [comment] 2022-10-21 18:13
I will close this as this is not a bug and @julio-34727 has shown the proper way to do this.

**Closed by ritchie46** 2022-10-21 18:13 UTC
Labels: bug, python
