### ISSUE TITLE
Using `LazyFrame.cache()` returns the wrong result

### ISSUE THREAD

**Issue by CaselIT** [pola-rs/polars#15675] opened 2024-04-15 17:55 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

See new example at https://github.com/pola-rs/polars/issues/15675#issuecomment-2057606671

```python
import polars as pl

data = pl.DataFrame(
    {"a": [1, 2, 3, 1, 2, 3], "b": [1, 1, 1, 1, 1, 1], "id": [1, 1, 1, 2, 2, 2]}
).lazy()
left = data.filter(id=1)
# for this example to work the id must be the same
right = data.filter(id=1)

joined = left.select(pl.all().name.prefix("l")).join(
    right.select(pl.all().name.prefix("r")), left_on=["la", "lb"], right_on=["ra", "rb"]
)
print(joined.with_columns().collect().shape)
print(joined.cache().with_columns().collect().shape)

```

### Log output

```shell
(3, 4)
(12, 4)
```

### Issue description

Calling `cache()` makes polars return the wrong result.
Note that this a minimal reproduction example I came up with. Of course it does not make any sense, but where I found this is a much more complex use and does not rely on the fact that the same filter is used twice.

It self join on the same starting df write though, so that may be the cause of the issue.

### Expected behavior

`cache()` should not alter the result of the query

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.19
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  0.11.0
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.5.6
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.3
pyarrow:              14.0.1
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.23
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment] 2024-04-15 18:01
I think this is fixed on main:

```python
(3, 4)
(3, 4)
```

**Comment by CaselIT** [comment] 2024-04-15 18:04
version 0.20.20 has been yanked, so I tried the last available one.
If you have a wheel I can give a try on main in my actual use case (I don't have rust installed on this pc)

**Comment by cmdlineluser** [comment] 2024-04-15 18:07
`0.20.21` is on the way: 

- https://github.com/pola-rs/polars/pull/15673

**Comment by CaselIT** [comment] 2024-04-15 18:07
this example is fixed also on version 0.20.20, but my use case is not.
I'll retry generating it. The issue is still connected to cache btw: replacing the use of cache with
`df.collect().lazy()` fixes the issue in my use case

**Comment by MarcoGorelli** [comment] 2024-04-15 18:33
can confirm this is fixed on `main` (fixed by https://github.com/pola-rs/polars/pull/15554 ?)

closing then, but thanks for the report @CaselIT !

**Comment by CaselIT** [comment] 2024-04-15 19:01
I can still reproduce on 0.20.20, so no I don't believe it's fixed.
```py
import polars as pl

data = pl.DataFrame(
    {"a": [1, 2, 3, 1, 2, 3], "b": [1, 1, 1, 1, 1, 1], "id": [1, 1, 1, 2, 2, 2]}
).lazy()

oneAndTwo = data.filter(id=1).join(data.filter(id=2), on=["a", "b"], how="semi")
onlyOne = data.filter(id=1).join(oneAndTwo, on=["a", "b"], how="semi")
onlyOne = onlyOne.cache()
res = onlyOne.group_by("b").agg(pl.all().sum())
print(res.with_columns().collect())
print(res.cache().with_columns().collect())
```
this prints
```
shape: (1, 3)
┌─────┬─────┬─────┐
│ b   ┆ a   ┆ id  │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 6   ┆ 3   │
└─────┴─────┴─────┘
shape: (1, 3)
┌─────┬─────┬─────┐
│ b   ┆ a   ┆ id  │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 12  ┆ 9   │
└─────┴─────┴─────┘
```

**Comment by CaselIT** [comment] 2024-04-15 19:02
let me know if you want me to open a new issue or we reopen this one.
if so I can update the OP

**Comment by CaselIT** [comment] 2024-04-15 19:20
Just tried 0.20.21. This https://github.com/pola-rs/polars/issues/15675#issuecomment-2057606671 still reproduces

**Comment by MarcoGorelli** [comment] 2024-04-15 19:42
on 0.20.21 I'm seeing:
```python
In [2]: import polars as pl
   ...:
   ...: data = pl.DataFrame(
   ...:     {"a": [1, 2, 3, 1, 2, 3], "b": [1, 1, 1, 1, 1, 1], "id": [1, 1, 1, 2, 2, 2]}
   ...: ).lazy()
   ...: left = data.filter(id=1)
   ...: # for this example to work the id must be the same
   ...: right = data.filter(id=1)
   ...:
   ...: joined = left.select(pl.all().name.prefix("l")).join(
   ...:     right.select(pl.all().name.prefix("r")), left_on=["la", "lb"], right_on=["ra", "rb"
   ...: ]
   ...: )
   ...: print(joined.with_columns().collect().shape)
   ...: print(joined.cache().with_columns().collect().shape)
(3, 4)
(3, 4)

In [3]: pl.__version__
Out[3]: '0.20.21'
```

Do you still see `(12, 4)` for the second one?

**Comment by MarcoGorelli** [comment] 2024-04-15 19:46
https://github.com/pola-rs/polars/issues/15675#issuecomment-2057606671 this one still reproduces though - reopening then, thanks

**Comment by cmdlineluser** [comment] 2024-04-15 19:48
The newer example seems to be a combination of `comm_subexpr_elim` and `projection_pushdown`

```python
import polars as pl

data = pl.DataFrame(
    {"a": [1, 2, 3, 1, 2, 3], "b": [1, 1, 1, 1, 1, 1], "id": [1, 1, 1, 2, 2, 2]}
).lazy()

oneAndTwo = data.filter(id=1).join(data.filter(id=2), on=["a", "b"], how="semi")
onlyOne = data.filter(id=1).join(oneAndTwo, on=["a", "b"], how="semi")
onlyOne = onlyOne.cache()
res = onlyOne.group_by("b").agg(pl.all().sum())

print(res.with_columns().collect())

print(res.cache().with_columns().collect())

print(res.cache().with_columns().collect(comm_subexpr_elim=False, projection_pushdown=False))
```

```python
shape: (1, 3)
# ┌─────┬─────┬─────┐
# │ b   ┆ a   ┆ id  │
# │ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ i64 │
# ╞═════╪═════╪═════╡
# │ 1   ┆ 6   ┆ 3   │
# └─────┴─────┴─────┘
# shape: (1, 3)
# ┌─────┬─────┬─────┐
# │ b   ┆ a   ┆ id  │
# │ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ i64 │
# ╞═════╪═════╪═════╡
# │ 1   ┆ 12  ┆ 9   │
# └─────┴─────┴─────┘
# shape: (1, 3)
# ┌─────┬─────┬─────┐
# │ b   ┆ a   ┆ id  │
# │ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ i64 │
# ╞═════╪═════╪═════╡
# │ 1   ┆ 6   ┆ 3   │
# └─────┴─────┴─────┘
```

**Comment by CaselIT** [comment] 2024-04-15 19:58
the reproducing example is again a simplified version of my real use case that has many combination with similar self joins (that do make sense).

I can try to create a wheel once there is a fix to report if everything else works. By any change is there a github workflow that creates one that I can run on a fork?

**Comment by MarcoGorelli** [comment] 2024-04-16 08:33
I've opened a new issue about the second bug you reported, let's close in favour of that one (if we keep adding new examples to the same issue it's easy to lose track of things) https://github.com/pola-rs/polars/issues/15688

thanks again for taking time to report this 🙏 !

**Closed by MarcoGorelli** 2024-04-16 08:33 UTC
Labels: python

**Comment by CaselIT** [comment] 2024-04-16 08:56
Ok. I've found another bug in lazy without any cache call. Not sure if it's related (it seems so)
```py
import polars as pl

y = pl.DataFrame({"a": [1, 2, 3, 1, 2, 3], "b": [1, 1, 1, 1, 1, 1], "y": [2, 3, 4, 5, 6, 7]}).lazy()

xf = y.filter(pl.col.y.is_in([2, 3, 4])).select(["a", "b"])
y_xf = y.join(xf, on=["a", "b"], how="semi")

y_xf_c = y_xf.select(a="a", b="b")
y_xf_c.collect()
```
```
polars.exceptions.ColumnNotFoundError: y
```

**Comment by MarcoGorelli** [comment] 2024-04-16 09:00
could you open a new issue please?

**Comment by MarcoGorelli** [comment] 2024-04-16 09:04
it might be, it's just easier to keep track of things if there's one bug per issue :) then, one PR closes an issue, rather than closing half-an-issue

**Comment by CaselIT** [comment] 2024-04-16 09:15
great will create a new one

**Comment by CaselIT** [comment] 2024-04-16 09:23
created https://github.com/pola-rs/polars/issues/15690
