### ISSUE TITLE
Polars drops pyarrow field-level metadata

### ISSUE THREAD

**Issue by jleibs** [pola-rs/polars#18316] opened 2024-08-22 15:18 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
schema = pa.schema([
    pa.field('pos', pa.list_(pa.float32(), 3), metadata={"archetype": "Points3D"}),
])

table = pa.table({"pos": pa.array([[1,2,3], [4,5,6]])}, schema)

table.schema
 
# pos: fixed_size_list<item: float>[3]
#  child 0, item: float
#  -- field metadata --
#  archetype: 'Points3D'

polars.from_arrow(table).to_arrow().schema

# pos: fixed_size_list<item: float>[3]
#  child 0, item: float
```

### Issue description

The arrow spec from https://arrow.apache.org/docs/format/Columnar.html#custom-application-metadata indicates:
>This extension metadata can annotate any of the built-in Arrow logical types. The intent is that an implementation that does not support an extension type can still handle the underlying data. For example a 16-byte UUID value could be embedded in FixedSizeBinary(16), and implementations that do not have this extension type can still work with the underlying binary values and pass along the custom_metadata in subsequent Arrow protocol messages.

### Expected behavior

Metadata attached to the columns of a schema that are passed into polars should be preserved when those columns are retrieved again.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             Linux-5.19.0-46-generic-x86_64-with-glibc2.36
Python:               3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.9.1.post1
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                2.2.2+cu121
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by Oreilles** [comment] 2024-08-23 17:08
Duplicate of https://github.com/pola-rs/polars/issues/9112

**Comment by ritchie46** [comment] 2024-08-24 10:32
I will close this as Polars doesn't aim to maintain full arrow metadata nor types. We might do extension types, but I am not guaranteeing that to be arrow types.

**Closed by ritchie46** 2024-08-24 10:32 UTC
Labels: bug, python, needs triage

**Comment by jleibs** [comment] 2024-08-24 13:30
> I will close this as Polars doesn't aim to maintain full arrow metadata nor types.

@ritchie46 This is a somewhat disappointing stance for Polars to take given the project claims:

> Polars utilizes the Apache Arrow memory model allowing you to easily integrate with existing tools in the data landscape.

This seems like it will functionally block polars from being a practical tool for working with data that caries more semantics than a raw type.

We are actively working on building out a specification and tools for working with semantic, multimodal, columnar data (images, pointclouds, geometric transforms, etc.), however having this work nicely means being able to store the data somewhere. Neither column-name, nor raw physical type are sufficiently expressive or structured for this.

Looks like geopolars (which has a similar goal for geo data) has hit a similar obstacle with using polars.

**Comment by ritchie46** [comment] 2024-08-25 07:06
> This seems like it will functionally block polars from being a practical tool for working with data that caries more semantics than a raw type.

Yes. It is what it is. If we would have to map 1:1 to arrow that would also be restrictive to us as we have different ideas for some datatypes and pinning us down would limit us. We support many arrow types 1:1, but just don't promise all types, and certainly not all meta types.

> This seems like it will functionally block polars from being a practical tool for working with data that caries more semantics than a raw type.

Polars will support extension types of their own. We are not there yet. But I am not sure this will be arrow metadata types.
