### ISSUE TITLE
[BUG] Write csv writing one final \n that shoulnd be there

### ISSUE THREAD

**Issue by wmoreiraa** [pola-rs/polars#6154] opened 2023-01-10 11:52 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When you call  DataFrame.write_csv without  the filepath to get the bytestring back, it writes one \n more than needed.

### Reproducible example

```python
import polars as pl
from polars.testing import assert_frame_equal
df = pl.DataFrame({"foo":["foo"]})
output_csv = df.write_csv()
assert_frame_equal(df, pl.read_csv(output_csv)) #This should evaluate to True!
>> False
pl.read_csv(output_csv)
foo
str
---
foo
null
```

### Expected behavior
```
import polars as pl
from polars.testing import assert_frame_equal
df = pl.DataFrame({"foo":["foo"]})
output_csv = df.write_csv()
assert_frame_equal(df, pl.read_csv(output_csv)) #This should evaluate to True!
>> True
pl.read_csv(output_csv)
foo
str
---
foo
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.13
Index type: UInt32
Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 6.0.1
pandas: 1.5.2
numpy: 1.22.4
fsspec: 2022.01.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.3
```

</details>

**Comment by ritchie46** [comment] 2023-01-10 13:22
It does:

```python
df = pl.DataFrame({"foo":["foo"]})
output_csv = df.write_csv()
assert df.frame_equal(pl.read_csv(output_csv.encode()))
```

If you pass a string to polars it will search for that file location, you must either pass it a `BytesIO` or encode it to a `bytes` object.

**Comment by ritchie46** [comment] 2023-01-10 13:23
> It does:
> 
> ```python
> df = pl.DataFrame({"foo":["foo"]})
> output_csv = df.write_csv()
> assert df.frame_equal(pl.read_csv(output_csv.encode()))
> ```
> 
> If you pass a string to polars it will search for that file location, you must either pass it a `BytesIO` or encode it to a `bytes` object.

Ending files with a new empty line is not a flawed csv.

**Comment by ritchie46** [comment] 2023-01-11 18:07
I will close this as this is not a bug on our side.

**Closed** 2023-01-11 18:07 UTC
Labels: bug, python
