### ISSUE TITLE
Infinite recursion with `read_parquet` and `memory://` URL

### ISSUE THREAD

**Issue by tamasfe** [pola-rs/polars#14417] opened 2024-02-11 17:13 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import fsspec

df= pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

with fsspec.open("memory:///whatever.parquet", "wb") as f:
    df.write_parquet(f)

df = pl.read_parquet("memory:///whatever.parquet")
```

### Issue description

`read_parquet` fails via fsspec but only via `memory://` URL, `read_csv` works fine.

Possible overlap with #12876, ~~but since it reaches fsspec, I don't think it's a filename issue.~~

### Expected behavior

Works as expected.

### Installed versions

<details>

```
Polars:               0.20.7
Index type:           UInt32
Platform:             Linux-6.7.4-zen1-1-zen-x86_64-with-glibc2.39
Python:               3.12.1 (main, Jan  4 2024, 11:27:05) [GCC 13.2.1 20230801]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2024.2.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             2.6.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by deanm0000** [comment] 2024-02-14 14:34
Maybe an enhancement request but not a bug I think.

This works

```
df= pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

with fsspec.open("memory:///whatever.parquet", "wb") as f:
    df.write_parquet(f)

with fsspec.open("memory:///whatever.parquet", "rb") as f:
    df2=pl.read_parquet(f)
```

**Comment by tamasfe** [comment] 2024-02-14 14:45
In the OP I wrote that it successfully reaches fsspec to read the data, which it does but it's only for the schema which is discarded afterwards:

https://github.com/pola-rs/polars/blob/d80cebfd0c1ae8c33f36f836374ff3decdc75f30/py-polars/polars/io/_utils.py#L182

And then it recurses infinitely like you said.

**Comment by deanm0000** [comment] 2024-02-14 17:10
polars doesn't support fsspec in `read_parquet` anymore so you'll have to open manually and the fix is just to give a `NotImplementedError`.

**Comment by stinodego** [comment] 2024-02-15 12:24
I'm closing this in favor of https://github.com/pola-rs/polars/issues/12876, which hits the same recursion issue.

**Closed by stinodego** 2024-02-15 12:24 UTC
Labels: bug, python, enhancement, A-interop
