### ISSUE TITLE
Inconsistent DataFrame creation when passing data with large `int`

### ISSUE THREAD

**Issue by ElDifinitivo** [pola-rs/polars#7438] opened 2023-03-08 21:43 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

DataFrame creation with a `schema` to map out dtypes is creating data with different results.

With a very large int, there seems to be two different ways polars is handling conversion to the `UInt64` dtype depending on how the passed data is collected. When passing the results as a list of dictionaries where each dict acts as a row to the data (how data pulled from SQL is organized), the value of the integer is unexpected. However if the passed data is modified to be a dictionary of lists, the resulting value is what should be expected.

### Reproducible example

```python
import polars as pl

sql_resultset = [{"num": 13888061535333455402}]  # auto-conversion to f64 without schema
pandas_expectation = {"num": [13888061535333455402]}  # OverflowError without schema

schema = {"num": pl.UInt64}
expected = pl.DataFrame(pandas_expectation, {"num": pl.UInt64})
wrong_conversion = pl.DataFrame(sql_resultset, {"num": pl.UInt64})

print(expected.frame_equal(wrong_conversion))  # False, should be True
print(wrong_conversion.filter(pl.col("num") == 13888061535333455402).is_empty())  # True, should be False
```

### Expected behavior

The above example will return `False` on equality between the two dataframes and `True` to checking if the incorrectly created DataFrame is empty; the boolean results should be inverted.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Linux-6.1.14_1-x86_64-with-glibc2.36
Python: 3.9.2 (default, Feb  8 2023, 09:39:22)
[GCC 12.2.0]
---Optional dependencies---
pyarrow: <not installed>
pandas: <not installed>
numpy: <not installed>
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by zundertj** [comment] 2023-03-09 06:17
Can reproduce on master:

```python
>>> pl.from_dict({"num": [13888061535333455402]}, schema={"num": pl.UInt64}).item()
13888061535333455402
>>> pl.from_dicts([{"num": 13888061535333455402}], schema={"num": pl.UInt64}).item()
13888061535333455872
```

Seems to happen in the Rust layer when reading the sequence of dicts:

```python
import polars
from polars.polars import PyDataFrame
from polars.internals import wrap_df

wrap_df(PyDataFrame.read_dicts([{'num': 13888061535333455402}], 100, {"num": pl.UInt64}))
shape: (1, 1)
┌──────────────────────┐
│ num                  │
│ ---                  │
│ u64                  │
╞══════════════════════╡
│ 13888061535333455872 │
└──────────────────────┘
```

**Comment by Wainberg** [comment] 2023-11-23 04:24
This can be closed since it's fixed in the current release:

```
>>> import polars as pl
>>>
>>> sql_resultset = [{"num": 13888061535333455402}]  # auto-conversion to f64 without schema
>>> pandas_expectation = {"num": [13888061535333455402]}  # OverflowError without schema
>>>
>>> schema = {"num": pl.UInt64}
>>> expected = pl.DataFrame(pandas_expectation, {"num": pl.UInt64})
>>> wrong_conversion = pl.DataFrame(sql_resultset, {"num": pl.UInt64})
>>>
>>> print(expected.frame_equal(wrong_conversion))  # False, should be True
True
>>> print(wrong_conversion.filter(pl.col("num") == 13888061535333455402).is_empty())  # True, should be False
False
```

**Comment by stinodego** [comment] 2024-01-16 15:16
@Wainberg feel free to tag me if you find an issue that can be closed!

**Closed** 2024-01-16 15:15 UTC
Labels: bug, python, needs triage
