### ISSUE TITLE
Load multiple files in a performant manner & some benchmarks

### ISSUE THREAD

**Issue by MrPowers** [pola-rs/polars#2219] opened 2021-12-29 11:03 UTC
Thanks for creating this great library.  Really excited about Polars!!

I'm trying to figure out if there is a performant way to work with multiple files & Polars or if the library is designed to work on data that's stored in a single file.  Are there parallel filesystem operations?  Are they on the roadmap?

I ran a simple filtering query on a 58.2 GB dataset that's stored in 1,097 files and was surprised it took 100 seconds, see [this notebook](https://github.com/MrPowers/polars-fun/blob/main/notebooks/parquet-benchmark.ipynb).  It's possible my code is bad and there is a way to run this query a lot faster.

Here's the code snippet:

```python
home = os.path.expanduser("~")
path = f"{home}/data/timeseries/20-years/parquet"
all_files = glob.glob(path + "/*.parquet")

ldf = pl.concat(list(pl.scan_parquet(f) for f in all_files))
ldf.select(pl.col("id").n_unique()).collect()
```

This same query only took 8.65 seconds with Dask on my local machine, see [this notebook](https://github.com/coiled/coiled-resources/blob/main/dataframes/scaling-pandas-with-dask.ipynb).

The dataset can be accessed via `s3://coiled-datasets/timeseries/20-years/parquet` or recreated on your local machine by running [this script](https://github.com/coiled/coiled-datasets/blob/main/create-scripts/timeseries.py).

The computations were run on Mac M1 with 8GB of RAM.  The data was stored on my SSD.

Thanks again for making this awesome library, really excited to track the progress of Polars and hopefully I will be able to contribute!

**Comment by ritchie46** [comment] 2021-12-29 12:11
I think there is something we could do smarter.  I think we scan in parallel but we don't do that.

How does this perform?

```python
df = pl.concat(list(pl.read_parquet(f) for f in all_files), rechunk=False)
df.select(pl.col("id").n_unique())
```

**Comment by MrPowers** [comment] 2021-12-29 12:36
@ritchie46 - I ran your code snippet above and it took 96 seconds to execute, so about the same amount of time.

Seems like Polars needs to read the files one-by-one, which is the bottleneck.  Dask can read multiple files in parallel, which is probably why it outperforms.

Out of curiosity, do you plan to continue building out Polars to eventually scale to clusters or is the vision of the project to just be a "really fast Pandas".

**Comment by ritchie46** [comment] 2021-12-29 12:47
> Seems like Polars needs to read the files one-by-one, which is the bottleneck. Dask can read multiple files in parallel, which is probably why it outperforms.

Ok, I will make sure we paralellize the concat in the physical plan.

> Out of curiosity, do you plan to continue building out Polars to eventually scale to clusters or is the vision of the project to just be a "really fast Pandas".

Single machine is the goal. I do plan more connection with clouds and streaming inputs. So that predicate pushdown will work on streaming dataframes for instance.

**Comment by MrPowers** [comment] 2021-12-29 14:36
@ritchie46 - didn't take you long to push up a fix ;)

I'll rerun the queries the next time you do a release to see the performance.  Thanks!

**Comment by ritchie46** [comment] 2021-12-30 08:46
It's released. Give it a spin?

**Comment by MrPowers** [comment] 2021-12-30 10:38
@ritchie46 - thanks for the ping.  I updated to Polars 0.12.6 and it looks like the code is running faster.  Here are the runtimes  (these are when I restart the Jupyter cluster after every run):

* 64 seconds
* 65 seconds
* 66 seconds

It's still not as fast as Dask, but a nice improvement from before.  Well done!!

I did notice that rerunning the same query makes it slower every time.  Here's what happens when I run the same query over and over:

* run 1: 75 seconds
* run 2: 136 seconds
* run 3: 190 seconds
* run 4: Errors out

<img width="615" alt="Screen Shot 2021-12-30 at 5 04 20 AM" src="https://user-images.githubusercontent.com/2722395/147743954-3d2a117b-64a8-42ba-91d1-aa805a83e72d.png">

I'm getting something is causing my computer to run out of memory and Python is just killing the process.

Here's the query I was running multiple times:

<img width="541" alt="Screen Shot 2021-12-30 at 5 02 52 AM" src="https://user-images.githubusercontent.com/2722395/147744008-467ddc8f-4e62-40e4-8e9a-8f3d5c7e8249.png">

I'm calling `collect()` repeatedly, but only on a 1 row DataFrame, so this memory error isn't expected.

I'm guessing there is some additional magic you can work to get this query runtime down to around 10 seconds, but I don't understand the inner workings, so don't have any useful suggestions on how to actually accomplish this.  Thanks for the quick responses!!

**Comment by ritchie46** [comment] 2021-12-30 11:11
I will take a closer look at this.

**Comment by ritchie46** [comment] 2021-12-30 11:27
The issue is an regression in `polars==0.10.27` I can load this sequentally in 11 seconds. Probably related to: #2233

**Comment by ritchie46** [comment] 2021-12-30 11:42
Did some local tests and the issue was that we did not do the projection pushdown. This is now fixed. I can locally load the 20 years in <6 secs. I will patch a release for this.

**Comment by MrPowers** [comment] 2021-12-30 11:45
@ritchie46 - awesome work.  I'll be happy to test it again on my end when the new release it on PyPi.

**Comment by ritchie46** [comment] 2021-12-30 11:46
> @ritchie46 - awesome work. I'll be happy to test it again on my end when the new release it on PyPi.

Cool, see #2233 for the status. I expect in an hour or 2 ;)

**Comment by ritchie46** [comment] 2021-12-30 14:53
3th time the charm @MrPowers ?

**Comment by Arengard** [comment] 2021-12-30 15:58
nicely done 👍

**Comment by universalmind303** [comment] 2021-12-30 18:38
would it be possible to have polars smart enough to detect folders and do this automatically instead of having to concat each file. Either through a flag, or as default behavior?

```py
pl.scan_parquet("path/to/directory")
```

**Comment by ritchie46** [comment] 2021-12-30 18:49
> would it be possible to have polars smart enough to detect folders and do this automatically instead of having to concat each file. Either through a flag, or as default behavior?
> 
> ```python
> pl.scan_parquet("path/to/directory")
> ```

That would be a welcome addition to the scan indeed.

**Comment by MrPowers** [comment] 2021-12-31 02:12
3rd time's the charm 🎊 🚀 

* Run 1: 9.5s
* Run 2: 9.9
* Run 3: 10.6
* Run 4: 9.6
* Run 5: 10.1

I am really impressed you were able to make this 10 times faster... in a day.  Truly excellent work.

**Comment by ritchie46** [comment] 2021-12-31 06:46
> I am really impressed you were able to make this 10 times faster... in a day. Truly excellent work.

Nice! Thanks for the help here!

You could squeeze out a bit more by setting rechunk and parallel to False. But I'd call it a day. :)

**Closed** 2021-12-31 06:50 UTC
