### ISSUE TITLE
Polars from Pandas - NaN no longer convert to Null when mixed datatypes

### ISSUE THREAD

**Issue by dguidara** [pola-rs/polars#17357] opened 2024-07-02 13:21 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import numpy as np
import polars as pl
df = pd.DataFrame(data=(['x']* 20) + [np.NaN], columns=["foo"])
df_polars = pl.from_pandas(df)
df_polars
```

### Log output

```shell
in pandas_to_pydf(data, schema, schema_overrides, strict, rechunk, nan_to_null, include_index)
   1043 convert_index = include_index and not _pandas_has_default_index(data)
...
    445 elif sum(values.shape) == 0:
    446     # Optimize by ingesting 1D and reshaping in Rust
    447     original_shape = values.shape

TypeError: 'float' object cannot be converted to 'PyString'
```

### Issue description

In previous versions of Polars, when a column had a mixed datatype (strings and then a NaN), polars converts the NaN to null.  In Polars 1.0.0 it complains that a float (nan) cant convert to PyString.  The error message is vague and does not indicate which column is the issue. 

### Expected behavior

The old behavior of converting NaN to null when the column is a string is ideal.  Or at the very least, a better error message indicating the column.   In Pandas if I do a replace of NaN to None and then from_pandas it the works fine.   

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  0.11.0
cloudpickle:          3.0.0
connectorx:           0.3.2
deltalake:            0.17.3
fastexcel:            0.10.4
fsspec:               2023.12.2
gevent:               24.2.1
great_tables:         <not installed>
hvplot:               0.9.2
matplotlib:           3.5.1
nest_asyncio:         1.5.4
numpy:                1.22.1
openpyxl:             3.0.10
pandas:               1.4.0
pyarrow:              16.0.0
pydantic:             2.7.1
pyiceberg:            0.6.1
sqlalchemy:           2.0.29
torch:                <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           3.0.2
```

</details>

**Comment by stinodego** [comment] 2024-07-02 15:22
Thanks for the report! Duplicate of https://github.com/pola-rs/polars/issues/17355

**Closed by stinodego** 2024-07-02 15:22 UTC
Labels: bug, python, needs triage
