### ISSUE TITLE
pl.Expr.take with None indices

### ISSUE THREAD

**Issue by josh** [pola-rs/polars#11522] opened 2023-10-04 19:03 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame({"a": [1, 2, 3]}).select(pl.col("a").take([0, None]))
```

### Log output

```shell
Traceback (most recent call last):
  File "/workspaces/foo/example.py", line 7, in <module>
    df = pl.DataFrame({"a": [1, 2, 3]}).select(pl.col("a").take([0, None]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.11.5/lib/python3.11/site-packages/polars/dataframe/frame.py", line 7727, in select
    return self.lazy().select(*exprs, **named_exprs).collect(eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.11.5/lib/python3.11/site-packages/polars/utils/deprecation.py", line 95, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.11.5/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1711, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
exceptions.ComputeError: take indices are out of bounds
```

### Issue description

As of 0.19.4, an indices series that uses `None` masked values can not be used safely with `pl.Expr.take`.

The old behavior still exists on `pl.Expr.list`. So even if this was intentional, there is now an API inconsistency.

```
pl.DataFrame({"a": [[1, 2, 3]]}).select(pl.col("a").list.take([0, None]))
# shape: (1, 1)
# ┌───────────┐
# │ a         │
# │ ---       │
# │ list[i64] │
# ╞═══════════╡
# │ [1, null] │
# └───────────┘
```

Notably, `pl.Expr.list` has this behavior with `null_on_oob` `True` or `False`.

Related #11521, if this change was intentional, it could potentially still be supported if `pl.Expr` also had a `null_on_oob` option. But I don't see anything in [the release notes](https://github.com/pola-rs/polars/releases/tag/py-0.19.4) about this being a "fix" or behavior change.

### Expected behavior

```
shape: (2, 1)
┌──────┐
│ a    │
│ ---  │
│ i64  │
╞══════╡
│ 1    │
│ null │
└──────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            Linux-6.2.0-1012-azure-x86_64-with-glibc2.31
Python:              3.11.5 (main, Sep 13 2023, 17:42:58) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by orlp** [comment] 2023-10-06 10:11
I'll take a look, this should just work.

**Comment by orlp** [comment] 2023-10-06 10:14
I think this is the same bug in `BitMask::get_u32` as in my `total-ord` branch that I've already fixed locally, because I can't reproduce in my branch anymore. So this should be fixed soon.

**Comment by orlp** [comment] 2023-10-06 10:41
I pulled out the fix into a separate PR.

**Closed** 2023-10-06 11:14 UTC
Labels: bug, python
