### ISSUE TITLE
`sink_parquet` not yet supported in standard engine when using s3fs

### ISSUE THREAD

**Issue by MarceColl** [pola-rs/polars#6213] opened 2023-01-13 19:42 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Hello!

I need to be able to stream read, operate, and stream write to S3, but it seems that with the standard engine `sink_parquet` is not yet supported.

Is that something that is configurable, can I change the engine? Am I blocked? I see no mention of this in the polars documentation [here](https://pola-rs.github.io/polars/py-polars/html/reference/lazyframe/api/polars.LazyFrame.sink_parquet.html).

May be related to #6212 .

### Reproducible example

```python
Install polars and s3fs.

Setup a local minio using:


docker run -p 9000:9000 -p 9001:9001 \
  quay.io/minio/minio server /data --console-address ":9001"
```

Go to http://localhost:9001/buckets and create a bucket named testbucket and then run:
```
import polars as pl
import s3fs

conn_data = { 'key': 'minioadmin', 'secret': 'minioadmin', 'client_kwargs': { 'endpoint_url': 'http://localhost:9000' }}

fs = s3fs.S3FileSystem(**conn_data)
df = pl.DataFrame({'data': list(range(500))})

s3_path = "s3://testbucket/file.parquet"

with fs.open(s3_path, "wb") as f:
    df.write_parquet(f)

dfl = pl.scan_parquet(s3_path, storage_options=conn_data)
dfl.sink_parquet("s3://testbucket/file.parquet")
```

```
thread '<unnamed>' panicked at 'sink_parquet not yet supported in standard engine. Use 'collect().write_parquet()'', /home/runner/work/polars/polars/polars/polars-lazy/src/physical_plan/planner/lp.rs:153:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/mcoll/capchase/code/client-monorepo/apps/metrics-api/test.py", line 17, in <module>
    dfl.sink_parquet("s3://testbucket/file.parquet")
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/polars/internals/lazyframe/frame.py", line 1257, in sink_parquet
    return ldf.sink_parquet(
pyo3_runtime.PanicException: sink_parquet not yet supported in standard engine. Use 'collect().write_parquet()'
```

### Expected behavior

Being able to use `sink_parquet` to avoid `collect().write_parquet()` which as far as I know would load everything to memory, which in my case is not a possible option.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: Linux-6.1.4-arch1-1-x86_64-with-glibc2.36
Python: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.2
numpy: 1.24.1
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment] 2023-01-18 09:13
This is only supported for file systems as of now. I will close this as it is not a bug. We will expand to object stores support in the future.

**Closed by ritchie46** 2023-01-18 09:13 UTC
Labels: bug, python

**Comment by MarceColl** [comment] 2023-01-18 16:06
Okay got it!

**Comment by guzmanlopez** [comment] 2023-01-20 18:48
I tried `sink_parquet` with files in my local notebook and in some cases it works and in some cases it does not. I'm not sure, but seems it depends on the processing between the `pl.scan_parquet` and the `.sink_parquet`. Seems that some polars processing stuff is supported and other is not.

**Comment by Niladri24dutta** [comment] 2023-01-26 18:12
>I tried sink_parquet with files in my local laptop and in some cases it works and in some cases it does not. I'm not sure, but seems it depends on the processing between the pl.scan_parquet and the .sink_parquet (what happens in the middle). Seems that some polars processing stuff is supported and other is not.

@guzmanlopez I agree . I am still facing the same issue. It seems it does not work when you manipulate or split the column value before using sink_parquet. 

@ritchie46 this issue exists for file systems.
