### ISSUE TITLE
enable simd in python

### ISSUE THREAD

**Issue by l1t1** [pola-rs/polars#14895] opened 2024-03-07 10:13 UTC
### Description

I use polars python modules to query parquet files.  it isn't very fast now. 
https://docs.pola.rs/user-guide/installation/ says
nightly - Several nightly only features such as SIMD and specialization.
does it mean we can't use simd in python? if so, could the feature be added?

**Comment by s-banach** [comment] 2024-03-07 12:21
I think that’s just talking about compiling it yourself in rust. The python wheels have all that enabled.

**Comment by alexander-beedie** [comment] 2024-03-07 14:02
SIMD _is_ enabled; can you clarify what you mean about seeing a slowdown?

**Comment by l1t1** [comment] 2024-03-08 00:43
I use my parquet file(30_000_000 rows) to test,the time of group by a integer col is 3 seconds, duckdb is 0.8 seconds.
to reproduced it, I try to test a public datasets, https://datasets-documentation.s3.eu-west-3.amazonaws.com/hackernews/hacknernews.parquet'
`duckdb.sql("select id%10 a,count(1) from 'd:/hacknernews.parquet' group by a").pl()` costs 11s
but it report an error
```sql
>>> t=time.time();sql.execute("select id from pt limit 1",eager=True);print(time.time()-t)
shape: (1, 1)
┌────────┐
│ id     │
│ ---    │
│ i64    │
╞════════╡
│ 344065 │
└────────┘
0.23601341247558594
>>> t=time.time();sql.execute("select id%10 from pt limit 1",eager=True);print(time.time()-t)
shape: (1, 1)
┌─────┐
│ id  │
│ --- │
│ i64 │
╞═════╡
│ 5   │
└─────┘
0.1890106201171875
>>> t=time.time();sql.execute("select id%10 a,count(1) from pt group by id%10",eager=True);print(time.time()-t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python38\lib\site-packages\polars\sql\context.py", line 277, in execute
    return res.collect() if (eager or self._eager_execution) else res
  File "D:\Python38\lib\site-packages\polars\lazyframe\frame.py", line 1937, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: cannot aggregate a literal
```

**Comment by cmdlineluser** [comment] 2024-03-08 08:19
With regards to parquet reading, could you test again on the latest version?

There was a recent refactor of the String type (In `0.20.6` I think?) so some things are still being ironed out.

e.g. this fix is part of the `0.20.13` release:

- #14657

**Comment by cmdlineluser** [comment] 2024-03-08 08:58
As for parquet reading, could you test the latest version of Polars?

I believe there was a recent String type refactor (`0.20.6`?) so some things are still being ironed out.

e.g. this was fixed in `0.20.13`

- #14657



The SQL error seems to be caused by `count(1)` not being supported?

I recall seeing `count(*)` having a fast path recently added which I guess is equivalent:

- #14574

**Comment by l1t1** [comment] 2024-03-08 10:07
the latest version still three times slower, and I%10 returns a list instead of a integer. very strange. 
```python

D select i%10,count(*)from 'tgz.parquet'group by i%10;
┌──────────┬──────────────┐
│ (i % 10) │ count_star() │
│  int32   │    int64     │
├──────────┼──────────────┤
│        1 │     10000000 │
│        3 │     10000000 │
│        6 │     10000000 │
│        7 │     10000000 │
│        8 │     10000000 │
│        0 │      9999999 │
│        9 │     10000000 │
│        5 │     10000000 │
│        2 │     10000000 │
│        4 │     10000000 │
├──────────┴──────────────┤
│ 10 rows       2 columns │
└─────────────────────────┘
Run Time (s): real 1.332 user 9.750000 sys 0.170000
 
>>> import polars as pl
>>> df = pl.scan_parquet("tgz.parquet")
>>> sql = pl.SQLContext(pt=df)
>>> import time
>>> pl.__version__
'0.20.14'
>>> t=time.time();sql.execute("select i%10 a,count(*) from pt group by i%10",eager=True);print(time.time()-t)
shape: (10, 2)
┌─────────────┬──────────┐
│ a           ┆ len      │
│ ---         ┆ ---      │
│ list[i32]   ┆ u32      │
╞═════════════╪══════════╡
│ [9, 9, … 9] ┆ 10000000 │
│ [3, 3, … 3] ┆ 10000000 │
│ [0, 0, … 0] ┆ 9999999  │
│ [6, 6, … 6] ┆ 10000000 │
│ [7, 7, … 7] ┆ 10000000 │
│ [4, 4, … 4] ┆ 10000000 │
│ [1, 1, … 1] ┆ 10000000 │
│ [5, 5, … 5] ┆ 10000000 │
│ [8, 8, … 8] ┆ 10000000 │
│ [2, 2, … 2] ┆ 10000000 │
└─────────────┴──────────┘
5.497818470001221
```

**Comment by l1t1** [comment] 2024-03-08 10:27
if no alias a, it returns the right result and takes 3.8s. 
```
>>> t=time.time();sql.execute("select i%10,count(*) from pt group by i%10",eager=True);print(time.time()-t)
shape: (10, 2)
┌─────┬──────────┐
│ i   ┆ len      │
│ --- ┆ ---      │
│ i32 ┆ u32      │
╞═════╪══════════╡
│ 0   ┆ 9999999  │
│ 3   ┆ 10000000 │
│ 9   ┆ 10000000 │
│ 6   ┆ 10000000 │
│ 4   ┆ 10000000 │
│ 7   ┆ 10000000 │
│ 1   ┆ 10000000 │
│ 8   ┆ 10000000 │
│ 2   ┆ 10000000 │
│ 5   ┆ 10000000 │
└─────┴──────────┘
3.8595447540283203
```

**Comment by orlp** [comment] 2024-03-08 16:10
I'm closing this issue because the perceived issue (SIMD is not enabled) is not true.

Feel free to open another issue (or comment on existing issues if there are) for slow parquet reader performance compared to competitors.

**Closed by orlp** 2024-03-08 16:10 UTC
Labels: enhancement
