### ISSUE TITLE
Exposing PyDataFrame from a rust library

### ISSUE THREAD

**Issue by jmrgibson** [pola-rs/polars#4264] opened 2022-08-04 22:44 UTC
#### Describe your feature request

I have a rust application using polars & pyo3. All the data collection, processing, etc, is done in rust, but I want the ability to return a  `pl.DataFrame/PyDataFrame` to the user for interactive work in a python terminal.

Unless I'm mistaken, it's not possible to create a `PyDataFrame` from rust, because `py-polars` isn't published to crates.io.

I realize I could probably do this by calling python code from rust, I would like to avoid having to have the user install `polars` (the python library) because we already distribute our rust app as a static binary with no external dependencies.

**Comment by ritchie46** [comment] 2022-08-05 07:16
This works: https://github.com/pola-rs/polars/tree/master/examples/python_rust_compiled_function

**Comment by jg2562** [comment] 2022-08-05 11:55
I believe this is a duplicate of #1325. I will also say that the example is not really ergonomic to use and fairly brittle to lib change.

**Comment by jmrgibson** [comment] 2022-08-08 20:58
Closing as duplicate.

**Closed** 2022-08-11 23:22 UTC
Labels: feature
