### ISSUE TITLE
Inconsistent Handling of Floating Point Numbers

### ISSUE THREAD

**Issue by benjamin-edwards-ec** [pola-rs/polars#20387] opened 2024-12-20 13:19 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from polars.testing import assert_frame_equal

df1 = pl.DataFrame([2011726.72]).with_columns(pl.col("column_0") / 1000)
df2 = pl.DataFrame([2011726.72, -46997.46]).with_columns(pl.col("column_0") / 1000)

expected_df1 = pl.DataFrame([2011.72672])
expected_df2 = pl.DataFrame([2011.72672, -46.99746])

assert_frame_equal(df1, expected_df1, check_exact=True) # Passes
assert_frame_equal(df2, expected_df2, check_exact=True) # Fails
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/bedwards/.pyenv/versions/3.10.14/lib/python3.10/site-packages/polars/testing/asserts/frame.py", line 108, in assert_frame_equal
    _assert_series_values_equal(
  File "/home/bedwards/.pyenv/versions/3.10.14/lib/python3.10/site-packages/polars/testing/asserts/series.py", line 197, in _assert_series_values_equal
    raise_assertion_error(
  File "/home/bedwards/.pyenv/versions/3.10.14/lib/python3.10/site-packages/polars/testing/asserts/utils.py", line 12, in raise_assertion_error
    raise AssertionError(msg) from cause
AssertionError: Series are different (exact value mismatch)
[left]:  [2011.7267200000001, -46.99746]
[right]: [2011.72672, -46.99746]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bedwards/.pyenv/versions/3.10.14/lib/python3.10/site-packages/polars/_utils/deprecation.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/home/bedwards/.pyenv/versions/3.10.14/lib/python3.10/site-packages/polars/testing/asserts/frame.py", line 118, in assert_frame_equal
    raise_assertion_error(
  File "/home/bedwards/.pyenv/versions/3.10.14/lib/python3.10/site-packages/polars/testing/asserts/utils.py", line 12, in raise_assertion_error
    raise AssertionError(msg) from cause
AssertionError: DataFrames are different (value mismatch for column 'column_0')
[left]:  [2011.7267200000001, -46.99746]
[right]: [2011.72672, -46.99746]
```

### Issue description

With the above DataFrame examples, I am performing a simple floating-point division operation. In the first case, with `df1`, dividing `2011726.72` by 1000 yields `2011.72672`, as expected. However, in the second case, with `df2`, dividing `2011726.72` by 1000 yields `2011.7267200000001`.

While I understand that `2011.72672` cannot be represented exactly in `Float64` and some floating-point error is expected, the issue here is the inconsistency in results: the outcome of the same division operation depends on the presence of other numbers in the DataFrame. I believe this behavior is incorrect, as the operation should produce consistent results regardless of the surrounding data.

### Expected behavior

I think the result of 2011726.72 / 1000 should not be dependent on the rest of the Dataframe. Ideally I would prefer it to not have floating point error but I can always use `Decimal` if that ends up being the solution.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.17.1
Index type:          UInt32
Platform:            Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.14 (main, May  2 2024, 13:14:01) [GCC 11.4.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  0.9.0
altair               <not installed>
boto3                <not installed>
cloudpickle          3.1.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2023.10.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         <not installed>
numpy                1.26.3
openpyxl             <not installed>
pandas               2.1.4
pyarrow              18.0.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           2.0.31
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by orlp** [comment] 2024-12-20 13:55
Duplicate of https://github.com/pola-rs/polars/issues/20038#issuecomment-2545331180.

**Closed by orlp** 2024-12-20 13:55 UTC
Labels: bug, python, needs triage
