### ISSUE TITLE
Add syntactic sugar for column selection based on a boolean expression

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#11254] opened 2023-09-22 16:41 UTC
### Description

Currently, the [recommended solution](https://github.com/pola-rs/polars/issues/6895#issuecomment-1431164286) to select columns based on a boolean expression (say `pl.all().n_unique() > 1`) is:

```python
df.select([col.name for col in df.select(pl.all().n_unique() > 1) if col.item])
```

When used in a method chain, this becomes:

```python
df.pipe(lambda df: df.select([col.name for col in df.select(pl.all().n_unique() > 1) if col.item]))
```

Another option that may be more performant with lots of columns is:

```python
df.pipe(lambda df: df.select(df.select(pl.all().n_unique() > 1).melt().filter(pl.col.value)['variable'].to_list()))
```

Column selection based on a boolean mask/expression is a fairly common operation (even though it forces materialization), and I wonder if it would be worth having some syntactic sugar for it?

**Comment by cmdlineluser** [comment] 2023-09-22 17:42
There was also a recent discussion about this which may be of interest #10967

Using the example given
```python
df.select(
   col.name for col in df.select(pl.all().n_unique() > 1) 
   if col.item()
)
```
Are there any ideas/suggestions on what the improved/sugared syntax would look like?

**Comment by Wainberg** [comment] 2023-09-22 17:51
@cmdlineluser Thanks for sharing! I quite like your `.select_where()` proposal.

I noticed that @orlp commented that ["Some puritanism is sacrificed for overwhelming user demand and ease of use, such as `pivot/melt`"](https://github.com/pola-rs/polars/issues/10967#issuecomment-1710014314). I think that's very well said, and I'd argue that this is one of those special cases, as evidenced by the fact that three people have independently brought this up as an issue in just the past month (#10870, #10967, and #11254).

**Comment by cmdlineluser** [comment] 2023-09-22 18:33
Would a DataFrame method that returns a list of column names for `true` be enough sugar? 
```python
df.select(pl.all().n_unique() > 1)
# shape: (1, 3)
# ┌──────┬──────┬───────┐
# │ A    ┆ B    ┆ C     │
# │ ---  ┆ ---  ┆ ---   │
# │ bool ┆ bool ┆ bool  │
# ╞══════╪══════╪═══════╡
# │ true ┆ true ┆ false │
# └──────┴──────┴───────┘
```
For example sake, we will call it `.col_true()` (inspired by `.arg_true()` which returns indexes)
```python
df.select(pl.all().n_unique() > 1).col_true()
# ['A', 'B']
```
```python
df.select(
   df.select(pl.all().n_unique() > 1).col_true()
)
```
It could perform shape/type check e.g. `bool`, `(1, N)` similar to `.item()`.

Or perhaps there are some better ideas.

**Comment by Wainberg** [comment] 2023-09-22 18:54
I don't think that would be enough, because it still references `df` twice and therefore needs to be wrapped in `df.pipe()` for method chains. Again, this is one of the most basic operations you can do on a DataFrame, it deserves its own method.

**Comment by gab23r** [comment] 2023-09-22 19:20
Is that something we could get from the `selectors` ? @alexander-beedie

**Comment by Wainberg** [comment] 2023-09-22 19:21
Column selection based on boolean expressions isn't currently possible with selectors.

**Comment by Wainberg** [comment] 2023-09-22 19:43
I'm also a fan of calling it `.filter_columns()` instead of `.select_where()`, because it's exactly analogous to `.filter()` but for columns instead of rows.

**Comment by cmdlineluser** [comment] 2023-09-22 20:07
> it still references df twice

> it deserves its own method

Yeah, from what I understand I think one of the main issues is that a DataFrame is essentially syntactic sugar around the Lazy API.

In LazyFrame terms, you need a first `.select(expr).collect()` to: compute the expression/generate the column names (which requires consuming all the data) and then the second `.select()` to keep/filter just those columns.

In order for there to be a single method, it would require having a "hidden" `.select()` call somewhere in the background.

**Comment by Wainberg** [comment] 2023-09-22 20:11
Yeah, you'd have to materialize by calling `collect()` beforehand, just like with `melt()`, `pivot()` and `join()`.

**Comment by alexander-beedie** [comment] 2023-09-22 20:52
> Is that something we could get from the `selectors` ? @alexander-beedie

No; selectors can only work with the schema information available at the point where they are expanded internally. It would be a pretty major anti-pattern to force column materialisation in order to introspect the data. Imagine you have a few expressions doing that at different levels of the graph - you'll almost completely kill all of the enormous potential performance advantages of query planning and lazy mode just to get a bit of syntactic sugar. I don't think it's a good trade-off 😅

**Comment by Wainberg** [comment] 2023-09-22 20:54
Yes, it seems like a bad idea to interleave this with the lazy API in any way. It would have to be a DataFrame-only method, like `melt()`, `pivot()` and `join()`.

**Comment by Wainberg** [comment] 2023-09-22 20:56
To make this more concrete, here's a utility function I wrote for boolean column selection, for internal use in my lab:

```python
def filter_columns(df, boolean_expression):
    """
    Selects columns from a polars DataFrame based on a boolean expression,
    analogous to filter() but for columns instead of rows. Use it in method
    chains, e.g. df.pipe(filter_columns, pl.all().n_unique() > 1).
    See github.com/pola-rs/polars/issues/11254.
    
    Args:
        df: a polars DataFrame
        boolean_expression: the boolean expression

    Returns:
        df, filtered to the columns that are true in the boolean expression.
    """
    return df.pipe(lambda df: df.select(df.select(
        boolean_expression).melt().filter(pl.col.value)['variable'].to_list()))
```

**Comment by alexander-beedie** [comment] 2023-09-22 21:01
> Yes, it seems like a bad idea to interleave this with the lazy API in any way. It would have to be a DataFrame-only method, like `melt()`, `pivot()` and `join()`.

Join isn't DataFrame-only (and it I spossible to make a lazy pivot _IF_ you require the user to declare the end-state columns as a parameter - I currently simulate this with a lazy `group_by`) ;)

**Comment by Wainberg** [comment] 2023-09-22 21:21
Ah good point! I'd forgot LazyFrames also have `join()`.

**Comment by gab23r** [comment] 2023-09-22 22:07
Melt works in lazy mode as well 😁

**Comment by chandlerliuliu** [comment] 2023-09-23 10:37
Hello all and @Wainberg,
I was the author of the `.select_where()` proposal at https://github.com/pola-rs/polars/issues/10967.
> @cmdlineluser Thanks for sharing! I quite like your `.select_where()` proposal.

I want to first summarize the previous discussion. My argument came from the use case where users think more in terms of Pandas' OO, in other words, sometimes we would also treat columns as data. However, Polars, on the other hand, is a columnar DataFrame interface with a fast query engine with many optimizations.

I would ask @alexander-beedie @cmdlineluser or any other contributor if one can **teach the community more extensively how to think more like Polars** instead of what we are used to. For instance, when we are facing cases like multiple choice data, if we want to count the frequency of various choices, what would be a better approach instead of one-hot the multiple choice column? (perhaps an extensive tutorial on `melt` and when to use nested datatypes might be a way to eliminate the need for selecting columns based on data)

**Comment by stinodego** [comment] 2024-01-05 09:45
Closing as a duplicate of https://github.com/pola-rs/polars/issues/10967

**Closed by stinodego** 2024-01-05 09:45 UTC
Labels: enhancement
