### ISSUE TITLE
Panic when trying to use `is_unique()` in an OR condition 

### ISSUE THREAD

**Issue by florianlaws** [pola-rs/polars#8222] opened 2023-04-14 12:01 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I want to retrieve all rows from a dataframe that are  unique with respect to a subset of columns OR contain a specific value in one of the columns.
The recommendation is to not use groupby+apply, so I thought I'd try `df.is_unique()` in an OR condition together with a filter condition on the column value.

I get a "PanicException: called `Option::unwrap()` on a `None` value".

I suspect it might not be possible to combine is_unique() with another condition, and I should use something like
`foo.filter((foo.get_column("origin") == 'T') | foo.select(["company_id", "person_id","entity_type","entity_id","tr_date"]).is_unique() )` 

 but I guess I would prefer a nicer exception than a PanicException in any case.

Exception backtrace:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/work/polars/polars/polars/polars-core/src/chunked_array/object/registry.rs:80:28
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[92], line 17
      2 import datetime
      3 foo = pl.DataFrame(
      4     [
      5         pl.Series("company_id", [1, 1, 1], dtype=pl.Int64),
   (...)
     13     ]
     14 )
     16 foo.filter(
---> 17     foo.select(["company_id", "person_id","entity_type","entity_id","tr_date"]).is_unique()
     18     | (pl.col("origin") == "T")
     19 )

File /opt/conda/lib/python3.10/site-packages/polars/series/series.py:438, in Series.__or__(self, other)
    436 def __or__(self, other: Series) -> Self:
    437     if not isinstance(other, Series):
--> 438         other = Series([other])
    439     return self._from_pyseries(self._s.bitor(other._s))

File /opt/conda/lib/python3.10/site-packages/polars/series/series.py:258, in Series.__init__(self, name, values, dtype, strict, nan_to_null, dtype_if_empty)
    255     self._s = range_to_series(name, values, dtype=dtype)._s
    257 elif isinstance(values, Sequence):
--> 258     self._s = sequence_to_pyseries(
    259         name,
    260         values,
    261         dtype=dtype,
    262         strict=strict,
    263         dtype_if_empty=dtype_if_empty,
    264         nan_to_null=nan_to_null,
    265     )
    266 elif _check_for_numpy(values) and isinstance(values, np.ndarray):
    267     self._s = numpy_to_pyseries(name, values, strict, nan_to_null)

File /opt/conda/lib/python3.10/site-packages/polars/utils/_construction.py:429, in sequence_to_pyseries(name, values, dtype, strict, dtype_if_empty, nan_to_null)
    427 if constructor == PySeries.new_object:
    428     try:
--> 429         return PySeries.new_from_anyvalues(name, values, strict)
    430     # raised if we cannot convert to Wrap<AnyValue>
    431     except RuntimeError:

PanicException: called `Option::unwrap()` on a `None` value
```

### Reproducible example

```python
import polars as pl
import datetime
foo = pl.DataFrame(
    [
        pl.Series("company_id", [1, 1, 1], dtype=pl.Int64),
        pl.Series("person_id", [1, 2, 2], dtype=pl.Int64),
        pl.Series("origin", ['P', 'P', 'T'], dtype=pl.Utf8),
        pl.Series("entity_type", ['Task', 'Task', 'Task'], dtype=pl.Utf8),
        pl.Series("entity_id", [23, 23, 23], dtype=pl.Int64),
        pl.Series("tr_date", [datetime.date(2023, 2, 7), datetime.date(2023, 2, 7), datetime.date(2023, 2, 7)], dtype=pl.Date),
        pl.Series("tr_id", [25584576, 25590150, 25590134], dtype=pl.Int64),
        pl.Series("value", [None, None, 240], dtype=pl.Int64),
    ]
)

# We want all rows that are unique wrt company_id, person_id, entity_type, entity_id, and tr_date (i.e. row 1)
# and all rows where origin=="T" (i.e. row 3)

foo.filter( 
foo.select(["company_id", "person_id","entity_type","entity_id","tr_date"]).is_unique()
 | (pl.col("origin") == "T"))

# This throws PanicException: called `Option::unwrap()` on a `None` value


```
 

### Expected behavior

A dataframe that contains the first and third row of the example dataframe.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.2
Index type: UInt32
Platform: Linux-4.14.309-231.529.amzn2.x86_64-x86_64-with-glibc2.31
Python: 3.10.6 (main, Oct  7 2022, 20:19:58) [GCC 11.2.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.4.4
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2022.7.1
matplotlib: 3.5.2
xlsx2csv: <not installed>
xlsxwriter: 3.0.3```

</details>

**Comment by mcrumiller** [comment] 2023-04-14 12:22
This is unrelated to `is_unique` and is actually a duplicate of #6971 (which seems like it should have an easy fix). Currently, an expression contains a series, the series cannot come first.

You're doing the `or` operation between a series and an expression. If you re-format your code, you get this:

```python
foo.filter( 
    foo.select(["company_id", "person_id","entity_type","entity_id","tr_date"]).is_unique() |
    (pl.col("origin") == "T")
)
```

which is equivalent to:

```python
foo.filter( 
    pl.Series([True, False, True]) |
    (pl.col("origin") == "T")
)
```

You need to swap the position of your arguments, as follows:

```python
foo.filter( 
    (pl.col("origin") == "T") |
    foo.select(["company_id", "person_id","entity_type","entity_id","tr_date"]).is_unique()
)
```
```
shape: (2, 8)
┌────────────┬───────────┬────────┬─────────────┬───────────┬────────────┬──────────┬───────┐
│ company_id ┆ person_id ┆ origin ┆ entity_type ┆ entity_id ┆ tr_date    ┆ tr_id    ┆ value │
│ ---        ┆ ---       ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---      ┆ ---   │
│ i64        ┆ i64       ┆ str    ┆ str         ┆ i64       ┆ date       ┆ i64      ┆ i64   │
╞════════════╪═══════════╪════════╪═════════════╪═══════════╪════════════╪══════════╪═══════╡
│ 1          ┆ 1         ┆ P      ┆ Task        ┆ 23        ┆ 2023-02-07 ┆ 25584576 ┆ null  │
│ 1          ┆ 2         ┆ T      ┆ Task        ┆ 23        ┆ 2023-02-07 ┆ 25590134 ┆ 240   │
└────────────┴───────────┴────────┴─────────────┴───────────┴────────────┴──────────┴───────┘
```
or you can call `is_unique` in an expression context along with `pl.struct`:

```python
foo.filter( 
    pl.struct(["company_id", "person_id","entity_type","entity_id","tr_date"]).is_unique() |
    (pl.col("origin") == "T")
)
```
```
shape: (2, 8)
┌────────────┬───────────┬────────┬─────────────┬───────────┬────────────┬──────────┬───────┐
│ company_id ┆ person_id ┆ origin ┆ entity_type ┆ entity_id ┆ tr_date    ┆ tr_id    ┆ value │
│ ---        ┆ ---       ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---      ┆ ---   │
│ i64        ┆ i64       ┆ str    ┆ str         ┆ i64       ┆ date       ┆ i64      ┆ i64   │
╞════════════╪═══════════╪════════╪═════════════╪═══════════╪════════════╪══════════╪═══════╡
│ 1          ┆ 1         ┆ P      ┆ Task        ┆ 23        ┆ 2023-02-07 ┆ 25584576 ┆ null  │
│ 1          ┆ 2         ┆ T      ┆ Task        ┆ 23        ┆ 2023-02-07 ┆ 25590134 ┆ 240   │
└────────────┴───────────┴────────┴─────────────┴───────────┴────────────┴──────────┴───────┘
```

**Comment by ritchie46** [comment] 2023-04-14 12:51
On it. Thanks for the breakdown @mcrumiller

**Closed** 2023-04-14 13:30 UTC
Labels: bug, python
