### ISSUE TITLE
Unexpected results when aggregating a column with NaN and null

### ISSUE THREAD

**Issue by leesavoie-voltaiq** [pola-rs/polars#2536] opened 2022-02-03 23:06 UTC
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

Tested on 0.12.2 and 0.12.20

#### What operating system are you using polars on?

Ubuntu 16.04

#### Describe your bug.

When I take the max of a column that includes NaN and null the max is NaN, but I expect to get the maximum non-NaN non-null value.

#### What are the steps to reproduce the behavior?

```
>>> import polars as pl
>>> import numpy as np
>>> d1 = pl.DataFrame({"a": [1.1, 2.2, np.NaN]})
>>> d1.select(pl.col("a").max())
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 2.2 │
└─────┘
>>> d2 = pl.DataFrame({"a": [1.1, 2.2, None]})
>>> d2.select(pl.col("a").max())
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 2.2 │
└─────┘
>>> d3 = pl.DataFrame({"a": [1.1, 2.2, np.nan, None]})
>>> d3.select(pl.col("a").max())
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ NaN │
└─────┘
```

In the 3rd example, I expect the max from d3 to be `2.2` like it is in the other examples, but it comes out as `NaN`. If this is not correct, what is the expected/guaranteed behavior?

**Comment by ritchie46** [comment] 2022-02-04 10:31
Now that is strange. I cannot reproduce this behavior.

**Comment by leesavoie-voltaiq** [comment] 2022-02-04 18:57
Odd. I see this behavior consistently. If it makes a difference, I'm using

Polars 0.12.2
NumPy 1.16.6
Python 3.7.5

**Comment by zundertj** [comment] 2022-02-07 19:02
I cannot reproduce this either (Windows 10, Polars 0.12.20, NumPy 1.21.4, tried both Python 3.10 & Python 3.7). 

You could try upgrading NumPy to a more recent version, just to check that is not driving this behaviour, but I would be surprised if that would fix it..

**Comment by leesavoie-voltaiq** [comment] 2022-02-09 22:52
I got the same result in a different virtual environment on the same system with numpy 1.21.5. I don't have another system readily available to test on. Maybe there is something unusual about my set up.

I am able to work around this issue, so it's not urgent to get it fixed.

**Comment by cnpryer** [comment] 2022-04-08 02:24
fwiw this doesn't occur on `0.13.18` (MacOS)

**Comment by zundertj** [comment] 2022-07-22 19:02
Checked this again, this time on:
* Debian Bullseye
* polars master
* Numpy 1.23.0
* Python 3.10

and still unable to reproduce. Given that no-one has been able to reproduce in this thread, or has reported similar issues, I am closing this issue. 

Feel free to open a new issue if it occurs again.

**Closed by zundertj** 2022-07-22 19:02 UTC
Labels: bug, help wanted

**Comment by jr200** [comment] 2022-09-15 14:13
Can someone spell-out the rationale for this please...

For `d1` I expected to get `np.NaN`. My thinking is, if I apply `max` to a list I am implying there is a well-defined ordering on the list - which there isn't. So I would want the result to be `NaN`.

If I wanted to ignore nans, I could easily `.fill_nan(None)`...

**Comment by zundertj** [comment] 2022-09-17 08:15
Pandas has the convention to `skip_na=True` by default on [Series.max](https://pandas.pydata.org/docs/reference/api/pandas.Series.max.html), so there are more conventions... I think you can reason both ways. If you want to have the discussion to change this, please open a new issue, with more details on why you think it should be changed.
