### ISSUE TITLE
Infinite memory allocation when using multiple when/thens in lazyFrame

### ISSUE THREAD

**Issue by Galedon1** [pola-rs/polars#13172] opened 2023-12-21 10:04 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import matplotlib as mpl

cmap1 = mpl.colors.LinearSegmentedColormap.from_list("GreenBlue", ["limegreen", "blue"]) # signal types


lf = pl.LazyFrame(
    {
     "a": [True, False, False],
     "b": [8,-1,25],
     "c": [1.5,2.254,5.3],
     }
    )

lf = lf.with_columns(
    pl.when( 
        pl.col("a").not_()
        )
    .then(
        mpl.colors.to_rgba("r")
        )
    .when(
        pl.col("b") != -1
        )
    .then(
        (pl.col("c")/1000)
        .map_batches(lambda x: pl.Series(cmap1(x)))
        # mpl.colors.to_rgba("g")
        )
    .otherwise(
        mpl.colors.to_rgba("k")
        )
    .alias("c1"),
    )

df = lf.collect()
# ff = lf.fetch()
# ex = lf.explain()
```

### Log output

```shell
memory allocation of 24696061952 bytes failed
```

### Issue description

After upgrading to 0.20.2 I am getting an infinite memory allocation when calling .collect(), .fetch(), or .explain() on LazyFrame with multiple when/then conditions. When I comment one of the conditions out, everything works. 
It also works well for "standard" conditions, but not for the matplotlib mapping of colors as shown in the MWE.

### Expected behavior

It worked well in 0.19.?? version. 

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Windows-10-10.0.22621-SP0
Python:               3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  0.7.0
cloudpickle:          2.2.1
connectorx:           0.3.2
deltalake:            0.12.0
fsspec:               2023.5.0
gevent:               23.9.1
matplotlib:           3.7.1
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.0.2
pyarrow:              12.0.0
pydantic:             2.4.2
pyiceberg:            0.5.0
pyxlsb:               <not installed>
sqlalchemy:           2.0.20
xlsx2csv:             0.8.1
xlsxwriter:           3.1.2
```

</details>

**Comment by cmdlineluser** [comment] 2023-12-21 11:01
This also panics on a non-release build

```rust
thread '<unnamed>' panicked at crates/polars-core/src/chunked_array/cast.rs:472:5:
assertion `left == right` failed
  left: Float64
 right: Unknown
```

It seems to be the `.map_batches`

Not sure what changed exactly, but it goes away if you set `return_dtype=` or add `.cast(pl.List(pl.Float64))`

**Comment by deanm0000** [comment] 2023-12-21 15:30
That's really weird. One way around it is to make temp columns first and then have the returns be those columns like this

```
(
    lf.lazy()
    .with_columns(
        r=pl.lit(mpl.colors.to_rgba("r")), 
        k=pl.lit(mpl.colors.to_rgba("k")),
        cmap=pl.col('c').truediv(1000)
            .map_batches(lambda x: (
                pl.Series(cmap1(x))
            ))
    )
    .with_columns(
    pl.when(pl.col("a").not_())
    .then("r")
    .when(pl.col("b") != -1)
    .then("cmap")
    .otherwise("k")
    .alias("c1")
    )
    .drop('r','k','cmap')
    .collect()
    )
```

It may seem like it has to do more work this way but when/then/otherwise always runs all the values through all the conditions and then chooses which to return. In this case I don't know why this works but having `map_batches` in a `then` doesn't but it shouldn't make it slower.

Another way to deal with the issue is to wrap all your when/thens into a coalesce block like this:

```
df.with_columns(
    pl.coalesce(
        pl.when(pl.col("a").not_())
            .then(mpl.colors.to_rgba("r")),
        pl.when(pl.col("b") != -1)
            .then(
            (pl.col("c")/1000)
            .map_batches(lambda x: pl.Series(cmap1(x)))
            ),
        mpl.colors.to_rgba("k")
        )
    .alias("c1"),
    )
```

As a tangent, if you have a when/then where under one condition it does an expensive operation but the other operation is cheap and you want to prevent it from running the expensive operation on all the values then you have to split up the df into those parts. One way would be like this (this is really hacky looking):

```
df.group_by('a','b').map_groups(lambda x: (
    x.with_columns(
        c=mpl.colors.to_rgba('r')
    ) if not x['a'][0] else (
    x.with_columns(
        c=pl.col('c').truediv(1000).map_batches( lambda c: (
            pl.Series(cmap1(c))))
    ) if x['b'][0]!=-1 else (
    x.with_columns(
        c=mpl.colors.to_rgba('k'))
    ))
))
```

it works with lazy too but you have to give it the output schema as a parameter of `map_groups`

**Comment by cmdlineluser** [comment] 2023-12-21 19:12
It's something to do with type inference on the `.map_batches`

It runs if you set the type

```python
lf = lf.with_columns(
    pl.when( pl.col("a").not_() )
      .then( mpl.colors.to_rgba("r") )
      .when( pl.col("b") != -1 )
      .then( 
          (pl.col("c") / 1000).map_batches(lambda x: pl.Series(cmap1(x))) 
          .cast(pl.List(pl.Float64))
      )
      .otherwise( mpl.colors.to_rgba("k") )
      .alias("c1"),
)
```

Although I'm not sure what changed between `0.19.19` and `0.20.0` to cause a difference in behaviour.

**Comment by ritchie46** [comment] 2023-12-22 09:50
This should be fixed. But note that we consider it a bug in a query if a user doesn't produce an output dtype in map_batches.

**Closed** 2023-12-22 10:25 UTC
Labels: bug, python
