### ISSUE TITLE
`.implode().list` method  is not valid before `.over`.

### ISSUE THREAD

**Issue by PierXuY** [pola-rs/polars#18225] opened 2024-08-16 02:41 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    'type': ['water','fire','water','earth']
})


out1 = df.select(
    pl.col('type').implode().over("type", mapping_strategy="explode").list.first()
)
print(out1)

# shape: (3, 1)
# ┌───────┐
# │ type  │
# │ ---   │
# │ str   │
# ╞═══════╡
# │ water │
# │ fire  │
# │ earth │
# └───────┘

# The code above works, but the expression below that I think is equivalent throws an error.

out2 = df.select(
    pl.col('type').implode().list.first().over("type", mapping_strategy="explode")
)
print(out2)
# InvalidOperationError: 'implode' followed by an aggregation is not allowed
```

### Issue description

The example is from another [issue](https://github.com/pola-rs/polars/issues/8967), and according to the issue, this expression was legal in earlier versions of polars.

In addition, the error reported in the current polars version is also confusing. 
In code that works fine:
```python
out1 = df.select(
    pl.col('type').implode().over("type", mapping_strategy="explode").list.first()
)
print(out1)
```
'implode' followed by an aggregation is allowed. 

But another code `pl.col('type').implode().list.first().over("type", mapping_strategy="explode")` reports an error: `InvalidOperationError: 'implode' followed by an aggregation is not allowed`. 

### Expected behavior

I think both expressions should be able to execute normally. If the error code is unreasonable, there should be a more accurate error message.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  1.1.0
cloudpickle:          3.0.0
connectorx:           0.3.3
deltalake:            0.19.0
fastexcel:            0.11.5
fsspec:               2024.6.1
gevent:               24.2.1
great_tables:         0.10.0
hvplot:               0.10.0
matplotlib:           3.9.2
nest_asyncio:         1.6.0
numpy:                2.0.1
openpyxl:             3.1.5
pandas:               2.2.2
pyarrow:              17.0.0
pydantic:             2.8.2
pyiceberg:            0.7.0
sqlalchemy:           2.0.32
torch:                <not installed>
xlsx2csv:             0.8.3
xlsxwriter:           3.2.0
```

</details>

**Comment by ritchie46** [comment] 2024-08-16 07:21
It is not a bug, we don't allow this operation, hence the error.

**Comment by PierXuY** [comment] 2024-08-16 09:12
> It is not a bug, we don't allow this operation, hence the error.

 It seems that #18228 is related to this reason.

**Comment by ritchie46** [comment] 2024-08-16 09:14
Yes, that one is the samse story. Not allowed for now. There is complexity in that, that I don't want to get into for now.

**Comment by ritchie46** [comment] 2024-08-18 09:01
I will close this as this is not a bug.

**Closed by ritchie46** 2024-08-18 09:01 UTC
Labels: bug, python, needs triage
