### ISSUE TITLE
Can we create a .collect method for polars.DataFrame?

### ISSUE THREAD

**Issue by phucb2** [pola-rs/polars#19995] opened 2024-11-26 10:06 UTC
### Description

Currently, polars.DataFrame and polars.LazyFrame have few different methods implementation for example .collect() Is it possible to make this method to easier switching between lazy and eager mode

**Comment by cmdlineluser** [comment] 2024-11-26 10:14
Relevant: https://github.com/pola-rs/polars/issues/7882#issuecomment-1616683055

**Comment by nameexhaustion** [comment] 2024-11-26 10:36
Duplicate of https://github.com/pola-rs/polars/issues/19548

**Closed by nameexhaustion** 2024-11-26 10:36 UTC
Labels: enhancement
