### ISSUE TITLE
regex filtering + grouped n_unique computation is very slow on glob of parquet files and crashes in polars 0.20

### ISSUE THREAD

**Issue by cpcloud** [pola-rs/polars#13127] opened 2023-12-19 12:51 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I don't have a copy-pastable example, but I did write a blog post comparing Ibis + DuckDB to Ibis + Polars, and Polars native API showing some stark differences in performance between DuckDB and Polars for this query.

Blog post: https://ibis-project.org/posts/pydata-performance-part2/

### Issue description

The Ibis + Polars and the Polars native query from the linked blog post (https://ibis-project.org/posts/pydata-performance-part2/) are very slow relative to DuckDB.

Not sure why this happens, but I thought I'd raise it here in case there's a known issue.

Notably I cannot use `streaming=False` or else the entire thing runs out of memory.

As of Polars 0.20 though both `streaming=True` and `streaming=False` run out of memory and cause the process to crash.

Happy to provide more information as needed!

### Expected behavior

I would expect Polars to be at least as fast as DuckDB given the value proposition. If it can't be as fast, I would still expect it to not crash by running out of memory.

### Installed versions

At the time of publishing the post the versions of things I used are listed there.

I ran this [`polars_native.py`](https://github.com/ibis-project/ibis/blob/36e1db56b59e6ca6f2851fd81b996ee095273284/docs/posts/pydata-performance-part2/datafusion_ibis.py) code against polars 0.20, and it seems things have gotten worse: Even when setting `streaming=True` Polars causes the process to get OOM-killed by the kernel and crashes.

The machine specs are the same as in the blog post.

Below are the latest versions I ran that code with.

<details>

```
--------Version info---------
Polars:               0.20.0
Index type:           UInt32
Platform:             Linux-6.1.68-x86_64-with-glibc2.38
Python:               3.10.13 (main, Aug 24 2023, 12:59:26) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            0.14.0
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              14.0.1
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.50
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment] 2023-12-19 13:33
Files: https://github.com/pypi-data/data/releases/tag/2023-12-18-03-06

It seems they are DeltaByteArray encoded which was recently added: https://github.com/pola-rs/polars/pull/12602

Using the smallest file as an example: index-14.parquet 

<details><summary>pypi-stats-duckdb.py</summary>

```python
import duckdb

print(

duckdb.sql("""
FROM 'index-14.parquet'
SELECT 
  datetrunc('month', uploaded_on) AS month,
  regexp_extract(path, '\.([a-z0-9]+)$', 1)
    .regexp_replace('cxx|cpp|cc|c|hpp|h', 'C/C++')
    .regexp_replace('^f.*$', 'Fortran')
    .replace('rs', 'Rust')
    .replace('go', 'Go')
    .replace('asm', 'Assembly') AS ext,

  COUNT(DISTINCT project_name) AS projects

WHERE (
  regexp_matches(path, '\.(asm|c|cc|cpp|cxx|h|hpp|rs|[Ff][0-9]{0,2}(?:or)?|go)$')
  AND NOT regexp_matches(path, '(^|/)test(s|ing)')
  AND NOT contains(path, '/site-packages/')
)
GROUP BY month, ext
ORDER BY month, projects DESC;
""").pl()

)
```

</details>

<details><summary>pypi-stats-polars.py</summary>

```python
import polars as pl

expr = (
    pl.scan_parquet("index-14.parquet")
    .filter(
        [
            pl.col("path").str.contains(
                r"\.(asm|c|cc|cpp|cxx|h|hpp|rs|[Ff][0-9]{0,2}(?:or)?|go)$"
            ),
            ~pl.col("path").str.contains(r"(^|/)test(s|ing)"),
            ~pl.col("path").str.contains("/site-packages/", literal=True),
        ]
    )
    .with_columns(
        month=pl.col("uploaded_on").dt.truncate("1mo"),
        ext=pl.col("path")
        .str.extract(pattern=r"\.([a-z0-9]+)$", group_index=1)
        .str.replace_all(pattern=r"cxx|cpp|cc|c|hpp|h", value="C/C++")
        .str.replace_all(pattern="^f.*$", value="Fortran")
        .str.replace("rs", "Rust", literal=True)
        .str.replace("go", "Go", literal=True)
        .str.replace("asm", "Assembly", literal=True)
        .replace({"": None}),
    )
    .group_by("month", "ext")
    .agg(project_count=pl.col("project_name").n_unique())
    .drop_nulls("ext")
    .sort(["month", "project_count"], descending=True)
)

print(expr.collect(streaming=True))
```

</details>

Name|Time|Memory
:-|:-|:-
duckdb|4.97s|0.7GB
polars|14.70s|4.6GB

With DuckDB all my cores are utilized 100% for the entire runtime. (according to htop)

Polars initially does for a second but then it seems to just utilize a single core.

**Comment by ritchie46** [comment] 2023-12-19 15:46
Thanks @cmdlineluser. Will take a look.

**Comment by ritchie46** [comment] 2023-12-19 17:04
> I would expect Polars to be at least as fast as DuckDB given the value proposition.

It all depends right? We don't claim to be faster (on all fronts)? In any case. Polars is first and foremost designed for in-memory use. We are adding support for streaming, but that engine is far from finished nor our desired performance.

What I assume here is that you go OOM and you swap. I cannot load the smallest file in memory (32GB) as it explodes due to its encoding. This is not polars specific. This also happens with pyarrow. The file leads to many string bytes.

Secondly,  The thing that is costly is arrow strings. This is something I am not happy with and something that we will address in the future. Arrow string types require a lot of byte copying when you do a filter or a gather. DuckDB strings are not arrow strings. They are inlined (or heap allocated somewhere else) and only need to copy a fixed (small) set of bytes. Polars will add support for the new arrow StringView which was designed to mitigate this problem.

Thirdly the regex of duckdb and polars are not equally expensive as polars defaults to unicode aware regexes (which can be orders of magnitudes slower). See discussion here: https://github.com/pola-rs/polars/issues/5613#issuecomment-1327495576

Here is the interesting part of the flamegraph: 
![image](https://github.com/pola-rs/polars/assets/3023000/fd28f6d2-b19f-4714-8f1d-14d2eb2ab2f3)


Almost all time is in the filter (and page faults) do to bytes copying due to arrow string types. This will get better. It is on our roadmap. ;)

**Comment by cpcloud** [comment] 2023-12-19 17:24
> Polars is first and foremost designed for in-memory use

I think my expectations were based on this

![image](https://github.com/pola-rs/polars/assets/417981/6e7b4cf0-cba3-4501-830f-84b30839557c)

How should I adjust my expectations about what should or shouldn't work when dealing with larger than memory datasets.

> What I assume here is that you go OOM and you swap.

No, I don't have swap enabled. The process is killed by the operating system.

> I cannot load the smallest file in memory (32GB) as it explodes due to its encoding. This is not polars specific. This also happens with pyarrow. The file leads to many string bytes.

Sure, but I'm just trying to run a query without running out of memory. As a user, the last thing I would do is try to load any of the files directly into memory.

> This will get better. It is on our roadmap. ;)

Wonderful!

**Comment by ritchie46** [comment] 2023-12-19 17:55
> I think my expectations were based on this

Hmm.. technically it isn't wrong (it is our goal), though I am surprised it states it as a done deal. It's mostly a hybrid engine where parts can be done out-of-core. The `n_unique` isn't supported in our streaming engine. So only the `filter` and `with_columns` run streaming in this case. 

Both datafusion and polars use arrow strings that's why you see comparable results here. Not happy with that string type...

**Comment by cpcloud** [comment] 2023-12-19 18:34
Good call on the unicode regexen! I hadn't considered that.

Seems like the dominating cost is allocation related, so I'll look out for that.

**Comment by cmdlineluser** [comment] 2024-04-13 21:39
I just tried this again after updating to the new version of Polars.

Using one of the files from: https://github.com/pypi-data/data/releases

Version|Time (seconds)
:-|:-
Polars 0.20.0|169.37382
Polars 0.20.20|14.70309
DuckDB 0.10.2-dev311|10.54572

Memory usage for Polars is pretty much the same in both versions.

I'm not sure how that translates to your overall benchmark, but there seems to besome significant improvements on the speed side of things.

**Comment by ritchie46** [comment] 2024-04-14 07:51
Yes, I think we can close this. The pathological string cases have been resolved. The memory will be improved later. We are designing a completely new streaming engine that will be able to run the whole Polars API, but that's still in the works.

**Closed by ritchie46** 2024-04-14 07:51 UTC
Labels: bug, python, needs triage
