### ISSUE TITLE
Type Checking Expression [Python]

### ISSUE THREAD

**Issue by UlvFoerlev** [pola-rs/polars#6908] opened 2023-02-15 14:51 UTC
### Problem description

I want to be able to test column types via polars expressions, so that I don't need to apply a python function. Say, I have a series of an unknown type. This could be a date column, that is sometimes linux timestamp ints, date string, or just a pl.Dates, I can't currently test it via polars without doing row-wise checks.

What I'd like to be able to do
```
(
  pl.when(pl.col("date").is_type(str))
 .then(pl.col("date").str.strptime(pl.Date, fmt="%Y-%m-%d"))
 .when(pl.col("date").is_type(int))
 .then(pl.from_epoch(pl.col("date"), unit="ms"))
 .otherwise(pl.col("date").cast(pl.Date))
)
 ```
 
 Currently I have to do something like this:
  ```
 def cast_dates(x):
        # isoformat date string
        if isinstance(x, str):
            return datetime.strptime(x, '%Y-%m-%d').date()
            return x.str.strptime(pl.Date, fmt="%Y-%m-%d")

        # linux timestamp
        if isinstance(x, int):
            return datetime.fromtimestamp(x / 1000).date()
            pl.from_epoch(x, unit="ms")

        return date(x)
 
 ...
   
  pl.col("date").apply(cast_dates)
  
 ```
 

 I don't know if this is possible (or feasible), but it would help a lot with casting, especially as I'm importing from json.

**Comment by mcrumiller** [comment] 2023-02-15 15:20
This is a duplicate of #4982 which has been hanging out for a while.

**Closed** 2023-02-15 15:31 UTC
Labels: enhancement

**Comment by cmdlineluser** [comment] 2023-02-15 15:41
Could you replace `.apply` with: https://github.com/pola-rs/polars/issues/2716#issuecomment-1046311564
```
dates = 1676473581, "2023-02-15", datetime.date(2023, 2, 15)

for _date in dates:
   (pl.DataFrame({"date": [_date]})
      .with_columns(pl.col("date").cast(pl.Utf8))
      .with_columns(
         pl.col("date")
           .str.strptime(pl.Date, fmt="%Y-%m-%d", strict=False)
           .fill_null(pl.col("date").str.strptime(pl.Datetime("ms"), fmt="%s", strict=False))
           .cast(pl.Date)))
```
```
shape: (1, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │
╞════════════╡
│ 2023-02-15 │
└────────────┘
shape: (1, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │
╞════════════╡
│ 2023-02-15 │
└────────────┘
shape: (1, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │
╞════════════╡
│ 2023-02-15 │
└────────────┘
```
