### ISSUE TITLE
fetch() and collect() returns different result on an aggregated DF

### ISSUE THREAD

**Issue by kylejhchen** [pola-rs/polars#1982] opened 2021-12-04 13:41 UTC
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.10.26

#### What operating system are you using polars on?

MacOS (& CentOS 7)

#### Describe your bug.

fetch() and collect() returns different results on an aggregated LazyFrame.

#### What are the steps to reproduce the behavior?

**Example**

```python
# System info
import polars as pl
import numpy as np
import sys
print(pl.__version__)
print(np.__version__)
print(sys.platform)


# Create a simple dataset on which we can reproduce the bug.
# 100,000 rows, store as parquet file for Reading
pl.DataFrame({
    'a_int': range(100000), 
    'b_str': list('abcdefghij'*10000),
    'c_float': np.linspace(1, 100, 100000),
             }
).to_parquet('test.parquet')

# Inconsistent results
print('non-lazy')
print(
    pl.read_parquet('test.parquet')
    .select(pl.count('a_int').alias('row_count'))
)

print('with LazyFrame.collect()')
print(
    pl.scan_parquet('test.parquet',)
    .select(pl.count('a_int').alias('row_count'))
    .collect()
)
print('with LazyFrame.fetch()')
print(
    pl.scan_parquet('test.parquet',)
    .select(pl.count('a_int').alias('row_count'))
    .fetch()
)
```

#### What is the actual behavior?

```
0.10.26
1.21.4
darwin

non-lazy
shape: (1, 1)
┌───────────┐
│ row_count │
│ ---       │
│ u32       │
╞═══════════╡
│ 100000    │
└───────────┘
with LazyFrame.collect()
shape: (1, 1)
┌───────────┐
│ row_count │
│ ---       │
│ u32       │
╞═══════════╡
│ 100000    │
└───────────┘
with LazyFrame.fetch()
shape: (1, 1)
┌───────────┐
│ row_count │
│ ---       │
│ u32       │
╞═══════════╡
│ 500       │
└───────────┘
```

#### What is the expected behavior?

LazyFrame.fetch has default `n_rows: int = 500`. However, this example is fetching an aggregated result of 1 row, where the answer should be 100,000. It seems that the query plan for fetch() truncates the data at the first step, so the pl.count() gets only 500 as a result.
I could reproduce this behavior on both MacOS and CentOS 7.

If my understanding of using fetch() is not correct. It's appreciated if you can correct my example.

**Comment by ritchie46** [comment] 2021-12-04 13:49
Yes, that's exactly what ferches do. It reads only n rows from the file into the query plan.

It's use case is to run queries on a subset of the data.

**Comment by ritchie46** [comment] 2021-12-05 09:37
I will close this, because this expected behavior.

**Closed by ritchie46** 2021-12-05 09:37 UTC
