### ISSUE TITLE
Allow passing `Expr` to numpy functions

### ISSUE THREAD

**Issue by foster999** [pola-rs/polars#11604] opened 2023-10-09 08:30 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Doesn't work:
```python
import polars as pl
import numpy as np

df = pl.DataFrame(
    {"independent": [510, 1000, 1795], "dependent": [1.5, 2.7, 4.3]}
)
target_independent = pl.Series(values=np.around(np.linspace(510, 1795, num=1011), 4))

df_interpolated = df.select(
    target_independent.alias("new_independent"),
    np.interp(target_independent, pl.col("independent"), pl.col("dependent")).alias("new_dependent")
)
print(df_interpolated)
```

Works:
```python
import polars as pl
import numpy as np

df = pl.DataFrame(
    {"independent": [510, 1000, 1795], "dependent": [1.5, 2.7, 4.3]}
)
target_independent = pl.Series(values=np.around(np.linspace(510, 1795, num=1011), 4))

df_interpolated = df.select(
    target_independent.alias("new_independent"),
    pl.Series(np.interp(target_independent, df["independent"], df["dependent"])).alias("new_dependent")
)
print(df_interpolated)
```

### Log output

```shell
Traceback (most recent call last):
  File "signal_processing.py", line 34, in <module>
    np.interp(target_independent, pl.col("independent"), pl.col("dependent")).alias("new_dependent")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/numpy/lib/function_base.py", line 1599, in interp
    return interp_func(x, xp, fp, left, right)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: object of too small depth for desired array
```

### Issue description

When attempting to use a non-ufunc numpy function, passing `Expr`s using `pl.col` seems to give a multidimensional arrays to numpy. While passing sliced `Series` works as expected, giving numpy a 1-D array. `Expr` behaviour is the same for `DataFrame` and `LazyFrame`.

### Expected behavior

Expect that using `pl.col` to pass a single column `Expr` to numpy gives a 1-D array.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            macOS-14.0-arm64-arm-64bit
Python:              3.11.4 (main, Jul 18 2023, 13:23:55) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

**Comment by stinodego** [comment] 2023-10-09 09:54
Not sure why you would expect that passing an Expr to numpy would work? We have implemented some magic to make this work for Series (they are arrays too), but an Expression is not.

If anything, this is a feature request and not a bug.

**Comment by ritchie46** [comment] 2023-10-09 10:09
> We do not want to do that implicitly.

We also cannot do that. What data would be evaluated at that point? I don't think this makes sense.

**Comment by foster999** [comment] 2023-10-09 10:12
I tried via Expressions because [using numpy ufuncs follows that approach](https://pola-rs.github.io/polars/user-guide/expressions/numpy/). But the issues is that the error from numpy implies that the expression is being evaluated to something that numpy can use (just the wrong shape)

Thanks, I think this was down to my lack of understanding behind the intention of using expressions vs series. Would it be more suitable to suggest a method like `LazyFrame.get_columns()` to conveniently and explicitly get Series from a LazyFrame?

**Comment by stinodego** [comment] 2023-10-09 10:16
> get_columns

Simply use `.select("a", "b").collect()`.

I'll close this for now.

**Closed by stinodego** 2023-10-09 10:16 UTC
Labels: python, enhancement

**Comment by deanm0000** [comment] 2023-10-09 14:23
@foster999 Not every np function is a ufunc. Interpolate isn't one of them. As you can read about on the numpy page, ufuncs have special properties that make them work. There are a handful of questions on SO interpolation. [This one](https://stackoverflow.com/a/77100065/1818713) has a polars expression based function to interpolate at the bottom.
