### ISSUE TITLE
Add drop_first argument to .to_dummies()

### ISSUE THREAD

**Issue by MariusMerkleQC** [pola-rs/polars#9483] opened 2023-06-21 15:06 UTC
### Problem description

When one hot encoding categorical features with [pandas](https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html), it is possible to drop the first column corresponding to one of the categories by specifying `drop_first = True`. 

I wish the function [`to_dummies`](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.to_dummies.html) would also have such an argument. Otherwise correlated features are created and one of the columns needs to be dropped manually.

**Comment by avimallu** [comment] 2023-06-21 15:32
Duplicate of https://github.com/pola-rs/polars/issues/8246, with a PR to close in #9143.

**Comment by alexander-beedie** [comment] 2023-06-22 20:11
https://github.com/pola-rs/polars/pull/9143 should merge soon, so will close this in the meantime.

**Closed by alexander-beedie** 2023-06-22 20:11 UTC
Labels: enhancement
