### ISSUE TITLE
map_dict(..., default=pl.first()) keeps the wrong column

### ISSUE THREAD

**Issue by stfdxv** [pola-rs/polars#15079] opened 2024-03-15 03:18 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"a": [1.0], "b": [2.0], "c": [3.0]})
df = df.with_columns(
    pl.col("c").map_dict({float("inf"): None}, default=pl.first()).alias("mapped_c")
)
print(df)

```

### Log output

```shell
no error
```

### Issue description

Since polars==0.20.0 `map_dict(some_dict, default=pl.first())` replaces the values, which are not in `some_dict`, with the values of an irrelevant column.
```
┌─────┬─────┬─────┬──────────┐
│ a   ┆ b   ┆ c   ┆ mapped_c │
│ --- ┆ --- ┆ --- ┆ ---      │
│ f64 ┆ f64 ┆ f64 ┆ f64      │
╞═════╪═════╪═════╪══════════╡
│ 1.0 ┆ 2.0 ┆ 3.0 ┆ 1.0      │
└─────┴─────┴─────┴──────────┘
```

### Expected behavior

`mapped_c` should be equal to 3.0 instead of 1.0.
```
┌─────┬─────┬─────┬──────────┐
│ a   ┆ b   ┆ c   ┆ mapped_c │
│ --- ┆ --- ┆ --- ┆ ---      │
│ f64 ┆ f64 ┆ f64 ┆ f64      │
╞═════╪═════╪═════╪══════════╡
│ 1.0 ┆ 2.0 ┆ 3.0 ┆ 3.0      │
└─────┴─────┴─────┴──────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16-rc.1
Index type:           UInt32
Platform:             Windows-10-10.0.19041-SP0
Python:               3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.1.1
pyarrow:              13.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by JulianCologne** [comment] 2024-03-15 06:55
can reproduce!

@stfdxv when you run your code you should get a warning that `map_dict` is deprecated
> DeprecationWarning: `map_dict` is deprecated. It has been renamed to `replace`.

It works with the new `replace` method
```python
pl.DataFrame({"a": [1], "b": [2], "c": [3]}).with_columns(
    c_mapped=pl.col("c").map_dict({0: 100}, default=pl.first()),
    c_replaced=pl.col("c").replace({0: 100}),
)

# shape: (1, 5)
# ┌─────┬─────┬─────┬──────────┬────────────┐
# │ a   ┆ b   ┆ c   ┆ c_mapped ┆ c_replaced │
# │ --- ┆ --- ┆ --- ┆ ---      ┆ ---        │
# │ i64 ┆ i64 ┆ i64 ┆ i64      ┆ i64        │
# ╞═════╪═════╪═════╪══════════╪════════════╡
# │ 1   ┆ 2   ┆ 3   ┆ 1        ┆ 3          │
# └─────┴─────┴─────┴──────────┴────────────┘
```

**Comment by stfdxv** [comment] 2024-03-15 07:05
@JulianCologne Yes, but see my next issue #15081.
In fact I had to dig through my code to get to the root problem. Only then I saw the description of map_dict() in my IDE saying it's deprecated.

**Comment by stinodego** [comment] 2024-03-15 14:51
Since `replace` works correctly, I would like to refrain from changing the functionality of a deprecated method. So I'm closing this. Please use `replace` instead!

**Closed by stinodego** 2024-03-15 14:51 UTC
Labels: bug, python, needs triage
