### ISSUE TITLE
The starts_with method unavailable with "strings" feature

### ISSUE THREAD

**Issue by ecashin** [pola-rs/polars#7474] opened 2023-03-10 13:56 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

The `starts_with` method is made available by opting into the "strings" feature, but only Python tests and examples illustrate its use.  When attempting to make a mask for use in a filter, the compiler reports that the method is not available.

### Reproducible example

An attempt to mirror the examples using `.gt()`, etc., ...

```
bash$ nl -b a Cargo.toml 
     1  [package]
     2  name = "eg"
     3  version = "0.1.0"
     4  edition = "2021"
     5
     6  # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
     7
     8  [dependencies]
     9  anyhow = "1.0.69"
    10  polars = { version = "0.27.2", features = ["strings"] }
bash$ nl -b a src/main.rs 
     1  use anyhow::Result;
     2  use polars::prelude::*;
     3
     4  fn main() -> Result<()> {
     5      let b = Series::new("b", ["one", "two", "three", "four"]);
     6      let result = b.starts_with("t");
     7      println!("{result:?}");
     8      Ok(())
     9  }
bash$ cargo clippy
    Checking eg v0.1.0 (/home/ecashin/src/rust/try-polars-starts_with/eg)
error[E0599]: no method named `starts_with` found for struct `polars::prelude::Series` in the current scope
 --> src/main.rs:6:20
  |
6 |     let result = b.starts_with("t");
  |                    ^^^^^^^^^^^ help: there is a method with a similar name: `sort_with`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `eg` due to previous error
bash$ 
```

### Expected behavior

I expected `.starts_with` to be an available method like `.gt` or `.equal`, but for columns that contain `str` data, when the "strings" feature has been activated.

### Installed versions

<details>
strings
</details>

**Comment by ecashin** [comment] 2023-03-11 00:42
One can do it manually as a workaround, as shown below, but I'm still interested in whether this is a bug or something that could be documented a bit.

```
bash$ nl -b a src/main.rs
     1  use anyhow::Result;
     2  use polars::prelude::*;
     3
     4  fn main() -> Result<()> {
     5      let b = Utf8Chunked::new(
     6          "b",
     7          [Some("one"), Some("thrice"), Some("three"), Some("four")],
     8      );
     9      let mask: BooleanChunked = b
    10          .into_iter()
    11          .map(|v| match v {
    12              Some(s) => s.starts_with("th"),
    13              None => false,
    14          })
    15          .collect();
    16      println!("{mask:?}");
    17      Ok(())
    18  }
bash$ 
```

**Comment by ritchie46** [comment] 2023-03-11 06:40
In rust this is only meant to be used on the expression layer. You are working with direct `Utf8CHunked` arrays which are seen as low level.

**Comment by ritchie46** [comment] 2023-03-11 11:34
I will close this as this is not a bug and intended to only be available on the expression API.

**Closed by ritchie46** 2023-03-11 11:34 UTC
Labels: bug, rust

**Comment by ecashin** [comment] 2023-03-11 12:57
> In rust this is only meant to be used on the expression layer. You are working with direct `Utf8Chunked` arrays which are seen as low level.
> 
> If you are not using the expressions/lazyframe API an `apply` seems fine. +1

Hang on---The docs don't make that clear at all.  The expression API is only documented with examples in Python, and I only turned to the chunked array because I couldn't find a way to use the high-level way in Rust.

Am I wrong?  I think either there's a bug in the documentation or the code, so if the code's OK, then the documentation could use text and examples explaining how Rust programmers can do the same thing that the Python examples show.

```
bash$ nl -b a src/main.rs
     1  use anyhow::Result;
     2  use polars::prelude::*;
     3
     4  fn main() -> Result<()> {
     5      let a = Series::new("a", [1, 2, 3, 4]);
     6      let b = Series::new("b", ["one", "two", "three", "four"]);
     7      let df = DataFrame::new(vec![a, b])?.filter(col("b").starts_with("t"));
     8      println!("{df:?}");
     9      Ok(())
    10  }
bash$ cargo run
   Compiling eg v0.1.0 (/home/ecashin/src/rust/try-polars-starts_with/eg)
error[E0425]: cannot find function `col` in this scope
 --> src/main.rs:7:49
  |
7 |     let df = DataFrame::new(vec![a, b])?.filter(col("b").starts_with("t"));
  |                                                 ^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `eg` due to previous error
bash$ grep polars Cargo.toml 
polars = { version = "0.27.2", features = ["strings"] }
bash$ 
```

[The docs](https://docs.rs/polars/latest/polars/prelude/fn.col.html) say `col` is in the `polars::prelude::*`, but although that's imported, `col` isn't in scope.

**Comment by ritchie46** [comment] 2023-03-11 13:22
You must activate the lazy feature

**Comment by ecashin** [comment] 2023-03-11 13:29
> You must activate the lazy feature

Thank you.  I think [the docs for col](https://docs.rs/polars/0.27.2/polars/prelude/fn.col.html) should say that, but anyway, activating lazy reveals the problem persists in the expression API.

```
bash$ cargo run
   Compiling polars v0.27.2
   Compiling polars-lazy v0.27.2
   Compiling eg v0.1.0 (/home/ecashin/src/rust/try-polars-starts_with/eg)
error[E0599]: no method named `starts_with` found for enum `Expr` in the current scope
 --> src/main.rs:7:58
  |
7 |     let df = DataFrame::new(vec![a, b])?.filter(col("b").starts_with("t"));
  |                                                          ^^^^^^^^^^^ help: there is a method with a similar name: `sort_with`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `eg` due to previous error
bash$ grep polars Cargo.toml 
polars = { version = "0.27.2", features = ["strings", "lazy"] }
bash$ 
```

**Comment by ecashin** [comment] 2023-03-11 15:34
This issue is closed and has several distracting tangents that will be great for people who search for similar problems but which are not needed for the main issue, so I'll create a new issue that is more specific.

**Comment by ecashin** [comment] 2023-03-11 15:47
If I activate the `lazy` feature and remember to `.str()` to get the strings namespace, and I use the expression API, it is incompatible with the `.filter` that I need to use.

How can I filter on the expression?  This type mismatch is the reason I started looking at the `.column` and the `ChunkedArray` solution mentioned above.

```
bash$ cargo run
   Compiling eg v0.1.0 (/home/ecashin/src/rust/try-polars-starts_with/eg)
error[E0308]: mismatched types
    --> src/main.rs:7:49
     |
7    |     let df = DataFrame::new(vec![a, b])?.filter(col("b").str().starts_with(lit("t")));
     |                                          ------ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found enum `Expr`
     |                                          |
     |                                          arguments to this function are incorrect
     |
     = note: expected reference `&ChunkedArray<BooleanType>`
                     found enum `Expr`
note: associated function defined here
    --> /home/ecashin/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.27.2/src/frame/mod.rs:1592:12
     |
1592 |     pub fn filter(&self, mask: &BooleanChunked) -> PolarsResult<Self> {
     |            ^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `eg` due to previous error
bash$ 
```

**Comment by ecashin** [comment] 2023-03-11 23:18
I think you have to explicitly make the `DataFrame` into a `LazyFrame` with `.lazy()` as well:

```
bash$ cargo run
   Compiling eg v0.1.0 (/home/ecashin/src/rust/try-polars-starts_with/eg)
    Finished dev [unoptimized + debuginfo] target(s) in 21.55s
     Running `target/debug/eg`
Ok(shape: (2, 2)
┌─────┬───────┐
│ a   ┆ b     │
│ --- ┆ ---   │
│ i32 ┆ str   │
╞═════╪═══════╡
│ 2   ┆ two   │
│ 3   ┆ three │
└─────┴───────┘)
bash$ diff -u src/main.rs.20230311_3 src/main.rs
--- src/main.rs.20230311_3      2023-03-11 18:14:13.526560553 -0500
+++ src/main.rs 2023-03-11 18:15:35.648861238 -0500
@@ -1,10 +1,14 @@
 use anyhow::Result;
+use polars::lazy::prelude::*;
 use polars::prelude::*;
 
 fn main() -> Result<()> {
     let a = Series::new("a", [1, 2, 3, 4]);
     let b = Series::new("b", ["one", "two", "three", "four"]);
-    let df = DataFrame::new(vec![a, b])?.filter(col("b").str().starts_with(lit("t")));
+    let df = DataFrame::new(vec![a, b])?
+        .lazy()
+        .filter(col("b").str().starts_with(lit("t")))
+        .collect();
     println!("{df:?}");
     Ok(())
 }
bash$ 
```
