### ISSUE TITLE
allow interval parameter for pl.datetime_ranges to be a pl.col

### ISSUE THREAD

**Issue by claysmyth** [pola-rs/polars#15270] opened 2024-03-24 22:34 UTC
### Description

Per documentation on `datetime_ranges`:

https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.datetime_ranges.html

The `interval` parameter must be a time delta. I would be nice if the `interval` parameter could also be a column corresponding to time deltas (or strings of time deltas), so that a datetime range could be performed row-wise for differing time deltas.

example usage would be in screenshot:

![image](https://github.com/pola-rs/polars/assets/39106407/55fa9994-171e-40ae-8d61-89a745dfcb8f)

**Comment by stinodego** [comment] 2024-03-24 22:50
Thanks for making an issue, but this is a duplicate of #12987

**Closed by stinodego** 2024-03-24 22:50 UTC
Labels: enhancement
