### ISSUE TITLE
Cannot construct PySeries with explicit dtype pl.List

### ISSUE THREAD

**Issue by thomasaarholt** [pola-rs/polars#2768] opened 2022-02-24 20:19 UTC
#### What language are you using?
Python

#### What version of polars are you using?
0.13.5

#### What operating system are you using polars on?

Debian 10 in Docker on an M1 Mac

#### What language version are you using
Python 3.9

#### Describe your bug.

I cannot construct a Series with dtype pl.List.

```
>>> pl.Series("a", [[1,2,3], [3,4,5]])
shape: (2,)
Series: 'a' [list]
[
	[1, 2, 3]
	[3, 4, 5]
]

>>>  pl.Series("a", [[1,2,3], [3,4,5]]).dtype
polars.datatypes.List

>>> pl.Series("a", [[1,2,3], [3,4,5]]).dtype is pl.List
True

>>> pl.Series("a", [[1,2,3], [3,4,5]], dtype=pl.List)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File /usr/local/lib/python3.9/site-packages/polars/datatypes_constructor.py:65, in polars_type_to_constructor(dtype)
     [64](file:///usr/local/lib/python3.9/site-packages/polars/datatypes_constructor.py?line=63)[ try:
---> ]()[65](file:///usr/local/lib/python3.9/site-packages/polars/datatypes_constructor.py?line=64)[     return _POLARS_TYPE_TO_CONSTRUCTOR[dtype]
     ]()[66](file:///usr/local/lib/python3.9/site-packages/polars/datatypes_constructor.py?line=65)[ except KeyError:  # pragma: no cover

KeyError: <class 'polars.datatypes.List'>

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/fabrica/projects/geocalendar/Untitled.ipynb Cell 8' in <module>
----> ]()[1](vscode-notebook-cell://attached-container%2B7b22636f6e7461696e65724e616d65223a222f67656f63616c656e646172227d/fabrica/projects/geocalendar/Untitled.ipynb#ch0000009vscode-remote?line=0)[ pl.Series("a", [[1,2,3], [3,4,5]], dtype=pl.List)

File /usr/local/lib/python3.9/site-packages/polars/internals/series.py:223, in Series.__init__(self, name, values, dtype, strict, nan_to_null)
    ]()[221](file:///usr/local/lib/python3.9/site-packages/polars/internals/series.py?line=220)[     self._s = numpy_to_pyseries(name, values, strict, nan_to_null)
    ]()[222](file:///usr/local/lib/python3.9/site-packages/polars/internals/series.py?line=221)[ elif isinstance(values, Sequence):
--> ]()[223](file:///usr/local/lib/python3.9/site-packages/polars/internals/series.py?line=222)[     self._s = sequence_to_pyseries(name, values, dtype=dtype, strict=strict)
    ]()[224](file:///usr/local/lib/python3.9/site-packages/polars/internals/series.py?line=223)[ elif _PANDAS_AVAILABLE and isinstance(values, (pd.Series, pd.DatetimeIndex)):
    ]()[225](file:///usr/local/lib/python3.9/site-packages/polars/internals/series.py?line=224)[     self._s = pandas_to_pyseries(name, values)

File /usr/local/lib/python3.9/site-packages/polars/internals/construction.py:127, in sequence_to_pyseries(name, values, dtype, strict)
    ]()[124](file:///usr/local/lib/python3.9/site-packages/polars/internals/construction.py?line=123)[     dtype = Float32
    ]()[126](file:///usr/local/lib/python3.9/site-packages/polars/internals/construction.py?line=125)[ if dtype is not None:
--> ]()[127](file:///usr/local/lib/python3.9/site-packages/polars/internals/construction.py?line=126)[     constructor = polars_type_to_constructor(dtype)
    ]()[128](file:///usr/local/lib/python3.9/site-packages/polars/internals/construction.py?line=127)[     pyseries = constructor(name, values, strict)
    ]()[130](file:///usr/local/lib/python3.9/site-packages/polars/internals/construction.py?line=129)[     if dtype in (Date, Datetime, Duration, Time, Categorical):

File /usr/local/lib/python3.9/site-packages/polars/datatypes_constructor.py:67, in polars_type_to_constructor(dtype)
     ]()[65](file:///usr/local/lib/python3.9/site-packages/polars/datatypes_constructor.py?line=64)[     return _POLARS_TYPE_TO_CONSTRUCTOR[dtype]
     ]()[66](file:///usr/local/lib/python3.9/site-packages/polars/datatypes_constructor.py?line=65)[ except KeyError:  # pragma: no cover
---> ]()[67](file:///usr/local/lib/python3.9/site-packages/polars/datatypes_constructor.py?line=66)[     raise ValueError(f"Cannot construct PySeries for type {dtype}.")

ValueError: Cannot construct PySeries for type <class 'polars.datatypes.List'>.]()
```

Using `list` as the dtype yields a similar error:
`[ValueError: Cannot construct PySeries for type <class 'list'>.]()`

#### What are the steps to reproduce the behavior?

```python
import polars as pl
pl.Series("a", [[1,2,3], [3,4,5]], dtype=pl.List)
```

**Comment by ritchie46** [comment] 2022-02-24 21:02
You must install pyarrow. This is an optional dependency. Duplicate of #2725.

**Closed by ritchie46** 2022-02-24 21:02 UTC
