### ISSUE TITLE
Allow operation with nested polars DataFrame

### ISSUE THREAD

**Issue by dafxy** [pola-rs/polars#18591] opened 2024-09-06 16:30 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from statsmodels.formula.api import ols as lm
from plotnine.data import mtcars
import polars as pl

# data
mtcars = pl.from_pandas(mtcars)
mtcars

# this works well, but requires going back and forth from structure to dataframes
covars = ['disp', 'hp']
mtcars_nested = (mtcars
                 .group_by('cyl')
                 .agg(
                     data      = pl.struct(covars).map_elements(lambda cols:  cols),
                     data_tidy = pl.struct(covars).map_elements(lambda cols: pl.DataFrame(cols))) 
                 )
mtcars_nested


# this works well, but require converting back and forth from struct to datafram
(mtcars_nested
 .with_columns(fit = pl.struct('data').map_elements(lambda row: lm('disp~hp', data=pl.DataFrame(row['data'])).fit() ))
 )

# this gives an error, but it is a much better design for many (!) reasons (I could elaborate on why, if needed), and follows a tidy principle
(mtcars_nested
 .with_columns(fit = pl.struct('data_tidy').map_elements(lambda row: lm('disp~hp', data=row['data_tidy']).fit() ))
 )






```

### Log output

```shell
    .with_columns(fit = pl.struct('data_tidy').map_elements(lambda row: lm('disp~hp', data=row['data_tidy']).fit() ))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
line 9046, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 line 2034, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: nested objects are not allowed
```

### Issue description

The problem is that poalrs is not allowing to perform operations when there are some type of data structure nested, except when the nested type is struct. This is quite inconvenient. It would be much better if it allowed using nested dataframes, following the tidy principle.

### Expected behavior

Allow rowwise operation with nested objects, such as nested polars dataframes

### Installed versions

<details>

```
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            Linux-6.5.0-44-generic-x86_64-with-glibc2.38
Python:              3.11.6 (main, Apr 10 2024, 17:26:07) [GCC 13.2.0]

----Optional dependencies----
adbc_driver_manager  1.1.0
altair               5.4.1
cloudpickle          3.0.0
connectorx           0.3.3
deltalake            0.19.1
fastexcel            0.11.6
fsspec               2024.6.1
gevent               24.2.1
great_tables         0.10.0
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.1.0
openpyxl             3.1.5
pandas               2.2.2
pyarrow              17.0.0
pydantic             2.8.2
pyiceberg            0.7.1
sqlalchemy           2.0.32
torch                2.4.0+cu121
xlsx2csv             0.8.3
xlsxwriter           3.2.0
```

</details>

**Comment by cmdlineluser** [comment] 2024-09-06 16:42
The problem is `data_tidy` has the dtype `object` (which is basically unusable).
```python
>>> mtcars_nested
shape: (3, 3)
┌─────┬─────────────────────────────────┬──────────────────┐
│ cyl ┆ data                            ┆ data_tidy        │
│ --- ┆ ---                             ┆ ---              │
│ i64 ┆ list[struct[2]]                 ┆ object           │ # <-
```

Trying to create a struct with that dtype is causing the error:

```python
pl.select(pl.struct(pl.lit(None, dtype=pl.Object)))
# InvalidOperationError: nested objects are not allowed
```

Polars doesn't allow you to store nested frames, you'd usually do `pl.DataFrame(cols).to_struct()` to allow it to be unpacked into lists/structs.

**Comment by ritchie46** [comment] 2024-09-07 09:37
This is also something we don't want to support. Using Polars supported types, lists, structs and arrays is the strategy you need to take.

I will close this as there is no bug on our side here .

**Closed by ritchie46** 2024-09-07 09:37 UTC
Labels: bug, python, needs triage

**Comment by dafxy** [comment] 2024-09-07 14:03
This is unfortunate. But thanks.

**Comment by dafxy** [comment] 2024-09-07 19:32
@ritchie46, this should be reopened. I think @cmdlineluser is partially correct. We cannot do anything with it because you imposed restrictions on the nested structure passed to pl. strict. But the `object` type is quite usable and useful in many cases. An example is below.

Is there any reason not to allow nested structures to be passed with `pl.struct()`? It was allowed in previous versions. Wouldn't it be better to enable nested DataFrames or general objects within `pl.struct`? It would avoid confusion, and you may lose many users with that restriction.

To elaborate, you are allowing `map_elements()` to be applied to nested DataFrame (pl.Object with `pl.col()`, but not with `pl.struct()`. See the case studies below. I think this is just poor design, and it makes things very confusing for users. Just allow the user to pass whatever to `pl.struct()`, and the user can decide which function to apply to those structures.

The example.

``` python
from plotnine.data import mtcars
from polars.selectors import *
import polars as pl
import numpy as np
from statsmodels.formula.api import ols as lm


df = pl.DataFrame(mtcars)

def multiply_by_100(df):
    df = df.with_columns(pl.col('gear')*100)
    return df

def multiply_by_100_return_struct(row):
    cyl = row['cyl']
    df = pl.DataFrame(row['data']) # <-- we have to apply this extra step everytime...
    if cyl == 4:
        df = df.with_columns(gear=pl.col('gear')*100)
    else:
        df = df.with_columns(gear=pl.col('gear')/100)
    df = df.to_struct()           # <-- ... and this one too
    return df

def multiply_by_100_return_DF(row):
    cyl = row['cyl']
    df = pl.DataFrame(row['data']) # <-- we have to apply this extra step everytime...
    if cyl == 4:
        df = df.with_columns(gear=pl.col('gear')*100)
    else:
        df = df.with_columns(gear=pl.col('gear')/100)
    return df


# Case 1 : using a nested structure
# ------
# ERROR: cannot return a struct....
#        we CAN pass data in struct format (nested) and cyl (not nested) to pl.struct(), but CANNOT return a struct !
tab = (df
       .group_by('cyl')
       .agg(data = pl.struct(matches("gear|am|carb")).map_elements(lambda cols: cols))
       .with_columns(data2 = pl.struct(['data', 'cyl']).map_elements(lambda d: multiply_by_100_return_struct(d)))
 )
tab
# polars.exceptions.ComputeError: ComputeError: dtypes don't match, got struct[4], expected: struct[4]


# WORKS: 
#        we CAN pass data in struct format (nested) and cyl (not nested) to pl.struct, and CAN return a pl.DataFrame !
tab = (df
       .group_by('cyl')
       .agg(data = pl.struct(matches("gear|am|carb")).map_elements(lambda cols: cols))
       .with_columns(data2 = pl.struct(['data', 'cyl']).map_elements(lambda d: multiply_by_100_return_DF(d)))
 )
tab

# but it creates a problem because now we cannot use 'data2' with pl.struct, because it is a DF (object), not a struct
tab = (df
       .group_by('cyl')
       .agg(data = pl.struct(matches("gear|am|carb")).map_elements(lambda cols: cols))
       .with_columns(data2 = pl.struct(['data', 'cyl']).map_elements(lambda d: multiply_by_100_return_DF(d)))
       .with_columns(data3 = pl.struct(['data2', 'cyl']).map_elements(lambda d: multiply_by_100_return_DF(d))) # <- ERROR nested objects are not allowed
 )
tab


# Case 2 : using a nested data frame
# ------
# ERROR: polars.exceptions.InvalidOperationError:
#        We CANNOT pass polars DataFrame (nested) and cyl (not nested) to pl.struct!
tab = (df
       .group_by('cyl')
       .agg(data = pl.struct(matches("gear|am|carb")).map_elements(lambda cols: pl.DataFrame(cols)))
       .with_columns(data2 = pl.struct(['data', 'cyl']).map_elements(lambda d: multiply_by_100(d)))
 )
tab


# WORKS: nested DataFrame with pl.col() and map_elements()
#        We CAN pass polars DataFrame (nested) to pl.col and apply a function to it!
tab = (df
       .group_by('cyl')
       .agg(data = pl.struct(matches("gear|am|carb")).map_elements(lambda cols: pl.DataFrame(cols.to_list())))
       .with_columns(data2 = pl.col('data').map_elements(lambda d: multiply_by_100(d)))
 )
tab

# but then, again, we cannot pass data2 in pd.struct()



# IDEAL CASE:
# Allowing nested DF and non-nested columns to be used with pl.struct would be
# trememdously useful to avoid converting the nested column back and forth from
# struct to DF

# And this would also be quite valuable for the data science community used to
# work with tidy data and fit objects

# Example of ideal case:


def estimate(row):
    model = row['model']
    data  = pl.DataFrame(row['data'])
    fit = lm(model, data=data).fit()
    return fit

def summarize_col(row):
    summ = row.summary2().tables[1].reset_index(drop=False)
    return summ
    
    
# ERROR: b/c data is a DF, but this should work
tab = (df
       .group_by('cyl')
       .agg(data = pl.struct(matches("gear|am|carb")).map_elements(lambda cols: pl.DataFrame(cols.to_list())))
       .with_columns(model = (pl
                              .when(pl.col('cyl')==4)
                              .then(pl.lit("am ~ gear"))
                              .when(pl.col('cyl')==6)
                              .then(pl.lit("am ~ gear + carb"))
                              .when(pl.col('cyl')==8)
                              .then(pl.lit("am ~ gear + carb + gear * carb"))
                              .otherwise(np.nan)
                              )
                     )
       .with_columns(fit = pl.struct(['data', 'model']).map_elements(lambda row: estimate(row)))
 )
tab


# This works, but with an annoying warning and we now have a "Object" res returned,
# it is nested, and we cannot pass that to pl.struct anymore
tab = (df
       .group_by('cyl')
       .agg(data = pl.struct(matches("gear|am|carb")).map_elements(lambda cols: cols))
       .with_columns(model = (pl
                              .when(pl.col('cyl')==4)
                              .then(pl.lit("am ~ gear"))
                              .when(pl.col('cyl')==6)
                              .then(pl.lit("am ~ gear + carb"))
                              .when(pl.col('cyl')==8)
                              .then(pl.lit("am ~ gear + carb + gear * carb"))
                              .otherwise(np.nan)
                              )
                     )
       .with_columns(fit = pl.struct(['data', 'model']).map_elements(lambda row: estimate(row)))
 )
tab

# this works
(tab
 .with_columns(summ = pl.col(['fit']).map_elements(lambda fit: summarize_col(fit)))
 )

# this gives an error (polars.exceptions.InvalidOperationError: nested objects are not allowed)
(tab
 .with_columns(summ = pl.struct(['fit', 'cyl']).map_elements(lambda fit: summarize(fit)))
 )

# I want to pass the fit object with other nested or non-nested columns
# to manipulate it. It is currently impossible to do it.

```

**Comment by ritchie46** [comment] 2024-09-08 08:19
As it is now:

What we allow is an `Object` column. You can put into `Object` anything you want, but at the cost of Polars knowing anything about this `Object`. If you want to interact with this object type, you must apply python functions (e.g. via `map_elements`).

We don't allow you to put `Object` in our Polars structures (`List`, `Struct`), (there is 1 exception for list, but that doesn't matter in this discussion). We don't allow this, because it is super costly and invasive as we are not dealing with POD (plain old data) anymore, but with arbitrary reference counted nested python objects. They need to be free'ed, we need the GIL when interacting with them (which means we can deadlock at any point in the code), and we need to recursively free all those objects at any time.

If we support nested objects in structs we need to complicate our code base, and it will create all kinds of problems. For this reason I want `Object` to stay global.

If you want to combine `Object` columns, you have to do that "locally" in python. 


```python
df = pl.DataFrame(
    {
        "a": [1, 2, 3, 4],
        "b": [4, 5, 6, 7],
        "c": [1, 2, 3, 4],
    }
)

class Foo:
    def __init__(self, v: int):
        self.v = v
        

# Create two object columns
df1 = df.with_columns(
    pl.col("a", "b").map_elements(lambda x: Foo(x))
)

# combine objects in a single column
s = pl.Series(Foo(a.v + b.v) for a, b in zip(df1["a"], df1["b"]))

```

**Comment by dafxy** [comment] 2024-09-09 00:12
But you do allow `Object` in `pl.col()`

We can do:

```
.with_columns(new_col = pl.col(<generic object column>).map_elements(my_func)
```

But we cannot do:
```
.with_columns(new_col = pl.<col/struct>(<generic object column>, <str col>, <int col>,...).map_elements(my_func)
```

That is, we can pass the `Object` type to `pl.col()`, but then we cannot pass it together with any other columns of the DF, like Int, str, float, or whatever.

At a bare minimum, it would be extremely helpful to have _some method_ to do this:

```
.with_columns(new_col = pl.<some method>(<generic object column>, <str col>, <int col>,...).map_elements(lambda row: my_func(row)
```

Is this possible?

**Comment by cmdlineluser** [comment] 2024-09-11 11:26
I think Ritchie's second paragraph is explaining why it is not possible:

> We don't allow this, because… 
> it is super costly
> need to be free'ed
> need the GIL 
> can deadlock at any point

To emulate `map_elements` with object + non-object columns, you could use `map_groups` (with the row number as the group)

```python
df = pl.DataFrame({
    "foo": ["a", "b"],
    "bar": [1, 2]
}, schema={"foo": pl.Object, "bar": pl.Int64})

df.with_columns(
    pl.map_groups(["foo", "bar"], lambda s: f"{s[0][0]}{s[1][0]}")
      .over(pl.int_range(pl.len()))
      .alias("baz")
)

# shape: (2, 3)
# ┌────────┬─────┬─────┐
# │ foo    ┆ bar ┆ baz │
# │ ---    ┆ --- ┆ --- │
# │ object ┆ i64 ┆ str │
# ╞════════╪═════╪═════╡
# │ a      ┆ 1   ┆ a1  │
# │ b      ┆ 2   ┆ b2  │
# └────────┴─────┴─────┘
```

But it's probably not something to be recommended.

**Comment by dafxy** [comment] 2024-09-11 15:31
I see. The function `over()` forces a row-wise operation over the DataFrame, then. It would be good to have a dedicated function to run this row-wise, like `.map_rows(<obj> , <non-obj>,...], lamda row: ...)`. This would make the code more intuitive, but `map_groups()` + `over()` runs in parallel, so it should do.

Thanks for the work you are putting into developing this package. It is faster than the alternatives indeed, and I hope you guys continue to develop it and communicate with the community to hear how you could make the package more useful for a broader set of users.
