### ISSUE TITLE
Lazy Frame cache doesn't work

### ISSUE THREAD

**Issue by kdcd** [pola-rs/polars#4380] opened 2022-08-12 12:55 UTC
#### What language are you using?

**Python**

#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

polars-0.14.0

#### What operating system are you using polars on?

Ubuntu 20.04.3 LTS

#### What language version are you using
python 3.10.5

#### Describe your bug.

After reading documentation I thought that if in execution plan of several lazy frames mark common part as cache it should be calculated only once, but after calling this method common part was calculated multiple times. 

#### What are the steps to reproduce the behavior?

```python
import numpy as np
import polars as pl

size = 10000000
df = pl.DataFrame({"a": np.random.randint(100, size = size), "b": np.random.randint(10, size = size)})

```

```python
%%time
ldf = df.lazy()
ldf = ldf.with_columns([
    pl.col("a").rolling_median(i) for i in range(10, 500, 10)
]).cache()
r = ldf.collect()
```

    CPU times: user 1min 8s, sys: 4.23 s, total: 1min 13s
    Wall time: 3.53 s

```python
%%time
r = pl.collect_all([
    ldf.filter(pl.col("b") == 0),
    ldf.filter(pl.col("b") == 1),
    ldf.filter(pl.col("b") == 2),
])
```

    CPU times: user 3min 29s, sys: 8.18 s, total: 3min 37s
    Wall time: 9.77 s

**Comment by ritchie46** [comment] 2022-08-12 13:54
That's not what cache are aimed to achieve. See: https://github.com/pola-rs/polars/issues/2842#issuecomment-1060999566

If you want to cache/materialize a result you can collect to a DataFrame.

**Comment by ritchie46** [comment] 2022-08-13 12:06
I will close this as this is not a bug.

**Closed by ritchie46** 2022-08-13 12:06 UTC
Labels: bug

**Comment by kdcd** [comment] 2022-08-14 11:58
Sorry for bothering, just completely got it wrong.
