### ISSUE TITLE
Roundtripping to parquet mangles Enums to Categoricals

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13918] opened 2024-01-23 02:39 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import io
import polars as pl
df = pl.DataFrame({'enum_col': ['hello', 'world']}, schema={'enum_col': pl.Enum(['hello', 'world'])})
f = io.BytesIO()
df.write_parquet(f)
f.seek(0)
df = pl.read_parquet(f)
print(df.dtypes)  # [Categorical(ordering='physical')]
```

### Issue description

Writing DataFrames with Enum columns to Parquet, and then reading them back, results in the Enums being converted to Categoricals.

### Expected behavior

All types should be preserved.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.5
Index type:           UInt32
Platform:             Linux-4.4.0-22621-Microsoft-x86_64-with-glibc2.35
Python:               3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.3
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by stinodego** [comment] 2024-01-23 07:34
Duplicate of [#13262](https://github.com/pola-rs/polars/issues/13262)

**Closed by stinodego** 2024-01-23 07:34 UTC
Labels: bug, python, needs triage
