### ISSUE TITLE
dataframe creation using datetime package has issues with dtype

### ISSUE THREAD

**Issue by laakejs** [pola-rs/polars#935] opened 2021-07-06 13:09 UTC
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.8.8

#### What operating system are you using polars on?

Python 3.6.9 on Ubuntu 18.04 (WSL)

#### Describe your bug.

I try to construct a polars Dataframe with datetime objects that can be sometimes null. However, I fail to construct a proper example df. Either the type is object, or the resulting values are all null.
Am I missing something, or is this a bug?

#### What are the steps to reproduce the behavior?

```python
import polars as pl
from datetime import datetime
# df construction v1
df = pl.DataFrame(
    {
        "nrs": [1, 2, 3, 4],
        "dates": [datetime(2021,1,1), datetime(2021,1,2),datetime(2021,1,3), datetime(2021,1,4)],
        "dates_with_none": [datetime(2021,1,1), datetime(2021,1,2), datetime(2021,1,3), None],
    }
)
print(df)
# df construction v2
df2 = pl.DataFrame(
    [
        pl.Series(name="nrs", values=[1,2,3,4], dtype=pl.Int64),
        pl.Series(name="dates", values=[datetime(2021,1,1), datetime(2021,1,2),datetime(2021,1,3), None], dtype=pl.Date64), 
        pl.Series(name="dates_with_none", values=[datetime(2021,1,1), datetime(2021,1,2),datetime(2021,1,3), datetime(2021,1,4)], dtype=pl.Date64)   
    ]
)
print(df2)
# try to add a proper column
print(df.with_column(pl.Series(name="test2", values=[datetime(2021,1,1), datetime(2021,1,2),datetime(2021,1,3), None])))
# manually define the dtype 
print(df.with_column(pl.Series(name="test", values=[datetime(2021,1,1), datetime(2021,1,2),datetime(2021,1,3), None], dtype=pl.Date64)))
# attempt to cast afterwards results in an error
# ->  RuntimeError: Any(InvalidOperation("cannot cast array of type ObjectChunked to arrow datatype"))
print(df.with_column(col("dates").cast(pl.Date64)))
```

#### What is the actual behavior?

```
shape: (4, 3)
╭─────┬─────────────────────┬─────────────────────╮
│ nrs ┆ dates               ┆ dates_with_none     │
│ --- ┆ ---                 ┆ ---                 │
│ i64 ┆ object              ┆ object              │
╞═════╪═════════════════════╪═════════════════════╡
│ 1   ┆ 2021-01-01 00:00:00 ┆ 2021-01-01 00:00:00 │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 2021-01-02 00:00:00 ┆ 2021-01-02 00:00:00 │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 2021-01-03 00:00:00 ┆ 2021-01-03 00:00:00 │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 4   ┆ 2021-01-04 00:00:00 ┆ None                │
╰─────┴─────────────────────┴─────────────────────╯
shape: (4, 3)
╭─────┬────────────┬─────────────────╮
│ nrs ┆ dates      ┆ dates_with_none │
│ --- ┆ ---        ┆ ---             │
│ i64 ┆ date64(ms) ┆ date64(ms)      │
╞═════╪════════════╪═════════════════╡
│ 1   ┆ null       ┆ null            │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ null       ┆ null            │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ null       ┆ null            │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 4   ┆ null       ┆ null            │
╰─────┴────────────┴─────────────────╯
shape: (4, 4)
╭─────┬─────────────────────┬─────────────────────┬─────────────────────╮
│ nrs ┆ dates               ┆ dates_with_none     ┆ test2               │
│ --- ┆ ---                 ┆ ---                 ┆ ---                 │
│ i64 ┆ object              ┆ object              ┆ object              │
╞═════╪═════════════════════╪═════════════════════╪═════════════════════╡
│ 1   ┆ 2021-01-01 00:00:00 ┆ 2021-01-01 00:00:00 ┆ 2021-01-01 00:00:00 │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 2021-01-02 00:00:00 ┆ 2021-01-02 00:00:00 ┆ 2021-01-02 00:00:00 │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 2021-01-03 00:00:00 ┆ 2021-01-03 00:00:00 ┆ 2021-01-03 00:00:00 │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 4   ┆ 2021-01-04 00:00:00 ┆ None                ┆ None                │
╰─────┴─────────────────────┴─────────────────────┴─────────────────────╯
shape: (4, 4)
╭─────┬─────────────────────┬─────────────────────┬────────────╮
│ nrs ┆ dates               ┆ dates_with_none     ┆ test       │
│ --- ┆ ---                 ┆ ---                 ┆ ---        │
│ i64 ┆ object              ┆ object              ┆ date64(ms) │
╞═════╪═════════════════════╪═════════════════════╪════════════╡
│ 1   ┆ 2021-01-01 00:00:00 ┆ 2021-01-01 00:00:00 ┆ null       │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 2021-01-02 00:00:00 ┆ 2021-01-02 00:00:00 ┆ null       │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 2021-01-03 00:00:00 ┆ 2021-01-03 00:00:00 ┆ null       │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 4   ┆ 2021-01-04 00:00:00 ┆ None                ┆ null       │
╰─────┴─────────────────────┴─────────────────────┴────────────╯
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-55-6433cf8e527a> in <module>
     25 # attempt to cast afterwards results in an error
     26 # ->  RuntimeError: Any(InvalidOperation("cannot cast array of type ObjectChunked to arrow datatype"))
---> 27 print(df.with_column(col("dates").cast(pl.Date64)))
     28 
     29 

~/tvnow/polars_playground/.venv/lib/python3.6/site-packages/polars/frame.py in with_column(self, column)
   1462         """
   1463         if _is_expr(column):
-> 1464             return self.with_columns([column])
   1465         return wrap_df(self._df.with_column(column._s))
   1466 

~/tvnow/polars_playground/.venv/lib/python3.6/site-packages/polars/frame.py in with_columns(self, exprs)
   1736             self.lazy()
   1737             .with_columns(exprs)
-> 1738             .collect(no_optimization=True, string_cache=False)
   1739         )
   1740 

~/tvnow/polars_playground/.venv/lib/python3.6/site-packages/polars/lazy/__init__.py in collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache, no_optimization)
    335             string_cache,
    336         )
--> 337         return wrap_df(ldf.collect())
    338 
    339     def fetch(

RuntimeError: Any(InvalidOperation("cannot cast array of type ObjectChunked to arrow datatype"))
```

#### What is the expected behavior?

```
╭─────┬─────────────────────┬─────────────────────╮
│ nrs ┆ dates               ┆ dates_with_none     │
│ --- ┆ ---                 ┆ ---                 │
│ i64 ┆ date64(ms)          ┆ date64(ms)          │
╞═════╪═════════════════════╪═════════════════════╡
│ 1   ┆ 2021-01-01 00:00:00 ┆ 2021-01-01 00:00:00 │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ 2021-01-02 00:00:00 ┆ 2021-01-02 00:00:00 │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3   ┆ 2021-01-03 00:00:00 ┆ 2021-01-03 00:00:00 │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 4   ┆ 2021-01-04 00:00:00 ┆ None                │
╰─────┴─────────────────────┴─────────────────────╯
```

**Comment by ritchie46** [comment] 2021-07-06 13:27
Its not a bug, we don't introspect python objects. But I will make it easier to construct a `Date64` from python datetimes.

For now you can convert the datetimes to timestamps in `ms` and cast the timestamps to `Date64`.

`list(map(lambda dt: int(dt.timestamp() * 1000), [datetime(2021,1,1), datetime(2021,1,2),datetime(2021,1,3), datetime(2021,1,4)])`


Then I will add utility to deal with python native datetime objects. :+1:

**Comment by ritchie46** [comment] 2021-07-06 13:39
An easier solution would be going via pyarrow:

```
a = pa.array([datetime(2021,1,1), datetime(2021,1,2),datetime(2021,1,3), datetime(2021,1,4, 12, 12), None])
pl.from_arrow(a)
```

```
shape: (5,)
Series: '' [date64]
[
	2021-01-01 00:00:00
	2021-01-02 00:00:00
	2021-01-03 00:00:00
	2021-01-04 12:12:00
	null
]
```

**Comment by laakejs** [comment] 2021-07-06 13:59
The latter one looks good to me, however I would use the from_arrow version of Series, so I can assign a column name.
`pl.Series.from_arrow(name="true_dates",  array=pa.array([datetime(2021,1,1), datetime(2021,1,2),datetime(2021,1,3), None]))   `

**Comment by laakejs** [comment] 2021-07-06 14:09
@ritchie46 Shall I close this Issue, or do you want to keep it as a reminder to make it easier to construct a Date64 from python datetimes?

**Comment by ritchie46** [comment] 2021-07-06 14:37
Keep it open. I will close it friday. Then I will have released the beforementioned utility.

**Comment by ritchie46** [comment] 2021-07-09 11:29
Fixed and released :+1:

**Closed by ritchie46** 2021-07-09 11:29 UTC
