### ISSUE TITLE
Cannot read s3 without .with_streaming(true)

### ISSUE THREAD

**Issue by elbaro** [pola-rs/polars#6694] opened 2023-02-05 19:25 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

polars tries to read a s3 file from the local filesystem when with_streaming(true) is not set.

### Reproducible example

```rs
let df = LazyFrame::scan_parquet("s3://a/b/c.parquet", args)?;
let df = df.with_streaming(true).select(&[col("key")]).first().collect();
```

works, but without with_streaming(true), polars panics.

```rs
let df = LazyFrame::scan_parquet("s3://a/b/c.parquet", args)?;
let df = df.select(&[col("key")]).first().collect(); // read local filesystem, panics
```

The stacktrace shows it ended up in a local filesystem.

```rs
#[cfg(any(feature = "ipc", feature = "parquet"))]
fn prepare_scan_args(
    path: &std::path::Path,
    predicate: &Option<Arc<dyn PhysicalExpr>>,
    with_columns: &mut Option<Arc<Vec<String>>>,
    schema: &mut SchemaRef,
    n_rows: Option<usize>,
) -> (std::fs::File, Projection, StopNRows, Predicate) {
    let file = std::fs::File::open(path).unwrap();
```

```
: polars_lazy::physical_plan::executors::scan::prepare_scan_args
             at .cargo/git/checkouts/polars-b0d90607192fd414/5bd7318/polars/polars-lazy/src/physical_plan/executors/scan/mod.rs:47:16
   5: polars_lazy::physical_plan::executors::scan::parquet::ParquetExec::read
             at .cargo/git/checkouts/polars-b0d90607192fd414/5bd7318/polars/polars-lazy/src/physical_plan/executors/scan/parquet.rs:32:53
   6: <polars_lazy::physical_plan::executors::scan::parquet::ParquetExec as polars_lazy::physical_plan::executors::executor::Executor>::execute::{{closure}}::{{closure}}
             at .cargo/git/checkouts/polars-b0d90607192fd414/5bd7318/polars/polars-lazy/src/physical_plan/executors/scan/parquet.rs:76:76
   7: polars_lazy::physical_plan::file_cache::FileCache::read
             at .cargo/git/checkouts/polars-b0d90607192fd414/5bd7318/polars/polars-lazy/src/physical_plan/file_cache.rs:52:13
   8: <polars_lazy::physical_plan::executors::scan::parquet::ParquetExec as polars_lazy::physical_plan::executors::executor::Executor>::execute::{{closure}}
             at .cargo/git/checkouts/polars-b0d90607192fd414/5bd7318/polars/polars-lazy/src/physical_plan/executors/scan/parquet.rs:74:17
   9: polars_lazy::physical_plan::state::ExecutionState::record
             at .cargo/git/checkouts/polars-b0d90607192fd414/5bd7318/polars/polars-lazy/src/physical_plan/state.rs:100:21
  10: <polars_lazy::physical_plan::executors::scan::parquet::ParquetExec as polars_lazy::physical_plan::executors::executor::Executor>::execute
             at .cargo/git/checkouts/polars-b0d90607192fd414/5bd7318/polars/polars-lazy/src/physical_plan/executors/scan/parquet.rs:72:9
  11: <polars_lazy::physical_plan::executors::udf::UdfExec as polars_lazy::physical_plan::executors::executor::Executor>::execute
             at .cargo/git/checkouts/polars-b0d90607192fd414/5bd7318/polars/polars-lazy/src/physical_plan/executors/udf.rs:16:18
  12: polars_lazy::frame::LazyFrame::collect
```

### Expected behavior

no panic

### Installed versions

5bd73183c79e2b77ebd279f5b4ef0a7ff142bcfe

**Comment by universalmind303** [comment] 2023-02-06 05:01
I believe this is a duplicate of #6196

**Comment by ritchie46** [comment] 2023-02-06 06:23
I will close in favor of #6196

**Closed by ritchie46** 2023-02-06 06:23 UTC
Labels: bug, rust
