### ISSUE TITLE
`rolling`: incorrect upper bound with `1mo_saturating`

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#12216] opened 2023-11-03 08:19 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# MWE
(
    pl.DataFrame({"date": [date(2020, 7, 31)]})
    .set_sorted("date")
    .rolling(
        index_column="date",
        period="1mo_saturating",
    )
    .agg(
        date_min=pl.min("date"),
        date_max=pl.max("date"),
    )
)
┌────────────┬──────────┬──────────┐
│ date       ┆ date_min ┆ date_max │
│ ---        ┆ ---      ┆ ---      │
│ date       ┆ date     ┆ date     │
╞════════════╪══════════╪══════════╡
│ 2020-07-31 ┆ null     ┆ null     │>>>>>>>>>>>>>>>>>>>> at least current row date should be in the window!
└────────────┴──────────┴──────────┘


# Bigger picture
df = pl.DataFrame(
    {
        "date": [
            date(2020, 6, 29),
            date(2020, 6, 30),
            date(2020, 7, 30),
            date(2020, 7, 31),
            date(2020, 8, 1),
        ],
        "val": [1, 2, 3, 4, 5],
    }
).set_sorted("date")

(
    df
    .rolling(
        index_column='date',
        period='1mo_saturating',
    )
    .agg(
        vals=pl.col('val'),
        date_min=pl.min('date'),
        date_max=pl.max('date')
    )
)

┌────────────┬───────────┬────────────┬────────────┐
│ date       ┆ vals      ┆ date_min   ┆ date_max   │
│ ---        ┆ ---       ┆ ---        ┆ ---        │
│ date       ┆ list[i64] ┆ date       ┆ date       │
╞════════════╪═══════════╪════════════╪════════════╡
│ 2020-06-29 ┆ [1]       ┆ 2020-06-29 ┆ 2020-06-29 │
│ 2020-06-30 ┆ [1, 2]    ┆ 2020-06-29 ┆ 2020-06-30 │
│ 2020-07-30 ┆ [3]       ┆ 2020-07-30 ┆ 2020-07-30 │
│ 2020-07-31 ┆ [3]       ┆ 2020-07-30 ┆ 2020-07-30 │ <<<<<<<<<<<<<< "4" missing & incorrect `date_max`
│ 2020-08-01 ┆ [3, 4, 5] ┆ 2020-07-30 ┆ 2020-08-01 │
└────────────┴───────────┴────────────┴────────────┘

# DUCKDB does this correctly
duckdb.sql('''
select
    date,
    list(val) over one_month as vals,
    min(date) over one_month as date_min,
    max(date) over one_month as date_max,
from df
window one_month AS (
    order by date asc
    range between interval 1 month preceding
    and current row
)
''')
┌────────────┬───────────┬────────────┬────────────┐
│    date    │   vals    │  date_min  │  date_max  │
│    date    │  int64[]  │    date    │    date    │
├────────────┼───────────┼────────────┼────────────┤
│ 2020-06-29 │ [1]       │ 2020-06-29 │ 2020-06-29 │
│ 2020-06-30 │ [1, 2]    │ 2020-06-29 │ 2020-06-30 │
│ 2020-07-30 │ [2, 3]    │ 2020-06-30 │ 2020-07-30 │
│ 2020-07-31 │ [2, 3, 4] │ 2020-06-30 │ 2020-07-31 │ >>>>>>>>>> Correct date_max
│ 2020-08-01 │ [3, 4, 5] │ 2020-07-30 │ 2020-08-01 │
└────────────┴───────────┴────────────┴────────────┘
```

### Issue description

(*credits to "Balthazar" on discord who found this unexpected behaviour)

The upper bound of time intervals is wrong (too low) if using `_saturating` and the day of the month gets adjusted.

As per documentation the windows created will be: `(t_x - period, t_x]`

Problem example
- date `2020-07-31` --> this should be upper bound
- go back `1mo_saturating` --> `2020-06-30` --> lower bound
- BUT then will it will take this lower bound and add 1mo --> `2020-07-30`  --> this should NOT be the upper bound??

Adding back this `period` is not correct as the current row date should always be the upper bound, right?

### Expected behavior

The upper bound should not change. Only the lower bound has be to calculated, or?

### Installed versions

<details>

```
0.19.12
```

</details>

**Comment by MarcoGorelli** [comment] 2023-11-06 09:07
Thanks for the report, closing as duplicate of https://github.com/pola-rs/polars/issues/12218

**Closed by MarcoGorelli** 2023-11-06 09:07 UTC
Labels: bug, python

**Comment by MarcoGorelli** [comment] 2023-11-06 10:54
> ```
> │ 2020-07-30 │ [2, 3]    │ 2020-06-30 │ 2020-07-30 │
> │ 2020-07-31 │ [2, 3, 4] │ 2020-06-30 │ 2020-07-31 │ >>>>>>>>>> Correct date_max
> ```

just to clarify, the expected date_min would be different in Polars because of the `closed='right'` default, correct?

Is 
```python
shape: (5, 4)
┌────────────┬───────────┬────────────┬────────────┐
│ date       ┆ vals      ┆ date_min   ┆ date_max   │
│ ---        ┆ ---       ┆ ---        ┆ ---        │
│ date       ┆ list[i64] ┆ date       ┆ date       │
╞════════════╪═══════════╪════════════╪════════════╡
│ 2020-06-29 ┆ [1]       ┆ 2020-06-29 ┆ 2020-06-29 │
│ 2020-06-30 ┆ [1, 2]    ┆ 2020-06-29 ┆ 2020-06-30 │
│ 2020-07-30 ┆ [3]       ┆ 2020-07-30 ┆ 2020-07-30 │
│ 2020-07-31 ┆ [3, 4]    ┆ 2020-07-30 ┆ 2020-07-31 │
│ 2020-08-01 ┆ [3, 4, 5] ┆ 2020-07-30 ┆ 2020-08-01 │
└────────────┴───────────┴────────────┴────────────┘
```
your expected output?

**Comment by JulianCologne** [comment] 2023-11-06 11:08
> just to clarify, the expected date_min would be different in Polars because of the `closed='right'` default, correct?

correct! You would get the same result as duckdb using `closed='both'`




> your expected output?

looks perfect! 😃
