### ISSUE TITLE
Add fast path for filtering on a sorted column

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#11805] opened 2023-10-17 12:16 UTC
### Description

I noticed the performance for the filter operation was roughly the same on a filtered and non-filtered column.

I imagine a fast path should be possible.

Consider this example:
```python
import numpy as np 
np.random.seed(3)
random_numbers = np.random.randint(0,100,1_000_000)

df_random = pl.DataFrame({'n':random_numbers})
df_sorted = pl.DataFrame({'n':sorted(random_numbers)}).sort('n')
```

In theory it should be faster to search `df_sorted` than `df_random`

I benchmarked filtering via  `df.filter(pl.col('n')==some_random_number_between_0_and_100)` using this code:

```python

import time 
results = {
    'Random':[],
    'Sorted':[]
}

for i in range(100_000):
    if i%1000 == 0:
        print(i, end=' ')
        
    random_integer = np.random.randint(0,100,1)[0]
    for df, key in zip([df_random, df_sorted], ['Random', 'Sorted']):
        s = time.time()    
        _ = df.filter(pl.col('n')==random_integer)
        e = time.time()
        results[key].append(e-s)
```

I was surprised that both approaches were basicity the same speed:

```python
pd.DataFrame(results).mul(1000).describe(percentiles=np.linspace(0,1,11)).T
```

![image](https://github.com/pola-rs/polars/assets/112868935/86900d6a-f66f-4129-a230-6acaaa0b4450)

**Comment by ion-elgreco** [comment] 2023-10-17 12:22
If I run your code, I get these results:

![image](https://github.com/pola-rs/polars/assets/15728914/7e5289bd-7b9f-4266-9ebe-c344d1981bf1)

**Comment by mkleinbort-ic** [comment] 2023-10-17 12:24
Interesting @ion-elgreco 

Edit: I replaced `time.time()` with `time.perf_counter_ns()` bacause I noticed some of the code was too fast for `time.time()`

![image](https://github.com/pola-rs/polars/assets/112868935/3a0f7236-81b8-4a1d-b7d0-3425d70e0faa)

**Comment by mkleinbort-ic** [comment] 2023-10-17 12:40
Maybe I'm wrong, there is a speedup from first sorting the array (though maybe hard to notice sometimes):

```python
import pandas as pd 
pd.DataFrame(results).plot(kind='kde', xlim=[0, 300_000]) # x-axis is ns
```
![image](https://github.com/pola-rs/polars/assets/112868935/0f235037-6d07-4d56-8e80-e9c4c8132823)

**Comment by mcrumiller** [comment] 2023-10-17 18:57
There are fast paths for the comparison operators <, >, <=, and >=, but not for == or !=. [See here](https://github.com/pola-rs/polars/blob/main/crates/polars-core/src/chunked_array/comparison/scalar.rs).

**Comment by mkleinbort-ic** [comment] 2023-10-17 19:18
Well, fancy that...

```python

import time 
results = {
    'Random':[],
    'Sorted':[], 
    'Sorted via optimized comparison':[]
}

for i in range(100_000):
    if i%1000 == 0:
        print(i, end=' ')
        
    random_integer = np.random.randint(0,100,1)[0]
    ith_filter = pl.col('n')==random_integer
    
    for df, key in zip([df_random, df_sorted], ['Random', 'Sorted']):

        s = time.perf_counter_ns()
        _ = df.filter(ith_filter)
        e = time.perf_counter_ns()
        results[key].append((e-s))
    
    ith_filter_via_optimized_comparison = (pl.col('n') <= random_integer) & (pl.col('n') >= random_integer)
    
    s = time.perf_counter_ns()
    _ = df_sorted.filter(ith_filter_via_optimized_comparison)
    e = time.perf_counter_ns()
    
    results['Sorted via optimized comparison'].append((e-s))
```

And then:

![image](https://github.com/pola-rs/polars/assets/112868935/725a343a-d9d1-44e5-8cb6-ec80808822da)

![image](https://github.com/pola-rs/polars/assets/112868935/bdb79f42-45dd-4c71-9455-28e049117423)


I guess this justifies the original feature request:

`(pl.col('n') <= random_integer) & (pl.col('n') >= random_integer)` is c. 35% faster than `pl.col('n') == random_integer`

**Comment by orlp** [comment] 2023-10-18 11:54
I can take care of this, I'm working on a comparison kernel project at the moment anyway.

**Comment by owenprough-sift** [comment] 2023-10-20 13:48
Is this issue a duplicate of #5448?

**Comment by ion-elgreco** [comment] 2023-10-20 14:14
> Is this issue a duplicate of #5448?

Rather related than duplicate

**Comment by owenprough-sift** [comment] 2023-10-23 12:55
This issue also seems related to #9127, so maybe orlp's work on this can close multiple issues. :)

**Comment by mkleinbort-ic** [comment] 2023-11-22 11:54
Just checking in. Since the implementation of `.filter(colName = value)` I think this feature (ie. quick filtering on equality when the column is sorted) would be a good speed win for many users.

**Comment by mkleinbort-ic** [comment] 2023-11-29 18:31
This is now very fast (at least as of version `0.19.17`)
![image](https://github.com/pola-rs/polars/assets/112868935/01a98bf3-7585-48b1-8815-b70cee804715)

**Comment by mkleinbort-ic** [comment] 2023-11-29 18:36
Nvm, still slow on larger data 


```python

import numpy as np 
np.random.seed(3)
random_numbers = np.random.randint(0, 10_000, 10_000_000)

df_random = pl.DataFrame({'n':random_numbers})
df_sorted = pl.DataFrame({'n':sorted(random_numbers)}).sort('n').set_sorted('n')


import time 
results = {
    'Random':[],
    'Sorted':[], 
    'Sorted via optimized comparison':[]
}

for i in range(10_000):
    if i%1000 == 0:
        print(i, end=' ')
        
    random_integer = np.random.randint(0,10_000,1)[0]
    ith_filter = pl.col('n')==random_integer
    
    for df, key in zip([df_random, df_sorted], ['Random', 'Sorted']):

        s = time.perf_counter_ns()
        _ = df.filter(ith_filter)
        e = time.perf_counter_ns()
        results[key].append((e-s))
    
    ith_filter_via_optimized_comparison = (pl.col('n') <= random_integer) & (pl.col('n') >= random_integer)
    
    s = time.perf_counter_ns()
    _ = df_sorted.filter(ith_filter_via_optimized_comparison)
    e = time.perf_counter_ns()
    
    results['Sorted via optimized comparison'].append((e-s))

import pandas as pd 
pd.DataFrame(results).plot(kind='kde', xlim=[0, 3_000_000])
```

![image](https://github.com/pola-rs/polars/assets/112868935/4d4d44a3-056c-426c-9aa7-57ba467caf74)

**Comment by imm-ds** [comment] 2024-02-13 15:18
Hi - I've recently run into the same issue here. I have ran the above code and 
`(pl.col('n')<= random_integer) & (pl.col('n') >= random_integer) is c. 35% faster than pl.col('n') == random_integer`
![test](https://github.com/pola-rs/polars/assets/155964249/7e2b5ef9-5522-4433-b708-7c86cfe402ef)

still remains true.

Is there any update regarding this?

I am on version 0.20.7
Thanks

**Closed** 2024-04-17 06:14 UTC
Labels: enhancement

**Comment by TateStaples** [comment] 2025-07-29 20:40
Wanted to update that I'm getting much slower filter (`pl.col(col).eq(val)`) results after `set_sorted` on a LazyFrame
