### ISSUE TITLE
Polars does not check whether expressions are valid in lazy evaluation mode

### ISSUE THREAD

**Issue by Hoeze** [pola-rs/polars#5832] opened 2022-12-16 15:17 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

In lazy evaluation mode, polars does not check whether expressions are actually valid.
E.g. it does not check whether columns actually exist until `collect()` is being called.

### Reproducible example

```python
import polars as pl
import numpy as np
# Create a simple dataset on which we can reproduce the bug.
df = pl.DataFrame({
    "foo": [None, 1, 2],
    "bar": np.arange(3)
}).lazy()

df.filter(pl.col("does_not_exist"))

print("did not fail!")
```

### Expected behavior

Polars should raise a `NotFoundError`

### Installed versions

<details>

```
---Version info---
Polars: 0.15.6
Index type: UInt32
Platform: Linux-4.18.0-372.26.1.el8_6.x86_64-x86_64-with-glibc2.28
Python: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.2
numpy: 1.23.2
fsspec: 2022.01.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.1

```

</details>

**Comment by ritchie46** [comment] 2022-12-17 13:29
This will error once we start optimization. The important thing is that we error before we run the query which we do.

**Comment by Hoeze** [comment] 2022-12-17 17:47
@ritchie46 is there a chance to get this fail immediately or have a traceback to the exact line where it fails?
This would make debugging much easier.

**Comment by ritchie46** [comment] 2022-12-20 10:55
This is an ongoing goal of polars. We want to improve error messages and also add the origin of the error. This will improve in the future.

**Comment by ritchie46** [comment] 2022-12-28 18:46
I will close this as there is not a bug, but rather on ongoing effort to improve error messages which we are working on.

**Closed by ritchie46** 2022-12-28 18:46 UTC
Labels: bug, python
