### ISSUE TITLE
Pivot can cause duplicate column names

### ISSUE THREAD

**Issue by ChristopherRussell** [pola-rs/polars#14444] opened 2024-02-12 20:38 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame({'a': [1], 'b': ['a'], 'c': [2]}).pivot('c', 'a', 'b')
```

### Issue description

Returns a dataframe with two columns called 'a'

### Expected behavior

Repeated columns names shouldn't be possible

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             macOS-12.3.1-arm64-arm-64bit
Python:               3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:36:57) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              15.0.0
pydantic:             2.6.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment] 2024-02-12 20:53
thanks for the report - closing as dupe of the issue addressed by https://github.com/pola-rs/polars/pull/14431, this will be fixed in the next release

**Closed by MarcoGorelli** 2024-02-12 20:53 UTC
Labels: bug, python, needs triage
