### ISSUE TITLE
Add `from_arrow` for pola-rs schema

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#19331] opened 2024-10-20 12:04 UTC
### Description

Currently you can convert a pyarrow schema to pola-rs by creating an empty arrow table and converting that to a Pola-rs frame.

Related https://github.com/pola-rs/polars/pull/19103

**Comment by deanm0000** [comment] 2024-10-25 03:51
is duplicate of https://github.com/pola-rs/polars/issues/15600?

**Closed** 2024-10-25 05:12 UTC
Labels: enhancement
