### ISSUE TITLE
Maybe the version of polars of user guide should be specified.

### ISSUE THREAD

**Issue by pbwdq** [pola-rs/polars#17037] opened 2024-06-18 01:34 UTC
### Description

Hello. This is my, an amateur's opinion. 
I hope fewer people will end up in the same situation.
Personally, the problem was solved.
I could be missing something or wrong.

yesterday I run
`pip install polars`
but it installed old version of polars on my computer.

on JupyterLab 4.2.2 (on Windows10)
pl.show_versions()
--------Version info---------
polars: 0.19.??(sorry I don't remember)
python: 3.11.3
numpy: 1.24.3

I followed the user-guide
https://docs.pola.rs/user-guide/concepts/contexts/#group-by-aggregation
and Error on this line
`pl.col("random").filter(pl.col("names").is_not_null()).sum().name.suffix("_sum"),`
which says
`.name.suffix("_sum")` 
has problem and it doesn't have "name" attribute.
I don't know what it means so I started Google Colab and run the same code and it was okay.

on Google Colab
pl.show_versions()
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-6.1.85+-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies---
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           3.7.1
numpy:                1.25.2
openpyxl:             3.1.3
pandas:               2.0.3
pyarrow:              14.0.2
pydantic:             2.7.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.30
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

Python's version is also different but I just installed(or updated to) polars 0.20.2 on my computer again like this
`pip install polars==0.20.2`
and problem solved. 
Thanks.

**Comment by mcrumiller** [comment] 2024-06-18 12:45
Hi @pbwdq, this sounds like an issue with packages on your end. You most likely already had an older version of polars installed, which means that running a simple `pip install polars` won't do anything. You need to run `pip install --upgrade polars` to get the latest version.

Because many people work with potentially large codebases written on older versions of polars, we need to provide documentation so that they can continue development. This is fairly common in large projects, as you'll see that (for example) [numpy](https://numpy.org/doc/stable/), [pandas](https://pandas.pydata.org/docs/), and [pyarrow](https://arrow.apache.org/docs/python/index.html) all provide similar drop-down menus to select the version. Imagine if Microsoft only provided help for the latest version of Excel--anyone with an older version would be out of luck if they had an issue.

**Comment by mcrumiller** [comment] 2024-06-18 12:46
Also--the major polars version *is* specified in the top right of the [API documentation](https://docs.pola.rs/py-polars/html/reference/):

![image](https://github.com/pola-rs/polars/assets/1896992/b2b61c0b-d9bb-4525-a8d3-18f53d1b144e)

**Comment by stinodego** [comment] 2024-06-22 15:05
Duplicate of https://github.com/pola-rs/polars/issues/11105

**Closed by stinodego** 2024-06-22 15:05 UTC
Labels: documentation
