### ISSUE TITLE
Pearson correlation function 

### ISSUE THREAD

**Issue by canimus** [pola-rs/polars#5879] opened 2022-12-21 18:15 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Making use of the new `pearson_corr`  function and evaluating against a particular scalar, throws negative results.
I assume is a rounding issue, but is not perceivable whilst printing the results. 
It emerges only when individual values on the dataframe or series are extracted.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"id":[10,20], "id2": [10,20]})
df.pearson_corr().select(pl.col("id2")).to_series() == 1.0
shape: (2,)
Series: 'id' [bool]
[
        false
        false
]

# Alternatively when obtaining the value
In [18]: df.pearson_corr().select(pl.col('id2')).to_series()[0]
Out[18]: 0.9999999999999999
```

### Expected behavior

I would expect the values on the scalar comparisson to be true or get the scalar represented in the dataframe or series.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.7
Index type: UInt32
Platform: Linux-5.4.0-1094-azure-x86_64-with-glibc2.31
Python: 3.10.4 (main, Nov  2 2022, 18:29:07) [GCC 9.4.0]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.0
```

</details>

**Comment by cmdlineluser** [comment] 2022-12-22 14:23
It appears `.pearson_corr()` [calls `np.corrcoef()`](https://github.com/pola-rs/polars/issues/5530)

```
>>> import numpy as np
>>> import polars as pl
>>> df = pl.DataFrame({"id":[10,20], "id2": [10,20]})
>>> np.corrcoef(df)
array([[1., 1.],
       [1., 1.]])
```

Bumping the precision formatting:

```
>>> with np.printoptions(precision=16):
...    np.corrcoef(df)
array([[0.9999999999999999, 0.9999999999999999],
       [0.9999999999999999, 0.9999999999999999]])
```

[`pandas.DataFrame.corr()`](https://github.com/pandas-dev/pandas/blob/v1.5.2/pandas/_libs/algos.pyx#L328) uses its own implementation which produces "exactly 1" for the same input.

```
>>> with np.printoptions(precision=16):
...     df.to_pandas().corr().to_numpy()
array([[1., 1.],
       [1., 1.]])
>>> pl.from_pandas(df.to_pandas().corr()) == 1
shape: (2, 2)
┌──────┬──────┐
│ id   ┆ id2  │
│ ---  ┆ ---  │
│ bool ┆ bool │
╞══════╪══════╡
│ true ┆ true │
├╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ true ┆ true │
└──────┴──────┘
```
Not sure what the differences are between the two approaches but perhaps polars could do what pandas does instead of using `np.corrcoef()`?

**Comment by ritchie46** [comment] 2022-12-23 10:05
This is not a bug. We are dealing with floating point numbers.

**Comment by zundertj** [comment] 2022-12-23 11:11
In addition to Ritchie's remark, with floating point numbers, it all depends on the precision and the algorithms used if it ends up at exactly 1 or not for your specific case, where it may be that not one algorithm is better in all cases. Relying on exact equality is thus risky: it may work, until it doesn't. Pandas clearly uses something slightly different here, but there is no reason we should prefer Pandas behaviour over Numpy behaviour in and of itself.

**Comment by ritchie46** [comment] 2022-12-26 11:24
I will close this as this is not something we should work on. Discussion on the algorithm used should be taken upstream to numpy, but I think they feel the same way.

**Closed by ritchie46** 2022-12-26 11:24 UTC
Labels: bug, python
