### ISSUE TITLE
set_tbl_cols is ignored for HTML output in Databricks most likely also in Jupyter.

### ISSUE THREAD

**Issue by keiv-fly** [pola-rs/polars#2928] opened 2022-03-18 13:26 UTC
#### What language are you using?

Python
#### What version of polars are you using?
0.13.12

#### What operating system are you using polars on?

Ubuntu
#### What language version are you using
python 3.8.10

Databricks latest

#### Describe your bug.

set_tbl_cols is ignored and the columns are truncated.
![image](https://user-images.githubusercontent.com/1749072/159010487-b6a23c5a-d457-4c9d-afc9-4b87605eb3cd.png)

#### What are the steps to reproduce the behavior?

```
import polars as pl
pl.cfg.Config.set_tbl_cols = 1000
temp_df = pl.DataFrame({str(i):[i] for i in range(1000)})
temp_df
```

#### What is the actual behavior?

Columns between 36 and 963 are cut.

#### What is the expected behavior?

See all 1000 columns in the HTML.

**Comment by ritchie46** [comment] 2022-03-18 14:04
duplicate of #2929

**Closed by ritchie46** 2022-03-18 14:04 UTC
Labels: bug

**Comment by keiv-fly** [comment] 2022-03-18 14:12
I wanted to delete this one, but did not know how.
