### ISSUE TITLE
Support for f-string formatting in pl.format

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#12299] opened 2023-11-07 15:13 UTC
### Description

The pl.format expression is great, but it does not support any f-string formatting. For example:

```python

df = pl.DataFrame({'x': [12516.1417]})

df.select(pl.format('{} is a number', pl.col('x'))) # Works
df.select(pl.format('{:,} is a number', pl.col('x'))) # Does not work
df.select(pl.format('{:.0f} is a number', pl.col('x'))) #  Does not work
df.select(pl.format('{:.0%} is a number', pl.col('x'))) #  Does not work

```

This limitation is a common cause for the use of `map_elements` - which I understand is much slower.

eg. 

```python
df.select(pl.col('x').map_elements(lambda x: f'{x:.0%} is a number'))
```

**Comment by mkleinbort-ic** [comment] 2023-11-07 15:18
Probably a duplicate of https://github.com/pola-rs/polars/issues/7133 and https://github.com/pola-rs/polars/issues/11297, bit those issues have not been touched on for a while.

**Comment by mcrumiller** [comment] 2023-11-07 18:38
@mkleinbort-ic take a look at my expression-based implementation [here](https://github.com/pola-rs/polars/issues/7133#issuecomment-1442422524). It's obviously not optimal and it's now pretty old, but it worked pretty well at the time. I do +1 this issue though.

**Comment by mkleinbort-ic** [comment] 2023-11-08 11:19
Yes, I saw, it gave me some good ideas.

I mainly need to support the "," separator and "%"'s, so currently rolling my own.

**Comment by stinodego** [comment] 2023-11-08 12:43
As you have noticed, this is a duplicate of https://github.com/pola-rs/polars/issues/7133

I have accepted that issue - if you can come up with an elegant implementation, we'd be happy to review.

Our issue tracker is packed enough as it is, let's try to avoid creating duplicate issues.

**Closed by stinodego** 2023-11-08 12:43 UTC
Labels: enhancement
