### ISSUE TITLE
.arr.eval(pl.element().sum()) much slower than .arr.sum()

### ISSUE THREAD

**Issue by ChristopherRussell** [pola-rs/polars#6348] opened 2023-01-20 20:11 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

From reading the [User Guide Section 3.6](https://pola-rs.github.io/polars-book/user-guide/dsl/list_context.html) I thought that using `arr.eval(pl.element().sum())` was the correct way to get the sum for each list in a column of lists. However I found that `arr.sum()` also works and is much much faster (I initially found out because the a call to the former on a bigger dataframe was crashing my kernel!)

Is this a bug, or am I misusing?

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    'list_col': [list(range(1000))] * 1000
})

# 331 µs ± 8.33 µs per loop
df.select(pl.col('list_col').arr.sum())

# 25.5 ms ± 3.28 ms per loop
df.select(pl.col('list_col').arr.eval(pl.element().sum()))
```

### Expected behavior

Closer performance by time.

### Installed versions

<details>

```
---Version info---
Polars: 0.15.16
Index type: UInt32
Platform: macOS-12.3.1-arm64-arm-64bit
Python: 3.10.8 (main, Nov 24 2022, 08:08:27) [Clang 14.0.6 ]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.5.2
numpy: 1.23.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by cmdlineluser** [comment] 2023-01-20 20:52
You can set [`parallel=True`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.arr.eval.html#polars.Expr.arr.eval) on `.arr.eval()` which should get the times closer.

They are slightly different though - the first one is returning `i64` whereas `.arr.eval()` is returning `list[i64]`

**Comment by ritchie46** [comment] 2023-01-20 21:49
What can I say? The one is generic over any expression. The is specialized for summing. Of course it is faster.

**Comment by ChristopherRussell** [comment] 2023-01-20 22:38
Points taken re: differences in use and return type, thanks both. 

I see setting parallel=True reduces the difference from 100x to 10x too.

**Comment by ritchie46** [comment] 2023-01-21 13:19
I will close this as this is not a bug, but an observation that is in line with expectations.

**Closed by ritchie46** 2023-01-21 13:19 UTC
Labels: bug, python
