### ISSUE TITLE
Adopt python `datetime.datetime.replace(...)` method as a `pl.col('date').dt.replace(...)`

### ISSUE THREAD

**Issue by Andre-Medina** [pola-rs/polars#17186] opened 2024-06-25 12:39 UTC
### Description

I seem to always be struggling with datetime and timezones and combining the two. But the current issue im having should have a simple solution.

I often find myself needing to replace a part of a datetime in polars. With basic built in methods, I am able to use something like the `datetime.datetime.replace()`. However polars does not have an equivalent. 

```python
# Have dateframe with a timezone
tz = 'Australia/Melbourne'
data = pl.DataFrame({
    "date" : [
        datetime.datetime(2020, 1, 31, 2, 3, 1,tzinfo=ZoneInfo(tz)), 
        datetime.datetime(2020, 3, 21, 2, 30, 1,tzinfo=ZoneInfo(tz)), 
        datetime.datetime(2020, 4, 30, 20, 3, 10,tzinfo=ZoneInfo(tz))
    ],
    "data" : [10, 12, 14],
}).with_columns(pl.col('date').dt.convert_time_zone(tz))

print(data)
"""shape: (3, 2)
┌─────────────────────────────────┬──────┐
│ date                            ┆ data │
│ ---                             ┆ ---  │
│ datetime[μs,                    ┆ i64  │
│ Australia/Melbourne]            ┆      │
╞═════════════════════════════════╪══════╡
│ 2020-01-31 02:03:01 AEDT        ┆ 10   │
│ 2020-03-21 02:30:01 AEDT        ┆ 12   │
│ 2020-04-30 20:03:10 AEST        ┆ 14   │
└─────────────────────────────────┴──────┘
"""

# Want to replace the year with this new year.
new_year = 2031

new_data = (
    data
    .with_columns(

        # I just want to replace the year
        pl.datetime(
            year = new_year,
            month = pl.col('date').dt.month(),
            day = pl.col('date').dt.day(),
            hour = pl.col('date').dt.hour(),
            minute = pl.col('date').dt.minute(),
            second = pl.col('date').dt.second(),
        )
        .dt.replace_time_zone(data['date'].dtype.time_zone)
        .alias('new_year')
    )
)
print(new_data)
"""shape: (3, 3)
┌─────────────────────────────────┬──────┬─────────────────────────────────┐
│ date                            ┆ data ┆ new_year                        │
│ ---                             ┆ ---  ┆ ---                             │
│ datetime[μs,                    ┆ i64  ┆ datetime[μs,                    │
│ Australia/Melbourne]            ┆      ┆ Australia/Melbourne]            │
╞═════════════════════════════════╪══════╪═════════════════════════════════╡
│ 2020-01-31 02:03:01 AEDT        ┆ 10   ┆ 2031-01-31 02:03:01 AEDT        │
│ 2020-03-21 02:30:01 AEDT        ┆ 12   ┆ 2031-03-21 02:30:01 AEDT        │
│ 2020-04-30 20:03:10 AEST        ┆ 14   ┆ 2031-04-30 20:03:10 AEST        │
└─────────────────────────────────┴──────┴─────────────────────────────────┘
"""

# Easy to do with datetimes
date = datetime.datetime(2020, 4, 30, 20, 3, 10, tzinfo=ZoneInfo(tz))
print(date)
"""2020-04-30 20:03:10+10:00"""
new_date = date.replace(year = new_year)
print(new_date)
"""2031-04-30 20:03:10+10:00"""
```

It is also possible to convert the datetime to a string and do more manipulations but its a very roundabout way of doing something which should be simple. 

I suggest adopting something like this to be inline with the standard datetime methods:
```python
new_data = (
    data
    .with_columns(
        pl.col('date').dt.replace(year = new_year).alias('new_year')
    )
)
```

I am using polars 20.31, congrats on nearly finished polars 1.0, I cant wait to be using it every day :)

**Comment by MarcoGorelli** [comment] 2024-06-25 12:47
thanks for the request - is this a dupe of #8879? ok to close in favour of that one?

**Comment by stinodego** [comment] 2024-06-25 22:23
Closing in favor of #8879

**Closed by stinodego** 2024-06-25 22:23 UTC
Labels: enhancement
