### ISSUE TITLE
`sink_parquet(...)` much slower than `.collect().write_parquet(...)`

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#11699] opened 2023-10-12 17:09 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Using the same data as in https://github.com/pola-rs/polars/issues/11698, I'm observing at least a 2x performance difference in the following:

```python
pl.scan_parquet(f).sink_parquet("/tmp/out")

# 2x faster:
pl.scan_parquet(f).collect().write_parquet("/tmp/out")
```

Interestingly when looking at htop, the version with `.collect()` seems to use all cores sometimes (during reading?) while the other version never uses more than ~ 1 core.

This is a reduced example; the original tables has many more columns and the performance difference is much larger.

### Issue description

See example

### Expected behavior

Should have similar performance.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            macOS-13.5.2-arm64-arm-64bit
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.0
openpyxl:            <not installed>
pandas:              2.0.3
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by nameexhaustion** [comment] 2023-10-13 01:02
Might be related to https://github.com/pola-rs/polars/issues/9756

**Comment by ritchie46** [comment] 2023-10-13 12:41
I cannot reproduce? 
![image](https://github.com/pola-rs/polars/assets/3023000/fbd3c7e1-8213-4d54-9694-bef94325b600)

**Comment by jonashaag** [comment] 2023-10-14 16:22
Weird...


```
In [27]: %timeit -n1 -r3 q.sink_parquet("/tmp/t")
1.8 s ± 13.5 ms per loop (mean ± std. dev. of 3 runs, 1 loop each)

In [29]: %timeit -n1 -r3 q.collect().write_parquet("/tmp/t")
1.55 s ± 10.8 ms per loop (mean ± std. dev. of 3 runs, 1 loop each)
```

Although on this machine (macOS M2) it's only a 1.2x slowdown, on the other machine (Linux, Xeon with AVX 512) it was more like 2x.

**Comment by jonashaag** [comment] 2023-10-14 16:39
2 core GitHub codespace:

```
In [1]: import polars as pl

In [2]: q = pl.scan_parquet("pl-perf-medium.parquet")

In [3]: %timeit -n1 -r3 q.sink_parquet("/tmp/t")
3.59 s ± 113 ms per loop (mean ± std. dev. of 3 runs, 1 loop each)

In [4]: %timeit -n1 -r3 q.collect().write_parquet("/tmp/t")
4 s ± 100 ms per loop (mean ± std. dev. of 3 runs, 1 loop each)
```

16 core GitHub codespace:

```
In [3]: %timeit -n1 -r3 q.sink_parquet("/tmp/t")
2.82 s ± 8.88 ms per loop (mean ± std. dev. of 3 runs, 1 loop each)

In [4]: %timeit -n1 -r3 q.collect().write_parquet("/tmp/t")
2.39 s ± 24.7 ms per loop (mean ± std. dev. of 3 runs, 1 loop each)
```

So seems to be related to the number of threads

**Comment by ritchie46** [comment] 2023-10-18 08:08
Sure it is fastest with more tests. But you still see samish performance within the same thread count.

**Comment by jonashaag** [comment] 2023-10-20 12:45
This is on the production machine, it's a larger file with 2x the rows

<img width="465" alt="Screenshot 2023-10-20 at 15 43 52" src="https://github.com/pola-rs/polars/assets/175722/3fa0e44c-9582-48b7-8661-7599a993bc1a">

**Comment by jonashaag** [comment] 2023-11-09 21:09
Similar behavior with a different Parquet and this code:

```
pl.scan_parquet(...).filter(...).sink_parquet(...)
```

Uses only 2 cores.

**Comment by thetkoseek** [comment] 2023-12-19 06:35
Is write_parquet meant to be multicore, as it only creates a single file?

**Comment by jonashaag** [comment] 2023-12-19 06:37
Yes it is

**Comment by braaannigan** [comment] 2024-01-11 11:44
I've also found sink_parquet to be very slow. This query takes about 1 s to evaluate but if I run `sink_parquet` at the end I have to kill the kernel after a few minutes when the file size has only got to 0.5 Mb.

```python
from datetime import datetime

import polars as pl

start_datetime = datetime(2020,1,1)
end_datetime = datetime(2024,1,1,)
N_ids = 10
interval = "1m"
df = pl.LazyFrame(
    {
        "time":pl.datetime_range(start_datetime,end_datetime,interval=interval,eager=True)
    }
).join(
    pl.LazyFrame(
        {
            "id":[f"id{i:05d}" for i in range(N_ids)],
            "value":list(range(N_ids))
        }
    ),how="cross"
).select("time","id","value")
```
If I do `df.collect()` with or without streaming it takes about a second to run. If I do df.sink_parquet it sinks my kernel

**Comment by braaannigan** [comment] 2024-01-11 12:04
Update this alternative approach has been running for about 10 minutes and has only written 10Mb of data so far
```python
df.collect(streaming=True).write_parquet("large.parquet")
```

**Comment by aberres** [comment] 2024-01-11 16:19
Oh, one more thing:  My data is nicely compressible. Using `use_pyarrow=True` brings the Parquet size down to 5Mb.

**Comment by itamarst** [comment] 2024-02-01 16:15
Going to try to figure out a fix for this.

**Comment by jonashaag** [comment] 2024-02-03 18:32
@itamarst thank you for looking into this! Were you able to reproduce the fact that the `sink_parquet()` route uses fewer cores? I think that explains most of the performance difference

**Comment by jonashaag** [comment] 2024-02-03 19:02
@itamarst

```
In [10]: %timeit -n1 -r1 pl.scan_parquet("tmp/pl-perf-medium.parquet").sink_parquet("/tmp/xx", compression="uncompressed")
2.29 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [11]: %timeit -n1 -r1 pl.read_parquet("tmp/pl-perf-medium.parquet").write_parquet("/tmp/xx", compression="uncompressed")
1.2 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [13]: %timeit -n1 -r1 pl.scan_parquet("tmp/pl-perf-medium.parquet").sink_parquet("/tmp/xx", compression="zstd")
2.97 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [12]: %timeit -n1 -r1 pl.read_parquet("tmp/pl-perf-medium.parquet").write_parquet("/tmp/xx", compression="zstd")
1.28 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

What's interesting is that the faster version uses fewer threads (I ran the benchmarks 3x here):

<img width="472" alt="Screenshot 2024-02-03 at 20 00 49" src="https://github.com/pola-rs/polars/assets/175722/1be424d6-040c-4691-9242-c10e6e1ea995">

While the slower one uses almost twice the number of threads (all of the threads from the image above plus some more)

<img width="333" alt="Screenshot 2024-02-03 at 20 00 54" src="https://github.com/pola-rs/polars/assets/175722/e14f19b9-a3d3-4662-a3f9-c6056cb86ff8">

<img width="382" alt="Screenshot 2024-02-03 at 20 01 01" src="https://github.com/pola-rs/polars/assets/175722/8923efff-aec2-4bd1-bca6-8b8a10543fb0">

**Comment by itamarst** [comment] 2024-02-03 19:47
Oh huh I didn't notice that part, no, I found some other (perhaps related) issue where the batch sizes of writes seem tiny.

**Comment by jonashaag** [comment] 2024-02-03 21:53
That would explain the very sparse-looking thread utilization graphs for the `sink_parquet()` variant

**Comment by itamarst** [comment] 2024-02-05 14:08
So I measured batch size and it's 2.5K rows written at a time with sink_parquet(), 256K rows written at a time with write_parquet() from a dataframe. The result is also visible in file sizes, with the former being 30MB and the latter 27MB.

I imagine the impacts are also pretty bad when writing over the network, because network latency becomes a bottleneck...

As I see it, there's two sides to the problem:

1. **Generated batch sizes:** Something somewhere is producing too few rows per batch. While this should be fixed, my _guess_ is that this isn't solvable in the general case, due to e.g. filtering. I could be wrong and this is solvable in general.
2. **Written batch sizes:** The writing code is happily writing overly small batches. Instead, it could merge batches that are too small before writing them.

Solving one would make solving the other less important. However, given the first part is more complex, I will see if the second part is something I can do.

**Comment by hugopendlebury** [comment] 2024-02-06 06:35
> @itamarst
> 
> ```
> In [10]: %timeit -n1 -r1 pl.scan_parquet("tmp/pl-perf-medium.parquet").sink_parquet("/tmp/xx", compression="uncompressed")
> 2.29 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
> 
> In [11]: %timeit -n1 -r1 pl.read_parquet("tmp/pl-perf-medium.parquet").write_parquet("/tmp/xx", compression="uncompressed")
> 1.2 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
> 
> In [13]: %timeit -n1 -r1 pl.scan_parquet("tmp/pl-perf-medium.parquet").sink_parquet("/tmp/xx", compression="zstd")
> 2.97 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
> 
> In [12]: %timeit -n1 -r1 pl.read_parquet("tmp/pl-perf-medium.parquet").write_parquet("/tmp/xx", compression="zstd")
> 1.28 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
> ```
> 
> What's interesting is that the faster version uses 13 threads (I ran the benchmarks 3x here):
> 
> <img alt="Screenshot 2024-02-03 at 20 00 49" width="472" src="https://private-user-images.githubusercontent.com/175722/302055908-1be424d6-040c-4691-9242-c10e6e1ea995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDExODgsIm5iZiI6MTcwNzIwMDg4OCwicGF0aCI6Ii8xNzU3MjIvMzAyMDU1OTA4LTFiZTQyNGQ2LTA0MGMtNDY5MS05MjQyLWMxMGU2ZTFlYTk5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwNjI4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzFhZjBjZWIzOTJhMDg5ZGU4ZGEyZmVjNjljNDYyZmFhMmJiODJlMzFkOWU4YjY0YWRlZGVmYzllZDAwNGVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fk2BVcShC6yFYH1ix-yWCRrOpD2-VIhqGl3fKKS_rD8">
> While the slower one uses 21 threads (all of the threads from the image above plus some more)
> 
> <img alt="Screenshot 2024-02-03 at 20 00 54" width="333" src="https://private-user-images.githubusercontent.com/175722/302055930-e14f19b9-a3d3-4662-a3f9-c6056cb86ff8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDExODgsIm5iZiI6MTcwNzIwMDg4OCwicGF0aCI6Ii8xNzU3MjIvMzAyMDU1OTMwLWUxNGYxOWI5LWEzZDMtNDY2Mi1hM2Y5LWM2MDU2Y2I4NmZmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwNjI4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjAyMGRlYTZmYWVjNTNjOWRmZTcwNjE0OWU1OWIwMzFmOTFmZTRlNjYwYTkzZWEwZTYzZTU5N2IyMmNkYzc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4r7Io1Ib755vMwb9i3KudiUh9_xUXgA0Q1VRmhZnheo"> <img alt="Screenshot 2024-02-03 at 20 01 01" width="382" src="https://private-user-images.githubusercontent.com/175722/302055934-8923efff-aec2-4bd1-bca6-8b8a10543fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDExODgsIm5iZiI6MTcwNzIwMDg4OCwicGF0aCI6Ii8xNzU3MjIvMzAyMDU1OTM0LTg5MjNlZmZmLWFlYzItNGJkMS1iY2E2LThiOGExMDU0M2ZiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwNjI4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzhhZTRjNDMxOTM1NDM1MDJhNzZhZjE2OGUxMDBiZDg5ZjQ0MDU0OGE4ZTVhYWY0ZTJhZmNhY2E1YTBkYmFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vKb9FNi8mHzREteWzMF_-486WsnA5APz_24Bu8om65Y">
> My machine has 12 cores

Not directly related but is this a vs code plugin ? How did you get these metrics ?

**Comment by jonashaag** [comment] 2024-02-06 07:26
@hugopendlebury it is macOS Instruments (comes with Xcode)

**Closed** 2024-02-13 20:02 UTC
Labels: bug, python, needs triage, A-io-parquet
