### ISSUE TITLE
write_parquet doesn't compute min/max when statistics=True

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#5296] opened 2022-10-21 20:57 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://www.npmjs.com/package/nodejs-polars) of Polars.

### Issue description

In looking at the stats of a parquet file written by pl the min, max are None.  Files written with pyarrow do have min/max.  The distinct_count says 0 but pa also does so I'm not sure if that means something different than I think.

### Reproducible example

```
blah=pl.DataFrame({'a':[1,2,3], 'b':[datetime(2020,1,1), datetime(2020,1,2), datetime(2020,1,3)]})
blah.write_parquet("testerstat.parquet", statistics=True)
pq.ParquetFile("testerstat.parquet").metadata.to_dict()['row_groups'][0]['columns'][0]

{'file_offset': 81,
 'file_path': '',
 'physical_type': 'INT64',
 'num_values': 3,
 'path_in_schema': 'a',
 'is_stats_set': True,
 'statistics': {'has_min_max': False,
  'min': None,
  'max': None,
  'null_count': 0,
  'distinct_count': 0,
  'num_values': 3,
  'physical_type': 'INT64'},
 'compression': 'ZSTD',
 'encodings': ('PLAIN', 'RLE'),
 'has_dictionary_page': False,
 'dictionary_page_offset': None,
 'data_page_offset': 4,
 'total_compressed_size': 77,
 'total_uncompressed_size': 72}
```
In contrast...

```
blah.write_parquet("testerpa.parquet", statistics=True, use_pyarrow=True)
pq.ParquetFile("testerpa.parquet").metadata.to_dict()['row_groups'][0]['columns'][0]

{'file_offset': 127,
 'file_path': '',
 'physical_type': 'INT64',
 'num_values': 3,
 'path_in_schema': 'a',
 'is_stats_set': True,
 'statistics': {'has_min_max': True,
  'min': 1,
  'max': 3,
  'null_count': 0,
  'distinct_count': 0,
  'num_values': 3,
  'physical_type': 'INT64'},
 'compression': 'ZSTD',
 'encodings': ('RLE_DICTIONARY', 'PLAIN', 'RLE'),
 'has_dictionary_page': True,
 'dictionary_page_offset': 4,
 'data_page_offset': 47,
 'total_compressed_size': 123,
 'total_uncompressed_size': 109}
```

### Expected behavior

Would expect pl's write_parquet to write those min/max values when statistics=True

**Comment by ritchie46** [comment] 2022-10-22 09:22
Shall I take this one upstream @jorgecarleitao ?

**Comment by jorgecarleitao** [comment] 2022-10-22 18:26
This is by design - min/max have been replaced by min_value/max_value 5 years ago or so and parquet recommends users not to use it since the ordering is not correct.

**Comment by ritchie46** [comment] 2022-10-24 10:29
Thanks for the clarification. :+1: I will close this as this is not a bug and polars uses `min_value` and `max_value` internally.

**Closed by ritchie46** 2022-10-24 10:29 UTC
Labels: bug
