### ISSUE TITLE
Can't sink parquet from pyarrow dataset scan

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#13605] opened 2024-01-10 16:27 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pyarrow.dataset as ds
import polars as pl

df = pl.DataFrame({
    "foo": [1,2,3,4,5]
})
df.write_parquet('test.parquet')

data = ds.dataset('test.parquet')
pl.scan_pyarrow_dataset(data).sink_parquet('result.parquet')
```

```
InvalidOperationError: sink_Parquet(ParquetWriteOptions { compression: Zstd(None), statistics: false, row_group_size: None, data_pagesize_limit: None, maintain_order: true }) not yet supported in standard engine. Use 'collect().write_parquet()'
```

### Issue description

Sinking from a pyarrow dataset scan returns invalid operation. Seems odd to me to not have this, can't we stream the recordbatches into polars and then sink from there?

This is slightly annoying because it's now not possible to read a delta lake table and then sinking since I need to collect everything in memory

### Expected behavior

Being able to sink parquet just fine from a pyarrow dataset scan.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python:               3.10.12 (main, Aug  9 2023, 14:47:34) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            0.15.1
fsspec:               2023.10.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.1
numpy:                1.23.5
openpyxl:             3.1.2
pandas:               1.5.3
pyarrow:              14.0.2
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.50
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9
```

</details>

**Comment by deanm0000** [comment] 2024-01-10 22:39
Is this a bug?I thought there was never a time that pyarrow datasets were streaming.

**Comment by ion-elgreco** [comment] 2024-01-11 07:23
@deanm0000 it looks like a bug because there is no indication anywhere of this not being supported

**Comment by ritchie46** [comment] 2024-01-11 09:46
This is not a bug?  Pyarrow datasets are not supported streaming. We also shouldn't have a bug report for all possible ways we don't support streaming.

You can add (if there isn't already) a feature request to support the pyarrow scanner in streaming. 

Will close this.

**Closed by ritchie46** 2024-01-11 09:46 UTC
Labels: bug, python

**Comment by ion-elgreco** [comment] 2024-01-11 10:23
@ritchie46 shouldn't there be a more graceful error here then, InvalidOperationError is strange, shouldn't it raise NotImplementedError instead

**Comment by deanm0000** [comment] 2024-01-11 13:14
I'd say this could be reopened as a feature request but it's already been requested https://github.com/pola-rs/polars/issues/11419

**Comment by deanm0000** [comment] 2024-01-11 17:33
`sink_parquet` is for writing when streaming. If you don't need streaming then use `.collect().write_parquet()`.

**Comment by ritchie46** [comment] 2024-01-11 17:51
It's invalid if not all of the query is streaming. There might even be operations we never will do streaming.

**Comment by ion-elgreco** [comment] 2024-01-11 17:52
But I didn't set streaming to True so I don't really follow

**Comment by deanm0000** [comment] 2024-01-11 18:07
sink_parquet doesn't have a streaming parameter because it is always/only streaming.

**Comment by ion-elgreco** [comment] 2024-01-11 18:09
Aaaah my bad I messed collect streaming and sink in my mind

**Comment by deanm0000** [comment] 2024-01-11 18:13
Ha, no worries (from me anyway) BTW the error you copy-pasted in does say to use `.collect().write_parquet()`. It's all the way off the right so maybe your IDE doesn't word wrap?
