### ISSUE TITLE
Support reading `.xls` files

### ISSUE THREAD

**Issue by amplifinn-admin** [pola-rs/polars#12534] opened 2023-11-17 07:02 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

>>> df =pl.read_excel('RefundDetails_REC_TATA1_2023101001360965_23101016_19.xls')
Traceback (most recent call last):
  File "/opt/ngerecon/env3.9/lib/python3.9/site-packages/xlsx2csv.py", line 201, in __init__
    self.ziphandle = zipfile.ZipFile(xlsxfile)
  File "/usr/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ngerecon/env3.9/lib/python3.9/site-packages/polars/io/spreadsheet/functions.py", line 244, in read_excel
    return _read_spreadsheet(
  File "/opt/ngerecon/env3.9/lib/python3.9/site-packages/polars/io/spreadsheet/functions.py", line 421, in _read_spreadsheet
    reader_fn, parser, worksheets = _initialise_spreadsheet_parser(
  File "/opt/ngerecon/env3.9/lib/python3.9/site-packages/polars/io/spreadsheet/functions.py", line 491, in _initialise_spreadsheet_parser
    parser = xlsx2csv.Xlsx2csv(source, **engine_options)
  File "/opt/ngerecon/env3.9/lib/python3.9/site-packages/xlsx2csv.py", line 203, in __init__
    raise InvalidXlsxFileException("Invalid xlsx file: " + str(xlsxfile))
xlsx2csv.InvalidXlsxFileException: Invalid xlsx file: RefundDetails_REC_TATA1_2023101001360965_23101016_19.xls

### Issue description

Unable to read .xls file in Polars

### Expected behavior

>>> df =pl.read_excel('RefundDetails_REC_TATA1_2023101001360965_23101016_19.xls')
Traceback (most recent call last):
  File "/opt/ngerecon/env3.9/lib/python3.9/site-packages/xlsx2csv.py", line 201, in __init__
    self.ziphandle = zipfile.ZipFile(xlsxfile)
  File "/usr/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ngerecon/env3.9/lib/python3.9/site-packages/polars/io/spreadsheet/functions.py", line 244, in read_excel
    return _read_spreadsheet(
  File "/opt/ngerecon/env3.9/lib/python3.9/site-packages/polars/io/spreadsheet/functions.py", line 421, in _read_spreadsheet
    reader_fn, parser, worksheets = _initialise_spreadsheet_parser(
  File "/opt/ngerecon/env3.9/lib/python3.9/site-packages/polars/io/spreadsheet/functions.py", line 491, in _initialise_spreadsheet_parser
    parser = xlsx2csv.Xlsx2csv(source, **engine_options)
  File "/opt/ngerecon/env3.9/lib/python3.9/site-packages/xlsx2csv.py", line 203, in __init__
    raise InvalidXlsxFileException("Invalid xlsx file: " + str(xlsxfile))
xlsx2csv.InvalidXlsxFileException: Invalid xlsx file: RefundDetails_REC_TATA1_2023101001360965_23101016_19.xls

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-5.15.0-1047-aws-aarch64-with-glibc2.31
Python:              3.9.18 (main, Aug 25 2023, 13:20:04) 
[GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  0.7.0
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           0.12.0
fsspec:              2023.1.0
gevent:              21.8.0
matplotlib:          3.4.3
numpy:               1.21.2
openpyxl:            3.1.2
pandas:              1.3.2
pyarrow:             12.0.0
pydantic:            1.8.2
pyiceberg:           0.5.0
pyxlsb:              1.0.9
sqlalchemy:          1.3.20
xlsx2csv:            0.8
xlsxwriter:          1.3.7
```

</details>

**Comment by avimallu** [comment] 2023-11-17 15:09
None of the underlying engines that Polars uses (`xlsx2csv`, `openpyxl` and `pyxlsb`) support XLS files. You'll need to use something like [`xlrd`](https://pypi.org/project/xlrd/) for this.

**Comment by amplifinn-admin** [comment] 2023-11-20 06:54
Will polars support xlrd?
if so how do we do it?

**Comment by stinodego** [comment] 2024-01-20 14:00
@alexander-beedie do we plan on supporting reading `xls` files? If not, I propose we close this as 'not planned'.

**Comment by alexander-beedie** [comment] 2024-01-21 15:15
> @alexander-beedie do we plan on supporting reading `xls` files? If not, I propose we close this as 'not planned'.

@stinodego: If it doesn't look like much work I can take a look; @avimallu's suggestion of running via `xlrd` may provide a simple answer. I'll look at it with low priority 😉 

@amplifinn-admin: could you confirm whether you tried setting any of the other optional engines that `pl.read_excel` supports? And, if you did, are you able to share the specific Excel file that raised an error?

**Comment by stinodego** [comment] 2024-01-21 15:39
If it was indeed deprecated that long ago, I think I'm with @avimallu on this one. No need to support _everything_...

**Comment by alexander-beedie** [comment] 2024-01-22 08:09
Interesting development; was looking at the `calamine` source code (which we do plan to add support for as an alternative/faster engine for reading) and it may actually support[^1] old-style ".xls" out of the box - if this turns out to be true then I'll reopen/accept this and close when `calamine` support is integrated 🤔 

[^1]: https://github.com/tafia/calamine/blob/2620510783cb150c84c4b174d3bdf461f1f68264/src/xls.rs#L141

**Comment by alexander-beedie** [comment] 2024-02-03 11:58
Confirmed: we can support this via the `calamine` engine.

**Closed** 2024-02-03 13:26 UTC
Labels: python, enhancement, accepted, A-io-excel
