### ISSUE TITLE
Allow `.agg()` to work on ungrouped data frames

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#1324] opened 2021-09-09 21:56 UTC
Sometimes it's handy to get summary statistics on an ungrouped data frame.

Example in pandas:
```python
import pandas as pd
import numpy as np

df = pd.DataFrame({'values': np.arange(1, 4)})

df.agg(avg_value = ('values', 'mean'))
```

In polars this doesn't work:
```python
import numpy as np
import polars as pl
from polars import col

df = pl.DataFrame({'values': np.arange(1, 4)})

df.agg(col('values').mean().alias('avg_value'))
```

**Comment by potter420** [comment] 2021-09-10 02:25
Hi, pretty sure you can use this:
```python
import numpy as np
import polars as pl
from polars import col

df = pl.DataFrame({'values': np.arange(1, 4)})

df.select(col('values').mean().alias('avg_value'))
```

**Comment by ritchie46** [comment] 2021-09-10 10:51
I will close this as @potter420's answer is the way to go.

**Closed by ritchie46** 2021-09-10 10:51 UTC

**Comment by markfairbanks** [comment] 2021-09-10 11:28
@ritchie46 Using `.select()` seems like a good workaround, but I still think there's a good case for `.agg()` to work for the sake of consistency.

Shouldn't the use of `.agg()` be to return summary statistics, whether on a grouped data frame or not?

**Comment by markfairbanks** [comment] 2021-09-10 11:44
Another thought - this is how it works in pandas as well as in R's dplyr. I think it will make the transition much easier for users of those libraries.

```python
# pandas
df.agg(avg = ('values', 'mean'))
df.groupby('groups').agg(avg = ('values', 'mean'))
```

```r
# dplyr
df |> summarize(avg = mean(values))
df |> group_by(groups) |> summarize(avg = mean(values))
```

**Comment by ritchie46** [comment] 2021-09-10 11:55
> @ritchie46 Using .select() seems like a good workaround, but I still think there's a good case for .agg() to work for the sake of consistency.

This is as intended. Polars expressions determine if we aggregate or not, not the context in which it is ran.

The context are as followed:

* `select`: selects data from `df`
* `with_columns`: add data to `df`
* `groubby(..).agg`: selects data from `df` on a per group basis

The expressions determine how we manipulate the data we select. We don't even have to aggregate in a `.agg` context. 

```python
df.groupby("bar).agg(col("foo")..sort())
```

Is perfectly valid. 


> Another thought - this is how it works in pandas as well as in R's dplyr. I think it will make the transition much easier for users of those libraries.

A counter example:

```sql
SELECT avg("bar") FROM "table"
```

Polars' API is different from pandas and does not aim to be similar.

**Comment by markfairbanks** [comment] 2021-09-10 12:15
Gotcha, makes sense. Thanks for the explanation 👍

And one last question - since `SELECT` works for both grouped and ungrouped syntax in sql, maybe it would be useful to allow that in polars as well?

```python
df.groupby("bar").select(col("foo").mean())
```

**Comment by ritchie46** [comment] 2021-09-10 15:41
> And one last question - since SELECT works for both grouped and ungrouped syntax in sql, maybe it would be useful to allow that in polars as well?

Yes, that would also be a fair name. The `agg` is more out of similarity with SQL's `AGGREGATE`. I think its good to have it, as it allows for disambiguation. If some did this:

```python
a = df.groubpby(..)
```

And later in the code did this:

```python
a.agg(..)
```

It is still clear that we are working on groups and not on columns.

**Comment by markfairbanks** [comment] 2021-09-10 16:59
What do you think of allowing both `.agg()` and `.select()` to work on grouped data frames? Or would you prefer that `.agg()` is the only way to do aggregations on groups?

**Comment by ritchie46** [comment] 2021-09-10 17:19
> What do you think of allowing both .agg() and .select() to work on grouped data frames? Or would you prefer that .agg() is the only way to do aggregations on groups?

That would be an alias for `.agg()`. IMO too much aliasing would clutter the api. And I like the explanation, `.agg` is on groups, `.select` is on columns.
