### ISSUE TITLE
Unexpected interaction between pl.when and pl.struct

### ISSUE THREAD

**Issue by LucasBou** [pola-rs/polars#15703] opened 2024-04-16 14:26 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

colint = pl.col("int")
colstr = pl.col("str")

a_struct = pl.struct(colint, colstr)
is_first_line = pl.col("id") == 1

resulting_expr = pl.when(is_first_line).then(a_struct)

data = pl.DataFrame({"id": [1, 2], "int": [5, 5], "str": ["str1", "str2"]})

result = data.select(resulting_expr)
print(data)
print(result)
```

### Issue description

When using a pl.Struct as the output of a [when-then-otherwise expression](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.when.html) and no otherwise clause is declared, we get a Struct with null fields.

### Expected behavior

I would expect a null to be output instead of a struct with null fields, which would be consistent with the [pl.when documentation](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.when.html#polars-when) :

> If none of the conditions are True, an optional .otherwise(<value if all statements are false>) can be appended at the end. If not appended, and none of the conditions are True, None will be returned.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.21
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              <not installed>
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by orlp** [comment] 2024-04-16 15:25
This is a duplicate of https://github.com/pola-rs/polars/issues/3462. Currently structs do not have outer nullability, and it would be a lot of work to add it.

**Closed by orlp** 2024-04-16 15:25 UTC
Labels: bug, python, needs triage
