### ISSUE TITLE
`mean_horizontal` and `std_horizontal`

### ISSUE THREAD

**Issue by sun-rs** [pola-rs/polars#10010] opened 2023-07-21 04:15 UTC
### Problem description

As `pl.sum` now focus on vertical sum and `pl.sum_horizontal` focus on horizontal, hope there would be a `mean_horizontal` and `std_horizontal` to use. Thank you !

**Comment by stinodego** [comment] 2023-07-21 09:18
Duplicate of #9966

**Closed by stinodego** 2023-07-21 09:18 UTC
Labels: enhancement
