### ISSUE TITLE
"no exclude expected at this point" No way to exclude regexp selected columns

### ISSUE THREAD

**Issue by vvilhonen** [pola-rs/polars#5381] opened 2022-10-31 07:40 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Polars uses rust's regex crate that doesn't support negative lookahead. There seems to be no way to exclude columns from regexp selected set in the selection phase or with the exclude function.

### Reproducible example

```python
import polars as pl

print(pl.__version__)

df = pl.DataFrame(
    {
        "aa": [1, 2, 3],
        "ba": ["a", "b", None],
        "cc": [None, 2.5, 1.5],
    }
)

df.select(pl.col('^.*a$').exclude("ba"))

# thread '<unnamed>' panicked at 'no exclude expected at this point', /polars/polars/polars-lazy/polars-plan/src/logical_plan/conversion.rs:148:32
```

### Expected behavior

Some way to exclude columns from regexp selected set

### Installed versions

<details>

```
---Version info---
Polars: 0.14.24
Index type: UInt32
Platform: macOS-13.0-arm64-arm-64bit
Python: 3.10.6 (main, Oct 24 2022, 11:04:07) [Clang 12.0.0 ]
---Optional dependencies---
```

</details>

**Comment by awendland** [comment] 2023-04-20 20:41
I'm also experiencing this issue when following the same reproduction steps with Polars 0.17.0 on Python 3.9.

**Comment by avimallu** [comment] 2023-07-17 02:15
@stijndegooijer, pinging you since you seem to be on an organization spree 😃 . This was fixed in https://github.com/pola-rs/polars/pull/9827.

**Comment by stijndegooijer** [comment] 2023-07-17 08:01
@avimallu Thanks, confirmed that this was resolved.

Please ping me on @stinodego in the future, this is my work account (will be decomissioned soon :))

**Closed** 2023-07-17 08:01 UTC
Labels: bug, python

**Comment by vvilhonen** [comment] 2023-07-17 08:02
works, thanks!
