### ISSUE TITLE
read_parquet error

### ISSUE THREAD

**Issue by hakantekbas** [pola-rs/polars#1932] opened 2021-11-29 19:54 UTC
Hi;

I'm trying to read data from parqeut file that is generated by spark. It is throwing error like this.

> Exception has occurred: ArrowNotImplementedError
Unsupported cast from string to large_utf8 using function cast_large_string
  File "/data/hakan/goTurkeyTempData/testKod.py", line 12, in <module>
    tempDf = pl.read_parquet(file,columns=["InsertedDateYilAyGun"])

There is a long string field. but pandas can read. Version of polars installed is latest version.

Data Sample:
![image](https://user-images.githubusercontent.com/19631334/143936573-b2f03fcc-b769-4dae-9e48-f4c88e20fbd0.png)

Thanks.

**Comment by ritchie46** [comment] 2021-11-29 20:51
If you `pip install pyarrow` it should work.

**Comment by jorgecarleitao** [comment] 2021-11-29 20:59
Is this something on the arrow2 side?

**Comment by ritchie46** [comment] 2021-11-29 21:06
I wanted to check this tomorrow. My first guess is cast from utf8 to large-utf8.

**Comment by hakantekbas** [comment] 2021-11-30 05:15
> If you `pip install pyarrow` it should work.

pyarrow exists in environment.

![image](https://user-images.githubusercontent.com/19631334/143989639-4e00b3ba-f36f-4972-a9e4-1559a6601b72.png)

**Comment by hakantekbas** [comment] 2021-11-30 05:41
if it helps you to spot the problem, you can convert from pandas to polars dataframe after you read data with pandas.

If you try to convert whole dataframe from pandas  to polars and then write to new parquet file, there is an another error coming when reading this dataframe with polars

> Invalid: Invalid read (offset = 4, size = -1111698137)
  File "/data/hakan/goTurkeyTempData/testKod.py", line 27, in <module>
    dataFull = pl.read_parquet("dataFull.parquet")

**Comment by zundertj** [comment] 2021-11-30 06:20
Note that pyarrow is at version 6.0.1 currently (see https://pypi.org/project/pyarrow/#history). Not sure if this solves your problem, but might be worth upgrading.

**Comment by hakantekbas** [comment] 2021-11-30 07:16
Sorry for wrong alert. @zundertj  is right about version problem. when I upgrade to version 6, it is running properyl. But if I don't force polars to use pyarrow when writing parquet, it is throwing invalid read error again. Is it expected behaviour?

Thanks.

**Comment by ritchie46** [comment] 2021-11-30 07:17
Could you share yout parquet file?

**Comment by jorgecarleitao** [comment] 2021-11-30 07:21
> Sorry for wrong alert. @zundertj is right about version problem. when I upgrade to version 6, it is running properyl. But if I don't force polars to use pyarrow when writing parquet, it is throwing invalid read error again. Is it expected behaviour?
> 
> Thanks.

Likely a bug in either parquet2 or arrow2. As @ritchie46 said, could you share it or a minimal example reproducing it (e.g. write using pyarrow or pyspark and reading in polars). This will allow us to track it down and fix it upstream.

**Comment by hakantekbas** [comment] 2021-11-30 07:33
parquet file is approximately 6 gb. it includes more than 70 millions rows data. I will try to create a small example to replicate same error.

**Comment by ghuls** [comment] 2021-11-30 08:26
> Sorry for wrong alert. @zundertj is right about version problem. when I upgrade to version 6, it is running properyl. But if I don't force polars to use pyarrow when writing parquet, it is throwing invalid read error again. Is it expected behaviour?
> 
> Thanks.

Did you mean reading instead of writing?
You can also try to write your spark parquet data without compression or a different compression scheme, to see if the bug only appears for certain compressions or that it happens after decompression.

**Comment by hakantekbas** [comment] 2021-11-30 09:41
yes. When I'm writing, it is not throwing error. But read command triggers error. (if I don't set pyarrow parameter to true)

**Comment by hakantekbas** [comment] 2021-11-30 17:46
I'm trying to replicate same error again but another error appeared. Is there any constraint for buffer size? My dataframe is approx. 80 millions. If I add use_pyarrow=True, problem disappears.

> dataFull.to_parquet("dataFull2.parquet")


> RuntimeError: Any(ArrowError(ExternalFormat("External format error: underlying snap error: snappy: input buffer (size = 3927930485) is larger than allowed (size = 4294967295)")))

**Comment by jorgecarleitao** [comment] 2021-11-30 17:49
interesting! that error comes from on the snappy library we use to decompress. It seems that they committed to using `u32`, because https://en.wikipedia.org/wiki/4,294,967,295

**Comment by ritchie46** [comment] 2021-11-30 17:58
> interesting! that error comes from on the snappy library we use to decompress. It seems that they committed to using `u32`, because https://en.wikipedia.org/wiki/4,294,967,295

Wow.. that seems to be quite easily met of we talk about no of bytes.

**Comment by alippai** [comment] 2021-11-30 18:07
https://github.com/BurntSushi/rust-snappy/issues/33 the conclusion is interesting :S

**Comment by hakantekbas** [comment] 2021-11-30 18:15
It seems small files generated in spark will not cause this type of problem. How does pyarrow skip this error? don't we use snappy when we set **use_pyarrow** parameter to True?

**Comment by jorgecarleitao** [comment] 2021-11-30 18:24
fwiw this could also be a bug on arrow2 or parquet2, where it incorrectly read the page and interpret 4 bytes on the page as the header of snappy when it is something else. We have integration tests against pyarrow's writer under snappy compression, but it cannot be discarded at this point.

This would require some digging into the particular column (and row group) that is causing this. This information is present in the footer, so if @hakantekbas is allowed to share the metadata, I would try that.

To print metadata to stdout, run `cargo run --example read_metadata -- <path_fo_file>` on https://github.com/jorgecarleitao/parquet2

**Comment by hakantekbas** [comment] 2021-11-30 19:36
@jorgecarleitao I will share this before the end of this week. Thanks.

**Comment by hakantekbas** [comment] 2021-12-07 05:05
@jorgecarleitao I can't replicate this issue after I updated to new version. I will put this issue on hold for a while. If it does not appear again, I will close this issue.

**Comment by zundertj** [comment] 2022-01-14 17:40
@hakantekbas : can this be closed?

**Closed** 2022-01-14 18:08 UTC
