### ISSUE TITLE
Add a "remaining" columns selector

### ISSUE THREAD

**Issue by avimallu** [pola-rs/polars#9218] opened 2023-06-04 14:32 UTC
### Problem description

Follow up from very short discussion from the excellent feature addition on #9204.

I wish I could have an easy function that would allow for "selecting all columns that are not explicitly (via name or `pl.col("...")` calls) or implicitly (via the new `polars.selectors` calls) specified". Let's say that I have a DataFrame object `df` with columns `id`, `aaa`, `bbb`, `cc`, `dddd`, `efg`, `hij`. When I add new columns:

```py
df = (
  df
  .with_columns(
    pl.col("aaa").str.concat("bbb").alias("new_1"),
    pl.col("cc").add.(pl.col("ddd")).alias("new_2"),
    pl.col("efg").str.to_uppercase().alias("new_3")
  )
```

I want to be able to easily reorder *within* the piping of operations such that `id`, `new_1`, `new_3` and `new_2` appear first followed by the rest of the columns:

```py
df = (
  df
  .with_columns(
    pl.col("aaa").str.concat("bbb").alias("new_1"),
    pl.col("cc").add.(pl.col("ddd")).alias("new_2"),
    pl.col("efg").str.to_uppercase().alias("new_3"))
  .select(
    pl.col("id"),
    s.matches("new_.*"), # From 9204
    s.remaining())
)
```

This will also help in cases of *existing* DataFrame objects, where I want to rearrange just a few columns:

```py
df.select(pl.col("id", "efg", "hij"), s.remaining())
```

Without explicitly creating a loop comprehension or another `pl.all().exclude(["id", "efg", "hij"])` statement where I have to redundantly specify `["id", "efg", "hij"]`.

**Comment by stinodego** [comment] 2023-08-09 18:27
Closing in favor of #10394 as there has been more discussion there.

**Comment by stinodego** [comment] 2023-08-09 18:28
Duplicate of #10394

**Closed by stinodego** 2023-08-09 18:28 UTC
Labels: enhancement
