### ISSUE TITLE
Allow string operations on Categorical types

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#7647] opened 2023-03-19 15:37 UTC
### Problem description

I wish I could take advantage of Categorical types to only modify unique values.

Here is an example:

```
import polars as pl

df = pl.DataFrame({
    'a' : ['United Kingdom', 'United States', 'France']
}, schema=[('a', pl.Categorical)])

df10000 = pl.DataFrame({
    'a' : ['United Kingdom', 'United States', 'France'] * 10_000
}, schema=[('a', pl.Categorical)])

# I have 3 unique values in both dataframes, so I would like to modify only those 3 values.
# Here are the time results

df.with_columns(
    pl.col('a').cast(pl.Utf8).str.to_uppercase()
)
# 133 µs ± 1.41 µs per loop

df10000.with_columns(
    pl.col('a').cast(pl.Utf8).str.to_uppercase()
)
# 1.1 ms ± 151 µs per loop

```
I understand that the problem in my test is that I'm converting all columns to Utf8, thus losing the benefit of the Categorical type. That is why I wish I could apply .str methods to categoricals.

Pandas seem to allow using .str methods with categoricals:

```
import pandas as pd

df10000_pd = df10000.to_pandas()

df10000_pd.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   a       30000 non-null  category
dtypes: category(1)

df10000_pd.a.str.upper()
#228 µs ± 5.54 µs per loop
```

Any thoughts? 
Are there different ways to achieve this that are already available?

**Comment by mcrumiller** [comment] 2023-03-20 13:34
+1 for this. I had a few huge projects in Matlab that would make extensive use of categoricals, and being able to change the underlying categories, find unique values, etc. was a huge plus.

IMO the API would be greatly improved with the following:

* `*.cat.categories`: return list or Series of categories.
* `*.cat.category_map`: return dict mapping or 2-column dataframe with str : int mappings.
* `*.cat.rename_categories(dict)`: rename categories without updating codings. Should be super fast.

**Comment by mcrumiller** [comment] 2023-03-20 13:38
Oh, another thing I liked: being able to set the actual ordering of the categories by value (i.e. physical ordering, but set the order of the values). So if you had:

```python
s = pl.Series(['a', 'b', 'c', 'd', 'e'], dtype=pl.Categorical)
s.sort()
```
```
Series: '' [cat]
[
        "a"
        "b"
        "c"
        "d"
        "e"
]
```

You could later re-order via

```
s.cat.reorder_categories(['e', 'd', 'c', 'b', 'a']).sort()
```
```
Series: '' [cat]
[
        "e"
        "d"
        "c"
        "b"
        "a"
]
```

**Comment by lucazanna** [comment] 2023-03-20 17:19
Hi @mcrumiller,

When you say `.cat.rename_categories(dict)`, you mean modifying directly the dictionary array ?
So we are not changing the mapping of each row to the dictionary values, but only modifying the dictionary values.

For setting the order of a category, I believe that is possible by doing within the same StringCache:
- creating a new Series with the correct order and casting it to Categorical
- casting the column to reorder to string, and then casting it again to Categorical

**Comment by mcrumiller** [comment] 2023-03-20 17:27
@lucazanna will that update all categorical arrays that reference the same string cache? We can test:

```python
import polars as pl

with pl.StringCache():
    s1 = pl.Series(['a', 'b', 'c'], dtype=pl.Categorical)
    s2 = pl.Series(['c', 'b', 'a'], dtype=pl.Categorical)

    print(s1.sort())
    print(s2.sort())
```

Answer: nope, each series has its own mapping/ordering, we can see that they re-use the indexes though:

```python
print(s1.to_physical())
print(s2.to_physical())
```
```
shape: (3,)
Series: '' [u32]
[
        0
        1
        2
]
shape: (3,)
Series: '' [u32]
[
        2
        1
        0
]
```
Each series must have its own ordering, so creating a new Series with the newly-desired order won't have any effect. Even if we say:

```
s2 = s2.cat.set_ordering("physical")
print(s2.sort())
```
```
shape: (3,)
Series: '' [u32]
[
        2
        1
        0
]
```
it doesn't order based on the actual physical values, it uses the original order map.

**Comment by mcrumiller** [comment] 2023-03-20 17:30
Based on this, I think an `ordering="explicit"` would make more sense as opposed to `ordering="physical"`, since it doesn't seem to actually depend on the result indicated by `Series.to_physical()`, it's some ordering of the underlying physical data.

Also, putting the ordering into the constructor makes a lot of sense to me:

```python
s = pl.Series(['c', 'b' ,'a'], dtype=pl.Categorical("lexical"))
```

or alternatively, add in a `pl.Categorical` constructor to do the same thing but with more flexibility:

```python
`s = pl.Categorical(['a', 'b', 'c'], categories=['c', 'b', 'd', 'a'], ordering="explicit")
```

**Comment by lucazanna** [comment] 2023-03-20 18:09
Hi @mcrumiller ,

I tried running your first example:

```
import polars as pl

with pl.StringCache():
    s1 = pl.Series(['a', 'b', 'c'], dtype=pl.Categorical)
    s2 = pl.Series(['c', 'b', 'a'], dtype=pl.Categorical)

    print(s1.sort())
    print(s2.sort())
```
I get:
```
shape: (3,)
Series: '' [cat]
[
	"a"
	"b"
	"c"
]
shape: (3,)
Series: '' [cat]
[
	"a"
	"b"
	"c"
]
```

So it looks like both series were sorted based on the order of the first series. (which is the order of the elements created under string cache). You mean something different?

I agree with you that making this more explicit with something like `.reorder_categories()` would be easier to read and easier to understand for newcomers to Polars.

**Comment by Wainberg** [comment] 2023-11-23 03:28
This issue can be closed as a duplicate of https://github.com/pola-rs/polars/issues/9773

**Comment by Wainberg** [comment] 2024-01-20 03:48
@stinodego you can close this one as a duplicate

**Comment by stinodego** [comment] 2024-01-20 12:22
Closing in favor of #7647

**Closed by stinodego** 2024-01-20 12:22 UTC
Labels: enhancement
