### ISSUE TITLE
`scan_csv` does not work on s3 path while `read_csv` works

### ISSUE THREAD

**Issue by michael72** [pola-rs/polars#13115] opened 2023-12-19 06:48 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
some_s3_file = f"s3://{BUCKET}/data.csv"
pl.read_csv(some_s3_file) # works
pl.scan_csv(some_s3_file) # doesn't work
```

### Log output

```shell
2023-12-19 07:43:57,983 - analysis_helper - ERROR - No such file or directory (os error 2): s3://*****************/data.csv
```

### Issue description

`scan_csv` fails reading s3 data

### Expected behavior

`scan_csv` should at least support the same locations as `read_csv`

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.1
Index type:           UInt32
Platform:             Linux-5.19.0-46-generic-x86_64-with-glibc2.35
Python:               3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
matplotlib:           3.7.2
numpy:                1.26.0
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              14.0.1
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment] 2023-12-19 15:43
Can you show a repro? I cannot reproduce?

**Comment by edblackburn** [comment] 2024-01-23 08:43
Hi @ritchie46 is there a plan to do introduce scanning CSV files from object storage like S3? Is it on a roadmap? Is there a roadmap I can look at, sorry if this is in neon lights elsewhere and I missed it. Are there any significant blockers, and is there anything the community can do to help? Sorry for so many questions!

**Comment by nameexhaustion** [comment] 2024-07-08 03:03
Closed by https://github.com/pola-rs/polars/pull/16674

**Closed by nameexhaustion** 2024-07-08 03:03 UTC
Labels: bug, python, needs triage, A-io-csv
