### ISSUE TITLE
pl.from_pandas fails when NaNs are in object columns

### ISSUE THREAD

**Issue by kmcentush** [pola-rs/polars#17403] opened 2024-07-03 14:18 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import pandas as pd
import polars as pl

df_pd = pd.DataFrame({"string": ["a", "b", "c", np.nan, np.nan]})
df_pl = pl.from_pandas(df_pd) # errors
```

### Log output

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 6
      3 import polars as pl
      5 df_pd = pd.DataFrame({"string": ["a", "b", "c", np.nan, np.nan]})
----> 6 df_pl = pl.from_pandas(df_pd)

File ~/mambaforge/envs/data-connector/lib/python3.10/site-packages/polars/convert/general.py:570, in from_pandas(data, schema_overrides, rechunk, nan_to_null, include_index)
    567     return wrap_s(pandas_to_pyseries("", data, nan_to_null=nan_to_null))
    568 elif isinstance(data, pd.DataFrame):
    569     return wrap_df(
--> 570         pandas_to_pydf(
    571             data,
    572             schema_overrides=schema_overrides,
    573             rechunk=rechunk,
    574             nan_to_null=nan_to_null,
    575             include_index=include_index,
    576         )
    577     )
    578 else:
    579     msg = f"expected pandas DataFrame or Series, got {type(data).__name__!r}"

File ~/mambaforge/envs/data-connector/lib/python3.10/site-packages/polars/_utils/construction/dataframe.py:1048, in pandas_to_pydf(data, schema, schema_overrides, strict, rechunk, nan_to_null, include_index)
   1043 convert_index = include_index and not _pandas_has_default_index(data)
   1044 if not convert_index and all(
   1045     is_simple_numpy_backed_pandas_series(data[col]) for col in data.columns
   1046 ):
   1047     # Convert via NumPy directly, no PyArrow needed.
-> 1048     return pl.DataFrame(
   1049         {str(col): data[col].to_numpy() for col in data.columns},
   1050         schema=schema,
   1051         strict=strict,
   1052         schema_overrides=schema_overrides,
   1053         nan_to_null=nan_to_null,
   1054     )._df
   1056 if not _PYARROW_AVAILABLE:
   1057     msg = (
   1058         "pyarrow is required for converting a pandas dataframe to Polars, "
   1059         "unless each of its columns is a simple numpy-backed one "
   1060         "(e.g. 'int64', 'bool', 'float32' - not 'Int64')"
   1061     )

File ~/mambaforge/envs/data-connector/lib/python3.10/site-packages/polars/dataframe/frame.py:360, in DataFrame.__init__(self, data, schema, schema_overrides, strict, orient, infer_schema_length, nan_to_null)
    355     self._df = dict_to_pydf(
    356         {}, schema=schema, schema_overrides=schema_overrides
    357     )
    359 elif isinstance(data, dict):
--> 360     self._df = dict_to_pydf(
    361         data,
    362         schema=schema,
    363         schema_overrides=schema_overrides,
    364         strict=strict,
    365         nan_to_null=nan_to_null,
    366     )
    368 elif isinstance(data, (list, tuple, Sequence)):
    369     self._df = sequence_to_pydf(
    370         data,
    371         schema=schema,
   (...)
    375         infer_schema_length=infer_schema_length,
    376     )

File ~/mambaforge/envs/data-connector/lib/python3.10/site-packages/polars/_utils/construction/dataframe.py:159, in dict_to_pydf(data, schema, schema_overrides, strict, nan_to_null, allow_multithreaded)
    146     data_series = [
    147         pl.Series(
    148             name,
   (...)
    154         for name in column_names
    155     ]
    156 else:
    157     data_series = [
    158         s._s
--> 159         for s in _expand_dict_values(
    160             data,
    161             schema_overrides=schema_overrides,
    162             strict=strict,
    163             nan_to_null=nan_to_null,
    164         ).values()
    165     ]
    167 data_series = _handle_columns_arg(data_series, columns=column_names, from_dict=True)
    168 pydf = PyDataFrame(data_series)

File ~/mambaforge/envs/data-connector/lib/python3.10/site-packages/polars/_utils/construction/dataframe.py:388, in _expand_dict_values(data, schema_overrides, strict, order, nan_to_null)
    385     updated_data[name] = s
    387 elif arrlen(val) is not None or _is_generator(val):
--> 388     updated_data[name] = pl.Series(
    389         name=name,
    390         values=val,
    391         dtype=dtype,
    392         strict=strict,
    393         nan_to_null=nan_to_null,
    394     )
    395 elif val is None or isinstance(  # type: ignore[redundant-expr]
    396     val, (int, float, str, bool, date, datetime, time, timedelta)
    397 ):
    398     updated_data[name] = F.repeat(
    399         val, array_len, dtype=dtype, eager=True
    400     ).alias(name)

File ~/mambaforge/envs/data-connector/lib/python3.10/site-packages/polars/series/series.py:299, in Series.__init__(self, name, values, dtype, strict, nan_to_null)
    296     self._s = sequence_to_pyseries(name, [], dtype=dtype)
    298 elif _check_for_numpy(values) and isinstance(values, np.ndarray):
--> 299     self._s = numpy_to_pyseries(
    300         name, values, strict=strict, nan_to_null=nan_to_null
    301     )
    302     if values.dtype.type in [np.datetime64, np.timedelta64]:
    303         # cast to appropriate dtype, handling NaT values
    304         input_dtype = _resolve_temporal_dtype(None, values.dtype)

File ~/mambaforge/envs/data-connector/lib/python3.10/site-packages/polars/_utils/construction/series.py:442, in numpy_to_pyseries(name, values, strict, nan_to_null)
    440     values, dtype = numpy_values_and_dtype(values)
    441     constructor = numpy_type_to_constructor(values, dtype)
--> 442     return constructor(
    443         name, values, nan_to_null if dtype in (np.float32, np.float64) else strict
    444     )
    445 elif sum(values.shape) == 0:
    446     # Optimize by ingesting 1D and reshaping in Rust
    447     original_shape = values.shape

TypeError: 'float' object cannot be converted to 'PyString'
```

### Issue description

Issues converting from Pandas to Polars when a column is of type `object` but contains NaNs.

It seems like `nan_to_null` is not taking effect, or at least not in the right order.

### Expected behavior

Using Arrow as an intermediary gets Polars to the correct result

```python
import numpy as np
import pandas as pd
import polars as pl
import pyarrow as pa

df_pd = pd.DataFrame({"string": ["a", "b", "c", np.nan, np.nan]})
df_pa = pa.Table.from_pandas(df_pd)
df_pl = pl.from_arrow(df_pa)
```

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0
Index type:           UInt32
Platform:             macOS-14.4.1-arm64-arm-64bit
Python:               3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:35:25) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.8.0
pyiceberg:            <not installed>
sqlalchemy:           2.0.31
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by stinodego** [comment] 2024-07-03 15:07
Duplicate of https://github.com/pola-rs/polars/issues/17355, a fix is already made 👍

**Closed by stinodego** 2024-07-03 15:07 UTC
Labels: bug, python, needs triage
