### ISSUE TITLE
question about polars.Expr.replace

### ISSUE THREAD

**Issue by zdlspace0528** [pola-rs/polars#12985] opened 2023-12-11 06:44 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

data = {
    'cut' : ['a', 'b', 'c', 'd']
}

df1 = pl.DataFrame(data=data)

df1.with_columns(pl.col('cut').replace({'a':1, 'b':2, 'c':3, 'd':4}).alias('cut_new'))

─────┬─────────┐
│ cut ┆ cut_new │
│ --- ┆ ---     │
│ str ┆ str     │
╞═════╪═════════╡
│ a   ┆ null    │
│ b   ┆ null    │
│ c   ┆ null    │
│ d   ┆ null    │
└─────┴─────────┘

```
What's wrong with this? why does the result is all null? 

### Issue description

What's wrong with this? why does the result is all null? 

### Expected behavior

┌─────┬─────────┐
│ cut ┆ cut_new │
│ --- ┆ ---     │
│ str ┆ i64     │
╞═════╪═════════╡
│ a   ┆ 1       │
│ b   ┆ 2       │
│ c   ┆ 3       │
│ d   ┆ 4       │
└─────┴─────────┘

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             macOS-14.1.2-arm64-arm-64bit
Python:               3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.3
pyarrow:              14.0.1
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by zdlspace0528** [comment] 2023-12-11 06:50
When I use `map_dict`, it will get the results I wanted. but it remind me that `map_dict` is deprecated.
```python
df1.with_columns(pl.col('cut').map_dict({'a':1, 'b':2, 'c':3, 'd':4}).alias('cut_new'))
┌─────┬─────────┐
│ cut ┆ cut_new │
│ --- ┆ --- │
│ str ┆ i64 │
╞═════╪═════════╡
│ a ┆ 1 │
│ b ┆ 2 │
│ c ┆ 3 │
│ d ┆ 4 │
└─────┴─────────┘

DeprecationWarning: `map_dict` is deprecated. It has been renamed to `replace`. The default behavior has changed to keep any values not present in the mapping unchanged. Pass `default=None` to keep existing behavior.
```

**Comment by stinodego** [comment] 2023-12-11 08:06
Duplicate of [#12728](https://github.com/pola-rs/polars/issues/12728)

You must provide `default=None`. We are working on a fix!

**Closed by stinodego** 2023-12-11 08:06 UTC
Labels: bug, python
