### ISSUE TITLE
Add formatting using format specifiers

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#11297] opened 2023-09-25 07:30 UTC
## Use Case
- a very common use case is to format values (especially numbers) according to a defined format
- python: f-strings, `.format` and more. Formatting: https://docs.python.org/3/library/string.html#format-specification-mini-language
- rust: `format!` marco. Formatting: https://doc.rust-lang.org/std/fmt/
- Note: `pl.format` does NOT support format specifiers! (confusing naming, it is rathing combining column values to a string)

### Easy
```python
val = 123456.789
f'Value: {val:.2f}!!!'
# 'Value: 123456.79!!!'
```

### Advanced
```python
# fill: _
# align: right
# sign: yes
# width: 20
# precision: 2
# type: float
f'Value: {val:_>+20.2f}!!!'
# 'Value: __________+123456.79!!!'
```

## Current Solution (`map_elements`: slow)
```python
df.with_columns(
    pl.col('...').map_elements(lambda x: f'value: {x:+08}!!')
)
ser.map_elements(lambda x: f'value: {x:+08}!!')
```

## Desired Solution (native integration in `str` namespace)
```python
df.with_columns(
    pl.col('...').str.format('value: {:+08}!!')
)
ser.str.format('value: {:+08}!!')
```

**Comment by cmdlineluser** [comment] 2023-09-25 12:26
Some previous discussion which may be relevant: #7133

**Comment by mcrumiller** [comment] 2023-09-26 00:31
Maybe we could first decide on a formatting syntax (do we want to use [python format specifiers](https://docs.python.org/3/library/string.html#format-specification-mini-language) or [rust format specifiers](https://doc.rust-lang.org/std/fmt/#syntax)), and then maybe incrementally supply

1) the capability (via a series of expressions), as in my (pretty old by now) solution (which would probably be greatly improved), with the future possibility of 2)

2) is not going to be easy due to `std::fmt` [requiring a string literal](https://doc.rust-lang.org/std/fmt/)

**Comment by stinodego** [comment] 2023-09-26 09:03
I'm closing this as a duplicate of https://github.com/pola-rs/polars/issues/7133.

If it's not a duplicate, please elaborate.

**Closed by stinodego** 2023-09-26 09:03 UTC
Labels: enhancement
