### ISSUE TITLE
Literal int column type different than cast to int column type

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2290] opened 2022-01-06 19:42 UTC
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.12.8

#### What operating system are you using polars on?

CentOS Linux release 8.1.1911 (Core)

#### Describe your bug.

Adding the literal value `1` to a dataframe doesn't results in a column with the same data type (specifically, same number of bits) as adding that value then casting it to the type `int`. This is nonintuitive as `1` in python is conceptually an `int`.

#### What are the steps to reproduce the behavior?

```
>>> pl.DataFrame({"a": [1, 2], "b": ["a", "b"]}).with_column(pl.lit(1))
shape: (2, 3)
┌─────┬─────┬─────────┐
│ a   ┆ b   ┆ literal │
│ --- ┆ --- ┆ ---     │
│ i64 ┆ str ┆ i32     │
╞═════╪═════╪═════════╡
│ 1   ┆ a   ┆ 1       │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ b   ┆ 1       │
└─────┴─────┴─────────┘
>>> pl.DataFrame({"a": [1, 2], "b": ["a", "b"]}).with_column(pl.lit(1).cast(int))
shape: (2, 3)
┌─────┬─────┬─────────┐
│ a   ┆ b   ┆ literal │
│ --- ┆ --- ┆ ---     │
│ i64 ┆ str ┆ i64     │
╞═════╪═════╪═════════╡
│ 1   ┆ a   ┆ 1       │
├╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2   ┆ b   ┆ 1       │
└─────┴─────┴─────────┘
```

Notice that one is an `i32` and the other is an `i64`. I guess it's possible that this is intentional, but that's at least not obvious to me.

**Comment by ritchie46** [comment] 2022-01-06 20:17
This is intentional. You cast with an `int` this is mapped to an `Int64`. If you want more control you need to cast with polars dtypes.

We prefer Int32 because that's less memory.

**Comment by ritchie46** [comment] 2022-01-06 20:17
I will close this because its not a bug. Discussion can continue.

**Closed by ritchie46** 2022-01-06 20:17 UTC

**Comment by LiterallyUniqueLogin** [comment] 2022-01-06 21:15
Good to know! It came up because of this: https://github.com/pola-rs/polars/issues/2292 . The two together led to surprising results, though I'm not sure either is unintended by itself.
