### ISSUE TITLE
`read_ndjson` with null column drops the column

### ISSUE THREAD

**Issue by CHDev93** [pola-rs/polars#8572] opened 2023-04-28 15:23 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When reading a file with `read_ndjson` that has a column that is null, this column gets dropped from the result dataframe rather than being included with a column with a single null entry

### Reproducible example

```python
from pathlib import Path

import pandas as pd
import polars as pl

payload_w_null = """{"x":1,"text":null}"""
payload_wo_null = """{"x":1,"text":"a"}"""

file_w_null = "jsonwithnull.jsonl"
file_wo_null = "jsonwithoutnull.jsonl"
Path(file_w_null).write_text(payload_w_null)
Path(file_wo_null).write_text(payload_wo_null)
print(
    pl.read_ndjson(file_w_null),
    pl.read_ndjson(file_wo_null),
    pd.read_json(file_w_null, lines=True),
    sep="\n",
)

# shape: (1, 1)
# ┌─────┐
# │ x   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# └─────┘
# shape: (1, 2)
# ┌─────┬──────┐
# │ x   ┆ text │
# │ --- ┆ ---  │
# │ i64 ┆ str  │
# ╞═════╪══════╡
# │ 1   ┆ a    │
# └─────┴──────┘
#    x  text
# 0  1   NaN
```

### Expected behavior

I would expect the output to match that of the below
```python
pl.DataFrame({"x": [1], "text": [None]})

shape: (1, 2)
┌─────┬──────┐
│ x   ┆ text │
│ --- ┆ ---  │
│ i64 ┆ f32  │
╞═════╪══════╡
│ 1   ┆ null │
└─────┴──────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.17.9
Index type: UInt32
Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
Python: 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2022.7.1
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: 3.1.0```

</details>

**Comment by universalmind303** [comment] 2023-04-30 21:55
duplicate of #7858

**Closed by universalmind303** 2023-04-30 21:55 UTC
Labels: bug, python
