### ISSUE TITLE
Python new release 1.0.0 causes regression.

### ISSUE THREAD

**Issue by mfahadakbar** [pola-rs/polars#17331] opened 2024-07-01 13:39 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# My Python script returned incorrect values, e.g. and sometimes produced null values, e.g. when I tried to calculate the mean, it came up empty. I converted to pandas and the results showed up. Then i downgraded to "0.20.31" and every thing went back to normal.
```

### Issue description

My Python script returned incorrect values, e.g. and sometimes produced null values, e.g. when I tried to calculate the mean, it came up empty. I converted to pandas and the results showed up. Then i downgraded to "0.20.31" and every thing went back to normal

### Expected behavior

No weird calculations

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             Linux-5.15.0-1061-azure-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            0.10.4
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.0
nest_asyncio:         1.5.6
numpy:                1.23.5
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              8.0.0
pydantic:             1.10.6
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           <not installed>```

</details>

**Comment by MarcoGorelli** [comment] 2024-07-01 13:48
hi @mfahadakbar - could you provide a reproducible example please? else there's no way to debug

have you read the upgrade guide? it _might_ help here, but it's hard to say without any details

**Comment by alexander-beedie** [comment] 2024-07-01 16:09
If you can give us a few clues? _"My Python script returned incorrect values"_ isn't currently actionable 🤔

**Comment by stinodego** [comment] 2024-07-04 11:58
Closing due to lack of reproducible example.

**Closed by stinodego** 2024-07-04 11:58 UTC
Labels: bug, python, regression, needs repro
