### ISSUE TITLE
`Hash` not consistent across polars versions

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#12034] opened 2023-10-25 17:29 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.select(pl.lit('hello world').hash(seed=0))

# polars: 0.18.15
shape: (1, 1)
┌──────────────────────┐
│ literal              │
│ ---                  │
│ u64                  │
╞══════════════════════╡
│ 14425472981513696975 │
└──────────────────────┘

# polars: 0.19.11
shape: (1, 1)
┌──────────────────────┐
│ literal              │
│ ---                  │
│ u64                  │
╞══════════════════════╡
│ 5931213245716154761│
└──────────────────────┘


```

### Issue description

The hashing doesn't return the same value since v0.19. This is really breaking because my tables were relying on the fact that I could create a surrogate key with a hash from multiple columns to join on. Now that the hash doesn't return the same value it means I can't do upserts anymore since the key won't match, which will result in duplicate data :(

Before I compared all v0.16 up until 0.18.15 and the hash was always consistent. If the hash is not intended for this use, could there then be another hashing function added where it stays consistent across all polars versions?

### Expected behavior

Return the same value as in older polars versions.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by ritchie46** [comment] 2023-10-26 05:26
This is not a bug. We don't guarantee stable hashes/plans/abi accross versions.

I believe there is already a feature request for supporting user defined hash functions.

I will close this one.

**Closed by ritchie46** 2023-10-26 05:26 UTC
Labels: bug, python

**Comment by ion-elgreco** [comment] 2023-10-26 07:49
@ritchie46 I think this needs to be clarified well in the docs then. I know that multiple folks are using the hashing function to create unique identifiers for their tables.
