### ISSUE TITLE
'Option::unwrap()' PanicException on estimated_size with pl.Object dtype

### ISSUE THREAD

**Issue by dpinol** [pola-rs/polars#15835] opened 2024-04-22 20:49 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl
pl.Series(np.array([[[2]]])).estimated_size()
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-arrow/src/compute/aggregate/memory.rs:68:18:
called `Option::unwrap()` on a `None` value
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[19], line 1
----> 1 pl.Series(np.array([[[2]]])).estimated_size()

File ~/.local/share/virtualenvs/sc-api-DipHMMiG/lib/python3.11/site-packages/polars/series/series.py:1523, in Series.estimated_size(self, unit)
   1493 def estimated_size(self, unit: SizeUnit = "b") -> int | float:
   1494     """
   1495     Return an estimation of the total (heap) allocated size of the Series.
   1496 
   (...)
   1521     3.814697265625
   1522     """
-> 1523     sz = self._s.estimated_size()
   1524     return scale_bytes(sz, unit)

PanicException: called `Option::unwrap()` on a `None` value
```

### Issue description

`pl.Series(np.array([[[2]]]))` correctly generates a Series of 2D np.arrays. However, `estimated_size()` panics with a low level error. 
oth, `pl.Series(np.array([[2]])).estimated_size()` works fine

### Expected behavior

It should return a size estimation.

### Installed versions

<details>

```
Polars:               0.20.22
Index type:           UInt32
Platform:             Linux-6.5.0-9-generic-x86_64-with-glibc2.38
Python:               3.11.5 (main, Sep 20 2023, 13:23:03) [GCC 12.2.0]
```

</details>

**Comment by coastalwhite** [comment] 2024-06-17 12:31
This does not reproduce anymore and seems to be fixed. Closing.

**Closed by coastalwhite** 2024-06-17 12:31 UTC
Labels: bug, python, P-low, A-dtype-object, A-panic

**Comment by howsiyu** [comment] 2024-07-10 14:34
```python
import polars as pl
from enum import Enum

Color = Enum("Color", ["RED", "GREEN", "BLUE"])

pl.Series([Color.RED]).estimated_size()
```

I get the same error with list of python's Enum.
