### ISSUE TITLE
Handling of null values in rolling

### ISSUE THREAD

**Issue by ZzzzHeJ** [pola-rs/polars#17474] opened 2024-07-07 13:03 UTC
### Description

In Polars 1.0.0, when using functions like rolling_sum and specifying a weight, the input sequence must not contain any null values. Is there a way to make it support null values? For example, when there are null values within the rolling window, the aggregation should return a null value.

```python
index = pl.Series([2,None,3,1,5,7], dtype=float)

r = index.rolling_sum(3, weights=[1,2,3])
"""
can’t run, because weights not yet supported on array with null values
expect :
[null,null,null,null,20,32]
"""
```

**Comment by MarcoGorelli** [comment] 2024-07-07 13:58
thanks @ZzzzHeJ for the report

closing as duplicate of https://github.com/pola-rs/polars/issues/13771

**Closed by MarcoGorelli** 2024-07-07 13:58 UTC
Labels: enhancement

**Comment by ZzzzHeJ** [comment] 2024-07-07 14:00
I can use nan instead of None to solve this problem, which probably shouldn't have been used in the first place...
