### ISSUE TITLE
`to_dicts` is taking first row and skipping others after using groupby

### ISSUE THREAD

**Issue by gam-phon** [pola-rs/polars#6687] opened 2023-02-05 14:50 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`to_dicts` is taking first row and skipping others in groupby

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    [
        {"status": "executed", "id": 1},
        {"status": "cancelled", "id": 2},
        {"status": "cancelled", "id": 3},
    ]
)

print(df.to_dicts())
# [{'status': 'executed', 'id': 1}, {'status': 'cancelled', 'id': 2}, {'status': 'cancelled', 'id': 3}]

data = df.lazy().groupby("status").agg(pl.count()).collect()
print(data)
"""
# return:
shape: (2, 2)
┌───────────┬───────┐
│ status    ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ cancelled ┆ 2     │
│ executed  ┆ 1     │
└───────────┴───────┘
"""
print(data.to_dicts())
# return: [{'status': 'cancelled', 'count': 2}]
```

### Expected behavior

it should return all rows in DataFrame when using `to_dicts`

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: macOS-13.1-arm64-arm-64bit
Python: 3.11.1 (main, Dec 23 2022, 09:28:24) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: 0.3.2_alpha.1
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

**Comment by ritchie46** [comment] 2023-02-05 15:05
I think we don't take all chunks.

**Comment by braaannigan** [comment] 2023-02-06 22:47
@ritchie46 See the issue I've just raised, I think the issue is in `iter_rows`

**Comment by alexander-beedie** [comment] 2023-02-07 07:16
> @ritchie46 See the issue I've just raised, I think the issue is in `iter_rows`

This one's my bad - had left a debugging check in place, and the error didn't show up on single-chunk frames... :(
Fixed now.

**Closed** 2023-02-07 17:20 UTC
Labels: bug, python

**Comment by gam-phon** [comment] 2023-02-09 06:52
@alexander-beedie thanks for resolving this
@ritchie46 thanks for merging this, can you please release 0.16.3 with this fix. My application is getting missing analysis and weird behaviors because of this bug. I am waiting for this merge, Thanks in advance

**Comment by alexander-beedie** [comment] 2023-02-09 07:04
> My application is getting missing analysis and weird behaviors because of this bug. I am waiting for this merge, Thanks in advance

@gam-phon: FYI, you can (temporarily) work around the problem while waiting for the imminent `0.16.3` update by calling `df.rechunk().to_dicts()` instead of `df.to_dicts()` (and then remove the call to recheck as soon as the new version is out).

**Comment by gam-phon** [comment] 2023-02-09 07:25
@alexander-beedie Thanks, I will do it now :)
