### ISSUE TITLE
Hive Partioning Reader Bug

### ISSUE THREAD

**Issue by uditrana** [pola-rs/polars#12903] opened 2023-12-05 20:09 UTC
I am noticing an interesting pattern/bug with this new feature.
I wrote a large dataset out using
```
df.write_parquet(
            file=DIR,
            use_pyarrow=True,
            pyarrow_options={
                "partition_cols": ["part_id_1", "part_id_2"],
                "basename_template": "test_{i}.parquet",
                "existing_data_behavior": "overwrite_or_ignore",
            },
        )
```
When I read these files back in using `pl.read_parquet()`, I observe 2 different results:
```
df1 = pl.read_parquet(DIR / "part_id_1=1" / "part_id_2="A" / "test_0.parquet")
df2 = pl.read_parquet(DIR / "part_id_1=1" / "part_id_2="A" / "*test_0.parquet")
```
In `df1`, `part_id_1` and `part_id_2` are missing from the columns, while they are present in `df2`. Basically, seems that `read_parquet` will not look for hive-partitioning structure if it is passed a single file, and even though in the second case it is reading only one file... the fact that the pattern could include multiple causes it to pick up the structure correctly.

_Originally posted by @uditrana in https://github.com/pola-rs/polars/issues/11284#issuecomment-1789565135_

**Comment by uditrana** [comment] 2023-12-05 20:10
Also this:
https://github.com/pola-rs/polars/pull/11284#issuecomment-1789575560

**Comment by deanm0000** [comment] 2023-12-05 23:52
It's not a bug. read doesn't look for hive. Use scan_parquet with collect

**Comment by deanm0000** [comment] 2023-12-12 16:39
@stinodego here's a close

**Comment by stinodego** [comment] 2023-12-14 09:50
Shouldn't `read_parquet` support Hive partitioning too, though? I would expect a `read` function to function exactly like a `scan` function followed by `collect`.

**Comment by stinodego** [comment] 2023-12-14 10:16
Closing this in favor of #13040

**Closed by stinodego** 2023-12-14 10:16 UTC
