### ISSUE TITLE
datetime '2017-04-02 02:00:00' is ambiguous in time zone 'Australia/Sydney'.

### ISSUE THREAD

**Issue by david-waterworth** [pola-rs/polars#9491] opened 2023-06-22 03:06 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I'm getting inconsistent results using datetime operations on a dataframe that contains a localised timestamp. For example `groupby_rolling` with a period of `1h` works but changing the period to `1w` results in the error

```
ComputeError: datetime '2017-04-02 02:00:00' is ambiguous in time zone 'Australia/Sydney'. Ambiguous datetimes are not yet supported
```

I get similar results using Truncate. I understand that '2017-04-02 02:00:00'  is ambiguous when timezone information is not present, but I'm using a localised timestamp. 

### Reproducible example

```python
from datetime import datetime, timedelta
import numpy as np

df = pl.DataFrame({
    "timestamp": pl.date_range(
        datetime(2017, 1, 1), 
        datetime(2018, 1, 1), 
        timedelta(minutes=15), 
        time_zone="Australia/Sydney", 
        time_unit="ms", eager=True),
        })
temperature = np.random.normal(20, 5, len(df))
df = df.with_columns([pl.Series(temperature).alias("temperature")])

# no error
df.groupby_rolling(index_column="timestamp", period="1h").agg(pl.mean("temperature").alias("mean_temperature"))

# raises error
df.groupby_rolling(index_column="timestamp", period="1w").agg(pl.mean("temperature").alias("mean_temperature"))

# raises error
df.with_columns(pl.col('timestamp').dt.truncate(freq).alias("truncated"))
```

### Expected behavior

I would expect datetime operations on a timezone aware column should not result in errors indicating that a naive datetime has been encountered.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Linux-5.15.0-72-generic-x86_64-with-glibc2.35
Python:      3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      1.5.3
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.5.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by MarcoGorelli** [comment] 2023-06-22 09:59
hi @david-waterworth - `freq` isn't defined in your example, what's it meant to be?

**Comment by david-waterworth** [comment] 2023-06-22 10:10
Sorry "15m"

**Comment by MarcoGorelli** [comment] 2023-06-22 10:14
Anyway, the issue is due to a DST transition

Here's a simpler reproducer:
```python
In [28]: df = pl.DataFrame({'timestamp': [datetime(2017, 10, 8, 2)]}).with_columns(pl.col('timestamp').dt.replace_time_z
    ...: one('Australia/Sydney').set_sorted())

In [29]: df['timestamp'].dt.offset_by('-1w')
---------------------------------------------------------------------------
ComputeError: datetime '2017-10-01 02:00:00' is non-existent in time zone 'Australia/Sydney'. Non-existent datetimes are not yet supported
```

If you try going back 1 week from `2017-10-08 02:00`, then you should get to `2017-10-01 02:00`. Problem is, that datetime doesn't exist, because Sydney went straight from `2:00` to `3:00`! See below:

```python
In [34]: pl.date_range(datetime(2017, 10, 1), datetime(2017, 10, 1, 4), '15m', time_zone='Australia/Sydney', eager=True)
    ...:
Out[34]:
shape: (13,)
Series: 'date' [datetime[μs, Australia/Sydney]]
[
        2017-10-01 00:00:00 AEST
        2017-10-01 00:15:00 AEST
        2017-10-01 00:30:00 AEST
        2017-10-01 00:45:00 AEST
        2017-10-01 01:00:00 AEST
        2017-10-01 01:15:00 AEST
        2017-10-01 01:30:00 AEST
        2017-10-01 01:45:00 AEST
        2017-10-01 03:00:00 AEDT
        2017-10-01 03:15:00 AEDT
        2017-10-01 03:30:00 AEDT
        2017-10-01 03:45:00 AEDT
        2017-10-01 04:00:00 AEDT
]
```

So, for `groupby_rolling`, the window for `2017-10-08 02:00` should be `(2017-10-01 02:00, 2017-10-08 02:00]`. Problem is, the left boundary doesn't exist, so the window isn't defined!

You'd get a similar error in April, but for the opposite reason:
```python
In [51]: pl.date_range(datetime(2017, 4, 2, 1), datetime(2017, 4, 2, 4), '15m', time_zone='Australia/Sydney', eager=True
    ...: )
Out[51]:
shape: (17,)
Series: 'date' [datetime[μs, Australia/Sydney]]
[
        2017-04-02 01:00:00 AEDT
        2017-04-02 01:15:00 AEDT
        2017-04-02 01:30:00 AEDT
        2017-04-02 01:45:00 AEDT
        2017-04-02 02:00:00 AEDT
        2017-04-02 02:15:00 AEDT
        2017-04-02 02:30:00 AEDT
        2017-04-02 02:45:00 AEDT
        2017-04-02 02:00:00 AEST
        2017-04-02 02:15:00 AEST
        2017-04-02 02:30:00 AEST
        2017-04-02 02:45:00 AEST
        2017-04-02 03:00:00 AEST
        2017-04-02 03:15:00 AEST
        2017-04-02 03:30:00 AEST
        2017-04-02 03:45:00 AEST
        2017-04-02 04:00:00 AEST
]
```
What does it mean for a timestamp to be 1 week before `2017-04-09 02:15:00` - should it be `2017-04-02 02:15:00 AEST`, or `2017-04-02 02:15:00 AEDT`?

**Comment by david-waterworth** [comment] 2023-06-22 10:22
I would expect that I’d get the same results as if I converted to UTC, performed the operation then converted back? 

Is the truncation error the same root cause?

**Comment by MarcoGorelli** [comment] 2023-06-22 10:34
In that case, each window would be exactly `24 hours * 7 days`. If that's what you want then, sure, but then also using `'168h'` should work

Note that if you convert to UTC, do rolling with `'1w'`, and then convert back, then note that `2017-10-08 01:00:00 AEDT` would go back to `2017-10-01 00:00:00 AEST`. If that's what you expect (rather than `2017-10-01 01:00:00 AEST`), then that sounds fine

**Comment by david-waterworth** [comment] 2023-06-22 23:50
Thanks @MarcoGorelli  - using a fixed 168hour duration makes sense for this dataset

Still seeing the truncate issue though, i.e. 

``` python
from datetime import datetime, timedelta
import numpy as np

df = pl.DataFrame({
    "timestamp": pl.date_range(
        datetime(2017, 1, 1), 
        datetime(2018, 1, 1), 
        timedelta(minutes=15), 
        time_zone="Australia/Sydney", 
        time_unit="ms", eager=True),
        })
temperature = np.random.normal(20, 5, len(df))
df = df.with_columns([pl.Series(temperature).alias("temperature")])

freq="15m"
df.with_columns(pl.col('timestamp').dt.truncate(freq).alias("truncated"))
```

Is that expected? In this case I don't think it should actually change any of the original timestamps? I've been working around this by using UTC

**Comment by MarcoGorelli** [comment] 2023-06-25 14:23
🤔 maybe `truncate('15m')` should be well-defined and unambiguous...'`15m'` is a fixed duration, not affected by DST (unlike days / weeks / months)

will get back to this, thanks

**Comment by MarcoGorelli** [comment] 2023-06-25 14:48
Consider these two times, which are on either side of a DST transition:
- `2020-10-25 01:00:00 BST`, and truncate by `'2h'`, and
- `2020-10-25 01:00:00 GMT`, and truncate by `'2h'`

I think: `2020-10-25 00:00:00 BST`

Then, consider the time `2020-10-25 01:00:00 +0545` - what would the expect output be if truncating by 2 hours?

I think: `2020-10-25 00:00:00 +0545`

But it we tried the "convert to UTC", truncate, then convert back, then the latter would give: `2020-10-24 23:45:00 +0545`

I remember now having looked into this here: https://github.com/pola-rs/polars/issues/7623#issuecomment-1474811208. I don't think there's a way to do this which wouldn't results in any surprises for anyone.

I think the current behaviour gives the expected output where possible, but occasionally may throw an error - in that case, then I'd say it's use-case dependent. If in your case converting to UTC and then converting back gives the expected output, then that looks fine

**Comment by MarcoGorelli** [comment] 2023-06-25 15:00
Actually, maybe there is a simple solution: don't do any time zone adjustment for non-calendar durations. If anyone is in a time zone with a non-round time zone offset, then they can just specify `offset` (e.g. in the Kathmandu example, `offset='-45min'`)

I'll put together a PR to demonstrate

**Comment by david-waterworth** [comment] 2023-06-25 22:58
Thanks, I agree I'd expect `2020-10-25 01:00:00 +0545` to truncate to `2020-10-25 00:00:00 +0545`

There are probably different use cases, but I consider it to be running time backwards up to but not longer than the actual truncation duration (so you should not go back more than 2 hours local time) until you land on the first occurrence of a value generated by something equivalent to `pl.date_range` generated with the specific truncation frequency and timezone (and potentially offset).

i.e. for each value in the original column, the result should be the closest same or preceding timestamp from

``` python
pl.date_range(
    datetime(2020, 10, 24),
    datetime(2020, 10, 26),
    timedelta(hours=2),
    time_zone="Asia/Kathmandu",
    time_unit="ms", eager=True)
```

I'm not a huge fan of the offset solution as I have to deal with timeseries from say `Australia/Sydney` and `Australia/South Australia` - the latter having a 30-minute offset. But I guess I can automate it though by parsing the minutes component of the UTC offset so its workable.

**Comment by MarcoGorelli** [comment] 2023-06-26 09:00
What about `Australia/Lord_Howe`? If you started the date_range in winter, then truncating `2020-10-25 01:00:00` by `'1h'` would give you `2020-10-25 00:30:00 +11`, would that be OK? When should the `date_range` start in general?

**Comment by david-waterworth** [comment] 2023-06-26 22:27
Yeah that's a good point, Lord Howe is special having a 30 minute DLS adjustment. 

For what I'm trying to do I suspect I'd still compute a resampled index but using `daterange` but using `30m` and then remove the rows where minutes=30

But to be honest that's not really a truncation - I'm just trying to reindex/interpolate my data

I suspect most users would expect that a truncate of 1h with no offset would return times of 00:00, 01:00, 02:00 etc. It would certainly seem unusual that truncate of  `2020-10-25 01:00:00` would not return itself?

Perhaps you need to implement similar options to pandas (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.round.html) where the user can specify different approaches for ambiguous/non-existent times?

**Comment by MarcoGorelli** [comment] 2023-06-27 08:15
> I suspect most users would expect that a truncate of 1h with no offset would return times of 00:00, 01:00, 02:00 etc. It would certainly seem unusual that truncate of 2020-10-25 01:00:00 would not return itself?

Yup, I agree - and in the absense of offsets, that's exactly what polars does, and what it would continue doing if https://github.com/pola-rs/polars/pull/9552 were merged

> Perhaps you need to implement similar options to pandas (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.round.html) where the user can specify different approaches for ambiguous/non-existent times?

That could be a solution, but even that can be surprising to users: https://github.com/pandas-dev/pandas/issues/37592. But conversely, pandas' [round](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.round.html) doesn't have an `offset` argument.

Arguably, one could defer to the[ polars truncate docs](https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.dt.truncate.html#polars.Series.dt.truncate), which say

> every
>
>    Every interval start and period length

Neither the pandas approach nor the current polars approach guarantee that each period's length would be `every`. Conversely, https://github.com/pola-rs/polars/pull/9552 would actually ensure that.

So, all in all, I'm leaning more and more towards https://github.com/pola-rs/polars/pull/9552

**Comment by david-waterworth** [comment] 2023-06-27 22:43
When I read the documentation (and specifically the fact that the parameters are named `interval`/`offset`), I feel it's describing a `resampling` operation - when you generate a sequence that has regular intervals with an offset added. In my mind `truncate` implies rounding to a specific `precision` with an `offset` added.

Not sure that helps :)

**Comment by MarcoGorelli** [comment] 2023-06-28 07:34
thanks - that is indeed how the docs look like to me, which would imply that the "convert to UTC, truncate, convert back" method should be used. If using the wall times (as pandas does, and polars currently does), then the intervals won't necessarily be of `every`:
```python
In [7]: pd.Series(pd.date_range('2020-10-25', periods=4, freq='H', tz='Europe/London')).dt.round('2h').diff()
Out[7]:
0               NaT
1   0 days 00:00:00
2   0 days 00:00:00
3   0 days 03:00:00
dtype: timedelta64[ns]
```

The current behaviour is feeling more and more like a bug to me to be honest. It's going to be virtually impossible to change this in pandas (https://xkcd.com/1172/), but in polars it feels like there's a chance (it's also pre-1.0, so breaking changes are a bit more excusable)

**Comment by MarcoGorelli** [comment] 2023-06-30 19:05
Hi @david-waterworth 

> But I guess I can automate it though by parsing the minutes component of the UTC offset so its workable.

Since #9629 (`.dt.dst_offset`) has been added, and #9636 (`.dt.base_utc_offset`) will hopefully also be approved / merged, does this solution seem more appealing now?

**Comment by david-waterworth** [comment] 2023-07-01 23:32
Hi @MarcoGorelli yes I think that should work fine! I wasn’t actually thinking of this when I posted on SO regarding ‘dst’ but ‘dt.dst_offset’ should work in this case as well.

**Comment by MarcoGorelli** [comment] 2023-07-11 18:59
Having slept on this a few nights, I'm leaning back towards just adding `use_earliest` (analogous to pandas' `ambiguous`). Having a difference between "daily truncation" and "hourly truncation" would be very surprising. It would also avoid making a breaking change.

`.dt.dst_offset` should also make it easier to deal with

If users want regular intervals, they can use `groupby_dynamic`

**Comment by MarcoGorelli** [comment] 2023-07-15 08:40
Hi @david-waterworth 

I've got a branch in which I've added a `use_earliest` argument to `truncate`. This would allow you to do
```python
df = pl.DataFrame({
    "timestamp": pl.date_range(
        datetime(2017, 1, 1), 
        datetime(2018, 1, 1), 
        timedelta(minutes=15), 
        time_zone="Australia/Sydney", 
        time_unit="ms", eager=True),
        })
temperature = np.random.normal(20, 5, len(df))
df = df.with_columns([pl.Series(temperature).alias("temperature")])

freq="15m"
df = df.with_columns(use_earliest=pl.col('timestamp').dt.dst_offset() == pl.duration(hours=1))
df = df.with_columns(
    pl.when(pl.col('use_earliest'))
    .then(pl.col('timestamp').dt.truncate('15m', use_earliest=True))
    .otherwise(pl.col('timestamp').dt.truncate('15m', use_earliest=False))
)
print(df)
```

Would this work for you?

**Comment by david-waterworth** [comment] 2023-07-15 09:25
Hi @MarcoGorelli yes that looks reasonable

**Comment by MarcoGorelli** [comment] 2023-07-15 09:27
awesome - thanks a tonne for your response and help here, it's high-quality feature requests and bug reports like these that help software progress! 🙌 
(wish github had an easy way to recognise such essential non-code contributions...)

**Comment by david-waterworth** [comment] 2023-07-16 23:04
Thanks @MarcoGorelli  - glad to help, particular with polars as I'm a big fan.

PS In your example, it should work in all timezones (i.e. without prior knowledge of the offset) if you do

``` python
df.with_columns(use_earliest=pl.col('timestamp').dt.dst_offset() > 0)
```

(just in case you add it to documentation anywhere).

Also I've not tried but can you do

```
pl.col('timestamp').dt.truncate('15m', use_earliest=pl.col('timestamp').dt.dst_offset() > 0)
```

Or do arguments to expressions have to be Python types?

**Closed** 2023-07-20 08:19 UTC
Labels: bug, python, timeseries

**Comment by MarcoGorelli** [comment] 2023-07-20 08:39
> Or do arguments to expressions have to be Python types?

they do currently - but I'll see if they can be expressions, that'd be more ergonomic!
