### ISSUE TITLE
Errors when aggregating on empty filtered column and its mean, redux

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#6185] opened 2023-01-12 04:08 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I commented on https://github.com/pola-rs/polars/issues/6074, but I figure it's easier to open to a new issue for posterity. https://github.com/pola-rs/polars/pull/6076 fixed part of the problem, but the following two examples still raise errors:

```python
import polars as pl

df_1 = pl.DataFrame(
    {"A": [0, 0], "B": [1, 2]}
)

df_2 = pl.DataFrame(
    {"A": [0, 0] * 2, "B": [1, 2] * 2}
)

expr = pl.col("A").filter(pl.col("A") > 0)
```

The following aggregation with `df_1` raises an error:

```python
df_1.groupby("B").agg((expr - expr.mean()).mean())

ComputeError: Cannot aggregate as mean. The column is already aggregated.
```

The same aggregation with `df_2` transiently raises

```python
# May need to run several times
df_2.groupby("B").agg((expr - expr.mean()).mean())

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `2`', /Users/runner/work/polars/polars/polars/polars-lazy/src/physical_plan/expressions/mod.rs:209:17
```

### Reproducible example

```python
import polars as pl

df_1 = pl.DataFrame(
    {"A": [0, 0], "B": [1, 2]}
)

df_2 = pl.DataFrame(
    {"A": [0, 0] * 2, "B": [1, 2] * 2}
)

expr = pl.col("A").filter(pl.col("A") > 0)

df_1.groupby("B").agg((expr - expr.mean()).mean())

df_2.groupby("B").agg((expr - expr.mean()).mean())
```

### Expected behavior

In both cases the result should be

```python
shape: (2, 2)
┌─────┬──────┐
│ B   ┆ A    │
│ --- ┆ ---  │
│ i64 ┆ f64  │
╞═════╪══════╡
│ 1   ┆ null │
│ 2   ┆ null │
└─────┴──────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: macOS-10.15.7-x86_64-i386-64bit
Python: 3.8.12 (default, Oct 18 2021, 20:31:01) 
[Clang 10.0.1 (clang-1001.0.46.4)]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.4.4
numpy: 1.21.5
fsspec: 2022.01.0
connectorx: 0.3.0
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment] 2023-01-14 09:53
@erinov1 I cannot reproduce the second example. Could you make a debug compilation and get a backtrace by setting `RUST_BACKTRACE=1`?

**Comment by erinov1** [comment] 2023-01-15 23:04
@ritchie46 thanks! Are you still unable to reproduce the second example? I noticed your comment https://github.com/pola-rs/polars/pull/6191#issuecomment-1382693705, but I'm not sure if the "2nd one" you are referring to is the second example in this issue. The backtrace I see is (from https://github.com/pola-rs/polars/pull/6191#issuecomment-1382246889)

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `2`', /Users/runner/work/polars/polars/polars/polars-lazy/src/physical_plan/expressions/mod.rs:209:17
stack backtrace:
   0:        0x106c05d6a - _ffi_select_with_compiled_path
   1:        0x1059036fa - _BrotliDecoderVersion
   2:        0x106bdbf74 - _ffi_select_with_compiled_path
   3:        0x106c0745a - _ffi_select_with_compiled_path
   4:        0x106c07083 - _ffi_select_with_compiled_path
   5:        0x106c080c5 - _ffi_select_with_compiled_path
   6:        0x106c07bb5 - _ffi_select_with_compiled_path
   7:        0x106c07b20 - _ffi_select_with_compiled_path
   8:        0x106c07af2 - _ffi_select_with_compiled_path
   9:        0x106d30f03 - _ffi_select_with_compiled_path
  10:        0x106d310fc - _ffi_select_with_compiled_path
  11:        0x106db2d76 - _ffi_select_with_compiled_path
  12:        0x10667e109 - _ffi_select_with_compiled_path
  13:        0x106681e04 - _ffi_select_with_compiled_path
  14:        0x10675377b - _ffi_select_with_compiled_path
  15:        0x1067533e9 - _ffi_select_with_compiled_path
  16:        0x106753199 - _ffi_select_with_compiled_path
  17:        0x106de4c9d - _ffi_select_with_compiled_path
  18:        0x106b0f2fb - _ffi_select_with_compiled_path
  19:        0x106b0ee99 - _ffi_select_with_compiled_path
  20:        0x106c0920a - _ffi_select_with_compiled_path
  21:     0x7fff71408109 - __pthread_start

--------------------------------------------
```

**Comment by erinov1** [comment] 2023-01-17 02:19
Actually, I'm no longer able to reproduce the second error after upgrading to 0.15.15.

**Comment by ritchie46** [comment] 2023-01-20 13:00
Ok, then I close this one. If the issue returns we can investigate.

**Closed by ritchie46** 2023-01-20 13:00 UTC
Labels: bug, python
