### ISSUE TITLE
read_parquet with glob files: unable to vstack. How to debug?

### ISSUE THREAD

**Issue by Macfly** [pola-rs/polars#10788] opened 2023-08-30 01:03 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

```
I can't write an example to reproduce the error, I have too many files and no idea where it fails. I try to activate the verbose mode but it doesn't display anything.
pl.Config.set_verbose(True)

what is the best way to know why it fails, like the file name and the row values?

### Issue description

When reading lots of files with read_parquet, I have the error below.

Shape error: unable to vstack, dtypes fro column "udl" don't match 'str' and 'null'

### Expected behavior

however when I put use_pyarrow= true, it works (using the glob.glob function to pass al the files).

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-4.14.322-244.536.amzn2.x86_64-with-glibc2.26
Python:              3.10.12 (main, Aug 29 2023, 09:37:01) [GCC 10.4.1 20221124 (Red Hat 10.4.0-1)] 

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.24.4
pandas:              2.0.3
pyarrow:             12.01
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>```

</details>

**Comment by ritchie46** [comment] 2023-08-30 05:07
Your files don't have the same schema.

**Comment by ritchie46** [comment] 2023-09-02 09:39
You can look at the schema of the individual files. I will close this as it is not a bug on our side

**Closed by ritchie46** 2023-09-02 09:39 UTC
Labels: bug, python
