### ISSUE TITLE
Lazyframe write to JSON panics for categorical columns

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#7137] opened 2023-02-23 22:29 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Lazyframe write to JSON works well for UTF8 columns, but panics for categorical columns

### Reproducible example

```python
import polars as pl

# UTF8 works well
pl.DataFrame({'a': ['x','y']},
    schema=[('a',pl.Utf8)]
    ).lazy().write_json()

# Result
'{"DataFrameScan":{"df":{"columns":[{"name":"a","datatype":"Utf8","values":["x","y"]}]},"schema":{"inner":{"a":"Utf8"}},"output_schema":null,"projection":null,"selection":null}}'

# Panics for Categorical columns
pl.DataFrame({'a': ['x','y']},
    schema=[('a',pl.Categorical)]
    ).lazy().write_json()

# Panic
thread '<unnamed>' panicked at 'not yet implemented', /home/runner/work/polars/polars/polars/polars-core/src/datatypes/_serde.rs:92:18

---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[73], line 3
      1 pl.DataFrame({'a': ['x','y']},
      2     schema=[('a',pl.Categorical)]
----> 3     ).lazy().write_json()

File ~/.local/lib/python3.11/site-packages/polars/internals/lazyframe/frame.py:553, in LazyFrame.write_json(self, file)
    551 if file is None or to_string_io:
    552     with BytesIO() as buf:
--> 553         self._ldf.write_json(buf)
    554         json_bytes = buf.getvalue()
    556     json_str = json_bytes.decode("utf8")

PanicException: not yet implemented
```

### Expected behavior

I would expect the write json to also work on categorical columns. Unless this is a known limitation of write_json?

### Installed versions

<details>

```
---Version info---
Polars: 0.16.8
Index type: UInt32
Platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python: 3.11.1 (main, Dec  7 2022, 01:11:44) [GCC 9.4.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.2
numpy: 1.24.0
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8.1
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

**Comment by ritchie46** [comment] 2023-02-24 06:20
Duplicate of #5723

**Closed by ritchie46** 2023-02-24 06:20 UTC
Labels: bug, python
