### ISSUE TITLE
sink_ipc throws an error when used with scan_ipc

### ISSUE THREAD

**Issue by StuffbyYuki** [pola-rs/polars#12747] opened 2023-11-28 14:42 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# create input file
import polars as pl
df = pl.DataFrame({'a': [1,2,3]})
df.write_ipc('test.arrow')

# scan_ipc and then sink_ipc
lf = pl.scan_ipc('test.arrow')
lf.sink_ipc('test_output.arrow')
```

### Log output

```shell
---------------------------------------------------------------------------
InvalidOperationError                     Traceback (most recent call last)
/Users/Yuki/Desktop/Polars-Cookbook/Chapter02/ch02.ipynb Cell 68 line 2
      1 lf = pl.scan_ipc('test.arrow')
----> 2 lf.sink_ipc('test_output.arrow')

File ~/Desktop/Polars-Cookbook/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py:2101, in LazyFrame.sink_ipc(self, path, compression, maintain_order, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, no_optimization)
   2054 """
   2055 Evaluate the query in streaming mode and write to an IPC file.
   2056 
   (...)
   2090 
   2091 """
   2092 lf = self._set_sink_optimizations(
   2093     type_coercion=type_coercion,
   2094     predicate_pushdown=predicate_pushdown,
   (...)
   2098     no_optimization=no_optimization,
   2099 )
-> 2101 return lf.sink_ipc(
   2102     path=path,
   2103     compression=compression,
   2104     maintain_order=maintain_order,
   2105 )

InvalidOperationError: sink_Ipc(IpcWriterOptions { compression: Some(ZSTD), maintain_order: true }) not yet supported in standard engine. Use 'collect().write_parquet()'
```

### Issue description

When sink_ipc is used with scan_ipc, the operation doesn't seem to have yet implemented, but if you use sink_ipc with scan_csv, it works fine. I know streaming doesn't support all the operations, but I'm not sure if this is the expected behavior or a potential bug since it works fine if you don't use scan_ipc. 
```python
# this one works fine
df = pl.DataFrame({'a': [1,2,3]})
df.write_csv('test.csv')
lf = pl.scan_csv('test.csv')
lf.sink_ipc('test_output.arrow')
```

### Expected behavior

sink_ipc should not thrown an error when used with scan_ipc

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.17
Index type:           UInt32
Platform:             macOS-14.1.1-arm64-arm-64bit
Python:               3.11.3 (main, Apr 15 2023, 22:27:28) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_manager:  0.7.0
cloudpickle:          <not installed>
connectorx:           0.3.2
deltalake:            0.12.0
fsspec:               2023.10.0
gevent:               <not installed>
matplotlib:           3.8.0
numpy:                1.26.1
openpyxl:             <not installed>
pandas:               2.1.1
pyarrow:              12.0.0
pydantic:             2.4.2
pyiceberg:            0.5.0
pyxlsb:               <not installed>
sqlalchemy:           2.0.22
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment] 2023-11-28 14:59
`scan_ipc` is not yet supported in the streaming engine.

**Comment by ritchie46** [comment] 2023-11-29 12:53
I will close this as this is not a bug, merely not yet supported.

**Closed by ritchie46** 2023-11-29 12:53 UTC
Labels: bug, python
