### ISSUE TITLE
Expr.list.median() as addition to Expr.list.mean()

### ISSUE THREAD

**Issue by Buedenbender** [pola-rs/polars#12163] opened 2023-11-01 12:16 UTC
### Possibility to get the median of a list

Thank you for all the work you provide. It would be highly appreciated if we could get a `Expr.list.median()` method for expressions on numeric [list dtypes](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/list.html).  Comparable to [`Expr.list.mean()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.list.mean.html#polars.Expr.list.mean)

**Comment by cmdlineluser** [comment] 2023-11-01 17:48
If unaware, it can be done with [`.list.eval()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.list.eval.html#polars.Expr.arr.eval) as a workaround https://github.com/pola-rs/polars/issues/9033

```python
df = pl.DataFrame({"A": [[1, 10, 3], [20, 3, 5]]})

df.with_columns(list_median = 
   pl.col("A").list.eval(pl.element().median()).flatten()
)

# shape: (2, 2)
# ┌────────────┬─────────────┐
# │ A          ┆ list_median │
# │ ---        ┆ ---         │
# │ list[i64]  ┆ f64         │
# ╞════════════╪═════════════╡
# │ [1, 10, 3] ┆ 3.0         │
# │ [20, 3, 5] ┆ 5.0         │
# └────────────┴─────────────┘
```

I tried to look at `.list.mean()` to see how that is implemented
https://github.com/pola-rs/polars/blob/1b9c1692bfa62e7e5cada66c9ca1140f28896216/crates/polars-ops/src/chunked_array/list/sum_mean.rs#L184

I'm guessing there must also be an optimized version for the non-null case?
https://github.com/pola-rs/polars/blob/1b9c1692bfa62e7e5cada66c9ca1140f28896216/crates/polars-ops/src/chunked_array/list/sum_mean.rs#L123

**Comment by stinodego** [comment] 2023-12-22 23:24
I'll close this as a duplicate of https://github.com/pola-rs/polars/issues/9033

**Closed by stinodego** 2023-12-22 23:24 UTC
Labels: enhancement, accepted
