### ISSUE TITLE
Wrong result when multiplying an expression by a literal

### ISSUE THREAD

**Issue by radugrosu** [pola-rs/polars#7988] opened 2023-04-04 14:28 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The average of a boolean series is (expected to be) a float, but if the `Expr` is multiplied by a python integer, the result is (wrongly) converted to an integer.

### Reproducible example

```python
In [1]: import polars as pl

In [2]: pl.DataFrame(dict(a=[True, False])).select(pl.col("a").mean() * 2.) # correct
Out[2]: 
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
└─────┘

In [3]: pl.DataFrame(dict(a=[True, False])).select(pl.col("a").mean() * 2) # incorrect
Out[3]: 
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i32 │
╞═════╡
│ 0   │
└─────┘
```

### Expected behavior

Expected behaviour is to get the correct result (1.0 in the example above).

### Installed versions

<details>

```
In [5]: pl.show_versions()
---Version info---
Polars: 0.16.18
Index type: UInt32
Platform: Linux-5.4.0-1098-azure-x86_64-with-glibc2.27
Python: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
---Optional dependencies---
numpy: 1.23.5
pandas: 2.0.0
pyarrow: 10.0.1
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.3.0
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by zundertj** [comment] 2023-04-09 06:23
Can reproduce.

The work around would be to cast `pl.col("a")` to an integer type first. Although `pl.col("a").mean()` is correctly a `f64`, multiplying through with an integer leads to the incorrect output type integer.

**Comment by zundertj** [comment] 2023-04-09 06:46
Actually, duplicate of #7651 . Please comment and/or update there. Closing this one.

**Closed by zundertj** 2023-04-09 06:46 UTC
Labels: bug, python
