### ISSUE TITLE
Panic when calling namespace method on `Expr.apply` output when `return_dtype` not specified

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#9816] opened 2023-07-11 14:55 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [[1, 2], [3, 4]]})

result = df.with_columns(
    pl.col("a")
    .apply(lambda x: x)
    .alias("output")
    .list.to_struct()
)
# pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```
If we specify the return dtype, it works fine:
```python
result = df.with_columns(
    pl.col("a")
    .apply(lambda x: x, return_dtype=pl.List(pl.Int64))
    .alias("output")
    .list.to_struct()
)
```
```
shape: (2, 2)
┌───────────┬───────────┐
│ a         ┆ output    │
│ ---       ┆ ---       │
│ list[i64] ┆ struct[2] │
╞═══════════╪═══════════╡
│ [1, 2]    ┆ {1,2}     │
│ [3, 4]    ┆ {3,4}     │
└───────────┴───────────┘
```

### Issue description

The docs for `apply` are confusing. It states that if `return_dtype` is not set, the dtype will be `pl.Unknown`. But that's not true:

```python
result = df.with_columns(
    pl.col("a")
    .apply(lambda x: x, return_dtype=pl.List(pl.Int64))
    .alias("output")
    .list.to_struct()
)
```
```
shape: (2, 2)
┌───────────┬───────────┐
│ a         ┆ output    │
│ ---       ┆ ---       │
│ list[i64] ┆ list[i64] │
╞═══════════╪═══════════╡
│ [1, 2]    ┆ [1, 2]    │
│ [3, 4]    ┆ [3, 4]    │
└───────────┴───────────┘
```

In fact, the engine does not know the dtype and treats it as `Null` before evaluating. So calling the `list` namespace on the null type probably results in a panic.

### Expected behavior

I would expect a nice error, telling me that I should specify the return type.

### Installed versions

master branch

**Comment by ritchie46** [comment] 2023-07-12 11:34
I see what the issue is. We first need to convert to `to_struct` function to the new function architecture and then we can properly return an error if we try to get the schema.

It fails because it tries to get the inner dtype of the `List` which is it cannot, because the type is `Unknown`.

**Comment by coastalwhite** [comment] 2024-06-17 15:16
I tried to reproduce this issue with:

```python
import polars as pl

df = pl.DataFrame({"a": [[1, 2], [3, 4]]})

result = df.with_columns(
    pl.map_groups(
        exprs = ['a'],
        function = lambda x: x,
    ).alias("output").list.to_struct()
)
```

It does not reproduce anymore and `apply` is deprecated. I will close this.

**Closed by coastalwhite** 2024-06-17 15:16 UTC
Labels: bug, python, needs triage
