### ISSUE TITLE
Numba can help with python UDF

### ISSUE THREAD

**Issue by rmekdma** [pola-rs/polars#9175] opened 2023-06-02 03:07 UTC
### Problem description

This is a small discovery. Numba + Expr.apply with threading can use multiple cpus.

```python
from numba import jit

@jit(nopython=True, nogil=True)
def func_jit(x):
    return x * x

df.select(pl.col("x").apply(func_jit, strategy='threading'))
```

Mentioning Numba in the [document](https://pola-rs.github.io/polars-book/user-guide/expressions/user-defined-functions/) would be helpful to people.

**Comment by avimallu** [comment] 2023-06-02 14:49
That is a nice find, especially for complex numeric calculation (haversine distance comes to mind). I'm surprised that multithreading works because I thought Polars sent row-by-row to the Python function used.

Would you like to file a PR on the [Polars book repo](https://github.com/pola-rs/polars-book) about this? Will probably be best in the UDF apply section.

**Comment by zundertj** [comment] 2023-06-04 19:38
Would be great to have PR on the book repo indeed, that is also the repo that hosts the page you are linking to. In case, for whatever reason, you are not creating a PR, could you create a new issue in the repo there. This repo is purely for the development of Polars, hence I'm closing this issue here.

**Closed by zundertj** 2023-06-04 19:38 UTC
Labels: enhancement

**Comment by rmekdma** [comment] 2023-06-04 22:06
I will make a pr on the book repo. Thanks for your advice!

**Comment by alugowski** [comment] 2023-07-22 05:59
Is there a way to extend this to a function that takes more than one argument?

**Comment by avimallu** [comment] 2023-07-22 13:37
Use of structs might help. Check the user guide for how to.

**Comment by alugowski** [comment] 2023-07-22 22:20
> Use of structs might help. Check the user guide for how to.

Like this?
```python
@jit(nopython=True, nogil=True)
def func(a, b, c):
    return a+b+c

df.select(pl.struct("a", "b", "c")).apply((lambda col: func(col[0]["a"], col[0]["b"], col[0]["c"])))
```

That lambda kills sequential performance and negates the `nogil` and `strategy='threading'` tricks. Is there another way to use structs?

**Comment by alugowski** [comment] 2023-07-22 22:46
One thing that does appear to work is to modify the function to accept a tuple then unpack the arguments manually:

```python
@jit(nopython=True, nogil=True)
def func_tuple(arg_tuple):
    a, b, c = arg_tuple
    return a+b+c

df.select([pl.col("a"), pl.col("b"), pl.col("c")]).apply(func_tuple)
```

That skips the need for a lambda shim.

**Comment by avimallu** [comment] 2023-07-22 23:24
You're using `apply` as `pl.DataFrame.apply`. Here's a few techniques with timings if speed is of utmost importance to you, and a corresponding expressions technique is simply not available (reproducible code for your benefit):

```py
import polars as pl
import numpy  as np
from string import ascii_letters
from numba import jit

@jit(nopython=True, nogil=True)
def numba_func(a, b, c):
    return a+b+c

@jit(nopython=True, nogil=True)
def func_tuple(arg_tuple):
    a, b, c = arg_tuple
    return a+b+c

def python_func(a, b, c):
    return a+b+c

def series_to_numba(x):
    a, b, c = map(lambda x: x.to_numpy(), x.to_frame().unnest("a").get_columns())
    return pl.Series("a", numba_func(a, b, c))

df = pl.DataFrame({
    "a": np.random.randint(0, 1000000, 1000000),
    "b": np.random.randint(0, 1000000, 1000000),
    "c": np.random.randint(0, 1000000, 1000000)})
```

Techniques (run on Jupyter notebooks):

#### Roundabout way of converting to `numpy` and back

Benefits: easily integrate in set of pipe operations, and use vectorized numba ops by passing a `Series` via `map`.

```py
%%timeit
df.select(pl.col("b"), pl.struct("a", "b", "c").map(series_to_numba))
# 1.88 ms ± 467 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

#### Using `func_tuple`

```py
%%timeit
df.select([pl.col("a"), pl.col("b"), pl.col("c")]).apply(func_tuple)
# 268 ms ± 905 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

#### Using your original numba function

```py
%%timeit
df.select(pl.struct("a", "b", "c").apply(lambda x: numba_func(x["a"], x["b"], x["c"])))
# 411 ms ± 4.19 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

#### Basic Python `apply`

```py
%%timeit
df.select(pl.struct("a", "b", "c").apply(lambda x: python_func(x["a"], x["b"], x["c"])))
338 ms ± 4.17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Feel free to experiment and see what works (and let us know here if you feel it's improved).

**Comment by alugowski** [comment] 2023-07-23 00:36
Thank you for the detailed explanations!

Would I be correct to say that the only way to go faster than the arg_tuple trick is if the user function is the equivalent of a numpy universal function?

The "Roundabout way of converting to numpy and back" approach changes the types of `a`, `b`, `c` from scalars to numpy arrays. Yes that's great for performance, but assumes that the function can work that way. Many do, but mine doesn't and cannot be easily modified to be. Naturally `a+b+c` is a stand-in, pasting a 70-line function would be a distraction.

**Comment by avimallu** [comment] 2023-07-23 00:57
> Would I be correct to say that the only way to go faster than the arg_tuple trick is if the user function is the equivalent of a numpy universal function?

I do not know enough about numpy ufunc to really comment here. The best way to go about it if you can't use Polars expressions is to use `map`, and allow your function to process the **whole input at once** rather than row-by-row vis-a-vis element-by-element vis-a-vis `apply`. It doesn't necessarily need to be something you can convert to `numpy`, but even specialized functions such as SpaCy's tokenizer that can handle Python `list` objects faster than it can handle individual `str` objects. The key is **whole input at once** rather than one element at a time.

**Comment by alugowski** [comment] 2023-07-23 02:06
Preaching to the choir.

**Comment by zundertj** [comment] 2023-12-27 11:30
I haven't created such a PR. @rmekdma  suggested in this thread he would, so maybe he knows?

**Comment by rmekdma** [comment] 2023-12-27 11:56
I'm sorry. I didn't submit the PR. I haven't been using polars recently, and I haven't properly tested numba. I hope someone interested will continue the work.

**Comment by xuJ14** [comment] 2024-05-23 02:19
Any update?
