### ISSUE TITLE
rolling_mean calculation changed before and after inf get replaced

### ISSUE THREAD

**Issue by wangbo00129** [pola-rs/polars#19001] opened 2024-09-29 07:31 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import numpy as np
df_example = pl.read_csv('df_example.csv')


print(df_example['a'].rolling_mean(2)[-1])
print(df_example['a'].replace(np.inf, None).rolling_mean(2)[-1])
print(df_example.select(pl.when(pl.col('a').is_infinite()).then(None).otherwise(pl.col('a')).rolling_mean(2))[-1,0])

```

[df_example.csv](https://github.com/user-attachments/files/17178358/df_example.csv)

### Log output

```shell
avg line length: 18.676758
std. dev. line length: 1.8349931
initial row estimate: 2955
no. of chunks: 6 processed by: 6 threads.
-25578911.636363186
-25538502.747473635
-25538502.747473635
```

### Issue description

rolling_mean calculation changed DRAMATICALLY before and after inf get replaced, no matter using .replace or pl.when

### Expected behavior

rolling_mean calculation should remain the same before and after inf get replaced

### Installed versions

<details>

```
--------Version info---------
Polars:              1.8.2
Index type:          UInt32
Platform:            Linux-5.15.0-107-generic-x86_64-with-glibc2.31
Python:              3.11.9 (main, May 31 2024, 13:11:24) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

```

</details>

**Comment by orlp** [comment] 2024-10-01 19:09
Duplicate of https://github.com/pola-rs/polars/issues/18919, no?  And your DRAMATIC change is ~0.15%, for the record.

The reason the results are worse if you replace infinities with `None`s is because we reset and recompute the window (currently) when an infinity/nan leaves the window, whereas otherwise we simply update the window by subtracting what leaves and adding what enters the window. We might change this in the future but ultimately this is within what Polars promises.

**Closed by orlp** 2024-10-01 19:09 UTC
Labels: bug, python, needs triage

**Comment by wangbo00129** [comment] 2024-10-08 05:20
Thank you for explaining to me.
