### ISSUE TITLE
`pl.col('str_col').cast(pl.UInt8).fill_null(pl.lit(0))` gets converted to Int16 type

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#17342] opened 2024-07-01 22:19 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

# Create a sample DataFrame with a string column
df = pl.DataFrame({
    "str_col": ["1", "2", "3", None, "5"]
})

# Apply the sequence of operations: cast to UInt8 and fill nulls with 0
df = df.with_columns(
    output_no_fill_null = pl.col("str_col").cast(pl.UInt8),
	output_with_fill_null = pl.col("str_col").cast(pl.UInt8).fill_null(pl.lit(0)),
)

# Print the DataFrame to observe the column type and values
print(df)
print(df.schema)

```

### Issue description

`pl.col('str_col').cast(pl.UInt8).fill_null(pl.lit(0))` gets converted to Int16 type

### Expected behavior

In the example, both new cols should be u8 type. Instead, the fill_null one is i16 type.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:               0.20.25
Index type:           UInt32
Platform:             Linux-6.5.0-1025-oem-x86_64-with-glibc2.35
Python:               3.9.19 (main, Apr  6 2024, 17:57:55) 
[GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  0.11.0
cloudpickle:          3.0.0
connectorx:           0.3.3
deltalake:            0.17.4
fastexcel:            0.10.4
fsspec:               2024.6.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               1.5.3
pyarrow:              16.1.0
pydantic:             2.7.4
pyiceberg:            <not installed>
pyxlsb:               1.0.10
sqlalchemy:           1.4.52
torch:                <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           3.0.9
```

</details>

**Comment by s-banach** [comment] 2024-07-01 23:29
I get u8 on my windows machine with polars 1.0.

**Comment by DeflateAwning** [comment] 2024-07-01 23:37
Hmm darn, I may have opened a pointless issue that's been resolved

**Comment by mcrumiller** [comment] 2024-07-02 00:37
This is #13789, and all of the linked issues. :D

**Comment by stinodego** [comment] 2024-07-02 07:19
> Hmm darn, I may have opened a pointless issue that's been resolved

Looks like it! Thanks for making the effort to open an issue though.

Closing this as it is not reproducible on Polars 1.0.0.

**Closed by stinodego** 2024-07-02 07:19 UTC
Labels: bug, python, needs triage
