### ISSUE TITLE
Dataframe wrong filtering with scan_parquet and Categorical data

### ISSUE THREAD

**Issue by pozitiff4ikk** [pola-rs/polars#17944] opened 2024-07-30 15:07 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"a": ["z", "x", "c"]})
df = df.with_columns(pl.col("a").cast(pl.Categorical))
df.write_parquet("df.parquet")
df = pl.scan_parquet("df.parquet")
df.filter(pl.col("a").is_in(["x"])).collect()
```

### Log output

```shell
shape: (0, 1)
┌─────┐
│ a   │
│ --- │
│ cat │
╞═════╡
└─────┘
```

### Issue description

Filtering Categorical values is showing wrong results with scan_parquet (read_parquet is working properly), also it works with .collect(no_optimization=True)

### Expected behavior

```python
df.filter(pl.col("a").is_in(["x"])).collect(no_optimization=True)
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ cat │
╞═════╡
│ x   │
└─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               1.3.0
Index type:           UInt32
Platform:             Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Python:               3.12.4 (main, Jul 22 2024, 09:21:14) [GCC 11.4.0]
----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             2.8.2
pyiceberg:            <not installed>
sqlalchemy:           2.0.31
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by coastalwhite** [comment] 2024-07-30 16:19
I did a bisect on this and it is because of this commit:

662696a0bbc7521ead8125d4d955d620b1b40706
perf: Support datetime in predicate during hive partition pruning (#17545)

@nameexhaustion Could you have a look at this?

**Comment by agossard** [comment] 2024-07-30 17:47
Duplicate of #17744

**Comment by nameexhaustion** [comment] 2024-07-30 22:39
> I did a bisect on this and it is because of this commit:

Thanks for the bisect!

**Closed** 2024-07-31 08:09 UTC
Labels: python, accepted, A-io-parquet, A-optimizer
