### ISSUE TITLE
int_range has incorrect exclusive bound for negative steps

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#10865] opened 2023-09-01 16:48 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.select(pl.int_range(3, 0, -1))
shape: (4, 1)
┌─────┐
│ int │
│ --- │
│ i64 │
╞═════╡
│ 3   │
│ 2   │
│ 1   │
│ 0   │
└─────┘
```

### Issue description

The second bound is not exclusive when the step is negative, unlike in Python:

```python
>>> list(range(3, 0, -1))
[3, 2, 1]
```

### Expected behavior

```python
>>> pl.select(pl.int_range(3, 0, -1))
shape: (3, 1)
┌─────┐
│ int │
│ --- │
│ i64 │
╞═════╡
│ 3   │
│ 2   │
│ 1   │
└─────┘
```

### Installed versions

0.19.1

**Comment by detrin** [comment] 2023-09-02 10:48
thanks to @milicevica23 who noticed this is bound to https://github.com/pola-rs/polars/issues/10867 

See https://github.com/pola-rs/polars/blob/c4fdbfe2c7f7ce7616ad9301981bc5d616c3beef/crates/polars-plan/src/dsl/function_expr/range.rs#L37C39-L37C39 there is additional `=`

**Comment by detrin** [comment] 2023-09-02 10:49
the new function would be then
```rust
fn int_range_impl<T>(start: T::Native, end: T::Native, step: i64) -> PolarsResult<Series>
where
    T: PolarsNumericType,
    ChunkedArray<T>: IntoSeries,
    std::ops::Range<T::Native>: Iterator<Item = T::Native>,
    std::ops::RangeInclusive<T::Native>: DoubleEndedIterator<Item = T::Native>,
{
    let name = "int";

    let mut ca = match step {
        0 => polars_bail!(InvalidOperation: "step must not be zero"),
        1 => ChunkedArray::<T>::from_iter_values(name, start..end),
        2.. => ChunkedArray::<T>::from_iter_values(name, (start..end).step_by(step as usize)),
        _ => {
            polars_ensure!(start > end, InvalidOperation: "range must be decreasing if 'step' is negative");
            ChunkedArray::<T>::from_iter_values(
                name,
                (end..start).rev().step_by(step.unsigned_abs() as usize),
            )
        },
    };

    let is_sorted = if end < start {
        IsSorted::Descending
    } else {
        IsSorted::Ascending
    };
    ca.set_sorted_flag(is_sorted);

    Ok(ca.into_series())
}
```

**Comment by detrin** [comment] 2023-09-02 10:52
```rust
fn main() {
    let start: i32 = 3;
    let end: i32 = 0;
    let step: i64 = -1;
    let l = (end..=start).rev().step_by(step.unsigned_abs() as usize);
    println!("{:?}", l.collect::<Vec<i32>>());
    // [3, 2, 1, 0]

    let start: i32 = 3;
    let end: i32 = 0;
    let step: i64 = -1;
    let l = (end..start).rev().step_by(step.unsigned_abs() as usize);
    println!("{:?}", l.collect::<Vec<i32>>());
    // [2, 1, 0]
}

```

**Comment by detrin** [comment] 2023-09-02 11:00
Okay, this won't be trivial to fix :D 
```
~/Documents/projects/rust-projects/polars/py-polars main ?1 ❯ pip install -e .                                                                                                       20m 25s Py polars
Obtaining file:///Users/danielherman/Documents/projects/rust-projects/polars/py-polars
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: polars
  Building editable for polars (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for polars (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Running `maturin pep517 build-wheel -i /Users/danielherman/Documents/projects/rust-projects/polars/env/bin/python3.11 --compatibility off --editable`
      🍹 Building a mixed python/rust project
      🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.8
      🐍 Not using a specific python interpreter
      💻 Using `MACOSX_DEPLOYMENT_TARGET=11.0` for aarch64-apple-darwin by default
         Compiling polars-plan v0.32.0 (/Users/danielherman/Documents/projects/rust-projects/polars/crates/polars-plan)
      error[E0277]: the trait bound `<T as polars_core::datatypes::PolarsNumericType>::Native: Step` is not satisfied
          --> /Users/danielherman/Documents/projects/rust-projects/polars/crates/polars-plan/src/dsl/function_expr/range.rs:37:30
           |
      37   |                 (end..start).rev().step_by(step.unsigned_abs() as usize),
           |                              ^^^ the trait `Step` is not implemented for `<T as polars_core::datatypes::PolarsNumericType>::Native`
           |
           = note: required for `std::ops::Range<<T as polars_core::datatypes::PolarsNumericType>::Native>` to implement `DoubleEndedIterator`
      note: required by a bound in `std::iter::Iterator::rev`
          --> /Users/danielherman/.rustup/toolchains/nightly-2023-08-26-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:3398:23
           |
      3396 |     fn rev(self) -> Rev<Self>
           |        --- required by a bound in this associated function
      3397 |     where
      3398 |         Self: Sized + DoubleEndedIterator,
           |                       ^^^^^^^^^^^^^^^^^^^ required by this bound in `Iterator::rev`
      help: consider further restricting the associated type
           |
      25   |     std::ops::RangeInclusive<T::Native>: DoubleEndedIterator<Item = T::Native>, <T as polars_core::datatypes::PolarsNumericType>::Native: Step
           |                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      
      error[E0599]: the method `step_by` exists for struct `Rev<Range<<T as PolarsNumericType>::Native>>`, but its trait bounds were not satisfied
        --> /Users/danielherman/Documents/projects/rust-projects/polars/crates/polars-plan/src/dsl/function_expr/range.rs:37:36
         |
      37 |                 (end..start).rev().step_by(step.unsigned_abs() as usize),
         |                                    ^^^^^^^ method cannot be called on `Rev<Range<<T as PolarsNumericType>::Native>>` due to unsatisfied trait bounds
         |
        ::: /Users/danielherman/.rustup/toolchains/nightly-2023-08-26-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/range.rs:80:1
         |
      80 | pub struct Range<Idx> {
         | --------------------- doesn't satisfy `_: DoubleEndedIterator`
         |
        ::: /Users/danielherman/.rustup/toolchains/nightly-2023-08-26-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/rev.rs:15:1
         |
      15 | pub struct Rev<T> {
         | ----------------- doesn't satisfy `_: Iterator`
         |
         = note: the following trait bounds were not satisfied:
                 `std::ops::Range<<T as polars_core::datatypes::PolarsNumericType>::Native>: DoubleEndedIterator`
                 which is required by `std::iter::Rev<std::ops::Range<<T as polars_core::datatypes::PolarsNumericType>::Native>>: Iterator`
                 `std::iter::Rev<std::ops::Range<<T as polars_core::datatypes::PolarsNumericType>::Native>>: Iterator`
                 which is required by `&mut std::iter::Rev<std::ops::Range<<T as polars_core::datatypes::PolarsNumericType>::Native>>: Iterator`
      
      Some errors have detailed explanations: E0277, E0599.
      For more information about an error, try `rustc --explain E0277`.
      error: could not compile `polars-plan` (lib) due to 2 previous errors
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `CARGO_ENCODED_RUSTFLAGS="-C\u{1f}link-arg=-undefined\u{1f}-C\u{1f}link-arg=dynamic_lookup" MACOSX_DEPLOYMENT_TARGET="11.0" PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON="/Users/danielherman/Documents/projects/rust-projects/polars/env/bin/python3.11" PYTHON_SYS_EXECUTABLE="/Users/danielherman/Documents/projects/rust-projects/polars/env/bin/python3.11" "cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/Users/danielherman/Documents/projects/rust-projects/polars/py-polars/Cargo.toml" "--release" "--lib" "--" "-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" "link-args=-Wl,-install_name,@rpath/polars.abi3.so"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Users/danielherman/Documents/projects/rust-projects/polars/env/bin/python3.11', '--compatibility', 'off', '--editable'] returned non-zero exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for polars
Failed to build polars
ERROR: Could not build wheels for polars, which is required to install pyproject.toml-based projects
```

**Comment by detrin** [comment] 2023-09-03 12:33
Okay, so this should make the trick
```
fn main() {
    // Withhout fix
    let start: i32 = 6;
    let end: i32 = 0;
    let step: i64 = -1;
    let l = (end..=start).rev().step_by(step.unsigned_abs() as usize);
    println!("{:?}", l.collect::<Vec<i32>>());
    // [6, 5, 4, 3, 2, 1, 0]

    let start: i32 = 6;
    let end: i32 = 0;
    let step: i64 = -2;
    let l = (end..=start).rev().step_by(step.unsigned_abs() as usize);
    println!("{:?}", l.collect::<Vec<i32>>());
    // [6, 4, 2, 0]

    let start: i32 = 6;
    let end: i32 = 0;
    let step: i64 = -3;
    let l = (end..=start).rev().step_by(step.unsigned_abs() as usize);
    println!("{:?}", l.collect::<Vec<i32>>());
    // [6, 3, 0]

    // With fix
    let start: i32 = 6;
    let end: i32 = 0;
    let step: i64 = -1;
    let l = (end+1..=start).rev().step_by(step.unsigned_abs() as usize);
    println!("{:?}", l.collect::<Vec<i32>>());
    // [6, 5, 4, 3, 2, 1]

    let start: i32 = 6;
    let end: i32 = 0;
    let step: i64 = -2;
    let l = (end+1..=start).rev().step_by(step.unsigned_abs() as usize);
    println!("{:?}", l.collect::<Vec<i32>>());
    // [6, 4, 2]

    let start: i32 = 6;
    let end: i32 = 0;
    let step: i64 = -3;
    let l = (end+1..=start).rev().step_by(step.unsigned_abs() as usize);
    println!("{:?}", l.collect::<Vec<i32>>());
    // [6, 3]
}
```

**Comment by detrin** [comment] 2023-09-03 13:22
I am stuck and I can't move forward
```rust
    let mut ca = match step {
        0 => polars_bail!(InvalidOperation: "step must not be zero"),
        1 => ChunkedArray::<T>::from_iter_values(name, start..end),
        2.. => ChunkedArray::<T>::from_iter_values(name, (start..end).step_by(step as usize)),
        _ => {
            polars_ensure!(start > end, InvalidOperation: "range must be decreasing if 'step' is negative");
            // increment end by 1 to make it inclusive
            let end_new: T::Native = T::Native::from(1) + end;  

            ChunkedArray::<T>::from_iter_values(
                name,
                (end_new..=start).rev().step_by(step.unsigned_abs() as usize),
            )
        },
    };
```
gives me
```
~/Documents/projects/rust-projects/polars/py-polars main ⇣6 !1 ❯ pip install -e .                                                                                                      7s Py py-polars
Obtaining file:///Users/danielherman/Documents/projects/rust-projects/polars/py-polars
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: polars
  Building editable for polars (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for polars (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Running `maturin pep517 build-wheel -i /Users/danielherman/Documents/projects/rust-projects/polars/py-polars/.venv/bin/python3.11 --compatibility off --editable`
      🍹 Building a mixed python/rust project
      🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.8
      🐍 Not using a specific python interpreter
      💻 Using `MACOSX_DEPLOYMENT_TARGET=11.0` for aarch64-apple-darwin by default
         Compiling polars-plan v0.32.0 (/Users/danielherman/Documents/projects/rust-projects/polars/crates/polars-plan)
      error[E0308]: mismatched types
         --> /Users/danielherman/Documents/projects/rust-projects/polars/crates/polars-plan/src/dsl/function_expr/range.rs:36:54
          |
      36  |             let end_new: T::Native = T::Native::from(1) + end;
          |                                      --------------- ^ expected associated type, found integer
          |                                      |
          |                                      arguments to this function are incorrect
          |
          = note: expected associated type `<T as polars_core::datatypes::PolarsNumericType>::Native`
                                found type `{integer}`
      note: associated function defined here
         --> /Users/danielherman/.rustup/toolchains/nightly-2023-08-26-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/convert/mod.rs:543:8
          |
      543 |     fn from(value: T) -> Self;
          |        ^^^^
      help: consider constraining the associated type `<T as polars_core::datatypes::PolarsNumericType>::Native` to `{integer}`
          |
      22  |     T: PolarsNumericType<Native = {integer}>,
          |                         ++++++++++++++++++++
      
      For more information about this error, try `rustc --explain E0308`.
      error: could not compile `polars-plan` (lib) due to previous error
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `CARGO_ENCODED_RUSTFLAGS="-C\u{1f}link-arg=-undefined\u{1f}-C\u{1f}link-arg=dynamic_lookup" MACOSX_DEPLOYMENT_TARGET="11.0" PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON="/Users/danielherman/Documents/projects/rust-projects/polars/py-polars/.venv/bin/python3.11" PYTHON_SYS_EXECUTABLE="/Users/danielherman/Documents/projects/rust-projects/polars/py-polars/.venv/bin/python3.11" "cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/Users/danielherman/Documents/projects/rust-projects/polars/py-polars/Cargo.toml" "--release" "--lib" "--" "-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" "link-args=-Wl,-install_name,@rpath/polars.abi3.so"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Users/danielherman/Documents/projects/rust-projects/polars/py-polars/.venv/bin/python3.11', '--compatibility', 'off', '--editable'] returned non-zero exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for polars
Failed to build polars
ERROR: Could not build wheels for polars, which is required to install pyproject.toml-based projects
```

**Comment by detrin** [comment] 2023-09-03 15:01
@stinodego could you have a look at this please?

**Comment by stinodego** [comment] 2023-09-04 04:48
This is a duplicate of #9671

But I guess since this issue is more recent and is seeing more activity, I'll close the other one in favor of this one.

**Comment by orlp** [comment] 2023-09-04 06:35
I will take a look today to fix this.

**Closed** 2023-09-04 14:11 UTC
Labels: bug, python, rust, accepted
