### ISSUE TITLE
Multiply all element of an array by value of another column

### ISSUE THREAD

**Issue by tim-habitat** [pola-rs/polars#9948] opened 2023-07-18 10:04 UTC
### Problem description

It would fantastic if i could just do:
```python
>>> df=pl.DataFrame({"a": [[1,2,3], [3,4,5]], "b": [0.5, 0.1]})
>>> df.with_columns(
...     new_col=pl.col("a").list.eval(pl.element() * pl.col("b") * 2)
... )
```
but this currently yields:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tim/Documents/Github/ercot-wind-optimisation/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 7335, in with_columns
    .collect(no_optimization=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tim/Documents/Github/ercot-wind-optimisation/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1531, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
exceptions.ComputeError: named columns are not allowed in `list.eval`; consider using `element` or `col("")`
```
on version `0.18.7`

On a side note, the error is counter intuitive as here i am using `pl.col("")`.

**Comment by ritchie46** [comment] 2023-07-18 10:16
Duplicate of #9188 and #8006

**Closed by ritchie46** 2023-07-18 10:16 UTC
Labels: enhancement

**Comment by ritchie46** [comment] 2023-07-18 10:35
For the record, it is planned, but let's keep discussion in the existing issues.

**Comment by stinodego** [comment] 2023-07-18 10:39
Yeah, the GitHub UI is confusing here. It says "closed as not planned" but the description is "Won't fix, can't repro, duplicate, stale". In this case it's a duplicate.
