### ISSUE TITLE
Expr.rolling_*(window_size: timedelta, center=True) does not do any centering

### ISSUE THREAD

**Issue by m-legrand** [pola-rs/polars#10338] opened 2023-08-07 13:27 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import datetime as dt
>>> import polars as pl
>>> n = 5
... winsize = dt.timedelta(hours=2)
... data = {"t": [dt.datetime(2000, 1, 1, i) for i in range(n)], "v": list(range(n))}
... df = pl.DataFrame(data).set_sorted("t")
... 
... for center in [False, True]:
...     print(f"{center=}")
...     dfi = df.with_columns(
...         v_min=pl.col("v").rolling_min(winsize, center=center, by="t", closed="both"),
...         v_max=pl.col("v").rolling_max(winsize, center=center, by="t", closed="both"),
...         v_mean=pl.col("v").rolling_mean(winsize, center=center, by="t", closed="both"),
...     )
...     print(dfi)
...     print()
...

center=False
shape: (5, 5)
┌─────────────────────┬─────┬───────┬───────┬────────┐
│ t                   ┆ v   ┆ v_min ┆ v_max ┆ v_mean │
│ ---                 ┆ --- ┆ ---   ┆ ---   ┆ ---    │
│ datetime[μs]        ┆ i64 ┆ i64   ┆ i64   ┆ f64    │
╞═════════════════════╪═════╪═══════╪═══════╪════════╡
│ 2000-01-01 00:00:00 ┆ 0   ┆ 0     ┆ 0     ┆ 0.0    │
│ 2000-01-01 01:00:00 ┆ 1   ┆ 0     ┆ 1     ┆ 0.5    │
│ 2000-01-01 02:00:00 ┆ 2   ┆ 0     ┆ 2     ┆ 1.0    │
│ 2000-01-01 03:00:00 ┆ 3   ┆ 1     ┆ 3     ┆ 2.0    │
│ 2000-01-01 04:00:00 ┆ 4   ┆ 2     ┆ 4     ┆ 3.0    │
└─────────────────────┴─────┴───────┴───────┴────────┘

center=True
shape: (5, 5)
┌─────────────────────┬─────┬───────┬───────┬────────┐
│ t                   ┆ v   ┆ v_min ┆ v_max ┆ v_mean │
│ ---                 ┆ --- ┆ ---   ┆ ---   ┆ ---    │
│ datetime[μs]        ┆ i64 ┆ i64   ┆ i64   ┆ f64    │
╞═════════════════════╪═════╪═══════╪═══════╪════════╡
│ 2000-01-01 00:00:00 ┆ 0   ┆ 0     ┆ 0     ┆ 0.0    │
│ 2000-01-01 01:00:00 ┆ 1   ┆ 0     ┆ 1     ┆ 0.5    │
│ 2000-01-01 02:00:00 ┆ 2   ┆ 0     ┆ 2     ┆ 1.0    │
│ 2000-01-01 03:00:00 ┆ 3   ┆ 1     ┆ 3     ┆ 2.0    │
│ 2000-01-01 04:00:00 ┆ 4   ┆ 2     ┆ 4     ┆ 3.0    │
└─────────────────────┴─────┴───────┴───────┴────────┘
```

### Issue description

When applying a rolling function with a timedelta (which has a fixed length, compared to calendar strings such as "1mo"), I expect for `center=True` to either:

- ideal: return the calculated fields by the time at the center of the window;
- less ideal: fail and say it is not supported
- unforeseen: the current behaviour, but with good explanations in the docs

I've added the last option, because admittedly I'm not sure I understand the wording of the docs:

> **center**
>     Set the labels at the center of the window

Instead it seems like `center=True` does not do anything.
For instance in the example above, with `window_size=dt.timedelta(hours=2), closed="both", center=True`, I would expect that the values 1 (1am), 2 (2am) and 3 (3am) be centered around 2am, for an average of `2.0`.
Instead it aggregates values between 0 and 2, for an average of `1.0`.

### Expected behavior

I'm able to somewhat reproduce the expected behaviour with the below function, but I don't have a ton o

```python
>>> print("center=True (custom)")
... dfi = df.groupby_rolling("t", period=winsize, offset=(-winsize/2), closed="both").agg(
...     v_min=pl.col("v").min(),
...     v_max=pl.col("v").max(),
...     v_mean=pl.col("v").mean(),
... )
... print(dfi)
...
center=True (custom)
shape: (5, 4)
┌─────────────────────┬───────┬───────┬────────┐
│ t                   ┆ v_min ┆ v_max ┆ v_mean │
│ ---                 ┆ ---   ┆ ---   ┆ ---    │
│ datetime[μs]        ┆ i64   ┆ i64   ┆ f64    │
╞═════════════════════╪═══════╪═══════╪════════╡
│ 2000-01-01 00:00:00 ┆ 0     ┆ 1     ┆ 0.5    │
│ 2000-01-01 01:00:00 ┆ 0     ┆ 2     ┆ 1.0    │
│ 2000-01-01 02:00:00 ┆ 1     ┆ 3     ┆ 2.0    │
│ 2000-01-01 03:00:00 ┆ 2     ┆ 4     ┆ 3.0    │
│ 2000-01-01 04:00:00 ┆ 3     ┆ 4     ┆ 3.5    │
└─────────────────────┴───────┴───────┴────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.7
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          0.3.2a7
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.25.0
pandas:              1.5.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          2.0.19
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by stinodego** [comment] 2023-10-14 14:43
Duplicate of #3717

**Closed by stinodego** 2023-10-14 14:43 UTC
Labels: bug, python
