### ISSUE TITLE
Black box function sample of module lazy is not working ...

### ISSUE THREAD

**Issue by gittesti** [pola-rs/polars#4741] opened 2022-09-06 04:40 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of polars.

### Issue Description

While learning about the Lazy DataFrame I noticed a few issue with the [Black box function sample](https://docs.rs/polars/latest/polars/docs/lazy/index.html#black-box-function). It does not compile / work as is.

### Reproducible Example

Just run the code sample @ ([Black box function](https://docs.rs/polars/latest/polars/docs/lazy/index.html#black-box-function)) 

Its starts with the column names used here `.select([concat_lst(["col_a", "col_b"])` but the definition is just "a" and "b" ... so that needs to be changed to "col_a" and "col_b" in the df creation `"a" => [1.0, 2.0, 3.0],` ==> `"col_a" => [1.0, 2.0, 3.0],`

`ERROR: thread **main** panicked at called **Result::unwrap()** on an **Err** value: NotFound("col_a")`

The second issue is the creation of a StructArray, which is needed for `let ca = s.struct_()?;` ... the previous `concat_list` does not create one.

`ERROR: thread **main** panicked at called **Result::unwrap()** on an **Err** value: SchemaMisMatch("Series of dtype: List(Float64) != Struct")`

### Expected Behavior

A working sample :)

### Installed Versions

<details>

rustc 1.65.0-nightly (289279de1 2022-09-04)

 polars = {version = "*", features = ["json", "lazy", "csv-file", "performant", "strings", "simd", "decompress", "sort_multiple", "rows", "parquet", "groupby_list", "is_in", "list", "dtype-full",]}

[[package]]
name = "polars"
version = "0.23.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "a75b1077fda63c0f67acc1cdc8586e7afce419be1e85bf7dfa8935e0e266d6b3"
dependencies = [
 "polars-core",
 "polars-io",
 "polars-lazy",
 "polars-ops",
 "polars-time",
]
</details>

**Comment by ritchie46** [comment] 2022-09-06 08:15
Duplicate of #4375

**Closed by ritchie46** 2022-09-06 08:15 UTC
Labels: bug, rust
