### ISSUE TITLE
Join drops right_on column

### ISSUE THREAD

**Issue by Hattonuri** [pola-rs/polars#14770] opened 2024-02-29 13:09 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({
    "id": [1, 2, 3, 4],
    # "employee_name": ["John Doe", "Jane Smith", "Emily Davis", "Michael Brown"],
    # "department_id": [101, 102, 101, 103]
})
df.join(
    df.select(pl.all().name.prefix('__')),
    left_on='id',
    right_on='__id'
)
```

### Log output

```shell
shape: (4, 1)
id
i64
1
2
3
4
```

### Issue description

 - 

### Expected behavior

Result DataFrame to contain right column 

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.13
Index type:           UInt32
Platform:             Linux-5.15.0-91-generic-x86_64-with-glibc2.31
Python:               3.11.6 (main, Oct 31 2023, 13:40:18) [GCC 13.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.7.1
numpy:                1.23.4
openpyxl:             3.0.7
pandas:               2.0.0rc1
pyarrow:              13.0.0
pydantic:             1.10.4
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.51
xlsx2csv:             <not installed>
xlsxwriter:           1.1.1
```

</details>

**Comment by avimallu** [comment] 2024-02-29 15:16
Related https://github.com/pola-rs/polars/issues/9335

**Comment by ritchie46** [comment] 2024-03-01 07:21
In an inner join, there is no point in keeping the right column, it is redundant. There is no extra information there.

**Comment by Hattonuri** [comment] 2024-03-01 12:54
It is not redundant because it has different name. If I have the code that puts some sense in the name of the second column - we lose that sense after join and have to use the first name

**Comment by orlp** [comment] 2024-03-11 11:11
This is currently by design but will be changed once we implement the `coalesce` parameter for joins. So I'm closing this issue in favor of that one.

https://github.com/pola-rs/polars/issues/14925

**Closed by orlp** 2024-03-11 11:11 UTC
Labels: bug, python, needs triage
