### ISSUE TITLE
Allow to add metadata on columns 

### ISSUE THREAD

**Issue by natir** [pola-rs/polars#8519] opened 2023-04-26 10:03 UTC
### Problem description

First thanks for your work on polars

I would like to be able to add metadata on the columns of my dataframe or lazyframe.

~~I understood that it was possible in the rust version but not yet in the python version.~~
Apparently it's not possible in rust version.

It's possible that I've searched wrongly that this feature is already available if it is the case I'm sorry to have created an issue for nothing.

**Comment by zundertj** [comment] 2023-05-06 09:31
Duplicate of #5117.

**Closed by zundertj** 2023-05-06 09:31 UTC
Labels: enhancement

**Comment by natir** [comment] 2023-05-09 08:09
Sorry thank !
