### ISSUE TITLE
when "columns =" is specified, "pl.read_csv()" doesn't import columns based on the specified order of "columns = "

### ISSUE THREAD

**Issue by 3SMMZRjWgS** [pola-rs/polars#15027] opened 2024-03-13 03:50 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example
```python
from io import StringIO
import polars as pl

df = pl.read_csv(
    source  = StringIO("id,y,x\n1,2,3"), 
    columns = ["id","x","y"],
)
```

### Log output
```python
# ┌─────┬─────┬─────┐
# │ id  ┆ y   ┆ x   │  << should be x, y (not y, x) ?
# │ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ i64 │
# ╞═════╪═════╪═════╡
# │ 1   ┆ 2   ┆ 3   │
# └─────┴─────┴─────┘
```

### Issue description

When specifying columns in `pl.read_csv()`, the method doesn't load csv columns based on the specified order, instead, retains original column order from the csv. Is there anyway that this order can be specified by the `columns =` parameter?

### Expected behavior
```python
# ┌─────┬─────┬─────┐
# │ id  ┆ x   ┆ y   │
# │ --- ┆ --- ┆ --- │
# │ i64 ┆ i64 ┆ i64 │
# ╞═════╪═════╪═════╡
# │ 1   ┆ 3   ┆ 2   │
# └─────┴─────┴─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.14
Index type:           UInt32
Platform:             Windows-10-10.0.22631-SP0
Python:               3.11.8 | packaged by Anaconda, Inc. | (main, Feb 26 2024, 21:34:05) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.3
numpy:                1.26.4
openpyxl:             3.0.10
pandas:               2.2.1
pyarrow:              15.0.0
pydantic:             2.5.3
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by alexander-beedie** [comment] 2024-03-13 06:37
The "columns" param doesn't actually say it will select the columns in the given order; just that it will select them. So, I wouldn't say this is a bug (as the parameter does what it says it will do), but I think I agree it probably should be updated to do what you expected 🤔

I'll tag this as an enhancement rather than a bug.

**Comment by 3SMMZRjWgS** [comment] 2024-03-13 06:47
Thank you so much for the quick response and willingness to include it as an enhancement, Alex! I agree, it's not technically a bug. I stumbled upon it as a recent polars user when i was doing pl.read_csv("path.csv", columns = ['a', 'b', 'c'], new_columns = ['x', 'y', 'z']), thinking that they'll match in sequence, then found out that the new header and the read in columns mismatched.

**Comment by mcrumiller** [comment] 2024-03-13 12:08
Duplicate of #13066.

**Comment by mcrumiller** [comment] 2024-03-13 12:15
FYI there are a *lot* of CSV parameter issues, the python function needs a complete revamp IMO with some stricter requirements laid out. Off the top of my head (these are mostly my issues, I know there are others):

* this issue
* `schema` parameter should be able to specify dtypes on columns selected, if that's a subset (currently requires schema of entire df I believe, regardless of whether columns are used)
* keys in `dtypes` or `schema` parameter should only allow `new_columns` as keys when `new_columns` is specified as a parameter (#11186)
* column names get overwritten when `dtypes` has more keys than columns (#13574)

**Comment by stinodego** [comment] 2024-06-08 09:27
Closing in favor of https://github.com/pola-rs/polars/issues/13066

**Closed by stinodego** 2024-06-08 09:27 UTC
Labels: python, enhancement
