### ISSUE TITLE
`from_arrow`  will error out while reading lists with datetimes

### ISSUE THREAD

**Issue by ion-elgreco** [pola-rs/polars#10160] opened 2023-07-29 10:56 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import datetime
import polars as pl
from polars import Datetime


df  = pl.DataFrame(
    [
        pl.Series("date_range", [[datetime.datetime(2010, 1, 1, 0, 0), datetime.datetime(2010, 1, 2, 0, 0)]], dtype=pl.List(Datetime(time_unit='us', time_zone='UTC'))),
    ]
)

pl.from_arrow(df.to_arrow())

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `Timestamp(Microsecond, None)`,
 right: `Int64`', /home/<redacted>/polars/crates/polars-core/src/chunked_array/from.rs:93:17
```

### Issue description

Polars is not able to read arrow tables that contains columns with List dtype and items with DateTime dtype.

### Expected behavior

Just being able to read the data. PyArrow can read it fine.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.9
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.11.4 (main, Jul 16 2023, 15:13:18) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           0.10.1
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.1
pandas:              1.5.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ion-elgreco** [comment] 2023-08-20 15:27
@stinodego this error is strange. In windows it will run fine, but in WSL (Linux) it will fail.
### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  0.5.1
cloudpickle:         1.6.0
connectorx:          0.3.1
deltalake:           0.10.0
fsspec:              2021.07.0
matplotlib:          3.3.4
numpy:               1.20.3
pandas:              1.3.0
pyarrow:             12.0.1
pydantic:            2.0.3
sqlalchemy:          1.4.13
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by stinodego** [comment] 2023-08-20 15:39
I can reproduce this on WSL. Can check Ubuntu later.

**Comment by chitralverma** [comment] 2023-08-21 15:03
Cant reproduce it on linux/ mac.
Although, there was a typo in your imports.

```
python
>>> import datetime
>>> import polars as pl
>>> from polars import Datetime
>>>
>>>
>>> df  = pl.DataFrame(
...     [
...         pl.Series("date_range", [[datetime.datetime(2010, 1, 1, 0, 0), datetime.datetime(2010, 1, 2, 0, 0)]], dtype=pl.List(Datetime(time_unit='us', time_zone='UTC'))),
...     ]
... )
>>> df.write_delta('/tmp/test', mode='append')
>>> pl.read_delta('/tmp/test')
shape: (1, 1)
┌───────────────────────────────────┐
│ date_range                        │
│ ---                               │
│ list[datetime[μs]]                │
╞═══════════════════════════════════╡
│ [2010-01-01 00:00:00, 2010-01-02… │
└───────────────────────────────────┘
>>>
>>> pl.show_versions()
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            macOS-13.4-arm64-arm-64bit
Python:              3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           0.10.1
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              <not installed>
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
>>>
```

**Comment by ion-elgreco** [comment] 2023-08-21 15:11
> Cant reproduce it on linux/ mac.
> Although, there was a typo in your imports.
> 
> ```
> python
> >>> import datetime
> >>> import polars as pl
> >>> from polars import Datetime
> >>>
> >>>
> >>> df  = pl.DataFrame(
> ...     [
> ...         pl.Series("date_range", [[datetime.datetime(2010, 1, 1, 0, 0), datetime.datetime(2010, 1, 2, 0, 0)]], dtype=pl.List(Datetime(time_unit='us', time_zone='UTC'))),
> ...     ]
> ... )
> >>> df.write_delta('/tmp/test', mode='append')
> >>> pl.read_delta('/tmp/test')
> shape: (1, 1)
> ┌───────────────────────────────────┐
> │ date_range                        │
> │ ---                               │
> │ list[datetime[μs]]                │
> ╞═══════════════════════════════════╡
> │ [2010-01-01 00:00:00, 2010-01-02… │
> └───────────────────────────────────┘
> >>>
> >>> pl.show_versions()
> --------Version info---------
> Polars:              0.18.15
> Index type:          UInt32
> Platform:            macOS-13.4-arm64-arm-64bit
> Python:              3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
> 
> ----Optional dependencies----
> adbc_driver_sqlite:  <not installed>
> cloudpickle:         <not installed>
> connectorx:          <not installed>
> deltalake:           0.10.1
> fsspec:              <not installed>
> matplotlib:          <not installed>
> numpy:               1.25.2
> pandas:              <not installed>
> pyarrow:             12.0.1
> pydantic:            <not installed>
> sqlalchemy:          <not installed>
> xlsx2csv:            <not installed>
> xlsxwriter:          <not installed>
> >>>
> ```
> 
> 
> 

Interesting, maybe it only affects WSL. Yes, the typo is unrelated, was an issue with copy pasting and editing afterwards :)

**Comment by chitralverma** [comment] 2023-08-21 15:14
yea, and the error is regarding a conversion problem - which I think is not related to delta integration. looks more like arrow side issue

**Comment by ion-elgreco** [comment] 2023-08-21 15:16
Correct, that's why added from_arrow as well

**Comment by ion-elgreco** [comment] 2023-08-21 15:59
> yea, and the error is regarding a conversion problem - which I think is not related to delta integration. looks more like arrow side issue

I've updated the description and title for more clarity :)

**Comment by ion-elgreco** [comment] 2023-09-23 19:01
Weird. can't reproduce this anymore in WSL on any version. I guess it can be closed now?

**Comment by stinodego** [comment] 2023-10-14 14:40
I also cannot reproduce it anymore. Maybe it was fixed on the arrow size.

**Closed by stinodego** 2023-10-14 14:40 UTC
Labels: bug, python, accepted
