### ISSUE TITLE
Join key columns are dropped regardless of whether their names match

### ISSUE THREAD

**Issue by cpcloud** [pola-rs/polars#9970] opened 2023-07-19 11:41 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
In [27]: import polars as pl

In [28]: left = pl.DataFrame({"a1": [1, 2, 3], "b": list("abc")})

In [29]: right = pl.DataFrame({"a2": [1, 2, None], "b": list("abc")})

In [30]: joined = left.join(right, left_on=["a1"], right_on=["a2"], how="left")

In [31]: joined
Out[31]:
shape: (3, 3)
┌─────┬─────┬─────────┐
│ a1  ┆ b   ┆ b_right │
│ --- ┆ --- ┆ ---     │
│ i64 ┆ str ┆ str     │
╞═════╪═════╪═════════╡
│ 1   ┆ a   ┆ a       │
│ 2   ┆ b   ┆ b       │
│ 3   ┆ c   ┆ null    │
└─────┴─────┴─────────┘

In [32]: # Where is a2?
```

### Issue description

Join key columns whose names don't match are discarded, which in the case of non-inner joins results in information loss if there are nulls in either side's join keys.

### Expected behavior

Ideally this information is at least preserved in the case where the column names do not match, instead of discarded.

### Installed versions

<details>

```
In [33]: pl.show_versions()
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Linux-6.1.38-x86_64-with-glibc2.37
Python:      3.10.12 (main, Jun  6 2023, 22:43:10) [GCC 12.3.0]

----Optional dependencies----
numpy:       1.25.0
pandas:      2.0.3
pyarrow:     10.0.1
connectorx:  <not installed>
deltalake:   0.10.0
fsspec:      2023.6.0
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by gab23r** [comment] 2023-07-19 11:51
duplicate of #9335 ?

**Comment by cpcloud** [comment] 2023-07-19 12:06
I think it's a bug that when the names are different one of them is dropped.

The discussion about how to handle the case where column names match is separate from this issue IMO.

**Comment by ritchie46** [comment] 2023-07-19 12:13
Yes, that's #9335. I will close this one on favor of that one.

We are looking in into that.

**Closed by ritchie46** 2023-07-19 12:13 UTC
Labels: bug, python

**Comment by cpcloud** [comment] 2023-07-19 12:15
Thanks @ritchie46!
