### ISSUE TITLE
Add `dt.replace` functions to specify specific day, month, year, etc. for `date` and `datetime`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#15794] opened 2024-04-19 20:37 UTC
### Description

The native `datetime` has `.replace` functions that allow the user to change the day, month, year, etc. to specific values:

```python
import datetime
datetime.date(2024, 1, 1).replace(month=3, day=5)
# datetime.date(2024, 3, 5)
```

This would be useful for our `Date` and `Datetime` dtypes as well:

```python
from datetime import date
import polars as pl

s = pl.Series([date(2024, 1, 31), date(2024, 5, 30)])
s.dt.replace(day=10)
# shape: (2,)
# Series: '' [date]
# [
#         2024-01-10
#         2024-05-10
# ]
```

This can currently be achieved via `s.dt.truncate("1mo").dt.offset_by("9d")` but it's a bit ugly.

**Comment by MarcoGorelli** [comment] 2024-04-20 09:24
I think this is a duplicate of your own issue 😉  #8879

**Closed** 2024-04-20 10:59 UTC
Labels: enhancement

**Comment by mcrumiller** [comment] 2024-04-20 17:03
Heh, sorry Marco, good find. 🤭
