### ISSUE TITLE
Can't read parquet from a path with square brackets: RecursionError

### ISSUE THREAD

**Issue by danielgafni** [pola-rs/polars#14733] opened 2024-02-27 21:40 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import pandas as pd


def test_read_parquet_square_brackets_path():
    path = "/tmp/[0].parquet"

    df = pl.DataFrame({"a": [0, 1, 2]})

    df.write_parquet(path)

    pd.read_parquet(path)  # works
    pl.read_parquet(path)  # fails
```

### Log output

```shell
>       return wrap_df(ldf.collect())
E       polars.exceptions.ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: ComputeError: RecursionError: maximum recursion depth exceeded

.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py:1939: ComputeError
```

### Issue description

`polars` fails to read a Parquet file from a path containing square brackets. 

This is a problem with Dagster's dynamic ops as they have `[i]` inserted in result paths regularly. 

I've marked this as `python` but it might be a `rust` bug, I'm not sure

### Expected behavior

The Parquet file should be ok to read 

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.11
Index type:           UInt32
Platform:             Linux-6.7.6-arch1-1-x86_64-with-glibc2.39
Python:               3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

</details>

**Comment by stinodego** [comment] 2024-02-27 23:18
Duplicate of https://github.com/pola-rs/polars/issues/12876

**Closed by stinodego** 2024-02-27 23:18 UTC
Labels: bug, python, needs triage
