### ISSUE TITLE
`pl.unique` cannot take a `pl.Expr` or `List[pl.Expr]` as arguments in `subset`

### ISSUE THREAD

**Issue by beckadd** [pola-rs/polars#7191] opened 2023-02-26 06:52 UTC
### Problem description

I would love to be able to specify columns for `unique` using an `Expr` rather than a string. Is this a possibility?

**Comment by universalmind303** [comment] 2023-02-26 18:23
duplicate of https://github.com/pola-rs/polars/issues/5760

**Closed by universalmind303** 2023-02-26 18:23 UTC
Labels: enhancement
