### ISSUE TITLE
Dictionary and json like data is being incorrectly processed.

### ISSUE THREAD

**Issue by Sergio-Pedraza** [pola-rs/polars#11715] opened 2023-10-13 14:33 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl
import pandas as pd


sample_data = [{'feature_1': 'abdc', 'feature_2': {}},
               {'feature_1': 'edfg', 'feature_2': {'a':'b'}},
               {'feature_1': 'ghij', 'feature_2': {'c':'d'}},
               ]


df = pl.DataFrame(sample_data)


print(df.to_pandas())

pandas_df = pd.DataFrame(sample_data)


print(pandas_df)
```

### Issue description

I found that when creating a dataframe from a list of dictionaries, if there is a dictionary field its schema is read wrong, as if some sort of regular structure was force upon it. 

### Expected behavior

The dictionary column should keep each record dictionary, as can be seen on the example, where each dictionary stays the same.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.8
Index type:          UInt32
Platform:            Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.10
Python:              3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         1.6.0
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2022.02.0
gevent:              21.1.2
matplotlib:          3.3.4
numpy:               1.24.3
openpyxl:            3.0.7
pandas:              2.0.3
pyarrow:             13.0.0
pydantic:            1.10.7
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.3.24
xlsx2csv:            <not installed>
xlsxwriter:          3.1.2
```

</details>

**Comment by DrMantisTobbogan** [comment] 2023-10-13 14:58
I can confirm that I'm seeing the same unexpected behavior on my development machine:
```
>>> print(df.to_pandas())
  feature_1               feature_2
0      abdc  {'a': None, 'c': None}
1      edfg   {'a': 'b', 'c': None}
2      ghij   {'a': None, 'c': 'd'}
>>> 
>>> pandas_df = pd.DataFrame(sample_data)
>>> print(pandas_df)
  feature_1   feature_2
0      abdc          {}
1      edfg  {'a': 'b'}
2      ghij  {'c': 'd'}
````
System info:
```
--------Version info---------
Polars:              0.19.5
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.9.2
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

**Comment by cmdlineluser** [comment] 2023-10-13 15:02
> as if some sort of regular structure was force upon it.

This is by design.

A column in Polars (pl.Series) has a single type.

In this case, `feature_2` has a type of `Struct([Field('a', Utf8), Field('c', Utf8)])` and all rows in the column must conform.

**Comment by ion-elgreco** [comment] 2023-10-13 18:07
Pandas doesn't have a struct type it simply will store the dict as a python object, that's why it retains that structure. Polars actually infers the full struct and will fill the missing fields in as None.

**Comment by DrMantisTobbogan** [comment] 2023-10-13 21:22
Thank you both for the answers! Both Sergio and I approached this with a Pandas mentality, and overlooked the first line about series in the user guide:

> Series are a 1-dimensional data structure. Within a series all elements have the same data type (e.g. int, string).

I think this request here has the feature that Sergio and I are looking for: https://github.com/pola-rs/polars/issues/8912.

We can probably close this issue out 😃

**Comment by romanovacca** [comment] 2023-10-19 22:36
@stinodego possible close

**Closed** 2023-10-19 22:43 UTC
Labels: bug, invalid, python
