### ISSUE TITLE
Add `.only` aggregation for expressions.

### ISSUE THREAD

**Issue by Andre-Medina** [pola-rs/polars#17202] opened 2024-06-26 04:51 UTC
### Description

Feature request from #16660

Would be very handed to have a way to select the 'only' element in a expression and to raise an error otherwise.

example:
if you had data such as
```python
data_with_groups = pl.DataFrame({
        "year": [2020, 2021, 2022] * 3,
        "groups": ["A"] * 3 + ["B"] * 3 + ["C"] * 3, 
        "data": [1, 2, 3, 10, 20, 30, 20, 20, 40]
    }).vstack(
        pl.DataFrame({
            "year" : [2021, 2030],
            "groups": ["A", "D"],
            "data": [10, 20],
        })
    )

print(data_with_groups)
"""
shape: (11, 3)
┌──────┬────────┬──────┐
│ year ┆ groups ┆ data │
│ ---  ┆ ---    ┆ ---  │
│ i64  ┆ str    ┆ i64  │
╞══════╪════════╪══════╡
│ 2020 ┆ A      ┆ 1    │
│ 2021 ┆ A      ┆ 2    │
│ 2022 ┆ A      ┆ 3    │
│ 2020 ┆ B      ┆ 10   │
│ 2021 ┆ B      ┆ 20   │
│ …    ┆ …      ┆ …    │
│ 2020 ┆ C      ┆ 20   │
│ 2021 ┆ C      ┆ 20   │
│ 2022 ┆ C      ┆ 40   │
│ 2021 ┆ A      ┆ 10   │
│ 2030 ┆ D      ┆ 20   │
└──────┴────────┴──────┘
"""
```
and you wanted to divide the data by the value of the data on a specific year, grouping by another column. You can do so currently by:

```python
print(
    data_with_groups
    .with_columns(
        pl.col('data')
        .truediv(
            pl.col('data').filter(pl.col('year') == 2021).first()
        )
        .over('groups')
        .alias('ratio')
    )
)
"""
shape: (11, 4)
┌──────┬────────┬──────┬───────┐
│ year ┆ groups ┆ data ┆ ratio │
│ ---  ┆ ---    ┆ ---  ┆ ---   │
│ i64  ┆ str    ┆ i64  ┆ f64   │
╞══════╪════════╪══════╪═══════╡
│ 2020 ┆ A      ┆ 1    ┆ 0.5   │
│ 2021 ┆ A      ┆ 2    ┆ 1.0   │
│ 2022 ┆ A      ┆ 3    ┆ 1.5   │
│ 2020 ┆ B      ┆ 10   ┆ 0.5   │
│ 2021 ┆ B      ┆ 20   ┆ 1.0   │
│ …    ┆ …      ┆ …    ┆ …     │
│ 2020 ┆ C      ┆ 20   ┆ 1.0   │
│ 2021 ┆ C      ┆ 20   ┆ 1.0   │
│ 2022 ┆ C      ┆ 40   ┆ 2.0   │
│ 2021 ┆ A      ┆ 10   ┆ 5.0   │
│ 2030 ┆ D      ┆ 20   ┆ null  │
└──────┴────────┴──────┴───────┘
"""
```
However, as seen it doesn't find an issue with the double 2021 A value or the D group with no value at the specific year. 

I suggest a simple method such as `.only()` which will select the only value, and if there's not exactly one value per group, raise an error.

e.g.
```python
(
    data_with_groups
    .with_columns(
        pl.col('data')
        .truediv(
            pl.col('data').filter(pl.col('year') == 2021).only()
        )
        .over('groups')
        .alias('ratio')
    )
)
"""
ValueError: Ambigious which item to select for grouping.
"""
```

In this simplistic example you could drop the duplicated but if the years were timestamps it might not be so obvious.

**Comment by stinodego** [comment] 2024-06-26 20:45
Duplicate of https://github.com/pola-rs/polars/issues/8689

**Closed by stinodego** 2024-06-26 20:45 UTC
Labels: enhancement
