### ISSUE TITLE
Typo on read_excel page

### ISSUE THREAD

**Issue by ianozsvald** [pola-rs/polars#12208] opened 2023-11-02 20:46 UTC
### Description

"engine in ocnjunction with the" should read "conjunction":
https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_excel.html

### Link

https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_excel.html

**Comment by mcrumiller** [comment] 2023-11-02 21:38
Duplicate of #11931 which has already been fixed via #11934.

**Comment by stinodego** [comment] 2023-11-03 00:59
Will be fixed with the next release.

**Closed by stinodego** 2023-11-03 00:59 UTC
Labels: documentation
