### ISSUE TITLE
Milliseconds are lost when using `.str.strftime` 

### ISSUE THREAD

**Issue by danielgafni** [pola-rs/polars#4575] opened 2022-08-26 12:09 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Polars seems to lose the information about milliseconds after converting `Utf8` to `Datetime`

### Reproducible Example

```python
import polars as pl
df = pl.DataFrame([pl.Series(values=["2022-08-26 11:38:14.123"], name="ts_str")]).with_column(pl.col("ts_str").str.strptime(pl.Datetime, "%Y-%m-%d %H:%M:%S.%f").alias("ts_dt"))
df.select(pl.col("ts_dt").dt.strftime("%Y-%m-%d %H:%M:%S.%f"))
Out[4]: 
shape: (1, 1)
┌───────────────────────────────┐
│ ts_dt                         │
│ ---                           │
│ str                           │
╞═══════════════════════════════╡
│ 2022-08-26 11:38:14.000000000 │
└───────────────────────────────┘
```

### Expected Behavior

milliseconds shouldn't be lost

### Installed Versions

<details>

---Version info---
Polars: 0.14.5
Index type: UInt32
Platform: Linux-5.19.2-arch1-1-x86_64-with-glibc2.35
Python: 3.8.12 (default, May 28 2022, 19:33:03) 
[GCC 12.1.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.3
numpy: 1.23.1
fsspec: <not installed>
connectorx: 0.3.0
xlsx2csv: <not installed>

</details>

**Comment by ritchie46** [comment] 2022-08-26 16:13
You parsed the milliseconds as nanoseconds: https://docs.rs/chrono/latest/chrono/format/strftime/

**Comment by alexander-beedie** [comment] 2022-08-26 17:00
You need `%3f` instead of `%f`:
```python
df.with_column( 
    pl.col("ts_str").str.strptime(pl.Datetime, "%Y-%m-%d %H:%M:%S.%3f").alias("ts_dt") 
)
# ┌─────────────────────────┬─────────────────────────┐
# │ ts_str                  ┆ ts_dt                   │
# │ ---                     ┆ ---                     │
# │ str                     ┆ datetime[μs]            │
# ╞═════════════════════════╪═════════════════════════╡
# │ 2022-08-26 11:38:14.123 ┆ 2022-08-26 11:38:14.123 │
# └─────────────────────────┴─────────────────────────┘
```
It might be slightly unexpected expected, but the docstring does mention it ;)
```
fmt
    Format to use - refer to the `chrono strftime documentation
    <https://docs.rs/chrono/latest/chrono/format/strftime/index.html>`_
    for specification. 
```

**Comment by cbilot** [comment] 2022-08-26 17:47
Let me see if I can help.  I believe that the issue is more simple: the `%` and `.` were accidentally interchanged in your format specifier.

For example, let's start with this data:
```python3
df = pl.DataFrame(
    {
        'ts_str': [
            "2022-08-26 11:38:14",
            "2022-08-26 11:38:14.123",
            "2022-08-26 11:38:14.123456",
            "2022-08-26 11:38:14.123456789",
        ]
    })
df
```
```
shape: (4, 1)
┌───────────────────────────────┐
│ ts_str                        │
│ ---                           │
│ str                           │
╞═══════════════════════════════╡
│ 2022-08-26 11:38:14           │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-08-26 11:38:14.123       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-08-26 11:38:14.123456    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-08-26 11:38:14.123456789 │
└───────────────────────────────┘
```
I'll use both format specifiers: `%.f` and `.%f`:
```python3
(
    df.with_columns(
        [
            pl.col("ts_str")
            .str.strptime(
                pl.Datetime,
                fmt="%Y-%m-%d %H:%M:%S%.f",
                strict=False,
            )
            .alias("%.f"),
            pl.col("ts_str")
            .str.strptime(
                pl.Datetime,
                fmt="%Y-%m-%d %H:%M:%S.%f",
                strict=False,
            )
            .alias(".%f"),
        ]
    )
)
```
```
shape: (4, 3)
┌───────────────────────────────┬────────────────────────────┬────────────────────────────┐
│ ts_str                        ┆ %.f                        ┆ .%f                        │
│ ---                           ┆ ---                        ┆ ---                        │
│ str                           ┆ datetime[μs]               ┆ datetime[μs]               │
╞═══════════════════════════════╪════════════════════════════╪════════════════════════════╡
│ 2022-08-26 11:38:14           ┆ 2022-08-26 11:38:14        ┆ null                       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-08-26 11:38:14.123       ┆ 2022-08-26 11:38:14.123    ┆ 2022-08-26 11:38:14        │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-08-26 11:38:14.123456    ┆ 2022-08-26 11:38:14.123456 ┆ 2022-08-26 11:38:14.000123 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2022-08-26 11:38:14.123456789 ┆ 2022-08-26 11:38:14.123456 ┆ 2022-08-26 11:38:14.123456 │
└───────────────────────────────┴────────────────────────────┴────────────────────────────┘
```
I think the format specifier that you want is `%.f` (not `.%f`.)

**Comment by danielgafni** [comment] 2022-08-26 19:35
Thanks a lot to everyone! This is very helpful! 

I got confused by [this](https://stackoverflow.com/a/698279) stackoverflow answer. Good to know the chrono format specification is a little different.

**Comment by zundertj** [comment] 2022-08-27 08:57
Closing, as the formatting language might be different from what you are used to, depending on your background. If there are places where we do not document that we are using the chrono format, please file a new issue (or better, raise a PR).

**Closed by zundertj** 2022-08-27 08:57 UTC
Labels: bug, python
