### ISSUE TITLE
Fork issue

### ISSUE THREAD

**Issue by moghadas76** [pola-rs/polars#20284] opened 2024-12-13 10:51 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
 with Pool() as pool:
        results = pool.map(impute_column, miss.keys())
```
RuntimeWarning: Using fork() can cause Polars to deadlock in the child process.
In addition, using fork() with Python in general is a recipe for mysterious
deadlocks and crashes.

### Log output

```shell
/python3.11/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_monkey.py:951: RuntimeWarning: Using fork() can cause Polars to deadlock in the child process.
In addition, using fork() with Python in general is a recipe for mysterious
deadlocks and crashes.
```

### Issue description

How to use fork() in python script using polar df?

### Expected behavior

Working!

### Installed versions

<details>

```
--------Version info---------
Polars:              1.14.0
Index type:          UInt32
Platform:            Linux-6.8.0-48-generic-x86_64-with-glibc2.35
Python:              3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2023.9.2
gevent               <not installed>
google.auth          2.23.3
great_tables         <not installed>
matplotlib           3.7.3
nest_asyncio         1.5.8
numpy                1.24.4
openpyxl             3.1.5
pandas               2.0.3
pyarrow              14.0.1
...
sqlalchemy           2.0.23
torch                2.3.0+cu121
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by MarcoGorelli** [comment] 2024-12-13 10:56
thanks for the report, closing as duplicate of #20255

**Closed by MarcoGorelli** 2024-12-13 10:56 UTC
Labels: bug, python, needs triage
