### ISSUE TITLE
ColumnNotFoundError on partition_by(as_dict=True, include_key=False)

### ISSUE THREAD

**Issue by polikutinevgeny** [pola-rs/polars#10791] opened 2023-08-30 04:56 UTC
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "a": ["a", "b", "a", "b", "c"],
        "b": [1, 2, 1, 3, 3],
        "c": [5, 4, 3, 2, 1],
    }
)
df.partition_by("a", as_dict=True, include_key=False)
```

### Issue description

Raises exception with this combination of keys, works with others.

### Expected behavior

Dataframe partitioned, no exception raised.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-6.4.12-arch1-1-x86_64-with-glibc2.38
Python:              3.9.17 | packaged by conda-forge | (main, Aug 10 2023, 07:02:31) 
[GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by reswqa** [comment] 2023-08-30 08:12
It seems that there is some conflict between `as_dict=True` and `include_key=False`. `as_dict` requires the `key` columns to extract dict keys but these key columns will not be returned from `partition_by` if `include_key=False`.

One approach is to simply fire an error for this configurations, and the other is to keep the key columns first, and then drop it after we compute dict key.

**Comment by mcrumiller** [comment] 2023-08-30 13:42
Duplicate of #9862.

I already have a PR to fix this, it's been sitting in the queue for a while now.

**Comment by stinodego** [comment] 2023-08-30 14:16
Duplicate of https://github.com/pola-rs/polars/issues/9862

**Closed by stinodego** 2023-08-30 14:16 UTC
Labels: bug, python
