### ISSUE TITLE
Month rounding of the 16th of the month is incorrect.

### ISSUE THREAD

**Issue by Houstonwp** [pola-rs/polars#7294] opened 2023-03-02 04:26 UTC
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

All 16th of months besides February round incorrectly down to the beginning of the current month instead of the beginning of the following month.

### Reproducible example

```python
import polars as pl
from datetime import date
dates = pl.date_range(date(2022,1,1),date(2023,1,1),interval="1d",name="date").to_frame().with_columns(pl.col("date").dt.round(every="1mo").alias("rounded_date"))
dates.filter(pl.col("date").dt.day()==16)
```

### Expected behavior

The 16th of the month should always round up to the following month, e.g. 2022-03-16 should round to 2022-04-01.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.9
Index type: UInt32
Platform: Darwin-22.3.0-arm64-arm-64bit
Python: 3.7.14 (default, Oct 24 2022, 11:12:10) 
[Clang 14.0.0 (clang-1400.0.29.102)]
---Optional dependencies---
pyarrow: <not installed>
pandas: <not installed>
numpy: <not installed>
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>```

</details>

**Comment by zundertj** [comment] 2023-03-05 12:58
So what this function really does here is to round to the nearest 1st day of the month. So if you take Jan 16th, that is (16-1=) 15 days from Jan 1st, and (32-16=) 18 days from February 1st.  So even Jan 17th is still rounded down to Jan 1st. The general pattern is that for calendar months with 30 days, everything up to and including the 16th is rounded down, and for 31 days, everything up to and including the 17th:

```python
>>> dates.filter(pl.col("date").dt.day()==17)
shape: (12, 2)
┌────────────┬──────────────┐
│ date       ┆ rounded_date │
│ ---        ┆ ---          │
│ date       ┆ date         │
╞════════════╪══════════════╡
│ 2022-01-17 ┆ 2022-01-01   │
│ 2022-02-17 ┆ 2022-03-01   │
│ 2022-03-17 ┆ 2022-03-01   │
│ 2022-04-17 ┆ 2022-05-01   │
│ 2022-05-17 ┆ 2022-05-01   │
│ 2022-06-17 ┆ 2022-07-01   │
│ 2022-07-17 ┆ 2022-07-01   │
│ 2022-08-17 ┆ 2022-08-01   │
│ 2022-09-17 ┆ 2022-10-01   │
│ 2022-10-17 ┆ 2022-10-01   │
│ 2022-11-17 ┆ 2022-12-01   │
│ 2022-12-17 ┆ 2022-12-01   │
└────────────┴──────────────┘
```

I agree that this can be a bit confusing, although rounding down the 16th for months with 31 days seems fine to me, it is the day right in the middle of the month, and could thus be allocated either way.

**Comment by mcrumiller** [comment] 2023-03-06 14:35
I think with the 16th of the month, the current implementation is clearly wrong. We need to view days as intervals with labels associated with each interval:

### 28-day month
The 16th should round up
![image](https://user-images.githubusercontent.com/1896992/223139319-bfbdc62d-d44e-43a2-89e2-37777fd7556a.png)

### 29-day month
The 16th should round up
![image](https://user-images.githubusercontent.com/1896992/223140278-e9810759-ef8c-4455-9806-26b04b88bb0b.png)

### 30-day month
The 16th should round up
![image](https://user-images.githubusercontent.com/1896992/223140423-0fff7844-b212-4a40-bef7-87063db18028.png)

### 31-day month
The only ambiguous case, can go either way. Normal rounding rules would say round up.
![image](https://user-images.githubusercontent.com/1896992/223140643-a428f5d2-1cf8-4344-8253-05dc822702b2.png)

**Comment by MarcoGorelli** [comment] 2023-03-06 15:46
> The 16th of the month should always round up to the following month, e.g. 2022-03-16 should round to 2022-04-01.

To be honest, I'd find the current behaviour expected - `2022-03-16` is closer to `2022-03-01` than it is to `2022-04-01`:

```python
In [76]: datetime(2022, 4, 1) - datetime(2022, 3, 16)
Out[76]: datetime.timedelta(days=16)

In [77]: datetime(2022, 3, 16) - datetime(2022, 3, 1)
Out[77]: datetime.timedelta(days=15)
```

Just for comparison, `lubridate` would do the same thing
```R
> library(lubridate)
> x <- ymd("2022-03-16")
> x
[1] "2022-03-16"
> round_date(x, "month")
[1] "2022-03-01"
```

**Comment by mcrumiller** [comment] 2023-03-06 15:57
@MarcoGorelli there's a problem here, which is that a `date` and a `datetime` are two entirely different constructs. One represents a point and the other represents an interval. The general rule for `date` -> `datetime` conversion is that dates are converted to their lower bound. So when you say "2022-03-16 is closer to 2022-03-01 than it is to `2022-04-01`, that may be true in the context of a datetime object, but it's not the equivalent of saying "There is less time between March 1st and March 16th than there is between March 16th and April 1st." The two distances are equal. Also, March is the least obvious example here.

To me, "rounding" means "If the value is below the midpoint, round down, otherwise round up." There is a clear midpoint between the beginning and the end of the month: the beginning is on the first of the month at 00:00, and the end is on the last of the month at 23:59:59.99999 (equal to the first of the next month at 00:00:00).

For a `pl.Datetime`, the 29-day months should round any time before the 15th at noon down to the 1st, and any time after the 15th at noon to the first of the next month. Likewise, the 31-day months should round any time before the 16th at noon in the same manner.

For `pl.Date`, we should follow normal rounding rules by rounding up.

**Comment by MarcoGorelli** [comment] 2023-03-06 18:43
> "There is less time between March 1st and March 16th than there is between March 16th and April 1st." The two distances are equal

Sorry, not sure I follow, please bear with me 😄 

From your diagram, suppose you're standing on the 16th of March square:
- if you want to walk to the 1st of March square, you walk left 15 times;
- if you want to walk to the 1st of April square, you walk right 16 times.

How do you work out that the two distances are equal?

Is there a reference, or another software, which would round the 16th of March to the 1st of April?

> normal rounding rules by rounding up.

Which rules are you referring to? IEEE754 at least rounds to the nearest even, e.g.
```console
$ python -c 'print(round(2.5))'
2
```

---

for reference, pandas doesn't allow rounding to months at all

**Comment by mcrumiller** [comment] 2023-03-06 18:48
> From your diagram, suppose you're standing on the 16th of March square:

> if you want to walk to the 1st of March square, you walk left 15 times;
> if you want to walk to the 1st of April square, you walk right 16 times.

Ok, I get that this is true if we mean the end of the 1st of the month. But I still stand by my basic point that rounding should look at the midpoint of the month and round up if we're above and down if we're below. With regards to even-splits, I don't have a preference: rounding to nearest even works for me, but in the context of `pl.Date` it seems a consistent up-or-down-on-ties would be less confusing.

I don't have a huge stake in this fight since I can't really see myself "rounding" to a month anyway--my code would usually be "what month am I current in?" in which case `.dt.month()` suffices.

**Comment by MarcoGorelli** [comment] 2023-05-26 10:42
going to close this for now as it looks like expected behaviour, but if anyone has any other arguments / other software which does something different, please do comment and this can be reopened. thanks for the issue!

**Closed by MarcoGorelli** 2023-05-26 10:42 UTC
Labels: bug, python
