### ISSUE TITLE
docs(python): Tracking what version something was added/changed

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#12083] opened 2023-10-28 14:03 UTC
### Description

When trying to find out/document what version something was added in Polars, I have been 
manually searching through https://github.com/pola-rs/polars/releases/ 

(am I doing this wrong?)

## Deprecations

For deprecation info, we can search for `deprecate_renamed_function` in the source code:
https://github.com/pola-rs/polars/blob/3f7c1904b3b6a243684f899d9bf322fd5f2b09f2/py-polars/polars/lazyframe/frame.py#L5905-L5906

## Additions/Changes

Python for example https://docs.python.org/3/library/itertools.html#itertools.accumulate has:
> New in version 3.2.
> Changed in version 3.3: Added the optional `func` parameter.
> Changed in version 3.8: Added the optional `initial` parameter.

For [py-polars](https://pola-rs.github.io/polars/development/contributing/#python):
> Polars uses Sphinx to build the API reference.

I'm not sure if Python uses Sphinx, or if these version notes are automically generated?

## Extras
Perhaps someone knowledgable in this field knows if it's possible to do some sort of "doc diff" to find out this kind of information?
<blockquote>

## Methods
- ### Added

Method|Version
:-|:-
polars.Expr.name.suffix|0.19.12

- ### Changed
Method|Previous|Version
:-|:-|-
DataFrame.rolling|DataFrame.group_by_rolling|0.19.10

## Parameters

- ### Added
- ### Changed
Method|Parameter|Latest|Previous|Version
-|-|-|-|-
Expr.shift|n|`int \| IntoExpr`|`int`|0.19.9

</blockquote>

**Comment by MarcoGorelli** [comment] 2023-10-28 14:31
if it's an argument, then the `.. deprecated::` directive can take a version number - e.g. check the `use_earliest` argument here https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.dt.replace_time_zone.html

similarly, `.. versionadded` is used here https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_excel.html

`versionchanged` also exists, and maybe could have been used when expressifying some arguments (cc @reswqa just FYI)

**Comment by cmdlineluser** [comment] 2023-10-28 16:53
Ah okay, so they are called directives in Sphinx:

https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded

Awesome stuff, thanks a lot @MarcoGorelli.

Perhaps a quick mention of this in the Contributing Guide could be useful for people not familiar?

https://pola-rs.github.io/polars/development/contributing/#python

**Comment by stinodego** [comment] 2023-10-29 16:41
This is a duplicate of https://github.com/pola-rs/polars/issues/6740

My answer there:

> I'm in favor of doing this when we hit 1.0.0. The API is still moving quite quickly now, and this would be too much of a burden to keep up with at the moment. We will add the accepted tag to this issue once we get there.

**Closed by stinodego** 2023-10-29 16:41 UTC
Labels: enhancement

**Comment by cmdlineluser** [comment] 2023-10-30 04:16
Thanks for the info @stinodego - I seem to have missed the previous issue in my searching.

I didn't realize it was mostly a manual process with the directives - makes sense not to have it enforced at the current stage of Polars development.

After some more searching about sphinx I did find:

https://sphinx-autodoc2.readthedocs.io/en/latest/quickstart.html#command-line-tool


```bash
$ autodoc2 -h
                                                                                                                          
 Usage: autodoc2 [OPTIONS] COMMAND [ARGS]...                                                                              
                                                                                                                          
 CLI for sphinx-autodoc2                                                                                                  
                                                                                                                          
╭─ Options ──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --version             -v        Show the application version and exit.                                                 │
│ --install-completion            Install completion for the current shell.                                              │
│ --show-completion               Show completion for the current shell, to copy it or customize the installation.       │
│ --help                -h        Show this message and exit.                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Commands ─────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ create-db         Create a database for a python module or package.                                                    │
│ list              Analyse a python module or package and stream the results to the console.                            │
│ resolve-all       Analyse the __all__ of a module and find potential matches                                           │
│ write             Create sphinx files for a python module or package.                                                  │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
Which gives back a JSON dump:
```python
"polars.functions.range.int_range.int_range": {
    "type": "function",
    "full_name": "polars.functions.range.int_range.int_range",
    "args": [
        [
            null,
            "start",
            "int | polars.type_aliases.IntoExprColumn",
            null
        ],
        [
            null,
            "end",
            "int | polars.type_aliases.IntoExprColumn",
            null
        ],
        [
            null,
            "step",
            "int",
            "1"
        ],
        [
            "*",
            null,
            null,
            null
        ],
        [
            null,
            "dtype",
            "polars.type_aliases.PolarsIntegerType",
            "Int64"
        ],
        [
            null,
            "eager",
            "bool",
            "False"
        ]
    ],
    "return_annotation": "polars.Expr | polars.Series",
```
I should be able to use this locally to compare different checkouts and generate some diff information.
