### ISSUE TITLE
[SQL] SELECT literal from dataframe return only 1 row instead of the dataframe height

### ISSUE THREAD

**Issue by rluvaton** [pola-rs/polars#20058] opened 2024-11-28 18:55 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import datetime as dt


df = pl.DataFrame(
    {
        "id": [1, 2, 3],
    }
)

ctx = pl.SQLContext(test=df, eager=True)

print(ctx.execute("SELECT 1 FROM test"))
```

### Issue description

I'm trying to duplicate literal for each data frame row, I tried it in rust by using `repeat_by` but I don't know the size to repeat by... so I tried using SQL in python and it gives the same output

the output is:
```
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ i32     │
╞═════════╡
│ 1       │
└─────────┘
```

which is not correct as it should return the literal for each row in the dataframe

### Expected behavior

The expected behavior is to output this:
```
[11]
0s
import polars as pl
import datetime as dt


df = pl.DataFrame(
    {
        "literal": [1, 1, 1],
    }
)


shape: (3, 1)
┌─────────┐
│ literal │
│ ---     │
│ i32     │
╞═════════╡
│ 1       │
│ 1       │
│ 1       │
└─────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            Linux-6.1.85+-x86_64-with-glibc2.35
Python:              3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               4.2.2
cloudpickle          3.1.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.8.0
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             3.1.5
pandas               2.2.2
pyarrow              17.0.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           2.0.36
torch                2.5.1+cu121
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by cmdlineluser** [comment] 2024-11-28 18:59
https://github.com/pola-rs/polars/issues/6360#issuecomment-1399424605

> This is as expected we only broadcast to the result selection.

You can repeat by `pl.len()` 

```python
>>> df.select(pl.lit(1).repeat_by(pl.len()).flatten())
shape: (3, 1)
┌─────────┐
│ literal │
│ ---     │
│ i32     │
╞═════════╡
│ 1       │
│ 1       │
│ 1       │
└─────────┘
```

**Comment by rluvaton-flarion** [comment] 2024-11-28 21:53
how can I do it in rust when using lazy?

**Comment by rluvaton** [comment] 2024-11-28 21:53
thanks, how can I do it in rust when using lazy?

**Comment by cmdlineluser** [comment] 2024-11-28 22:21
It should be pretty much the same way I think?

```rust
df.lazy().select([lit(1).repeat_by(len()).flatten()]).collect()
```

**Comment by nameexhaustion** [comment] 2024-11-29 06:21
We should match the behavior of SQL execution for queries that use the SQL interface here

**Comment by AlexeyDmitriev** [comment] 2024-12-06 09:17
Dupe of #18404 ?

**Closed** 2024-12-10 09:22 UTC
Labels: bug, python, A-sql, accepted, P-medium
