### ISSUE TITLE
test_decimal_write_parquet_12375 fails with TypeError: 'Decimal' object cannot be interpreted as integer

### ISSUE THREAD

**Issue by ctdunc** [pola-rs/polars#13702] opened 2024-01-13 20:22 UTC
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

follow the documentation for new contributors up to: 
`cd py-polars`
`make test`

### Log output

```shell
____________________________________________________________________ test_decimal_write_parquet_12375 _____________________________________________________________________
[gw5] linux -- Python 3.11.6 /home/connor/code/polars/.venv/bin/python
tests/unit/datatypes/test_decimal.py:266: in test_decimal_write_parquet_12375
    df = pl.DataFrame(
polars/dataframe/frame.py:372: in __init__
    self._df = dict_to_pydf(
polars/utils/_construction.py:941: in dict_to_pydf
    for s in _expand_dict_scalars(
polars/utils/_construction.py:850: in _expand_dict_scalars
    updated_data[name] = pl.Series(
polars/series/series.py:295: in __init__
    self._s = sequence_to_pyseries(
polars/utils/_construction.py:597: in sequence_to_pyseries
    return _construct_series_with_fallbacks(
polars/utils/_construction.py:360: in _construct_series_with_fallbacks
    return constructor(name, values, strict)
E   TypeError: 'Decimal' object cannot be interpreted as an integer
========================================================================= short test summary info =========================================================================
FAILED tests/unit/datatypes/test_decimal.py::test_decimal_write_parquet_12375 - TypeError: 'Decimal' object cannot be interpreted as an integer
========================================================== 1 failed, 4968 passed, 4 skipped, 1 xfailed in 12.96s ==========================================================
```

### Issue description

Output of rustup --version: 
```
rustup 1.26.0 (2023-11-14)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.77.0-nightly (d6d7a9386 2023-12-22)`
```

### Expected behavior

tests should pass

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.4
Index type:           UInt32
Platform:             Linux-6.6.10-zen1-1-zen-x86_64-with-glibc2.38
Python:               3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]

----Optional dependencies----
adbc_driver_manager:  0.9.0
cloudpickle:          3.0.0
connectorx:           0.3.2
deltalake:            0.15.1
fsspec:               2023.12.2
gevent:               23.9.1
hvplot:               0.9.1
matplotlib:           3.8.2
numpy:                1.26.3
openpyxl:             3.1.2
pandas:               2.1.4
pyarrow:              14.0.2
pydantic:             2.5.3
pyiceberg:            0.5.1
pyxlsb:               1.0.10
sqlalchemy:           2.0.25
xlsx2csv:             0.8.1
xlsxwriter:           3.1.9

```

</details>

**Comment by stinodego** [comment] 2024-02-18 21:32
Not sure what you're running into, but this runs fine in the CI and also with me locally.

Closing this since I am not able to reproduce this.

If this still fails for you on the latest main branch, let me know, and we can try to figure out what's going on. Maybe something with your OS - not sure.

**Closed by stinodego** 2024-02-18 21:32 UTC
Labels: bug, python, A-dtype-decimal, A-io-parquet
