### ISSUE TITLE
add decimal and float_format arguments to `write_csv` like in pandas

### ISSUE THREAD

**Issue by schakalakka** [pola-rs/polars#7806] opened 2023-03-27 06:23 UTC
### Problem description

For european data like french and german (and possibly more) it would be very conventient to add a decimal and float_format argument to `write_csv` similar to the `to_csv` method in pandas. 

Example: 
`df.write_csv(file='foo.csv', sep=';', decimal=',')`
Output: 
```
col1;col2
0,1;12,34
```

**Comment by alexander-beedie** [comment] 2023-03-27 07:27
I have this on the TODO list - duplicate of https://github.com/pola-rs/polars/issues/6698, so will close this in favour of the earlier issue 👍

**Closed by alexander-beedie** 2023-03-27 07:27 UTC
Labels: enhancement
