### ISSUE TITLE
no index in Polars(iloc and loc)

### ISSUE THREAD

**Issue by lm-cyber** [pola-rs/polars#12312] opened 2023-11-08 07:25 UTC
### Description

As there is no index in Polars there is no .loc or iloc method in Polars - and there is also no SettingWithCopyWarning in Polars

you can change df.loc[index,col] in pandas to df[index,col] in polars and etc
fix doc please 

### Link

https://pola-rs.github.io/polars/user-guide/migration/pandas/#key-syntax-differences

**Comment by ritchie46** [comment] 2023-11-08 07:27
>  fix doc please

Sorry, can you elaborate a bit what the problem is?

**Comment by cmdlineluser** [comment] 2023-11-08 08:12
It sounds they are asking for the `df[row_nr, col]` syntax to be shown as an example?

```python
>>> df = pl.DataFrame({"A": [1, 2], "B": [3, 4]})
>>> df[1, 'B']
4
>>> df.item(1, 'B')
4
```

**Comment by ritchie46** [comment] 2023-11-08 08:19
Index access is very seldom the idiomatic way to do things in polars, that's why we don't show it here. They also don't allow assignment, so I doubt it would match peoples acceptations.

In any case, the user guide should explain idiomatic polars, not all the available options (that belongs in the reference guide). I will close this.

**Closed by ritchie46** 2023-11-08 08:19 UTC
Labels: documentation

**Comment by lm-cyber** [comment] 2023-11-08 10:43
They also don't allow assignment?
df = DataFrame({
        'target': [1, 2, np.nan, 4, None,None],
        'b': [6, 7, 8, 9, 10,11],
        'bool':[False, True, False, True, False,True],
    })
df[[2,4,5],'target'] = np.array([-1,-1,-1])
print(df)
![image](https://github.com/pola-rs/polars/assets/73221496/5973bd65-009b-4610-8d29-e1527efb7e79)

**Comment by lm-cyber** [comment] 2023-11-08 10:45
They also don't allow assignment?
``` python
df = DataFrame({
        'target': [1, 2, np.nan, 4, None,None],
        'b': [6, 7, 8, 9, 10,11],
        'bool':[False, True, False, True, False,True],
    })
df[[2,4,5],'target'] = np.array([-1,-1,-1])
print(df)
```
![image](https://github.com/pola-rs/polars/assets/73221496/5973bd65-009b-4610-8d29-e1527efb7e79)

**Comment by cmdlineluser** [comment] 2023-11-08 11:26
> They also don't allow assignment?

Assignment was removed from Polars: #4331 #4430 

(I didn't realize it was valid again.)

It seems it was reintroduced in #4544 - perhaps @ritchie46 forgot about that.
