### ISSUE TITLE
pl.Duration as string

### ISSUE THREAD

**Issue by misantroop** [pola-rs/polars#14189] opened 2024-02-01 16:05 UTC
### Description

Unable to get a pl.Duration col as displayed in repr ("15m"). Timedelta objects are returned instead, which makes sense in most cases but a string representation would be useful.

```
df = pl.DataFrame({"Duration": [900000000, 900000000]}, schema={"Duration": pl.Duration})
df["Duration"].to_list()
>> [datetime.timedelta(seconds=900), datetime.timedelta(seconds=900)]
```

**Comment by MarcNuebel** [comment] 2024-02-01 17:24
You can already use something like

```
(df["Duration"].dt.total_minutes() + "m").to_list()
```

Maybe one could extend `polars.Expr.dt.to_string` to accept `duration` type

**Comment by misantroop** [comment] 2024-02-01 17:31
That would work only for larger units and conversion is necessary. Duration already holds this information and getting the string out would be the most efficient path.

**Comment by MarcNuebel** [comment] 2024-02-01 18:21
What do you mean by "holds the information" and "getting the string out"?
The internal representation of the duration datatype is just an integer and when you print it it is converted, too.

**Comment by misantroop** [comment] 2024-02-01 19:18
My bad, that's true. Nevertheless the conversion is done for print and getting that value out should be possible.

**Comment by alexander-beedie** [comment] 2024-02-03 07:15
FYI: duplicate of https://github.com/pola-rs/polars/issues/7174.

**Closed** 2024-02-04 20:23 UTC
Labels: enhancement
