### ISSUE TITLE
Horizontal Mean for Lazy or Expr 

### ISSUE THREAD

**Issue by baron-digit** [pola-rs/polars#9963] opened 2023-07-19 02:46 UTC
### Problem description

So far only the DataFrame implementation of column-wise mean is implemented.
As requested by Ritchie, putting the request for the Expr API for row-wise mean here.

Thanks for your support and the great work.

**Comment by ritchie46** [comment] 2023-07-19 05:01
We already have this implemented as `DataFrame::hmean`, so we just need to expose a horizontal expression.

**Comment by deanm0000** [comment] 2023-07-19 16:41
Is this going to be the same performance or better than doing?

```
df.select(pl.concat_list('a','b').list.mean())
``

**Comment by ritchie46** [comment] 2023-07-20 07:16
Probablr better, it will not reallocate into a list, but will compute the intermediate states columnar.

**Comment by stinodego** [comment] 2023-07-21 09:19
Duplicate of #9966

Closing in favor of #9966 as it is more complete.

**Closed by stinodego** 2023-07-21 09:19 UTC
Labels: enhancement, accepted
